### ISSUE TITLE
Sensu-Client Runs on Embedded Ruby even though its disabled

### ISSUE THREAD

**Issue by nsizov** [sensu/sensu#1000]
Hello, I checked my "ps aux | grep sensu" and got this:

```
/opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-client.pid -l /var/log/sensu/sensu-client.log -L info
```

At the same time I have:

```
use_embedded_ruby  => false,
```

Any thoughts on this?

**Comment by portertech** [comment]
The embedded ruby is always used for Sensu, when using the packages. The EMBEDDED_RUBY variable in `/etc/default/sensu` is to allow the use of the embedded ruby for check plugin and handler execution.
