### ISSUE TITLE
Sensu Embedded Ruby

### ISSUE THREAD

**Issue by shakycode** [sensu/sensu#1003]
I have sensu installed on Centos 6.5 from the rpm package/repo.  I have EMBEDDED_RUBY=true in my /etc/default/sensu so that it uses embedded ruby from the omnibus package /opt/sensu/embedded/bin/ruby but my problem is getting gems to install in the embedded ruby/sensu user path since sensu has no shell.  How do I do this?

I tried doing a /opt/sensu/embedded/bin/gem install pg (to install the Postgres adapter) but it ended up installing it to my .rmv directory under /home/deploy (my rails app deploy user with RVM/Ruby installed).  

How can I get gems to install for sensu using the embedded Ruby/Gem?  I don't want to break RVM for the deploy user, but most of these checks/plugins need Ruby and have gem dependencies so I want to use embedded ruby.

I tried posting on Stack and on the user list but haven't received much info yet, this is the missing piece from getting me to make sensu work and get useful checks going.

**Comment by portertech** [comment]
Hey @shakycode! Does manually setting/overriding the GEM_PATH for the session shell allow you to install to Sensu's embedded Ruby? Like: https://github.com/sensu/sensu-build/blob/master/sensu_configs/init.d/sensu-service#L168 RVM will be setting this environment variable, which could be fighting you and your efforts.

**Comment by shakycode** [comment]
I could try this, but how would I export that?  I guess what I’m asking is as what user?  I have a deploy user which we use for our rails app and has RVM.  I could try this as the sensu user but the problem is sensu has no shell to login with and I don’t want to change that.

Basically I set embedded_ruby=TRUE in /etc/default/sensu so sensu will use the omnibus ruby in /opt/embedded/bin/ruby but where I’m having problems is how to actually install gem dependencies for these different plugins.  It seems like Sensu assumes that everyone has a global ruby and/or doesn’t use RVM for specific users/apps.

Sorry that I’m so lost, but this is my first go at Sensu and I’ve got everything setup and talking, now to just get some useful plugins installed to get checks going. :)

**Comment by portertech** [comment]
You could try installing a gem w/ your deploy user, e.g:

```
GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.0.0 /opt/sensu/embedded/bin/gem install redphone
```

**Comment by shakycode** [comment]
Ok thanks.

I just tried that on a server that doesn’t have system/rvm ruby installed, trying to install the fileutils gem and i get this:

—
sudo GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.0.0 /opt/sensu/embedded/bin/gem install fileutils
Building native extensions.  This could take a while...
ERROR:  Error installing fileutils:
	ERROR: Failed to build gem native extension.

    /opt/sensu/embedded/bin/ruby extconf.rb
checking for gcc... no
No C compiler found in ${ENV['PATH']}. See mkmf.log for details.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/sensu/embedded/bin/ruby


Gem files will remain installed in /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rmagick-2.15.3 for inspection.
Results logged to /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rmagick-2.15.3/ext/RMagick/gem_make.out

—

So it looks like specifying the gem path works on a system where there is/isn’t RVM installed.  So this is progress.  But obviously I am missing something in the system on Centos 6.5 since there’s no c compiler found in the path.  How to correct this?

Thanks for all your help and patience. :)

**Comment by portertech** [comment]
@shakycode looks like that machine needs: `yum groupinstall "Development Tools"` :+1:

**Comment by shakycode** [comment]
Bam, that worked!  I just downloaded the check-prods.rb script and installed the dependencies and I’m good to go.

Now here’s my question.  There are a lot of great plugins in sense-community plugins.  How do I get those onto my nodes?  Obviously I need to setup omnibus/embedded ruby, but should I just clone the repo on my local machine and then cut/paste each plugin I want to use onto each node and manually resolve their dependencies?

Note: I will be rolling out chef in the next couple of months so far now I’m having to do a lot of manual ops works.  So yeah laugh it up. :)

-James
