### ISSUE TITLE
Question: sensu event filter 

### ISSUE THREAD

**Issue by alex-leonhardt** [sensu/sensu#1008]
Hi,

I've had a go at using event filters to only specify alerts to be sent from certain DCs / environments based on a custom host attribute, this works fine as long as I only specify one environment name / filter - however - as soon as I add a second, it does not seem to work as I had expected. 

Does this https://github.com/sensu/sensu/blob/master/lib/sensu/server/filter.rb#L194 mean that, unless all event filters match, that the event will be filtered ? An AND action, rather than OR ? 

I couldn't find clear documentation about this, hence me asking. The behaviour does suggest that it's doing a AND rather than OR.

If it's doing a AND ( e.g. filter unless env=prod AND env=qa ) is there a way to instruct the filter "engine" to do a OR (e.g. filter unless env=prod OR env=qa) ?

Let me know if it doesn't make sense :) 

Thanks,
Alex

**Comment by portertech** [comment]
Hey @alex-leonhardt, it is `AND`. You could make use of an eval filter attribute - https://sensuapp.org/docs/latest/filters#filter-eval-attributes - e.g. `"env": "eval: %w[prod qa].include?(value)"` :+1:

**Comment by alex-leonhardt** [comment]
Thanks @portertech - I guess I should raise a feature request to add ability to specify if it's a AND or a OR :) ? I'll try that eval you've got there and post results here.
