### ISSUE TITLE
Plans to support key when using Redis as transport?

### ISSUE THREAD

**Issue by NeckBeardPrince** [sensu/sensu#1014]
Right now we can select a db for redis to use as a transport but that will be removed at some point. Any plans to use namespaces?

**Comment by portertech** [comment]
No mention of it being deprecated on http://redis.io/commands/SELECT

Do you have a reference to a doc/page?

**Comment by portertech** [comment]
This issue should be moved to https://github.com/sensu/sensu-transport we can add support for using a Redis "namespace" option to the Redis library.

**Comment by calebhailey** [comment]
Created https://github.com/sensu/sensu-transport/issues/28 to track this issue and will close this now.
