### ISSUE TITLE
[ SENSU Server ] : The dangers of multiple masters/leaders - My story

### ISSUE THREAD

**Issue by chiriaev** [sensu/sensu#1019]
Hi, Sean. I hope you are well. There is something I wanted to share with you. I recently discovered that my infrastructure was occasionally running multiple masters. In fact I was DoS(sing) myself. 

After thorough investigations I learnt that blocking calls from extensions (I simulated artificial delays) and/or client traffic and extensive read and write activity to Redis (I had around 3000 stashes and growing number of clients, in the hundreds; plus Sensu is storing all check results since version “0.18.0” and it has a cost) were just enough to block the event loop and prevent the server from updating the “leader” lock. (i.e.: I have system traces for both cases) In consequence, I was ending up with 16+ masters and a near-death experience, operationally speaking.

I also noticed these freezes were sometimes taking minutes and generated gaps in alarm and metrics coverage. A big issue in other words.

Grateful if you can share your thoughts on the matter. There are multiple things to it. One would be to force the “frozen” master to resign once it has detected a switch in leadership. That’s something that I/my team may contribute back with a PR shortly. It should also include a way to record the current master/leader's name in Redis. 

The second idea would be to have a new server role on the top of the current leader and worker instances. That would be a “publisher” solely responsible for broadcasting check requests and perhaps something more. (i.e.: in fact that’s one of my big concerns besides the DoS)

I am afraid that at scale, thousands of clients and lots of checks with a mix of metric and regular, one master with more than enough responsibilities: updating stale items, writing check results, publishing back to Rabbit, sending check requests, etc… will not cope. That’s where I am coming from with my message. 

I hope it generates some good ideas and comments from you and the community. Happy to share more details if needed…

Have a nice day.

Regards, Andrei

P.S.: the above was tested with “0.18.x” and “0.19.x” on Oracle Linux.

**Comment by portertech** [comment]
@chiriaev was the event loop actually being blocked or was the machine just starved of resources and CPU time was being allocated elsewhere? Having a simple mechanism to detect another master (that created a more recent lock) does make sense.

**Comment by portertech** [comment]
Do you normally use extensions that make blocking IO calls, blocking the event loop?

**Comment by portertech** [comment]
The act of publishing check requests is extremely lightweight, scaling with the number of defined checks (not clients). I think the process of inspecting check results (TTLs) and client keepalives should be improved, not just relocated.

**Comment by portertech** [comment]
Looks like there may also be a bug with master election :-1:

The initial leader lock timestamp does not include milliseconds:

```
-        @redis.setnx("lock:leader", Time.now.to_i) do |created|
+        @redis.setnx("lock:leader", (Time.now.to_f * 1000).to_i) do |created|
```

Race condition, between master lock update (w/ milliseconds) and other viable leaders (Sensu servers).

**Comment by portertech** [comment]
I am whipping up a fix.

**Comment by portertech** [comment]
@chiriaev please take a look at https://github.com/sensu/sensu/pull/1022, I am working on documenting it now.

**Comment by dreamerz** [comment]
@portertech We have a couple of extension handlers.
1. Wizardvan sending metrics to graphite. https://github.com/opower/sensu-metrics-relay
2. Our custom extension forwarding alerts to REST api.
From our investigation, delay in these extension probably block sensu event loop from updating lock timestamp.

**Comment by portertech** [comment]
@dreamerz is the REST API extension making use of an eventmachine HTTP library? like: https://github.com/igrigorik/em-http-request

**Comment by dreamerz** [comment]
@portertech  No. It simply uses rest-client (https://github.com/rest-client/rest-client).

**Comment by chiriaev** [comment]
Thanks, @dreamerz and @portertech. I looks like we need to revisit our extension(s) and include calls to https://github.com/igrigorik/em-http-request. @dreamerz. Hi. Could you please share our multi-master related code updates with Sean P.? 

Regards, Andrei

**Comment by dreamerz** [comment]
@portertech I have a different approach by adding leader unique id and add it into redis. UID consists of hostname and pid. Leader will check the leader uid every times before updating lock timestamp.
Pros: We can query who is current leader.
Cons: It increases calls to redis by checking leader every times before updating lock timestamp.
Please see the code at https://github.com/thomsonreuters/sensu-1/pull/1. Note that log level is changed to make  our observation easier.

**Comment by portertech** [comment]
@dreamerz I do like your approach. Not sure if there are any hidden potential race conditions. Undecided on which approach to move forward with, leaning towards my PR as a patch level fix, e.g. 0.20.3.

**Comment by portertech** [comment]
Considering having a generic task/job queue for Sensu servers, for things like keepalive and result inspection. We could have the Sensu server leader generate keepalive and result batches, throw a payload onto the transport.
