### ISSUE TITLE
Sensu does not set event[:check][:type] = "standard" for standard checks.

### ISSUE THREAD

**Issue by erenfro** [sensu/sensu#1025]
Checks with type "metric" specifically set, always has that returned in the json/hash of the event object, but standard checks, which are the default, unless specifically defined in the client config, do not specifically provide the value for event[:check][:type], and it should be "standard".

This causes issues when trying to handle standard and metric checks, and any other kind of future checks that may eventually be implemented. With the way ruby hash's work, the only viable method I found to determine specifically if a check is standard is with the following code:

          if event[:check].key?(:type)
            check_type = event[:check][:type]
          else
            check_type = "standard"
          end

Which.. Honestly, isn't very good to assume everything is standard.

**Comment by portertech** [comment]
:+1: we should set the default to either "standard" or "service" for defined context.

**Comment by portertech** [comment]
This is an excellent question for the next Sensu community survey.

**Comment by calebhailey** [comment]
Tagging this for 0.24.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/990
