### ISSUE TITLE
[ SENSU && REDIS 3.0 ] : Clustering support?

### ISSUE THREAD

**Issue by chiriaev** [sensu/sensu#1029]
Guys, Hi. Any plans to support the recent Redis 3.0+ clustering features? Can it be as simple as updating the corresponding "gem"? ;) Regards, Andrei 

P.S.:  below is what I'am getting from my shiny cluster in SENSU API;
...
"Redis server returned error code: MOVED 15643 10.206.141.56:7003"}
...
[ from http://redis.io/topics/cluster-spec ] 
...
Since cluster nodes are not able to proxy requests, clients may be redirected to other nodes using redirection errors -MOVED and -ASK. The client is in theory free to send requests to all the nodes in the cluster, getting redirected if needed, so the client is not required to hold the state of the cluster. However clients that are able to cache the map between keys and nodes can improve the performance in a sensible way.
...

**Comment by portertech** [comment]
Hi @chiriaev, the EventMachine Redis libraries do not currently support Redis 3.0 clustering. Quite frankly, all of the EM Redis libraries are crap, we need to write a new lib using the current protocol parser and redo connection handling to support it.

**Comment by portertech** [comment]
We should move this issue to https://github.com/sensu/sensu-transport

**Comment by thomaslitton** [comment]
Has there been any work done on this?  I'm interested in getting Sensu to work with a redis cluster, and was wondering if there is anything done that I could take a look at yet.

**Comment by calebhailey** [comment]
@chiriaev @thomaslitton native support for Redis Sentinel was implemented in Sensu 0.23, which was released this past week! \o/ 

See: https://sensuapp.org/docs/0.23/changelog

I'm going to go ahead and close this with a :boom:

**Comment by colmex** [comment]
Is there any documentation for this? I see documentation for sentinel support, but I don't see any for redis cluster as I believe they are different.

**Comment by adveres** [comment]
+1 it seems redis sentinel got supported, but redis clustering is not.
I only see reference to sentinel [the docs](https://sensuapp.org/docs/latest/reference/redis.html).

**Comment by tomaszzz** [comment]
We are very interested in finding out if Redis 3.2 clustering available on AWS is or will be supported by Sensu.
