### ISSUE TITLE
Stopping sensu-client:Timed out waiting for sensu-client to stop ... failed!

### ISSUE THREAD

**Issue by opsidevzi** [sensu/sensu#1033]
###### Sensu version: 0.20.1

We have a couple of Sensu clients that's running a lot of standalone checks. When we try stopping/restarting them we get this error

> service sensu-client stop
> [....] Stopping sensu-client:Timed out waiting for sensu-client to stop ... failed!
> failed!

We've found that we have to kill the processes (using kill -9 or kill -15) and delete the pid and lock files manually to successfully stop/restart the client.

Each of these clients are running between 500 - 1000 standalone checks.
Have we hit some type of limit here? If so, what is the limit?

**Comment by portertech** [comment]
@opsidevzi what sort of check intervals? how aggressive are they in relation to execution times?

**Comment by brianhu2006** [comment]
@opsidevzi: did you solve this issue? I meet the same issue when start up sensu-client. the failure occur occassionaly

**Comment by chiriaev** [comment]
Guys, Hi. Same here. On Unix, the override happens with "SERVICE_MAX_WAIT" either in "/etc/default/sensu" or "/etc/sysconfig/sensu-client". It set it to "180" in the latter, for example.

Regards, Andrei

**Comment by portertech** [comment]
Similar to https://github.com/sensu/sensu/issues/1052

**Comment by portertech** [comment]
The Sensu 0.27 packages now utilize the appropriate service manager for the platform/release, e.g. systemd, upgrading is recommended. `SERVICE_MAX_WAIT` is still relevant when sysvinit scripts are in use.
