### ISSUE TITLE
Windows client dependent on .NET Framework 3.5 ?

### ISSUE THREAD

**Issue by hurrycaine** [sensu/sensu#1037]
I ran the windows client no problem on Windows 2008 but on Windows 2012 the service failed to start. 
I got a misleading error of 

    Windows could not start the Sensu Client service on Local Computer.

    Error 1053: The service did not respond to the start or control request in a timely fashion

The event log said that the service request timed out 30000 milliseconds but the error happens instantly.

Running the sensu-client.exe came up with at Failure to install .Net Framework 3.5 . I had 4.5 installed not 3.5 installed, after installing 3.5 Feature it worked ok. Fortunately it was no problem for this particular server/app to install .net 3.5 as well.

It looks like maybe the sensu-client.exe is a .net wrapper of some sort? 

Perhaps we could just add this to documentation under windows?

**Comment by chiriaev** [comment]
Guys, Hi. Same here. Was about to post the below. Regards, Andrei
...
Guys, Sean, Hi. I have an dependency issue when installing Sense client "0.19" on a Windows 2012 R2, version "6.3.9600". The "d:/compass/monitor/app/sensu/bin/sensu-client.exe install" triggers 
a system message requesting ".NET Framework 3.5". The host in question only has version "4.5" installed. Any thoughts? Can this be fixed on a meta-data level somehow? (i.e.: installer, etc...)
...

**Comment by portertech** [comment]
I believe this may be an unnecessary version dependency brought on by https://github.com/sensu/sensu-build/blob/master/recipes/winsw.rake

**Comment by portertech** [comment]
I am pretty sure this is the culprit https://github.com/sensu/sensu-build/blob/master/recipes/winsw.rake

**Comment by FlorinAndrei** [comment]
I have the exact same problem with sensu-0.20.6-1

Is there a way to fix it without installing .Net 3.5?

I really need to install the client on the Windows instance, but this bug is getting in the way.

**Comment by FlorinAndrei** [comment]
More specifically, I can't install .Net 3.5 on Windows Server 2012 R2 running as an instance in AWS. I haven't done a full investigation, but the installer flat out refuses to run there.

**Comment by portertech** [comment]
@FlorinAndrei odd that you are unable to install Net 3.5, as the build box is 2012 R2. I too would like to get sensu-build using a more recent version.

**Comment by sandeepmendiratta** [comment]
Do you know if Net 3.5 dependency will be removed in new sensu client for windows? I am running into same issue with Windows 2012 R2.

**Comment by FlorinAndrei** [comment]
I was able to install .NET 3.5 via the Server Manager app that comes with Windows Server 2012. After that the Sensu client 0.21.0 worked just fine.

**Comment by agoddard** [comment]
@sandeepmendiratta .NET 3.5 install should be possible w/ 2012 R2. We're working on updating the .NET dependency on Windows

**Comment by sandeepmendiratta** [comment]
Yes, I was able to install but there is known issue with existing security patches which will allow you to install unless you uninstall some few security patches. See the Microsoft KB. It will be nice to get rid of .NET dependency or move to .NET4.5.
https://support.microsoft.com/en-us/kb/3002547

**Comment by calebhailey** [comment]
Presumptively tagging this for 0.24.

**Comment by calebhailey** [comment]
Actually, I believe this was silently resolved in https://github.com/sensu/sensu-build/commit/e78a20ac2ce0835271a35f9375a5027329a45881 and included the 0.22.1+ packages. I'm going to presumptively close this issue, but please feel free to create a new issue if this isn't actually resolved. #monitoringlove

**Comment by sandeepmendiratta** [comment]
Thank you for the update. I will test this out and report back,

**Comment by efalkner** [comment]
Running into the same issue, curious if it was fixed. Thanks!

**Comment by hurrycaine** [comment]
This is working with 0.23.1...  Thank you!

**Comment by dgoradia** [comment]
Not resolved for `sensu-0.23.2-1.msi` on win srv 2008 r2.

Message:
```
To run this application, you first must install one of the following versions of the .NET Framework:
  v3.5
  v4.0
...
```

**Comment by hurrycaine** [comment]
@dgoradia  from my testing v3.5 is no longer required (which was the issue I logged) but I did not test if it would work without .Net4.5... all my servers have 4.5

**Comment by dgoradia** [comment]
@hurrycaine When running `sensu-client.exe install` I get the above message. This happens with `NetFx3` feature installed. Under Server Manager > Features, I can see that `.NET Framework 3.5.1` is installed.

Tried a reboot too, still same message.

It only works after installing .NET Framework 4. 4.5 may also work but I haven't tested.

If .NET is a required dependency, fine but the error message is misleading in that 3.5 would suffice.

**Comment by cixelsyd** [comment]
Hi Sean!  We hit this issue on Windows 2008 as well.  The [reference provided above]( https://github.com/sensu/sensu-build/blob/master/recipes/winsw.rake#L11) is absolutely an issue for those of us with only 3.51 on Windows 2008.  Could you let us know if the solution to this is on your schedule?  If not, I can try to hack a solution.
