### ISSUE TITLE
Expire redis keys for stale checks

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu#1038]
If a host runs a check a bunch of times, and then for whatever reason that check is no longer needed, once the config is removed, the sensu check will remain in the redis keys forever more with a 0 status and the last execution time increasing. It's essentially a zombie check.

I feel like it would be beneficial to use Redis's EXPIRE setting to remove this redis key that is no longer relevant. I'm not sure about the logistics of how this would work, but removing checks without a TTL might make sense (although it puts the emphasis on the user to make sure the TTL is set, otherwise the check will disappear)

**Comment by portertech** [comment]
Perhaps we should add support to the Sensu API for `DELETE /results/:client/:check`, so users can remove this "zombie" checks using something  like Uchiwa.

@jaxxstorm What do you think?

![299](https://cloud.githubusercontent.com/assets/149630/10592164/26f59018-766f-11e5-8dc0-1d2ed9aaa186.gif)

**Comment by jaxxstorm** [comment]
Seems ideal to me, let's do it!

**Comment by law** [comment]
I would be interested in seeing this feature be implemented, please.  Currently dealing with a LOT of stale checks that don't seem to want to go away.

**Comment by calebhailey** [comment]
It looks like this issue was resolved in [Sensu 0.21][1]: 

> Added the Sensu API DELETE /results/:client/:check endpoint, supporting check result deletion via the Sensu API. This feature allows users to clean up "stale" check result data for checks that have been removed.

Having said that, it doesn't seem to be documented yet, so I created https://github.com/sensu/sensu-docs/issues/361 to track that effort. I'll go ahead and close this ticket now. 


[1]: https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0210---2015-11-13
