### ISSUE TITLE
Support for "aggregate checks"

### ISSUE THREAD

**Issue by apognu** [sensu/sensu#1041]
Hi there,

I'm not sure the title really conveys what I'm trying to say here, let me explain.

One of the thing I want to monitor is a Mesos cluster, which runs Docker. One of my checks would be "I need to have at least three instances of this Docker container *across my whole cluster"*.

The same paradigm could be applied to some other datacenter-oriented OS's, with a check that would be triggered if the total available RAM across the cluster falls beneath a certain point.

At this moment, to my knowledge, checks only apply to a single node's context.

Thank you for your ideas and suggestions.

Regards,
A.

**Comment by portertech** [comment]
Hello @apognu, this functionality currently available Sensu core, and is known as check aggregates :+1: You can add the check definition attribute `"aggregate": true` (https://sensuapp.org/docs/latest/checks#definition-attributes) to any check definition and an aggregate will be created for each execution. Sensu check aggregates are "lazy", int that there is technically no end to one, you can query the check aggregates via the Sensu API https://sensuapp.org/docs/latest/api-aggregates

**Comment by br0ch0n** [comment]
Just to be clear, there is or is not support for standalone aggregates yet?  I see a few different open issues/PRs about this.  Unless I'm missing something, my only option for standalone aggregates at this point is to make a check querying/aggregating redis data directly like @solarkennedy has done with his cluster check script. @portertech , is this true?

**Comment by calebhailey** [comment]
Tagged this for renewed discussing in #1218.

**Comment by calebhailey** [comment]
A proposal for "aggregates 2.0" has been published as a comment on issue #1218. Barring any objections, this proposal will be implemented in Sensu 0.24 and will resolve this issue.

**Comment by portertech** [comment]
Aggregates 2.0 has been merged into the release/0.24 branch https://github.com/sensu/sensu/pull/1273 Sensu 0.24 will be available sometime next week.
