### ISSUE TITLE
Resolved issues not clearing from events in API and Uchiwa

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu#1051]
I have a reoccurring issue that I cant figure out and I found this issue (https://github.com/sensu/uchiwa/issues/329) That made me realize that other ppl are having it too... 

The check this always happens on is CPU check from the sensu community plugins https://github.com/sensu/sensu-community-plugins/blob/master/plugins/system/check-cpu.rb 
A system will have a brief CPU spike but then return to normal however the check will not resolve its self.. It still shows up in the events section of the api and Uchiwa... 
To resolve the issue I usually delete the machine from uchiwa and sensu and then let it re register. 

My only guess is the flap threshold? could this cause this??
Thanks!! 
Here is my events data from the API.
[
  {
    "id": "4e124e77-ff29-4e83-9f92-04765c0561ee",
    "client": {
      "name": "service1.prod.dub",
      "address": "10.100.100.20",
      "subscriptions": [
        "dub-prod",
        "service",
        "base"
      ],
      "version": "0.17.0",
      "timestamp": 1441982124
    },
    "check": {
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check_cpu.rb -w 90 -c 95",
      "handlers": [
        "chef_node",
        "graphite_notify"
      ],
      "standalone": true,
      "interval": 180,
      "notification": "CPU issue",
      "occurrences": 1,
      "refresh": 300,
      "event_description": "System CPU Issues!",
      "low_flap_threshold": 5,
      "high_flap_threshold": 25,
      "name": "check_cpu",
      "issued": 1441982132,
      "executed": 1441982132,
      "duration": 1.235,
      "output": "CheckCPU TOTAL OK: total=78.15 user=35.29 nice=0.0 system=10.92 idle=21.85 iowait=0.0 irq=0.0 softirq=0.0 steal=31.93 guest=0.0\n",
      "status": 0,
      "history": [
        "0",
        "2",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0"
      ],
      "total_state_change": 17
    },
    "occurrences": 14,
    "action": "flapping"
  },
  {
    "id": "361db35d-47c7-45cd-bf31-cc3c812ef60c",
    "client": {
      "name": "scheduler1.prod.dub",
      "address": "10.100.100.15",
      "subscriptions": [
        "dub-prod",
        "scheduler",
        "base"
      ],
      "version": "0.17.0",
      "timestamp": 1441982179
    },
    "check": {
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check_cpu.rb -w 90 -c 95",
      "handlers": [
        "chef_node",
        "graphite_notify"
      ],
      "standalone": true,
      "interval": 180,
      "notification": "CPU issue",
      "occurrences": 1,
      "refresh": 300,
      "event_description": "System CPU Issues!",
      "low_flap_threshold": 5,
      "high_flap_threshold": 25,
      "name": "check_cpu",
      "issued": 1441982186,
      "executed": 1441982186,
      "duration": 1.387,
      "output": "CheckCPU TOTAL OK: total=14.15 user=3.77 nice=0.0 system=0.94 idle=85.85 iowait=0.0 irq=0.0 softirq=0.0 steal=9.43 guest=0.0\n",
      "status": 0,
      "history": [
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0"
      ],
      "total_state_change": 0
    },
    "occurrences": 70,
    "action": "flapping"
  },
  {
    "id": "1688586a-78b0-4676-898a-cd97a09629e8",
    "client": {
      "name": "scheduler2.prod.dub",
      "address": "10.100.100.10",
      "subscriptions": [
        "dub-prod",
        "scheduler",
        "nfsclient",
        "asterisk",
        "base"
      ],
      "version": "0.17.0",
      "timestamp": 1441982290
    },
    "check": {
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check_cpu.rb -w 90 -c 95",
      "handlers": [
        "chef_node",
        "graphite_notify"
      ],
      "standalone": true,
      "interval": 180,
      "notification": "CPU issue",
      "occurrences": 1,
      "refresh": 300,
      "event_description": "System CPU Issues!",
      "low_flap_threshold": 5,
      "high_flap_threshold": 25,
      "name": "check_cpu",
      "issued": 1441982289,
      "executed": 1441982289,
      "duration": 1.244,
      "output": "CheckCPU TOTAL OK: total=48.04 user=26.47 nice=0.0 system=3.92 idle=51.96 iowait=0.0 irq=0.0 softirq=0.0 steal=17.65 guest=0.0\n",
      "status": 0,
      "history": [
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "2",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0"
      ],
      "total_state_change": 10
    },
    "occurrences": 8,
    "action": "flapping"
  }
]

**Comment by joshzitting** [comment]
Dug a little deeper and found this issue #959 I guess maybe it does have to do with my flapping. I will take the flapping setting out and see if it gets better...

**Comment by portertech** [comment]
Hey @joshzitting, sorry for the very late response. Your event data does show an outdated Sensu client (`"version": "0.17.0"`), I recommend upgrading your Sensu servers and clients to fix flap detection :+1:

**Comment by portertech** [comment]
An upgrade to a recent version of Sensu (0.20.6) will solve this issue.
