### ISSUE TITLE
deb is missing for version 0.20.4 and 0.20.5

### ISSUE THREAD

**Issue by psychonaut** [sensu/sensu#1054]
Sensu 0.20.4 and 0.20.5 are already released but on http://repos.sensuapp.org/apt there is 0.20.3 as latest. 

Is deb building still supported? Or should I switch to gem (or private build)

**Comment by teadur** [comment]
+1

**Comment by portertech** [comment]
The Sensu build box that was donated by EOL has been unexpectedly terminated :-1: A new Sensu build box is under construction, improvements to the pipeline are also in progress.

**Comment by psychonaut** [comment]
thank you.

**Comment by portertech** [comment]
Still working on this :-1:

**Comment by teadur** [comment]
Any ideas on timeline ?
Maybe we can help somehow to speed up the proccess ?

**Comment by portertech** [comment]
The Sensu core repositories have moved (new build pipeline) - https://sensuapp.org/docs/latest/install-repositories - containing all of the 0.20.x release packages, including 0.20.6-1 :+1: 

e.g. http://repositories.sensuapp.org/apt/

repos.sensuapp.org has been deprecated and will no longer receive updates. We plan to send out a newsletter and survey next week to notify users.

**Comment by psychonaut** [comment]
Thank you very much. :+1:
