### ISSUE TITLE
Sensu client 0.20.3 on Windows having Windows handles leak

### ISSUE THREAD

**Issue by sombut** [sensu/sensu#1057]
Hi,

I found an issue where our Windows boxes that running the sensu-client (ruby) are having the Windows handles leaks. This happened for a long time and I've tried to upgrade to the sensu 0.20.3 as well as upgrade the ruby to the latest 2.0.0.p647 but still found this problem.

The number of Windows handles leaks depends on how frequent of the check running (check interval). I've setup a test box and configure a simple check that setting the check interval to 1 second, the number of handles will be increasing very quickly. You can use this as a reproduce step.

To see the number of Windows handles you need to enable it manually.
Please follow the below steps:
1) Start the task manager
2) Go to Views -> Select Column
3) Select Handles
4) Sort by the column of Handles 
5) You will see the ruby of sensu is the most consumed of the Windows handles

![image](https://cloud.githubusercontent.com/assets/11056237/10015823/cb2f20f0-614c-11e5-9020-06bdf896b7b4.png)

Thanks,
Sombut

**Comment by portertech** [comment]
@sombut thank you for reporting :+1: Do you have a way to identify what the handles are being used for (specifically)?

**Comment by portertech** [comment]
Probably due to https://github.com/jarib/childprocess/blob/master/lib/childprocess/windows/handle.rb

**Comment by portertech** [comment]
I need to add a platform conditional to the upfront childprocess requires in sensu-spawn: https://github.com/sensu/sensu-spawn/blob/master/lib/sensu/spawn.rb#L10-L14

**Comment by sombut** [comment]
Hi @portertech 

Thanks for the update. I'm going to investigate this more. The quick look is the most handle type consumed by the ruby process is Job. I'll let you when having more details about this issue 

![image](https://cloud.githubusercontent.com/assets/11056237/10041802/3a05fa5c-6211-11e5-864c-51051a3f5e2d.png)

**Comment by sombut** [comment]
Hi Sean

Just giving more information. The job handles that leaked has no name associated to them so only these info available from the process explorer. 

![image](https://cloud.githubusercontent.com/assets/11056237/10162713/4fe9b884-66d7-11e5-93fa-baea4231cf68.png)

**Comment by portertech** [comment]
Thank you @sombut, I should have some more time this week to push a possible solution.

**Comment by sombut** [comment]
Hi @portertech, just for checking if you have any chance to look at this issue. Please feel free to let me know if any further information required. Thank you.

Regards,
Sombut

**Comment by portertech** [comment]
Hey @sombut, I believe you have provided enough to help me get started. I keep getting pulled in other directions, however, this issues is a top priority for the next Sensu core release. Thank you for keeping this on my radar :+1:

**Comment by portertech** [comment]
@sombut just waiting on https://github.com/jarib/childprocess/pull/94 to be merged and released.

**Comment by portertech** [comment]
@sombut Thank you for your help! :+1:

**Comment by sombut** [comment]
@portertech Thank you too.
