### ISSUE TITLE
Request processing times in sensu-api log

### ISSUE THREAD

**Issue by somic** [sensu/sensu#1061]
Right now sensu-api calls request_log_line _before_ request is processed. As a result, timestamp in the log file corresponds to when request was received AND log file has no information about how long sensu-api took to process the request.

If logging is moved to _after_, timestamp will now correspond to when request was finished but we gain ability to also log how long the request took to process.

Wondering what everybody thinks about this potential change.

**Comment by portertech** [comment]
@somic we should be logging the request and then the response. I would gladly accept a PR that is able to wire into Rack for the response details.

**Comment by somic** [comment]
So 2 log entries per request - one with information about request (what we have now) and another with information about response? I am also guessing we don't need to log entire response, just something like say size of response?

**Comment by portertech** [comment]
@somic status code and content length would be sufficient :+1:

**Comment by portertech** [comment]
Hey @somic, did you have a go at this?

**Comment by somic** [comment]
Sorry, no, didn't event start looking into this yet. If you have available cycles now, please feel free to take it. If not, I do hope to do something for this, I just don't know when.

**Comment by portertech** [comment]
There may be issues with logging API query responses with async Sinatra. I do not currently plan to work on this feature.

**Comment by somic** [comment]
@portertech What about something like this - https://github.com/somic/sensu/commit/19798eb6be59090590a2a5a64f7e8b3ac0ed3340

**Comment by portertech** [comment]
@somic is `@request_start_time` scoped to the single request?

**Comment by somic** [comment]
Yes, based on my reading of http://www.sinatrarb.com/intro#Request/Instance%20Scope

**Comment by portertech** [comment]
@somic Awesome :+1: Perhaps use an epoch timestamp and make the log event look more like the request log line with more context?

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1607 implements this.
