### ISSUE TITLE
Correct RHEL/CentOS yum repo URL?

### ISSUE THREAD

**Issue by queeno** [sensu/sensu#1062]
Hi there,

As reported by @joseofarrill-work in queeno/ansible-uchiwa#2, the new official sensu yum repo url is: `http://repos.sensuapp.org/yum/el/$basearch/` according to the [sensu documentation](https://sensuapp.org/docs/0.20/install-repositories).

This replaces the old sensu repo url which looks like this: `http://repos.sensuapp.org/yum/el/$releasever/$basearch/`. In fact, `$releasever` is set to `latest` on some systems (AWS free tier AMI) which results in an inexistent URL.

Browsing in http://repos.sensuapp.org, I have noticed that you are still updating the `http://repos.sensuapp.org/yum/el/$releasever/$basearch` repos, for example `http://repos.sensuapp.org/yum/el/6/x86_64/`. The expected new repo pattern `yum/el/$basearch` appears to exist for yum-unstable only: http://repos.sensuapp.org/yum-unstable/el/x86_64.

Could you please clarify which yum URL we should use to install sensu?

**Comment by portertech** [comment]
Hey @queeno, the `$releasever` directories should just be links, as we currently only build the omnibus RPMs on CentOS 5. I will check the stable repository to ensure the same links are in place.

**Comment by portertech** [comment]
@queeno The Sensu core repositories have moved (new build pipeline) - https://sensuapp.org/docs/latest/install-repositories

Example: `http://repositories.sensuapp.org/yum/$basearch` (the `el` and `$releasever` symlinks still exist)

**Comment by queeno** [comment]
@portertech Thanks very much! I like the new sensu repo :+1:
