### ISSUE TITLE
Exit codes >1 hide RESOLVEs

### ISSUE THREAD

**Issue by jeremybz** [sensu/sensu#1067]
Noticed a strange behaviour with handlers: when handling checks which have multiple possible statuses,  handlers ignore RESOLVEs for certain sequences (for example: 1,1,1,2,0,0,0).

I isolated it to results of the following standalone check:
{  "checks": { "EXIT_CODE_TESTING": {
      "command": "perl -e 'exit `cat /tmp/exitcode.txt`'",
      "interval": 5,
      "occurrences": 3,
      "standalone": true,
      "handlers": [
        "default"
      ] } } }

Changing /tmp/exitcode.txt to 0, 1, 2 gives the following results:
0, 0, 0, 1, 1, 1, 0,  => Works as expected, all handlers report a FAIL and a RESOLVE
0, 0, 0, 1, 1, 1, 2, 2, 2, 0 => Works as expected, FAIL, OTHER, RESOLVE
0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0... => Only FAIL, no RESOLVE. Server log reports: "not enough occurrences" message in all handlers.
0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0... => Same problem, no RESOLVE.

I think this is due to server's process.rb, which does not update event[:occurrences] if the current fail status is different from the previous fail status, but I don't know enough about sensu (or ruby) to actually figure it out and submit a patch.
https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L345
I am using version 0.20.3

**Comment by portertech** [comment]
@jeremybz event "occurrences" represents a count of recurrences of a single state (e.g. status: 2), not non OK as you may be expecting. The filtering logic that you are referring to is in the sensu-plugin library, that is used by most community event handlers https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-handler.rb#L97

**Comment by portertech** [comment]
@jeremybz we could use event check history (21 exist status codes) for non OK recurrence filtering, instead of event occurrences.

**Comment by jeremybz** [comment]
I tried adding a new 'nonzero_occurrences' variable to handle the problem, as parsing the history left me feeling uneasy.  I am not skilled at git or ruby, please let me know if this is horribly wrong.

https://github.com/sensu-plugins/sensu-plugin/pull/97
https://github.com/sensu/sensu/pull/1069

**Comment by jeremybz** [comment]
Ok, that was awful.  I've tried using history (like you originally suggested).  This seems to work:
https://github.com/sensu-plugins/sensu-plugin/pull/98

What should sensu do with a status sequence like 1,1,2,1,2,1 ?

**Comment by portertech** [comment]
Hey @jeremybz, we should create a new event attribute to store the last epoch timestamp that the client/check pair produced a result with an OK status. We can then use this timestamp for alert filtering, using time instead of occurrences.

**Comment by jeremybz** [comment]
Hi @portertech,
Thanks!  I want to start by writing some unit tests, but I can't seem to get them to work.
I'm trying to add to filter_spec.rb:
    handler = {
      :severities => ["critical","warning","ok","unknown"]
    }
    @event[:check][:occurrences] = 3
    @event[:check][:history] = [1, 1]
    @event[:check][:status] = 0
    expect(@server.handle_action?(@handler, @event)).to be(false)

But this somehow generates a true.
Can you point me in the right direction?

**Comment by kshep** [comment]
@portertech Is this a recurrence of https://github.com/sensu-plugins/sensu-plugin/issues/47?

Fix in https://github.com/sensu-plugins/sensu-plugin/pull/48, but then regressed in https://github.com/sensu-plugins/sensu-plugin/pull/50?

**Comment by jeremybz** [comment]
@kshep @portertech is there anything I can do to help?  I'm low on technical skill but extremely motivated to fix this.

**Comment by jeremybz** [comment]
I fixed it here:
https://github.com/sensu-plugins/sensu-plugin/pull/107
Please let me know what you think.

**Comment by xyntrix** [comment]
After read this, I think this is why we've seen issues like this:  https://github.com/sensu/sensu/issues/1097
Will try to test your code @jeremybz if I find a few moments here.

**Comment by xyntrix** [comment]
We've reproduced this in 0.21, specifically this causes keepalive clear/resolves to not engage the defined handler (not enough occurrences) if the previous sequence of consecutive alarm levels (warn/crit) do not meet the total number of defined occurrences.

Ex:  if occurrences=3,  and we have a history of:  0,1,1,1,2,2,0  the handler will not execute on that last clear, and will return "not enough occurrences.   

We expect the behavior such that if the state changes to clear, we ship the clear.   I wonder if there shouldn't be a logic flag of "ignore_occurrences_on_clear"?

**Comment by kshep** [comment]
It seems to me a long term fix for this would handle a few different scenarios, once a Critical check triggers a page/event. One might want to clear the event...

* ... the first time the check returns an OK value
* ... the first time the check returns a value other than Critical
* ... after the check returns N OK values
* ... after the check returns N non-Critical values

**Comment by skymob** [comment]
What are people using as a work-around for this? Not receiving a RESOLVE email is a minor annoyance for us, but when an event triggers a pagerduty event, it's a little more problematic to not have the event resolved via the pagerduty handler.

**Comment by kshep** [comment]
@skymob I'm a little embarrassed to admit we're still on 0.20.3 and sensu-plugin 1.2. I figure we'll get current once this issue is resolved. Meanwhile. I've hacked https://github.com/sensu-plugins/sensu-plugin/blob/v1.2.0/lib/sensu-handler.rb#L111 and instead of:

```
      if @event['occurrences'] < occurrences
        bail 'not enough occurrences'
      end
```

we're just brute forcing things with:

```
      if @event['occurrences'] < occurrences && @event['action'] != 'resolve'
        bail 'not enough occurrences'
      end
```

**Comment by cwjohnston** [comment]
Hi @jeremybz @xyntrix @kshep @skymob ! Sorry that this remains an issue for you and so many others. 

I've opened sensu-plugins/sensu-plugin#134 to document my thoughts around a meaningful solution to this problem, which I believe involves deprecating and eventually removing filtering from the Sensu::Handler class. If you have any thoughts you'd like to share in that issue, your feedback is much appreciated. Thanks!

**Comment by calebhailey** [comment]
I wonder if we can close this now? We've made a number of [improvements around occurrence filtering](https://github.com/sensu/sensu-extensions/pull/11), which appears to have been the source of the issue here, including a PR that [specifically addressed issues related to resolutions](https://github.com/sensu-extensions/sensu-extensions-occurrences/pull/2). 

Barring any new updates to this issue indicating otherwise, we will look to close this issue due to inactivity at our next issue triage. :v:

**Comment by portertech** [comment]
Sensu release >= 0.26 include the "occurrences" built in feature, which uses the event `occurrences_watermark` attribute to solve this problem - https://github.com/sensu-extensions/sensu-extensions-occurrences/blob/master/lib/sensu/extensions/occurrences.rb#L26

In your handler definition: `"filters": ["occurrences"]`
