### ISSUE TITLE
sensu-client changelog and github repo

### ISSUE THREAD

**Issue by dodedodo** [sensu/sensu#1068]
Hi,

Where can I find info on the sensu client, like a changelog and how often it's updated? Is there a github page? I'm mainly interested in the windows sensu-client.

The only information about the sensu-client I could find was on this page http://repos.sensuapp.org/index.html  

Thank you in advance.

~
Thijs

**Comment by portertech** [comment]
Hello @dodedodo, the Sensu core changelog can be found at https://github.com/sensu/sensu/blob/master/CHANGELOG.md The latest version of the Sensu package (includes the Sensu client) can be found at http://repositories.sensuapp.org/apt/pool/sensu/main/s/sensu/
