### ISSUE TITLE
repos.sensuapp.org missing sensu-0.20.6

### ISSUE THREAD

**Issue by sureshsubramaniam** [sensu/sensu#1072]
The repo is not updated with the latest release of the Sensu, whether the repo has been moved to a different URL ?

**Comment by portertech** [comment]
Hey @sureshsubramaniam, the Sensu core repositories have moved (new build pipeline) - https://sensuapp.org/docs/latest/install-repositories

e.g. http://repositories.sensuapp.org/apt/

repos.sensuapp.org has been deprecated and will no longer receive updates. We plan to send out a newsletter and survey next week to notify users.

**Comment by portertech** [comment]
Closing this one :boom:
