### ISSUE TITLE
windows encode issue

### ISSUE THREAD

**Issue by samahee** [sensu/sensu#1073]
{"timestamp":"2015-10-17T04:30:04.990838+0900","level":"info","message":"received check request","check":{"name":"check-windows-cpu-load","issued":1445023652,"command":"/etc/sensu/plugins/check-windows-cpu-load.rb"}}
{"timestamp":"2015-10-17T04:30:05.037713+0900","level":"warn","message":"reconnecting to transport"}
C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `encode': "\xC1" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `to_json'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `dump'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:127:in `create_log_event'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:51:in `add'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:31:in `block (2 levels) in create_level_methods'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:88:in `publish_check_result'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:157:in `block in execute_check_command'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-worker-0.0.2/lib/em/worker.rb:21:in `call'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-worker-0.0.2/lib/em/worker.rb:21:in `block (2 levels) in do_task'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:951:in `call'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:951:in `run_deferred_callbacks'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run_machine'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:18:in `run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-client:10:in `<top (required)>'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `load'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `<main>'

**Comment by samahee** [comment]
sorry my misstaken

**Comment by portertech** [comment]
@samahee no longer an issue?
