### ISSUE TITLE
feature/add jit_origin to jit client data

### ISSUE THREAD

**Issue by roobert** [sensu/sensu#1075]
Currently there is no way to tell the origin of a check with `:source` defined. Adding a `jit_origin` parameter to check event data would add context to the check event data.

**Comment by portertech** [comment]
:+1: Yes to this.

![1338](https://cloud.githubusercontent.com/assets/149630/10592241/ac75f37c-766f-11e5-8e61-0d8012a633e4.gif)

**Comment by calebhailey** [comment]
Looks like this one fell of the radar, but it should be really easy to implement in 0.24.

**Comment by roobert** [comment]
@calebhailey good stuff!

**Comment by calebhailey** [comment]
I propose we call the attribute `origin`.

**Comment by portertech** [comment]
#1267 was merged, adding this feature :+1:
