### ISSUE TITLE
is there any down side when using Redis version 3.0.x

### ISSUE THREAD

**Issue by chrisduong** [sensu/sensu#1076]
Hi,

I wonder if it is OK to use **Sensu** with Redis version 3.0.x. I wanted to use the latest stable Redis for some advanced feature (maybe later).

Thanks a lot.

**Comment by JackBauer8301** [comment]
Hi @chrisduong ,
there should be no issues with using Redis 3.0.x . I have my Sensu instance set to use Redis 3.0.5 and it's been working as expected.

Hope that helps

**Comment by chiriaev** [comment]
Guys, Hi. Same here. Using it from "3.0.3". Upgrading to "3.0.5" today.
Regards, Andrei

**Comment by chrisduong** [comment]
Thanks all.

I was worried about this issue: https://github.com/sensu/sensu/issues/1029. But turn out it is a feature :).
