### ISSUE TITLE
Sensu server does not send the extension name for checks 

### ISSUE THREAD

**Issue by franceesco** [sensu/sensu#1078]
Sensu server does not include the extension name in the payload when publishing checks to clients, the problem is in the embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.6/lib/sensu/server/process.rb file:
payload[:command] = check[:command] if check.has_key?(:command)
payload[:source] = check[:source] if check.has_key?(:source)
Here the extension should be added after the line 500 which adds the source:
payload[:extension] = check[:extension] if check.has_key?(:extension)
(Extension checks work only if the extension name and the check name is the same because the client uses check name as fallback when it doesn't find the extension field.)

**Comment by franceesco** [comment]
The problem is the same with the extension options, this object isn't passed to the client either.
E.g.: the haproxy check extension (https://github.com/sensu/sensu-community-plugins/blob/master/extensions/checks/haproxy.rb) expects an object assigned to the "haproxy" key in the check object (e.g.: in line 186) which it never gets.
It would be nice if there was an optional "options" field in the check settings besides the name, command etc. attributes which would be sent to the client.

**Comment by portertech** [comment]
@franceesco we will accept a PR to add extension to the request payload if it exists :+1:

**Comment by gsalisbury** [comment]
I'd like to have a go at this if you're not already working on it @franceesco ?

**Comment by franceesco** [comment]
@gsalisbury Feel free, I haven't had the time.

**Comment by gsalisbury** [comment]
I've opened PR #1082 for this.

**Comment by calebhailey** [comment]
Closing this as it looks like this was merged a long time ago! \o/ 

#monitoringlove
