### ISSUE TITLE
Check request via sensu API doesn't get executed if subscribers are roundrobin style

### ISSUE THREAD

**Issue by epierotto** [sensu/sensu#1083]
I've got a pool of sensu clients that are subscribed in a roundrobin style, trying to execute a check via sensu API pointing the request to the roundrobin subscription I get a success 202 but no action is performed by the client. 
I've looked into the client's log and it doesn't receive any check execution or errors regarding the request.
Just changing the subscription to a normal one I get the same 202 but the check is executed as expected.

**Comment by portertech** [comment]
@epierotto thank you for reporting, this was overlooked.

**Comment by portertech** [comment]
Hey @epierotto, I just pushed https://github.com/sensu/sensu/pull/1104 if everything goes green, you can expect it in the next Sensu Core release, which is soooon! :+1:
