### ISSUE TITLE
Sensu snmptrap listener: feature

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1086]
I am considering writing an in-process SNMP trap listener for Sensu, which would behave like the client tcp socket listener, and be an optional (default: off) feature.   This would allow for rapid integration with  enterprise hardware vendor monitoring/management daemons which emit SNMP traps (Dell, HP, SuperMicro, Cirrascale, etc).

I am then also looking to write a server extension to map specific OIDs against a stored set of MIBs as well as a generic catch-all MIB translator, which would be used by handlers and/or mutators.  

Does this sounds useful for the community, or would this type of feature clash with the general design ideals around the Sensu client?

I noticed Cloudant has a python external daemon for this (https://github.com/cloudant/sensu-trapd), but I'd rather not have to run a second daemon or manage all of the colorful Python dependencies across various o/s releases (an omnibus'd/embedded Python+pysnmp release would make this moot).

**Comment by portertech** [comment]
@xyntrix a Sensu check extension to does this functionality would be awesome, then it's simply an opt-in via putting it in `/etc/sensu/extensions` :+1:

**Comment by portertech** [comment]
@xyntrix A good example of a check extension that listens on a socket and periodically sends check results is https://github.com/sensu/sensu-community-plugins/blob/master/extensions/checks/statsd.rb

**Comment by xyntrix** [comment]
Cool. Thanks for the feedback on this.  Closing.

**Comment by joemiller** [comment]
@xyntrix  +1
