### ISSUE TITLE
apt repository - no updates since 0.20.3-1

### ISSUE THREAD

**Issue by heffergm** [sensu/sensu#1088]
Is there any plan to fix the apt repository? It doesn't appear that the chef cookbook supports another installation method, so I'm currently stuck at 0.20.3-1 as no updates have been published to the repo since.

```
grant@sensu-server3:~$ sudo apt-get update && sudo apt-cache madison sensu
Ign http://repos.sensuapp.org sensu InRelease
.....
Reading package lists... Done
     sensu |   0.20.3-1 | http://repos.sensuapp.org/apt/ sensu/main amd64 Packages
     sensu |   0.20.2-1 | http://repos.sensuapp.org/apt/ sensu/main amd64 Packages
     sensu |   0.20.1-1 | http://repos.sensuapp.org/apt/ sensu/main amd64 Packages
...
```

**Comment by palourde** [comment]
Hi @heffergm, the Sensu core repositories have moved (new build pipeline) - https://sensuapp.org/docs/latest/install-repositories

e.g. http://repositories.sensuapp.org/apt/

repos.sensuapp.org has been deprecated and will no longer receive updates. We plan to send out a newsletter and survey next week to notify users.

**Comment by heffergm** [comment]
Perfect, thanks.
