### ISSUE TITLE
Sensu 0.20 crashing by itself after running for quite lot of time. 

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/sensu#1089]
Sensu Version: 0.20.3 and 0.20.6 (observed in both clusters)
Redis: 3.x
Rabbitmq: RabbitMQ 3.5.4, Erlang 17.4

We noticed that all the sensu servers in our environment crashed at around 02:00 am. I pulled out some relevant parts from the last log. We have a relay handler connecting to graphite server (using WizardWan https://github.com/opower/sensu-metrics-relay). When sensu runs, the metrics are correctly getting pushed to graphite. MAX_QUEUE_SIZE set to 128 in WIZARDWAN config. 

{"timestamp":"2015-11-05T02:03:05.075724-0800","level":"info","message":"Connection closed unintentionally."}
{"timestamp":"2015-11-05T02:03:05.075915-0800","level":"info","message":"Scheduling reconnect in  seconds for relay channel: graphite."}
{"timestamp":"2015-11-05T02:03:05.886094-0800","level":"info","message":"Attempting to reconnect relay channel: graphite."}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:776:in `connect_server': no implicit conversion of String into Integer (TypeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:776:in `reconnect'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/connection.rb:628:in `reconnect'
        from /etc/sensu/extensions/handlers/relay.rb:86:in `block in reconnect'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:23:in `run'
 ESCOC

**Comment by portertech** [comment]
Same as #1090 (not Sensu core, it's an issue with the metric relay extension).

**Comment by portertech** [comment]
Closing this issue, as it's either a configuration error or a bug in https://github.com/opower/sensu-metrics-relay

**Comment by kaushiksriram100** [comment]
yes, this was a config issue. we correct our cookbook as well. Thank you
very much.

**Comment by grbulat** [comment]
Same issue here.
@kaushiksriram100 Do you remember the solution? 
[link](https://github.com/opower/sensu-metrics-relay/blob/master/lib/sensu/extensions/handlers/relay.rb#L184) is broken now.
