### ISSUE TITLE
Redis reconnect_on_error doesn't work for cluster failover

### ISSUE THREAD

**Issue by davent** [sensu/sensu#1094]
When using reconnect_on_error for the Redis connection, Sensu will stop completely if the Redis server it is connected to becomes a Slave (i.e. during master/slave failover). This is in keeping with the comments in the source:

    # The Sensu
    # service will stop gracefully in the event of a Redis error, and
    # pause/resume in the event of connectivity issues.

However, as during master/slave failover the actual connection is not lost then no reconnect is attempted.

**Comment by portertech** [comment]
@davent using HAProxy to facilitate the failover?

**Comment by davent** [comment]
I have tried with HAProxy 1.5 and also AWS ElsatiCache

**Comment by portertech** [comment]
@davent are you able to configure HAProxy to kill the Sensu connection if the backend connection (Redis) dies? The opposite of redispatch.

**Comment by zbintliff** [comment]
We are using AWS ElastiCache with a 3 cluster Replication Group.  When manually failing over we get the following log line in sensu-server.log:
```
{"timestamp":"2015-12-07T17:32:16.058198+0000","level":"fatal","message":"redis connection error","error":"Redis server returned error code: READONLY You can't write against a read only slave."}
{"timestamp":"2015-12-07T17:32:16.058326+0000","level":"warn","message":"stopping"}
{"timestamp":"2015-12-07T17:32:16.058384+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-12-07T17:32:16.058565+0000","level":"warn","message":"resigning as leader"}
{"timestamp":"2015-12-07T17:32:16.058652+0000","level":"info","message":"completing event handling in progress","handling_event_count":0}
{"timestamp":"2015-12-07T17:32:16.058826+0000","level":"warn","message":"reconnecting to redis"}
{"timestamp":"2015-12-07T17:32:16.058877+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-12-07T17:32:16.558929+0000","level":"warn","message":"stopping reactor"}
```

We are running version 20.3 and here is our redis.json:
```
{
  "redis": {
    "port": 6379,
    "host": "CNAME to Redis",
    "reconnect_on_error": true,
    "db": 0,
    "auto_reconnect": true
  }
}
```
We tested it with a redis reboot, and it recovered fine but the failover it was unable and the process stops.  Once we start the process again everything continues normally.

**Comment by davent** [comment]
@zbintliff This was also my result when tested with ElastiCache. The connection to the cluster is not lost so when the Redis Master becomes a slave, and goes in to read-only mode, the client attempts to write and gets the read-only error message which it treats as terminal and stop the application entirely.

This is a real shame as if this didn't happen it would be simple, with the use of Rabbit Federation as well, to really easily great a fully HA Sensu setup.

**Comment by davent** [comment]
Here is my original suggestion to a fix: https://github.com/sensu/sensu/pull/920/files

It was discounted due to "It is built into the Redis client." However, in this instance that does not appear to be the case. Making this change, which was just taken from the RabbitMQ client code a few lines above, appears to work well. For me anyway :)

**Comment by calebhailey** [comment]
@davent hi there. :) 

I'm curious if the new native Redis Sentinel support in Sensu 0.23 might resolve this issue for you? See here: https://sensuapp.org/docs/0.23/changelog and here: https://sensuapp.org/docs/0.23/redis#configuring-sensu-for-ha-redis 

I'm going to go ahead and close this with the assumption that this solution will resolve this issue, but please feel free to open a new issue if you disagree. :) #monitoringlove

**Comment by zbintliff** [comment]
Hey @davent  have you tested with ElatiCache yet?  Its in our backlog. Will update when/if we get to it.
