### ISSUE TITLE
Please securely distribute repository signing keys

### ISSUE THREAD

**Issue by CVTJNII** [sensu/sensu#1099]
Per https://sensuapp.org/docs/latest/install-repositories the following gpg key is to be used on Debian based systems:  http://repositories.sensuapp.org/apt/pubkey.gpg.  This key is being distributed via HTTP, which leaves it vulnerable to man in the middle attacks.  The key is not available securely via HTTPS due to certificate issues:

```
curl https://repositories.sensuapp.org/apt/pubkey.gpg
curl: (51) SSL: no alternative certificate subject name matches target host name 'repositories.sensuapp.org'
```

Also, per https://sensuapp.org/docs/latest/install-repositories gpg signing is not available for Yum based systems (gpgcheck=0 in the repo definition).

Not using GPG opens Sensu users to attack via the Sensu repositories as client systems have no way to validate that the software they're downloading is correct.  This vector could be used to install malicious software on client machines.  Please create (if needed) and securely distribute signing keys for your repos so that users can trust they're secure.  Thank you.

**Comment by rs-mrichmond** [comment]
Merely putting the pubkey.gpg file in the github repo would solve the first https problem at no real cost.

**Comment by portertech** [comment]
The GPG key is available at https://sensu.global.ssl.fastly.net/apt/pubkey.gpg

**Comment by pkaeding** [comment]
Is that same GPG key used for the yum packages as well?
