### ISSUE TITLE
sensu-install update

### ISSUE THREAD

**Issue by stephan13360** [sensu/sensu#1114]
Hi, just installed my plugins with sensu-install instead of gem install and now i am wondering how do i keep my plugins updated. sensu-install doesen't seem to have an update option.

**Comment by portertech** [comment]
Hi @stephan13360, you can update sensu plugin gems with sensu-install, by specifying a newer or the latest release, e.g. `sensu-install -v -p mysql:0.0.7`

Documentation can be found at https://sensuapp.org/docs/latest/plugins#sensu-install-example

We highly recommend installing specific versions at all times.

**Comment by portertech** [comment]
Please close this issue if this helps :+1:
