### ISSUE TITLE
test server config before restarting service

### ISSUE THREAD

**Issue by davidneudorfer** [sensu/sensu#1117]
Is it possible to test configuration changes before restarting `/etc/init.d/sensu-service server restart`

**Comment by portertech** [comment]
No, it's is not currently possible to verify configuration prior to restarting the service.

We could add a Sensu CLI argument, e.g. `--verify_config`, which would go through the steps of loading and verifying configuration, and then exit with a report.

**Comment by gsandie** [comment]
Love to see this feature added :+1:

**Comment by jmangs** [comment]
Seconding this; it would be much easier to write tests for changes people make in our Sensu configs with this.

:+1:

**Comment by calebhailey** [comment]
@davidneudorfer, @gsandie, @jmangs: this has been implemented as a new `--pring_config` or `-P` CLI argument; see here for more info: https://sensuapp.org/docs/0.23/changelog 

Documentation will get released in a few days along with https://github.com/sensu/sensu-docs/pull/346 :) 

I'm going to go ahead and close this, but feel free to create a new issue if you have any feedback on the new feature. :)

**Comment by gsandie** [comment]
@calebhailey Awesome, thanks!!

**Comment by calebhailey** [comment]
@gsandie your welcome! Let us know if you have any further questions. :-)
