### ISSUE TITLE
Packages for non x86 platforms

### ISSUE THREAD

**Issue by mtippett** [sensu/sensu#1121]
Hello,

I would like to use sensu on non-intel platforms.  However the installation guidelines are heavily distribution specific, and there is no armhf platform in the repositories.  

rabbitmq creates binary independent packages - for example http://www.rabbitmq.com/debian/dists/testing/main/

**Comment by portertech** [comment]
We can research what it will take to add support for other architectures to the pipeline.

**Comment by portertech** [comment]
This issue is related to https://github.com/sensu/sensu-build

**Comment by mtippett** [comment]
Thanks.  Since logging the defect, I've since found sensu-build.  I could follow most of the instructions at http://blog.cloudpack.jp/2014/11/17/run-sensu-client-on-raspberry-pi/  including building a dpkg.    The primary gaps seem to be around runit tests and generation of a correct architecture on armhf.

Note that I do agree that this defect should be against sensu-build.

I will self-close.
