### ISSUE TITLE
Bump thin (API) to 1.6.4

### ISSUE THREAD

**Issue by analytically** [sensu/sensu#1122]
https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L7

1.6.4 was released:
https://github.com/macournoyer/thin/blob/master/CHANGELOG

**Comment by portertech** [comment]
@analytically not really any improvement for us, but I will happily merge a PR :+1:

**Comment by calebhailey** [comment]
Tagging this for 0.24 since it's such a small change.

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1261 was merged :+1:
