### ISSUE TITLE
Sensu server crash after a redis failover

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/sensu#1123]
Hi,
We observed that 3/5 sensu servers crashed after a redis failover exactly when master redis failed over to another node (we are using sentinel). We saw these in the logs. After we started the sensu server manually in 2/3 crashed ones, they identified the new master redis and started working again. 

Here are my questions:
1. How many retry attempts will sensu attempt when it sees redis as slave? Our Haproxy settings for redis have RISE and FALL values as 1 right now. If needed we can revisit that. 
2. Based on this observation, why didn't all 5 servers crash? 3/5 crashed and we manually started 2 of them. Is that expected? 
3. Is it like sensu-servers crashed only on machines that were actively using redis and it is not necessary that all 5 sensu-server need to use redis at any given moment?

...skipping...
{"timestamp":"2015-11-25T00:59:57.202184-0800","level":"warn","message":"stopping"}
{"timestamp":"2015-11-25T00:59:57.202253-0800","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-11-25T00:59:57.202368-0800","level":"info","message":"completing event handling in progress","handling_event_count":0}
{"timestamp":"2015-11-25T00:59:57.202501-0800","level":"fatal","message":"redis connection error","error":"Redis server returned error code: READONLY You can't write against a read only slave."}
{"timestamp":"2015-11-25T00:59:57.202576-0800","level":"warn","message":"stopping"}
{"timestamp":"2015-11-25T00:59:57.202642-0800","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-11-25T00:59:57.202748-0800","level":"info","message":"completing event handling in progress","handling_event_count":0}
{"timestamp":"2015-11-25T00:59:57.202867-0800","level":"fatal","message":"redis connection error","error":"Redis server returned error code: READONLY You can't write against a read only slave."}
{"timestamp":"2015-11-25T00:59:57.202940-0800","level":"warn","message":"stopping"}
{"timestamp":"2015-11-25T00:59:57.203013-0800","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-11-25T00:59:57.203126-0800","level":"info","message":"completing event handling in progress","handling_event_count":0}
{"timestamp":"2015-11-25T00:59:57.203248-0800","level":"fatal","message":"redis connection error","error":"Redis server returned error code: READONLY You can't write against a read only slave."}
{"timestamp":"2015-11-25T00:59:57.203326-0800","level":"warn","message":"stopping"}
{"timestamp":"2015-11-25T00:59:57.203392-0800","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-11-25T00:59:57.203506-0800","level":"info","message":"completing event handling in progress","handling_event_count":0}
{"timestamp":"2015-11-25T00:59:57.203623-0800","level":"fatal","message":"redis connection error","error":"Redis server returned error code: READONLY You can't write against a read only slave."}

**Comment by portertech** [comment]
@kaushiksriram100 you can set `"reconnect_on_error": true` in your redis definition - https://sensuapp.org/docs/0.21/redis#definition-attributes This will cause Sensu to keep attempting to reconnect.

**Comment by kaushiksriram100** [comment]
@portertech  got it. I will add that. thank you very much for that pointer. Also trying to see if you have any inputs on why only few crashed?

**Comment by portertech** [comment]
@kaushiksriram100 only a few of them attempted a Redis write operation during the failover time window.

**Comment by portertech** [comment]
@kaushiksriram100 I am going to close this issue, as it looks like "reconnect_on_error" solves it for you :+1:

**Comment by tanin47** [comment]
My sensu-server still stops after I restart Redis with `service redis onerestart`. Here's the log:

```
{"timestamp":"2015-12-29T05:58:56.198354+0700","level":"warn","message":"reconnecting to redis"}
{"timestamp":"2015-12-29T05:58:56.198777+0700","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-12-29T05:58:56.199552+0700","level":"warn","message":"resigning as leader"}
{"timestamp":"2015-12-29T05:58:57.231074+0700","level":"info","message":"reconnected to redis"}
{"timestamp":"2015-12-29T05:58:58.246613+0700","level":"debug","message":"subscribing to keepalives"}
{"timestamp":"2015-12-29T05:58:58.247780+0700","level":"debug","message":"subscribing to results"}
{"timestamp":"2015-12-29T05:59:00.277057+0700","level":"fatal","message":"redis connection error","error":"Redis server returned error code: LOADING Redis is loading the dataset in memory"}
{"timestamp":"2015-12-29T05:59:00.277371+0700","level":"warn","message":"stopping"}
{"timestamp":"2015-12-29T05:59:00.277485+0700","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-12-29T05:59:00.277894+0700","level":"debug","message":"not currently the leader"}
{"timestamp":"2015-12-29T05:59:00.278003+0700","level":"info","message":"completing event handling in progress","handling_event_count":0}
{"timestamp":"2015-12-29T05:59:00.790844+0700","level":"warn","message":"stopping reactor"}
```

I wonder if this is related to the issue. Thanks!

--------

My regis config looks like this:

```
  "redis": {
    "host": "localhost",
    "port": 6379,
    "reconnect_on_error": true,
    "auto_reconnect": true
  },
```

My Sensu version is 0.21. Here's `gem list`:

```
sensu (0.21.0)
sensu-extension (1.3.0)
sensu-extensions (1.4.0)
sensu-logger (1.1.0)
sensu-settings (3.1.0)
sensu-spawn (1.6.0)
sensu-transport (3.3.0)
```
