### ISSUE TITLE
Possible to use tokens in more things than command strings?

### ISSUE THREAD

**Issue by davpx** [sensu/sensu#1126]
I'd like to be able to use tokens anywhere in a check definition if possible, not just command strings.

**Comment by portertech** [comment]
Where else would they need to be applied?

**Comment by davpx** [comment]
In the handler(s) parameter in the check definition but they may also be
useful elsewhere.

**Comment by hany** [comment]
👍 to this. It would be very helpful when combined with Uchiwa so one can embed links to Graphite/Grafana for service-specific checks that auto-fill the hostname based on tokens.

**Comment by calebhailey** [comment]
@davpx, @hany: this has been implemented in Sensu Core version 0.24, released earlier this week. \o/ 

See here: 
- Release: https://sensuapp.org/blog/2016/06/07/sensu-core-v0-24-0.html
- New "check token substitution" docs: https://sensuapp.org/docs/latest/reference/checks.html#check-token-substitution
