### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by davpx** [sensu/sensu#1127]
Add parameter that ensures a check persists state on the dashboard for a certain amount of time in seconds.

Example using check-log.rb looking for "error" every minute but I want the alert to persist on the dashboard for 5-30 minutes even if the subsequent checks within that 5-30 minutes are OK.

**Comment by portertech** [comment]
@davpx you probably want to use the check definition attribute `"auto_resolve": false`, so the event will persist (not resolving) and show on the dashboard until someone resolves it manually.

https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L354

This feature still need to be documented. We are creating an associated issue to have this done.

**Comment by portertech** [comment]
Please close this out if this works for you :+1:

**Comment by agoddard** [comment]
Docs issue for this being tracked @ https://github.com/sensu/sensu-docs/issues/303

**Comment by davpx** [comment]
This should achieve the desired effect. I've turned this on for the checks I need to behave as such and will watch to see if it helps. I do think a configureable timespan would be beneficial to some. Or multi-level handlers perhaps, example: occurrences > 3 do this, occurrences > 10 do something else and so on.

Thanks for following up. I'll close this down.

**Comment by davpx** [comment]
This actually does not achieve the desired effect. The alert does indeed not auto resolve but when the user resolves the alert, it it not resolved at the handler.

**Comment by davpx** [comment]
Saw this working on another handler. Updated the problematic one and is working as needed. Thanks
