### ISSUE TITLE
If the value in a check definition includes invalid characters in the source field, sensu-api crashes.

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1130]
If the value in a check definition includes invalid characters (spaces) in the source field, sensu-api crashes instead of just marking the check as invalid and moving on.

Sensu version 0.20.3.

{
  "_index": "logstash-2015.12.07",
  "_type": "json",
  "_id": "xxxsomeid",
  "_score": null,
  "_source": {
    "timestamp": "2015-12-07T14:05:59.350300-0700",
    "level": "fatal",
    "message": "check source cannot contain spaces or special characters",
    "object": {
      "handlers": [
        "notify_slack"
      ],
      "command": "/etc/sensu/conf.d/team/plugins/check-http.rb -s -h xxsomehost -u 'https://xxsomehostapi/v0.1/healthcheck/' -q '\"message\": \"OK\",'",
      "interval": 60,
      "subscribers": [
        "xxsome-poller-phx"
      ],
      "source": "foo.host.com PHX",
      "name": "check_url_api_phx"
    },
    "@version": "1",
    "@timestamp": "2015-12-07T21:05:59.651Z",
    "type": "json",
    "host": "xxxsomehost",
    "path": "/var/log/sensu/sensu-api.log",
    "sensu_team": "xxxsometeam"
  },
  "sort": [
    1449522359651,
    1449522359651
  ]
}

**Comment by portertech** [comment]
Sensu's configuration validation is strict and this applies to the Sensu API, as it too interacts with Sensu check definitions, e.g. check request publishing.
