### ISSUE TITLE
Sensu silently fails on non-processing queue

### ISSUE THREAD

**Issue by CVTJNII** [sensu/sensu#1134]
I'm stressing Sensu to try and find and remediate failures we may see in production.  In an attempt to simulate a failure mode I[m concerned about I set my RabbitMQ to not process messages (By setting the high watermark to 0: https://www.rabbitmq.com/memory.html) attempting to simulate a locked-up rabbit and observed the results.  In this case Rabbit is up, the server/API is connected, there are no messages on the queue, but no check data is coming through.

I have my checks configured with keepalives, I had expected all my checks to go into keepalive alarm.  However, no keepalive events occurred.  Listing the sensu queue in Rabbit it looks like keepalives process through Rabbit, so a non-processing queue will break keepalives.

I also polled the health API endpoint and it was returning healthy.  As the consumers were attached and the queues were empty the healthcheck passed.

My concern is that, while this is admittedly an edge case, it is also a silent failure.  The health API passing isn't surprising, but the keepalives failing is.  Is there any way to monitor Sensu to know if the queues are processing beyond /health?  Is it possible for the check keepalives to not use the queue, which would cause the checks to correctly go into alarm as they're not being updated?

**Comment by davpx** [comment]
This has impacted me in real-world. Please fix

**Comment by portertech** [comment]
@CVTJNII does a locked up RabbitMQ broker as a result of exceeding the watermark "block" connections? https://www.rabbitmq.com/connection-blocked.html

**Comment by CVTJNII** [comment]
@portertech I'm not sure, that seems to be at the RabbitMQ connection level which would be deep in Sensu.  I'm assuming that message would come through if Rabbit isn't processing, but I'm not sure how to verify that without digging into the Sensu to Rabbit binding.

However, as a solution for this issue I don't think that's a good option.  I wouldn't be surprised if there are Rabbit failure modes where that isn't sent, and relying on Rabbit to say "Hey, I'm broken" seems like a poor design choice.  I think it would be better to have some timer external to Rabbit to ensure data is being received off the queue.  As I mentioned above I think doing this with the existing keepalives would be as graceful solution, or perhaps using message data fed by the servers themselves to heartbeat through Rabbit to drive the healthcheck.  In any case the block message mentioned seems like it will be too unreliable to catch such a serious failure mode, I'd like to see something more active for something as important as monitoring health.
