### ISSUE TITLE
Sensu mutators do not scale under many events

### ISSUE THREAD

**Issue by johntdyer** [sensu/sensu#1136]
Hello,

 It seems like Sensu Mutators are very expensive and if you are handling many alerts Sensu starts to fold under the load of forking so many events.   Is there a best practice on how to scale these?   

-John

**Comment by portertech** [comment]
@johntdyer you will either need to write the mutator in an efficient language (e.g. golang or c) or write a mutator extension (eventmachine Ruby) that runs within the Sensu server process (much or efficient).

**Comment by calebhailey** [comment]
@johntdyer can you provide some additional context around what you're trying to do with mutators? Perhaps there's an alternative solution for what you're trying to accomplish, or maybe some improvements to the documentation will help... please advise.

**Comment by johntdyer** [comment]
@calebhailey So we this one process which returns a list of IP's it can not reach.  We have a mutator which checks this list of IP's against another source of truth to see if they are out of routing

```
gateway ----->   [runtime,runtime,runtime,runtime,runtime]
```

Sometimes we take a runtime out of routing for maintenance and there is no reason to get a page for a blacklisted runtime in that case.   

I think what I would love to see is if you could have a mutator scoped to a check, or class of checks, and only then run the mutator under those conditions. 

 I hope that makes sense...

Here is the mutator as it stands today: 
```
#!/usr/bin/env ruby

require 'rubygems'
require 'json'
require 'net/http'
require 'uri'
require 'sensu/logger'
require 'logger'

logger = Logger.new('/var/log/sensu/gateway_blacklist_mutator.log')

# Read event data
event = JSON.parse(STDIN.read)
logger.info("CHECK NAME: #{event['check']['name']}")
logger.info("CHECK OUTPUT: #{event['check']['output'].delete('\n')}")
if event['action'].to_s != 'create'
  logger.info("This event is not a 'create' action event for the 'check-gateway-blacklist' check -- No need to run this mutator.  Exiting...")
  puts event.to_json
  exit
end
if event['check']['name'] != 'check-gateway-blacklist'
  logger.info("This event is not a 'create' action event for the 'check-gateway-blacklist' check -- No need to run this mutator.  Exiting...")
  puts event.to_json
  exit
end

# Modify event action so that certain check alerts do not get resolved automatically via API
begin
  blacklisted_ips = event['check']['output'].split("--[")[1].split("]--")[0].gsub(/\s|"/, "").split(',')
  logger.info("BLACKLISTED_IPS: #{blacklisted_ips}")
rescue
  logger.info("I was not able to parse the blacklisted IP's from the event output. Exiting...")
  puts event.to_json
  exit
end

## Get the number of hosts in the blacklist
counter = blacklisted_ips.length
blacklisted_ips.each do |i|
  logger.info("IP: #{i}")

  begin

    uri = URI.parse("http://ops.xxxx.com/routing/#{i.chomp}")
    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    status = JSON.parse(response.body)['routing']

    if status['inbound'] == false && status['outbound'] == false
      logger.info("IP(#{i}) Seems to be out of routing. Ignoring...")
      counter -= 1
    end

  rescue Errno::ECONNREFUSED => e
    logger.error("Unabled to hit routing dashboard")
  end
end

if counter == 0
  logger.info("All of the Blacklisted IPs are out of routing. No need to alert.")
  event['action'] = 'resolve'
  event.merge!('mutated' => true, 'why_mutated' => "Alerting hosts are out of routing")
else
  logger.info("One or more of the blacklisted IPs is in Routing.  We must alert.")
end

puts event.to_json

```

**Comment by portertech** [comment]
This is a known limitation of spawning/forking many processes. Using the right language for your mutators can make a big difference, particularly those without a heavy runtime vm to start up, i.e. golang or c.
