### ISSUE TITLE
How to get log of an UDP handler

### ISSUE THREAD

**Issue by chrisduong** [sensu/sensu#1140]
Hi,

I'm not able to trace any logs of an UDP handler. Here is my Sensu config.

- InfluxDB UDP handler:
```json
{
  "handlers": {
    "influxdb_udp": {
      "type": "udp",
      "mutator": "influxdb_line_protocol",
      "socket": {
        "host": "192.168.50.31",
        "port": 8189
      }
    }
  }
}
```

The mutator `influxdb_line_protocol` is from [mutator-influxdb-line-protocol.rb
](https://github.com/sensu-plugins/sensu-plugins-influxdb/blob/master/bin/mutator-influxdb-line-protocol.rb). The mutator does **yield** **0** when run so I guess Sensu log should show some info about this handler but it doesn't.

I'm able to query those inserted metrics in InfluxDB. However, in the **sensu-server.log** (INFO level) I cannot see any log message like other `TCP handler`("message":"handler output").

Is it because of nature of UDP (shoot and forget) or can we  improve this. Because if InfluxDB not working, I cannot trace anything from **Sensu**.

**Comment by chrisduong** [comment]
I'm using Sensu version **0.21.0-2**.

**Comment by portertech** [comment]
@chrisduong you can toggle debug logging with a SIGTRAP. You will see your mutator output in the Sensu log file: https://github.com/sensu/sensu/blob/master/lib/sensu/server/handle.rb#L159

**Comment by chrisduong** [comment]
Hi, 

Could I ask one more silly question. 
How to toggle debug logging with a SIGTRAP in **Sensu**, could you tell a little more specifically. Thanks

**Comment by portertech** [comment]
`kill -TRAP $sensu-server-pid` where `$sensu-server-pid` is the Sensu server process ID.
