### ISSUE TITLE
sensu client attempts to reconnect when it should have given up and crashed

### ISSUE THREAD

**Issue by somic** [sensu/sensu#1142]
This could be somewhat related to https://github.com/sensu/sensu/issues/1044

sensu 0.19.2-1 on ubuntu, clustered rabbitmq on server side

One server (of several) stopped responding due to AWS degraded hardware event. What I expected is sensu-client processes connected to this server should have terminated (we have a mechanism to restart them so no big deal), based on my reading of https://github.com/sensu/sensu/blob/master/lib/sensu/daemon.rb#L190 (verified same thing is in 0.19.2-1) and the fact that nowhere in our /etc/sensu/conf.d configs do we have reconnect_on_error=true.

Instead, I see some clients were stuck in reconnecting (note how long it took):

```
{"timestamp":"2015-12-22T10:56:36.077870-0800","level":"warn","message":"reconnecting to transport"}
{"timestamp":"2015-12-22T11:47:34.490099-0800","level":"info","message":"reconnected to transport"}
```

It looks like `@transport.on_error` block was never called - I don't see `transport connection error` error message in client log.

Thoughts? Could be a bug or could be misplaced expectations on my part.

**Comment by somic** [comment]
Looks to me like reconnect is hard coded on tcp connection loss which I suspect is what caused this behavior - https://github.com/sensu/sensu-transport/blob/master/lib/sensu/transport/rabbitmq.rb#L12

**Comment by somic** [comment]
Alternatively, periodically_reconnect should probably give up after some time instead of trying to reconnect forever - https://github.com/sensu/sensu-transport/blob/master/lib/sensu/transport/rabbitmq.rb#L152

**Comment by portertech** [comment]
Perhaps something like a RabbitMQ `max_reconnect`? Allowing process supervision to take it from there.

**Comment by portertech** [comment]
Not going to implement. The Sensu 1.x RabbitMQ transport has improved reconnect capabilities, including DNS hostname lookup (outside of EM connect). [Sensu 2.x](https://github.com/sensu/sensu-go) removes RabbitMQ from the architecture altogether.
