### ISSUE TITLE
API should log response codes

### ISSUE THREAD

**Issue by CVTJNII** [sensu/sensu#1143]
I'm currently troubleshooting phantom 503s from the /health endpoint.  I'm watching the logs which are recording the requests, but not the responses being sent back:

```
{"timestamp":"2015-12-24T02:23:05.405664+0000","level":"info","message":"GET /health","remote_address":"${ip}","user_agent":null,"request_method":"GET","request_uri":"/health","request_body":""}
```

It would be very useful for Sensu to log the response code similar to how Apache and Nginx log http responses.  This would aid troubleshooting.

**Comment by calebhailey** [comment]
@CVTJNII thank you for this submission! We'll investigate this and tag it to a milestone as soon as we have a plan.

**Comment by portertech** [comment]
The Sensu API has seen many improvements since the creation of this issue. The API does log response codes :+1: 

```
{"timestamp":"2017-02-23T08:51:16.152110-0800","level":"debug","message":"api request","remote_address":"127.0.0.1","user_agent":"curl/7.35.0","method":"GET","uri":"/info","query_string":null,"body":""}
{"timestamp":"2017-02-23T08:51:16.155207-0800","level":"info","message":"api response","request":{"remote_address":"127.0.0.1","user_agent":"curl/7.35.0","method":"GET","uri":"/info","query_string":null,"body":""},"status":200,"content_length":200}
```
