### ISSUE TITLE
Logical operators for subscribers in check.

### ISSUE THREAD

**Issue by winggundamth** [sensu/sensu#1144]
I want to request feature to have logical operators for subscribers in check. My use case like below

```
{
  "checks": {
    "memory": {
      "command": "check-memory-percent.rb -w 90 -c 95",
      "interval": 30,
      "subscribers": [
        "all",
        "python && redis"
      ],
    }
  }
}
```

On Sensu client I have specific check that need to do on server that has both python and redis on the same server only but not the server that has only python. I don't want to create new subscription name because it will cause a lot of filter on my custom dashboard. I don't think the syntax above is good but hope you get an idea.

**Comment by portertech** [comment]
This will likely not work with many transport options. Sensu itself is not aware of individual clients, only subscriptions, and the transport is responsible for mapping those subscriptions to message bus primitives etc.

**Comment by portertech** [comment]
Closing this, as the Sensu transport will not be able to support such routing configuration.
