### ISSUE TITLE
Sensu 0.21 ruby 2.0.0 -> 2.2.0 update breaks backwards compatbility

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1145]
We have come to rely on ruby 2.0.0 as the Sensu omnibus standard, so we install gems into the Sensu environment as this ensures the most compatibility.   By changing the path and updating to Ruby 2.2.0, this breaks backwards compatibility.    Sensu should have a major version jump due to the breaking change.  Also, I didn't see anything in the changelog about this change.

We recently upgraded our servers from 0.20.3 to 0.21 and most of our notification handlers were broken due to this change.  We have not deployed this out to our clients yet, but if we had, this would have resulted in a breaking change for our clients across the board as well.

**Comment by xyntrix** [comment]
We are working on a workaround for our own scripts for this change.. this seems to be a viable band-aid for shell scripts where if we detect the new path, we use that, otherwise default to the old path:

if [ -e /opt/sensu/embedded/lib/ruby/gems/2.2.0 ]; then
  export GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.2.0:${GEM_PATH}
else
  export GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.0.0:${GEM_PATH}
fi

**Comment by calebhailey** [comment]
@xyntrix thank you for submitting this issue. Sensu will not maintain backwards compatibility for old Rubies in future releases; in fact, yesterday's [0.23 release moved to Ruby 2.3 and dropped support for Rubies < 2.0](https://sensuapp.org/docs/0.23/changelog). Having said that, there are a few changes we have made and will make: 

1. We have begun to and will continue to do a better job of documenting ruby version changes in the changelog 
2. We are now publishing the changelogs in the Sensu documentation, to make them more visible; e.g.: 
  - https://sensuapp.org/docs/0.22/changelog
  - https://sensuapp.org/docs/0.23/changelog
3. We are planning on improving the sensu-install documentation to include warnings about the need to reinstall any plugin gems when upgrading Sensu (which should be cared for by automation); see: https://github.com/sensu/sensu-docs/issues/352

**Comment by xyntrix** [comment]
Feels like this was addressed by checking the box on documentation/changelog items as well as setting ruby versioning expectations. We have adjusted our dependencies to align with expectations.
