### ISSUE TITLE
Large metrics results result in a hung process

### ISSUE THREAD

**Issue by Kaelten** [sensu/sensu#1146]
I have a custom metrics check which generated 88KB of data to ship to Sensu for processing.  This hung the metrics check until the timeout completed.  

There appears to be a 64k buffer for stdout and the way the buffer is read into sensu-spawn it appears that it waits for the check to finish before sensu reads any of the data from the buffer.  A more robust system for reading in the data more aggressively should resolve this.

**Comment by cryptk** [comment]
I too have a check which generates (currently) 1029 lines of metrics.  This comes out to about 77K of data.  This metric now hangs and hits the configured timeout after 60 seconds even though the check itself runs in ~0.04 seconds when run manually.

**Comment by portertech** [comment]
@Kaelten does the same behavior occur if you do not specify a check timeout in the definition?

**Comment by Kaelten** [comment]
@portertech Then it locks forever.   

With the timeout it's a 10m timeout for a script that takes 200ms to execute.

**Comment by cwjohnston** [comment]
Hi @Kaelten @cryptk, I'm going to close this issue as I believe we shipped a fix for it in Sensu 0.23.3 (see https://github.com/sensu/sensu-spawn/pull/17 and [the Sensu changelog](https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0233---2016-05-26)). 

Will you please open a new issue if you are able to reproduce this on the latest version of Sensu?
