### ISSUE TITLE
Feature request - run all Sensu checks and then exit

### ISSUE THREAD

**Issue by cruschke** [sensu/sensu#1148]
Our workflow for writing Chef cookbook is that someone implements the desired functionality, test the code using Testkitchen, write ServerSpec tests for cookbook regression testing and add all the Sensu checks that are needed (using the Sensu Chef LWPR, client standalone mode mainly).

We would like to verify the code of our Sensu checks using Serverspec too, so we are pretty sure that they will work before deploying them somewhere.

Therefore it would be really helpful if the Sensu client would have a feature to perform all the checks that are configured as standalone and then exit accordingly (exit 0 if all checks are OK and !=0 when a check is failing). This could also be implemented as a separate executable stripped down to the minimum featureset.

The Serverspec code then could look like this ...

    describe command('/opt/sensu/bin/sensu-client-runonce') do
        its(:exit_status) { should eq 0 }
    end

Thanks Christian

**Comment by runningman84** [comment]
This looks like a great feature. Right now we install a sensu server during our tests and check the status via api... This is a time consuming test because you have to install rabbitmq, redis and so on in order to run the full sensu server.

**Comment by klynch** [comment]
+1 On this feature. We now have devs writing custom checks and check scripts. This would help us validate the checks before automatically deploying them.

It would also come in handy during VM provisioning, as we can then validate the checks pass, and then proceed with registering the server if all checks pass.

**Comment by sebbu** [comment]
+1 It sounds very useful.

**Comment by portertech** [comment]
Hmm, this is neat, although it would only be applied to standalone checks. This is something we can add to the road map for investigation.

**Comment by calebhailey** [comment]
@cruschke so, after some internal discussion, we all think this is a very cool idea, but it would also require a lot of work. 

Historically, we have always recommended that checks can be tested by executing the commands in the same way as the Sensu client would. Have you attempted implementing a testing framework based on executing all of the defined [check commands](https://sensuapp.org/docs/0.23/checks#check-commands)? Please advise.

**Comment by cruschke** [comment]
We haven't yet looked at implementing something on our own as in the end it would generate some sort of code duplication (e.g parsing Sensu check configs).

Would it make things easier if a separate client would be implemented (instead of extending the sensu-client) that just performs config parsing and execution of standalone checks?

**Comment by calebhailey** [comment]
@cruschke sorry, I don't know why I didn't link to this in my previous comment &ndash; as of version 0.23, Sensu has added support to "run once" and print out the compiled configuration via a new `--print_config` CLI option. See here for more information: https://sensuapp.org/docs/latest/configuration#sensu-command-line-interfaces-and-arguments 

Once you would have the compiled config JSON, you could test Sensu's check execution behavior by running all of the commands as the `sensu` user (and on Sensu's embedded Ruby, if applicable); for example: 

~~~ 
$ sudo -u sensu /opt/sensu/embedded/bin/ruby /path/to/check/plugin.rb --args
~~~

...or...

~~~
$ sudo -u sensu <command> <command arguments>
~~~ 

I hope this makes sense. :)

**Comment by cruschke** [comment]
@calebhailey that makes perfectly sense, thanks for the hint!

**Comment by calebhailey** [comment]
\o/
