### ISSUE TITLE
Verify dependencies for standalone tests within sensu-client

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1149]
It would be great if the sensu-client would consider the dependencies.

For example we have these standalone checks:
```
	elasticsearch_process 	CheckProcess CRITICAL: Found 0 matching processes; cmd /bin/java .*-Des.pidfile=/var/run/elasticsearch/elasticsearch.pid/; user elastic+ 	a minute ago
 	elasticsearch_node-status 	ESNodeStatus CRITICAL: Connection refused 	a minute ago
	elasticsearch_cluster-status 	ESClusterStatus CRITICAL: Connection refused 	a few seconds ago
	elasticsearch_http 	CheckHttp CRITICAL: Request error: Connection refused - connect(2) for "127.0.0.1" port 9200 	a few seconds ago
	elasticsearch_circuit-breakers.rb 	ESCircuitBreaker CRITICAL: Connection refused 	a few seconds ago
	elasticsearch_file-descriptor 	ESFileDescriptors WARNING: Connection refused 	a minute ago
	elasticsearch-cluster_metrics 	Connection refused 	a few seconds ago
	elasticsearch-graphite_metrics 	Connection refused    a few seconds ago
```

In case of an elasticsearch crash (the first test will fail) avoiding to run these other tests would reduce the system load (running these tests is time consuming if the server answers slowly our timeouts). 

Maybe all other checks could return a warning status and output like "dependency not met".

**Comment by portertech** [comment]
This would require `sensu-client` to maintain state. Most users silence event notifications based on these dependencies. Even Sensu Enterprise provides an event filter for this purpose https://sensuapp.org/docs/0.21/enterprise-built-in-filters#checkdependencies

**Comment by runningman84** [comment]
The sensu-client can just maintain the state in RAM, there is no need for a persistent state. This would reduce the load at the client.
You can filter the events on the server but this will still lead to a lot of hanging checks on the client...

**Comment by calebhailey** [comment]
@runningman84 his is currently supported via the Sensu Plugin gem, so any Sensu handler plugins that are based on the Sensu Plugin gem will support the dependencies attribute; see here for additional information: https://sensuapp.org/docs/0.21/checks#sensu-plugin-attributes

It is also possible to implement custom dependency resolution in custom Sensu handlers. The handler would simply need to query the Sensu Events API for the corresponding dependency.

We're going to go ahead and close this issue, but please feel free to comment if you have any further questions. If you need help learning Sensu, please consider [Sensu Training](https://sensuapp.org/training), or try hanging out in the #sensu Freenode channel - there are usually many Sensu users there who can help.
