### ISSUE TITLE
Apt: Failing to install with apt v1.1.10

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu#1151]
Followed the official guide: https://sensuapp.org/docs/0.21/install-repositories#ubuntudebian

Error when running ```apt-get update``` or ```aptitude update```:

```
Suite: sensu W: Failed to fetch http://repositories.sensuapp.org/apt/dists/sensu/Release  No Hash entry in Release file /var/lib/apt/lists/partial/repositories.sensuapp.org_apt_dists_sensu_Release, which is considered strong enough for security purposes
```

From https://github.com/rcrowley/freight/pull/65 it appears apt v1.1 requires the 'Date' field now. https://wiki.debian.org/RepositoryFormat#Date.2CValid-Until 
This completely blocks me from using the official repos on Debian stretch/sid

**Comment by rs-mrichmond** [comment]
Currently this is also an issue with Ubuntu 16.04 (Beta)

**Comment by jaredledvina** [comment]
Closing issue as duplicate of https://github.com/sensu/sensu/issues/1135
