### ISSUE TITLE
Sensu-client fails to start on CentOS 5.10

### ISSUE THREAD

**Issue by johntdyer** [sensu/sensu#1152]
I am unable to start Sensu 0.21.0-2 on CentOS 5.10. 
## Error:

``` bash
[root@tropo-cdr2 logs]# /etc/init.d/sensu-client start
Starting sensu-clientbash: line 1: 28454 Segmentation fault      /opt/sensu/bin/sensu-client -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-client.pid -l /var/log/sensu/sensu-client.log -L info
```
## Version

``` bash
[root@tropo-cdr2 logs]# rpm -qa | grep sensu
sensu-0.21.0-2
```
## Package Info

``` bash
[root@tropo-cdr2 logs]# yum info sensu-0.21.0-2
Loaded plugins: priorities, security
Installed Packages
Name       : sensu
Arch       : x86_64
Epoch      : 1
Version    : 0.21.0
Release    : 2
Size       : 61 M
Repo       : installed
Summary    : A monitoring framework that aims to be simple, malleable, and scalable.
URL        : http://sensuapp.org
License    : MIT License
Description: A monitoring framework that aims to be simple, malleable, and scalable.
```

I assume EL5 is supported, considering there is a package for it.  Anyone else having this issue ?

**Comment by johntdyer** [comment]
I was able to get things working again by switching to this RPM

http://repos.sensuapp.org/yum/el/5/x86_64/sensu-0.19.1-1.x86_64.rpm

**Comment by kholloway** [comment]
Seeing the same issue on RHEL 5.11, looks like Ruby 2.2.0 is the culprit.

Rhel 5.11: Linux 2.6.18-404.el5xen #1 SMP Sat Mar 7 04:16:55 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

Last few lines from strace output while running the embedded ruby binary that ships with this RPM.
I did try increasing the stack limit as it was originally set to '10240', I increased it to '65535' for testing which didn't change anything.

```
brk(0x1bf43000)                         = 0x1bf43000
open("/usr/lib/locale/locale-archive", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=56422176, ...}) = 0
mmap(NULL, 56422176, PROT_READ, MAP_PRIVATE, 3, 0) = 0x2b4c30cfc000
close(3)                                = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
open("/proc/self/maps", O_RDONLY)       = 3
getrlimit(RLIMIT_STACK, {rlim_cur=65535*1024, rlim_max=65535*1024}) = 0
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2b4c342cb000
read(3, "00400000-00401000 r-xp 00000000 "..., 1024) = 1024
read(3, "d8cc02000-3d8ce02000 ---p 000020"..., 1024) = 1024
read(3, "thread-2.5.so\n3d8d618000-3d8d61c"..., 1024) = 1024
read(3, ".2.2.0\n2b4c30acd000-2b4c30ccc000"..., 1024) = 743
close(3)                                = 0
munmap(0x2b4c342cb000, 4096)            = 0
sched_getaffinity(3313, 32,  { 3, 0, 0, 0 }) = 32
getrlimit(RLIMIT_STACK, {rlim_cur=65535*1024, rlim_max=65535*1024}) = 0
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
```

**Comment by kholloway** [comment]
@johntdyer the 0.20 Sensu package also works fine on RHEL5 just not the 0.21 package.

**Comment by johntdyer** [comment]
@kholloway  - I tested 0.20 and it didnt work.  I am not near my computer right this sec so I cant test again but I will try to later tonight

**Comment by kholloway** [comment]
Ahh ok we have been running 0.20 on RHEL5.11 for a while now with no issues, only this new 0.21 package doesn't work. I don't have 5.10 to test with though so maybe it's specific to that version.

**Comment by portertech** [comment]
Is it Ruby 2.2.3 that cannot run On RHEL5.10 or is it that we build the omnibus Ruby on potentially a newer release? https://github.com/sensu/sensu-build/blob/master/dockerfiles/centos-x86_64#L1

**Comment by kholloway** [comment]
Oddly enough Sensu 0.21 with embedded Ruby 2.2.3 worked fine on one of our RHEL 5.10 hosts but segfaults on all of our 5.11 hosts.

**Comment by johntdyer** [comment]
@portertech  any update here? 0.19.2-1 no longer appears on the repos

**Comment by calebhailey** [comment]
@johntdyer thanks for this submission! This is a known issue, which we are now tracking in the sensu-build repo.

**Comment by portertech** [comment]
Fixed https://github.com/sensu/sensu-build/issues/155#issuecomment-253598195
