### ISSUE TITLE
Feature request: delete-client bullet

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1155]
Several of our clients are ephemeral instances that spin up and down as needed.  Sometimes these clients are spun up with the same name but a different IP.  Our standard course of action is to manually delete the client by name, which will remove both the old and new client..  and we generally just hope the new client reconnects.

It would be nice to handle this synchronously, where if we send a particular signal to the Sensu process it generates a "terminate-client" message and shut down the Sensu client daemon.    This message when received will remove that specific client+ip from the client registry and prevent keepalive errors.

In addition to this, it might be handy to auto-create a unique identifier in the Sensu client for the life of the client itself so that messages associated with that client can be traced back to a specific client regardless of the name/ip used in the client config.  

Thanks!

**Comment by xyntrix** [comment]
Also, I think I can probably submit a PR to handle this -- so, I'd like to ensure what I'm thinking of doing is within the design ideals before I go and make a mess.  I'm thinking of creating a keepalive message with a special flag on it.

**Comment by portertech** [comment]
Deleting a client from the registry will not affect the client transport connection or keepalives.

**Comment by portertech** [comment]
@xyntrix why not auto-generate a config snippet on bootstrap that has `{"client": "id": "a_uuid"}`?

**Comment by xyntrix** [comment]
I think both Sensu 0.22's new feature and  managing via a client parameter as suggested by @portertech  where we track initial registration date (for instance) provide a good solution here.

Client auto de-registration on sensu-client process stop is now supported by the Sensu package init script. Setting CLIENT_DEREGISTER_ON_STOP=true and CLIENT_DEREGISTER_HANDLER=example in /etc/default/sensu will cause the Sensu client to publish a check result to trigger the event handler named "example", before its process stops.

Thank you!
