### ISSUE TITLE
Add examples for how to use `sensu-install --source` to help and documentation.

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1156]
How do you use `sensu-install --source` parameter to install from a custom source?

`sensu-install --help` doesn't provide any examples to make it clear what the format is.

**Comment by calebhailey** [comment]
@nhooey thanks for this submission - I've created an issue for this in the sensu-docs repo, and tagged it for the 0.24 documentation (we've got a lot in the queue for the 0.23 docs already). 

#monitoringlove

**Comment by nhooey** [comment]
Closed this since it's tracked in the `sensu-docs` repo.
