### ISSUE TITLE
Checks with double-quotes for the subscribers property cause api/server to Crash.

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1159]
Sensu sever 0.21.0.  If someone adds a check definition where subscribers is set to [ "" ], this causes the API and Server to crash, instead of just ignoring that check definition during start up.

It would be great if that check definition was just ignored due to invalid syntax so server/api could still start.  Alternatively. it might be okay for the check to default to publish:false with no subscribers if publish isn't explicitly set and subscribers is blank or set to "". 

Thanks!

**Comment by calebhailey** [comment]
@xyntrix thanks for this submission - nice catch! We'll add some validation to check for empty strings. We're tagging this for the 0.24 release.

**Comment by portertech** [comment]
Closing this, as https://github.com/sensu/sensu/pull/1254 was merged, consistently applying strong validation. Sensu build will be updated to use `--validate_config` for restarts, prior to cutting 0.24 :+1:
