### ISSUE TITLE
Keepalive check impossibly flaps between very recent success and failure from a while ago

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1160]
I have Sensu 0.21, and while watching a server's page on Uchiwa, I see the keepalive check flap between these states in sequence, with only a few seconds between each state:

```
12:01:16 OK:       Keepalive sent from client 17 seconds ago
12:01:38 CRITICAL: No keepalive sent from client for 313 seconds (>=180)
12:01:51 OK:       Keepalive sent from client 7 seconds ago
12:02:06 CRITICAL: No keepalive sent from client for 343 seconds (>=180)
```

If the check is going to flap between `OK` and `CRITICAL` every <= 30 seconds, then the "No keepalive sent from client" message should be 30 seconds maximum. So this state should be impossible.

Is this likely an issue with Uchiwa or with Sensu itself?

**Comment by xyntrix** [comment]
This can mean a number of things.  Is your keepalive queue more than your server(s) can process in a timely manner? http://sensu-api/info  should show total messages in the results/keepalive queues.  It could also mean you have a single server which is pointing to multiple redis stores and they aren't in sync or replication is broken.  This can also mean you have multiple servers and your servers are pointed at completely different redis stores.

**Comment by xyntrix** [comment]
This can also mean the time on the client/server is way off -- time is very important.  NTP all the things!

**Comment by nhooey** [comment]
I think I had a rogue Sensu server at the time, since this isn't happening anymore.
