### ISSUE TITLE
Support batch API requests for Uchiwa dashboard's efficiency

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1161]
When you execute actions on multiple events or clients in Uchiwa, it spawns a request for each entity which is very slow for a large number of entities. Currently there is no other way because there isn't a batch API for Sensu.

Here is a good [reference implementation of a batch API for Neo4J](http://neo4j.com/docs/stable/rest-api-batch-ops.html) which looks like the most flexible and least controversial, in my opinion, because it just takes a list of raw REST requests, and returns a list of their responses. There are no decisions about whether to make requests like `DELETE /clients/1,2,3` or `DELETE /clients/1;2;3` or `DELETE /clients/batch?id=1,2,3`, and the more difficult decision about how to format their responses.

There is an [issue in Uchiwa](https://github.com/sensu/uchiwa/issues/440) to make use of such an API when it exists.

**Comment by calebhailey** [comment]
@nhooey thanks for your submission!

**Comment by portertech** [comment]
Not going to implement this functionality in the <= 1.x Sensu API. Certainly something we will investigate while designing the new Sensu API.

**Comment by nhooey** [comment]
How about leaving the issue open, so we can still track the functionality, and tagging it `Sensu API 2.x`?
