### ISSUE TITLE
Keepalive status nonsensical when server clock is wrong

### ISSUE THREAD

**Issue by jootuom** [sensu/sensu#1162]
I was testing Sensu and Uchiwa in VM's and NTP/host time syncing were not enabled so my Sensu server's clock was set to the past whilst the client had the correct time.

This resulted in a nonsensical keepalive status where Sensu (or Uchiwa) was displaying that everything is OK whilst the timestamp was negative.

The dates were more or less:
# server
date
Tue Feb  2 20:51:54 EET 2016
# client
date
Wed Feb  3 12:56:42 EET 2016

See attached ![screenshot](https://cloud.githubusercontent.com/assets/11478922/12780973/05ec4402-ca7a-11e5-8766-3a32a9e0ff03.png).

**Comment by webmstr** [comment]
Um, +1

**Comment by calebhailey** [comment]
@jootuom thank you for your submission. I'm going to close this issue as it's not a Sensu issue, and the negative time value (e.g. -57865) reported by Sensu is actually correct, and an indication that you should probably synchronize your system clocks. 

We've recently added this to the Sensu FAQ, here: https://sensuapp.org/faq#do-system-clocks-need-to-be-synchronized. I've added an issue in the Sensu docs repo to make this more obvious: https://github.com/sensu/sensu-docs/issues/351

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.
