### ISSUE TITLE
subscriber name limits can cause checks not to be executed

### ISSUE THREAD

**Issue by maxlock** [sensu/sensu#1164]
Hi,
I have created a subscriber group name with non word characters, ie. a dot or an underscore. In both cases checks assigned to these subscriber groups fail to be run. Once the dots or underscores are removed, checks run. 

sensu-0.20.3-1.x86_64

**Comment by maxlock** [comment]
On further testing this could also be a length restriction, my original subscriber group name has 41 chars. Removing non word chars reduces this to 37, which is working.

**Comment by maxlock** [comment]
I've additionally tried prefixing my 37 char subscriber with an underscore, this breaks too. So it appears there are both limits to length and content. Can this be clarified please.

**Comment by calebhailey** [comment]
The only validation performed by Sensu on subscription names is that they must be strings. It sounds like this might be an issue or limitation with the underlying [transport](https://sensuapp.org/docs/latest/transport). We'll look into this and see if there's something we do to improve the documentation. 

In any case, this definitely isn't an issue with Sensu, so there won't be a fix related to this issue.

**Comment by agoddard** [comment]
@maxlock fyi I've done a test on 0.22 with a 53 character subscription name, containing a ".", "-" and "_" and the check executed fine. For reference, the subscription name is `yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-._y` and I'm using RabbitMQ as the transport

**Comment by calebhailey** [comment]
I'm going to go ahead and close this issue as it doesn't appear to be an issue with Sensu. Please feel free to open a new issue if this matter is not resolved. #monitoringlove
