### ISSUE TITLE
TTL checks are hard coded as warnings

### ISSUE THREAD

**Issue by centromere** [sensu/sensu#1166]
It would be nice if I could mark a stale TTL as critical instead of it being [hardcoded as a warning](https://github.com/sensu/sensu/blob/faf178deca0abe53cb1bdeaed28fa3c25f221a86/lib/sensu/server/process.rb#L802).

**Comment by calebhailey** [comment]
@centromere thanks for this submission! Can you provide some more context about your use case for wanting to control TTL severities / behavior?

**Comment by centromere** [comment]
Sure. Right now I have a web server which sends a TTL every few seconds to the local Sensu client indicating whether or not it is connected to an upstream RabbitMQ instance. If that connection does not exist, it is absolutely a critical problem that needs attention, and the web server will indicate that by returning '2'. However, if the web server itself dies, that is another critical problem that absolutely needs attention. Currently, the web server dying will mean the RMQ check is stale, and it will be a warning rather than a critical alert.

**Comment by lp0** [comment]
I'd like to configure this with a state of '3' so that I know the real status is unknown.

**Comment by logikal** [comment]
I also would like to have the option to have these be a critical. I'm using something similar to the [dead man's switch](https://sensuapp.org/docs/latest/reference/clients.html#creating-a-dead-mans-switch) set up in the docs, but I _must_ use the API, not the socket.

I'm trying to set up a dead man's switch for Chronos, since we know there are ways that Chronos can enter a state where it can't schedule new jobs.

```
# how we create the check and update the results
curl -s -i -X POST -H 'Content-Type: application/json' -d '
{
  "source": "chronos",
  "name": "check_chronos_scheduling",
  "output": "Chronos Deadman: This job should run every 5 minutes, but hasnt run for 10. Check that Chronos can run jobs and doesnt need to be re-registered.",
  "status": 0,
  "ttl": 600,
  "handle": "true",
  "handlers": "prodops"
}
' http://sensu0003s1mdw1:4567/results

# what we get after > 600 seconds: 'status' should be 2
curl -s http://sensu0003s1mdw1:4567/results/chronos/check_chronos_scheduling | jq '.'
{
  "client": "chronos",
  "check": {
    "source": "chronos",
    "name": "check_chronos_scheduling",
    "output": "Last check execution was 1082 seconds ago",
    "status": 1,
    "ttl": 600,
    "handle": "true",
    "handlers": "prodops",
    "issued": 1469466685,
    "executed": 1469466685
  }
}
```

**Comment by logikal** [comment]
Ah, It's not limited to the API like I was hoping. Testing with the deadman's switch set up in the documentation will also lead to only a warning using Sensu 0.22.0.

**Comment by agh** [comment]
@calebhailey RE: usage case, we'd like to tack whether chef-client has stopped invoking correctly. Seems like the best way to do that is a [Dead Man Switch](https://sensuapp.org/docs/latest/reference/clients.html#creating-a-dead-mans-switch) but not being able to set this as critical is problematic. It doesn't give us the desired control over severity of a condition.

**Comment by fessyfoo** [comment]
quickly [looking at the more recent code](https://github.com/sensu/sensu/blob/899e582/lib/sensu/server/process.rb#L971), which has been updated since this ticket was opened, I believe you can set `ttl_status` on the check to control this..

**Comment by wfindley** [comment]
apparently you can also fix this with a mutator.
https://gist.github.com/logikal/41a37c0a78b2e43cbfce0955b31782f6

**Comment by agh** [comment]
Magic. ✨ 💖

**Comment by portertech** [comment]
Closing, as it seems `ttl_status` does the trick :+1:

**Comment by TiagoTT** [comment]
I could not find this check attribute `ttl_status` in the documentation.
Shouldn't it be here? https://sensuapp.org/docs/1.0/reference/checks.html#check-attributes

**Comment by wfindley** [comment]
It does indeed look to be an undocumented feature.  

It was added here:
https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0270---2017-01-26

You should probably open another issue asking that it be added somewhere to the documentation.

**Comment by wfindley** [comment]
made https://github.com/sensu/sensu/issues/1779
