### ISSUE TITLE
sensu seems to invoke email handler multiple times. resulting in multiple emails

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/sensu#1167]
Not always but time to time, we see multiple keep alive alarms from the same host. Our configuration is set to send only 1 email for a keep alive however seeing two emails from the same sensu server. Below is the log of the timestamp when this issue happened. 

[root@dc-appblx110-29 sensu]# cat sensu-server.log|grep -i "dc-appblx007-14"|grep -i "keepalive"|grep -i "T10:"
{"timestamp":"2016-02-15T10:19:00.850567-0800","level":"info","message":"processing event","event":{"id":"2691a96d-a3a7-4f4b-a82a-aaa50ba05af4","client":{"name":"dc-appblx007-14.prod.example.com","address":"10.65.48.63","subscriptions":["openstack-stg-hypervisors-juno"],"CPU_Metrics":"http://esm-graphite.prod.example.com/render?width=400&from=-2hours&until=now&height=250&target=openstack.dcSTG02.dc-appblx007-14-prod-example-com.CPU.Usage&_uniq=0.3660747123609889&title=openstack.dcSTG02.dc-appblx007-14-prod-example-com.CPU.Usage&uchiwa_force_display_as_image=.jpg","Memory_Metrics":"http://esm-graphite.prod.example.com/render?width=400&from=-2hours&until=now&height=250&target=openstack.dcSTG02.dc-appblx007-14-prod-example-com.MEM.Usage&_uniq=0.8804576504004867&title=openstack.dcSTG02.dc-appblx007-14-prod-example-com.MEM.Usage&uchiwa_force_display_as_image=.jpg","Network_Metrics":"http://esm-graphite.prod.example.com/render?width=400&from=-2hours&until=now&height=250&target=openstack.dcSTG02.dc-appblx007-14-prod-example-com.Network.p2p1_rxpck&_uniq=0.8804576504004867&title=openstack.dcSTG02.dc-appblx007-14-prod-example-com.Network.p2p1_rxpck&uchiwa_force_display_as_image=.jpg","dc":"dc","cloud":"dcSTG02","nodetype":["HYPERVISOR"],"team":"esm-monitoring@example.com,GECTSDIA38@email.example.com,unixadmin@example.com","keepalive":{"handlers":["generic_email_notify","decomm"]},"version":"0.20.6","timestamp":1455560030},"check":{"thresholds":{"warning":300,"critical":1800000},"handlers":["generic_email_notify","decomm"],"name":"keepalive","issued":1455560333,"executed":1455560333,"output":"No keepalive sent from client for 303 seconds (>=300)","status":1,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","1","1"],"total_state_change":5},"occurrences":1,"action":"create","timestamp":1455560340}}
{"timestamp":"2016-02-15T10:19:00.895408-0800","level":"info","message":"processing event","event":{"id":"f7bb3f83-3720-4f6d-a352-010439cc2294","client":{"name":"dc-appblx007-14.prod.example.com","address":"10.65.48.63","subscriptions":["openstack-stg-hypervisors-juno"],"CPU_Metrics":"http://esm-graphite.prod.example.com/render?width=400&from=-2hours&until=now&height=250&target=openstack.dcSTG02.dc-appblx007-14-prod-example-com.CPU.Usage&_uniq=0.3660747123609889&title=openstack.dcSTG02.dc-appblx007-14-prod-example-com.CPU.Usage&uchiwa_force_display_as_image=.jpg","Memory_Metrics":"http://esm-graphite.prod.example.com/render?width=400&from=-2hours&until=now&height=250&target=openstack.dcSTG02.dc-appblx007-14-prod-example-com.MEM.Usage&_uniq=0.8804576504004867&title=openstack.dcSTG02.dc-appblx007-14-prod-example-com.MEM.Usage&uchiwa_force_display_as_image=.jpg","Network_Metrics":"http://esm-graphite.prod.example.com/render?width=400&from=-2hours&until=now&height=250&target=openstack.dcSTG02.dc-appblx007-14-prod-example-com.Network.p2p1_rxpck&_uniq=0.8804576504004867&title=openstack.dcSTG02.dc-appblx007-14-prod-example-com.Network.p2p1_rxpck&uchiwa_force_display_as_image=.jpg","dc":"dc","cloud":"dcSTG02","nodetype":["HYPERVISOR"],"team":"esm-monitoring@example.com,GECTSDIA38@email.example.com,unixadmin@example.com","keepalive":{"handlers":["generic_email_notify","decomm"]},"version":"0.20.6","timestamp":1455560030},"check":{"thresholds":{"warning":300,"critical":1800000},"handlers":["generic_email_notify","decomm"],"name":"keepalive","issued":1455560333,"executed":1455560333,"output":"No keepalive sent from client for 303 seconds (>=300)","status":1,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","1","1"],"total_state_change":5},"occurrences":1,"action":"create","timestamp":1455560340}}

Default sensu configuration:
'occurrences' => 1,
'interval' => 30,
'refresh' => 10713600

**Rabbitmq:** We have a 2 node cluster in a datacenter and another 2 node cluster is another datacenter. Messages are federated between two datacenters (exchanges and queues).

**Comment by kaushiksriram100** [comment]
Server 1:

{"timestamp":"2016-02-22T15:13:36.970710-0800","level":"info","message":"processing event","event":{"id":"e621efb4-99d4-4322-a539-9274b2386578","client":{"name":"dc-appblx102-12.prod.example.com","address":"10.247.208.44","subscriptions":["cassandra-docker-hosts"],"CPU_Metrics":"http://esm-graphite.prod.example.com/render?width=800&from=-2hours&until=now&height=350&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.cpu.*&title=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.cpu&lineMode=connected&_uniq=0.7897298135689663&uchiwa_force_display_as_image=.jpg","Memory_Metrics":"http://esm-graphite.prod.example.com/render?width=800&from=-2hours&until=now&height=350&target=Cassandra-docker.dc-appblx001-12-prod-example-com.vmstat.memory.free&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.memory.cache&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.memory.swap_used&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.memory.buffers&lineMode=connected&_uniq=0.51436139656068863&uchiwa_force_display_as_image=.jpg","team":"UnixAdmin@example.com, skaushik@example.com, hvyas@example.com, GECDBACA12@ex-ample.com","keepalive":{"handlers":["generic_email_notify"]},"alias":"","application":"Cassandra-docker","version":"0.20.3","timestamp":1456182801},"check":{"handlers":["generic_email_notify"],"command":"check-procs.rb -p cassandra.config.loader -C 2 ","interval":60,"team":"dbadmin2@example.com,skaushik@example.com,hvyas@example.com","standalone":true,"name":"standalone_cassandra_proc_docker","issued":1456182816,"executed":1456182816,"duration":0.168,"output":"CheckProcs CRITICAL: Found 1 matching processes; cmd /cassandra.config.loader/\n","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2","2"],"total_state_change":5},"occurrences":1,"action":"create","timestamp":1456182816}}
{"timestamp":"2016-02-22T15:13:37.996929-0800","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/generic_email_notify.rb","name":"generic_email_notify"},"output":[]}


Server 2: 
{"timestamp":"2016-02-22T15:13:36.967162-0800","level":"info","message":"processing event","event":{"id":"ebd4c4b4-914a-4e64-bcb1-cf4db6fcffa8","client":{"name":"dc-appblx102-12.prod.example.com","address":"10.247.208.44","subscriptions":["cassandra-docker-hosts"],"CPU_Metrics":"http://esm-graphite.prod.example.com/render?width=800&from=-2hours&until=now&height=350&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.cpu.*&title=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.cpu&lineMode=connected&_uniq=0.7897298135689663&uchiwa_force_display_as_image=.jpg","Memory_Metrics":"http://esm-graphite.prod.example.com/render?width=800&from=-2hours&until=now&height=350&target=Cassandra-docker.dc-appblx001-12-prod-example-com.vmstat.memory.free&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.memory.cache&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.memory.swap_used&target=Cassandra-docker.dc-appblx102-12-prod-example-com.vmstat.memory.buffers&lineMode=connected&_uniq=0.51436139656068863&uchiwa_force_display_as_image=.jpg","team":"UnixAdmin@example.com, skaushik@example.com, hvyas@example.com, GECDBACA12@ex-ample.com","keepalive":{"handlers":["generic_email_notify"]},"alias":"","application":"Cassandra-docker","version":"0.20.3","timestamp":1456182801},"check":{"handlers":["generic_email_notify"],"command":"check-procs.rb -p cassandra.config.loader -C 2 ","interval":60,"team":"dbadmin2@example.com,skaushik@example.com,hvyas@example.com","standalone":true,"name":"standalone_cassandra_proc_docker","issued":1456182816,"executed":1456182816,"duration":0.168,"output":"CheckProcs CRITICAL: Found 1 matching processes; cmd /cassandra.config.loader/\n","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2","2"],"total_state_change":5},"occurrences":1,"action":"create","timestamp":1456182816}}
{"timestamp":"2016-02-22T15:13:38.232363-0800","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/generic_email_notify.rb","name":"generic_email_notify"},"output":[]}

**Comment by calebhailey** [comment]
@kaushiksriram100 this doesn't look like an issue with Sensu itself, so I'm going to go ahead and close this. 

If you need help learning Sensu, please consider [Sensu Training](https://sensuapp.org/training), or try hanging out in the #sensu Freenode channel - there are usually many Sensu users there who can help.

#monitoringlove
