### ISSUE TITLE
JIT client does not show up in API (or dashboard) but "source" is defined

### ISSUE THREAD

**Issue by pwn777** [sensu/sensu#1169]
I am trying to wrap my head around JIT clients. I have looked at all the issues posted on JIT clients to figure out what i'm doing wrong, but I really don't know. 

I only have a check configured to ping:

{
  "checks": {
    "ping-test": {
      "command": "/opt/sensu/embedded/bin/check-ping.rb -h testhost1",
      "handle": false,
      "source": "testhost1",
      "subscribers": [
        "testhost1"
      ],
      "interval": 5
    }
  }
}

But it never shows up in the API and therefore does not show up in the dashboard. I don't know what I am doing wrong, I have tried all the variations within the check definition, including using "standalone", a handler, no subscribers, etc. Any help would be appreciated :)

**Comment by luisdalves** [comment]
do you have 'testhost1' as subscriptions in running sensu-client???

**Comment by pwn777** [comment]
WOW, Thankyou SO much. I can't believe I am that daft. 

:+1:

**Comment by pwn777** [comment]
@luisdalves Do you know if it is possible to populate the "Address" field for a JIT client? This issue is resolved though, thank you again.

![image](https://cloud.githubusercontent.com/assets/6895947/13154550/5b9da41c-d62e-11e5-8ca2-379b6e5e4c33.png)
