### ISSUE TITLE
check dependencies functionality not working on sensu handler extensions  (0.22.0)

### ISSUE THREAD

**Issue by hanynowsky** [sensu/sensu#1170]
I am unable of making use of the dependencies functionality for the flapjack extension handler
```
# cat check_procs_apache2.json 
{
    "checks": {
        "check_apache_proc": {
            "command": "check-process.rb -p apache2",
            "interval": 60,
            "occurrences": 2,
            "subscribers": ["apachetwo"],
            "handlers": ["flapjack", "logstash", "irc", "riemann"]
        }   
    }   
}
root@sensu-server (sensu) in /etc/sensu/conf.d/check 
# cat check_procs_crond.json 
{
    "checks": {
        "check_crond_proc": {
            "command": "check-process.rb -p cron -C 1",
            "dependencies": ["check_apache_proc"],
            "interval": 60,
            "occurrences": 2,
            "subscribers": ["production"],
            "handlers": ["flapjack", "logstash", "irc"]
        }
    }
}
```

- Both checks plugins are using the sensu-plugin

EDDIT: The irc handler responds well to the dependencies functionnality. yet the flapjack extension handler does not. 

Please help

**Comment by ptqa** [comment]
From my understanding handler should be aware of dependencies and check them like this https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-handler.rb#L172

**Comment by hanynowsky** [comment]
SOrry for the false issue report.
Actually I discovered that dependencies are not working for extension handlers like: flapjack.rb extension handler! I am editing the title. So how can that handler use the : https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-handler.rb#L172

**Comment by hanynowsky** [comment]
OK. I modified the FlapJack Extension and implemented methods from sensu-plugin. Now flapjack extension handler is capable of using occurrences and dependencies.

**Comment by dgoradia** [comment]
@hanynowsky Would you mind sharing the changes you made to the flapjack extension? I may be running into a similar problem.

**Comment by hanynowsky** [comment]
@dgoradia https://gist.github.com/hanynowsky/9c700af0913d96ee4c99

**Comment by dgoradia** [comment]
Thanks! @hanynowsky
