### ISSUE TITLE
Yum Repository Missing GPG-Signed Packages

### ISSUE THREAD

**Issue by dmizelle** [sensu/sensu#1172]
Not sure if this is the right place to put this, so scold me if I'm wrong.

It looks like that the RPM packages in the yum repository aren't signed via GPG. The APT/Debian/Ubuntu repo has signed packages though.

A request for security: can we please get them signed?

**Comment by smbambling** [comment]
:+1:

**Comment by jaxxstorm** [comment]
This should probably go to https://github.com/sensu/sensu-build

**Comment by calebhailey** [comment]
@dmizelle I'm going to close this because this isn't the right repo for it, but please feel free to create an issue for this in https://github.com/sensu/sensu-build 

#monitoringlove
