### ISSUE TITLE
Sensu handler ignoring filter 

### ISSUE THREAD

**Issue by genagain** [sensu/sensu#1174]
Right now I am configuring an email handler to send an email after a check's status as been critical for a while. I want the email to be sent, every hour that the check's event history has been critical for a long time. Below is the filter, handler and the check configuration.

/etc/sensu/conf.d/filter_alert.json
```
{
  "filters": {
    "alert": {
      "attributes": {
        "history": "eval: value.split(',').all? { |status| status.gsub("'","") == '2' }",
        "occurrences": "eval: value % 12 == 0"
      }
    }
  }
}
```

/etc/sensu/conf.d/handlers/handler_memory-email.json
```
{
  "handlers": {
    "memory-email": {
      "type": "pipe",
      "filter": "alert",
      "severities": [
        "critical"
      ],
      "command": "mailx -s 'The memory usage is more than 80%' ohta.g@husky.neu.edu"
    }
  }
}
```

/etc/sensu/conf.d/hardware/check_memory_metrics.json
```
{
  "checks": {
    "memory_metrics": {
      "handlers": ["default","influxdb", "memory-email"],
      "type": "metric",
      "command": "/etc/sensu/plugins/memory-metrics.rb -t 70",
      "subscribers": [
        "moc-sensu"
      ],
      "interval": 300
    }
  }
}
```

Unfortunately instead of receiving an email every hour, I am not receiving any. When I took out the history attribute in my filter it worked as expected, so the problem is with the history attribute.

**In my filter, how do you evaluate every status in the history attribute, so it returns true when all of the statuses are 2?**

For example if my history is "[\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\"]", the evaluation should return true.  If my history is "[\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"0\"]", the evaluation should return false.

**Comment by kobbe** [comment]
I fail to see why you would want to test both occurrences and history since they are the same in this case. The occurrences counts how many times the check have been returning the same value. So if the occurrences is 12, then per definition the last 12 values in the history will have the same value.

(Since this is a pure ruby problem, sensu issue tracker might not be the best place to ask.)

**Comment by calebhailey** [comment]
@genagain there isn't enough information here to suggest that this is an issue with Sensu itself so I'm going to go ahead and close this as a "Training" issue. 

If you need help learning Sensu, please consider [Sensu Training](https://sensuapp.org/training), or try hanging out in the #sensu Freenode channel - there are usually many Sensu users there who can help. 

Please feel free to comment here if you should have any further questions.

**Comment by p53** [comment]
@genagain 
history is array of strings, thus you need to convert it to array of numbers, like this:
```
value.map { |x| x.to_i;}
```
i am commenting it, just in case someone else would be looking for this

**Comment by scosist** [comment]
@p53 I tried that in the `"history": "eval: ..."` statement but it threw a filter attribute eval error in the log:
```
"error":"undefined method `map' for nil:NilClass\nDid you mean?  tap"
```
Perhaps the `map` method is not available in this context? Is an `eval` on the `history` attribute supported?
