### ISSUE TITLE
Same log level for config sucess and failure at startup

### ISSUE THREAD

**Issue by kobbe** [sensu/sensu#1176]
At startup when sensu is loading all configuration files each file is logged with the "warn" log level, independently of weither the configuration file actually was successfully loaded or not.

    {"timestamp":"...","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/check_test.json"}
    {"timestamp":"...","level":"warn","message":"config file must be valid json","file":"/etc/sensu/conf.d/check_test.json","error":"lexical error: invalid char in json text.\..."}
    {"timestamp":"...","level":"warn","message":"ignoring config file","file":"/etc/sensu/conf.d/check_test.json"}
    {"timestamp":"...","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/default_handler.json"}
    {"timestamp":"...","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/default_handler.json","changes":...}}`

In this example both the ignored `check_test.json` and the successfully `default_handler.json` loaded file are logged with the same log level. As it is now it is impossible to locate errors in the log file since there are so many events with the log level "warn".

My suggestion is that that start up procedure is only logged with info level and all error are logged with the warn level.

**Comment by runningman84** [comment]
+1

**Comment by calebhailey** [comment]
Configuration loading is supposed to be logged at the "warn" level to allow for better control over logging, however errors are supposed to be logged with an "error" level. We'll get this fixed 0.24.

**Comment by portertech** [comment]
We can update https://github.com/sensu/sensu/blob/master/lib/sensu/daemon.rb#L103, perhaps adding `@settings.errors` to the sensu-settings API https://github.com/sensu/sensu-settings

**Comment by portertech** [comment]
Closing this, as https://github.com/sensu/sensu/pull/1254 was merged, which changes this behaviour :+1:
