### ISSUE TITLE
/info endpoint should show all servers

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu#1179]
It would be awesome for the `/info` API endpoint to be able to list all the currently know about sensu servers.

That way, if I query `/health` or something and there's a server missing for whatever reason, we can determine the status.

My use case for this is being able to say there should be > 3 sensu servers taking messages off the queue, and if there isn't, I'd like to be able to spin up a new one automagically.

**Comment by calebhailey** [comment]
@jaxxstorm thank you for submitting this issue. This functionality is already available via the [Sensu Health API](https://sensuapp.org/docs/0.21/api-health). Unfortunately this isn't documented very well, but we have this and several other API documentation fixes coming soon. 

In the interim, the information you're looking for is called "consumers". It is possible to query the Health API for a specific number of consumers and it will return a `503` status code (i.e. "service unavailable") if there are fewer than the expected number of consumers. 

```
$ curl -i 'http://localhost:4567/health?consumers=3'
HTTP/1.1 503 Service Unavailable
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Content-Length: 0
Connection: keep-alive
Server: thin
```

See https://github.com/sensu/sensu-docs/pull/324 for more info. 

PS- consumer health is not available when using Redis as the [Sensu Transport](https://sensuapp.org/docs/latest/transport); see: https://github.com/sensu/sensu-docs/issues/350

**Comment by calebhailey** [comment]
Tagging this for the 0.25 release, when we hope to implement a number of API enhancements.

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by portertech** [comment]
@jaxxstorm this is in 0.28.0-1 https://github.com/sensu/sensu/pull/1573 :+1:
