### ISSUE TITLE
Parent/child relationships

### ISSUE THREAD

**Issue by dgoradia** [sensu/sensu#1180]
Does Sensu have the ability to set a parent to a client?

For example, `server-a` is the gateway to `server-b` and `server-c` so if `server-a` goes offline, alerts for `server-b` and `server-c` are suppressed. In this case `server-a` is the parent of `server-b` and `server-c`

This nagios doc probably explains better what I'm getting at: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/networkreachability.html

**Comment by calebhailey** [comment]
@dgoradia this is currently supported via the Sensu Plugin gem, so any Sensu handler plugins that are based on the Sensu Plugin gem will support the `dependencies` attribute; see here for additional information: https://sensuapp.org/docs/0.21/checks#sensu-plugin-attributes 

It is also possible to implement custom dependency resolution (e.g. "parent/child relationships") in custom Sensu handlers. The handler would simply need to query the [Sensu Events API](https://sensuapp.org/docs/0.21/api-events) for the corresponding dependency. 

We're going to go ahead and close this issue, but please feel free to comment if you have any further questions. If you need help learning Sensu, please consider Sensu Training: https://sensuapp.org/training
