### ISSUE TITLE
Sensu Checks not working

### ISSUE THREAD

**Issue by Udhuman** [sensu/sensu#1181]
Hi,

I am new to sensu. I have installed Sensu server, API & Uchiwa in one machine and RabbitMQ & Redis in another machine in redundant mode.

Sensu clients and checks are visible in Uchiwa dashboard, but the issue is, checks are not getting refreshed. Seems checks are not working.

Below is our memory check config.
{
  "checks": {
    "memory": {
      "command": "/etc/sensu/plugins/check-memory.sh -w 956 -c 928 -p",
      "interval": 10,
      "subscribers": [ "Linux" ],
      "refresh": 60,
      "handler": "default"
    }
  }
}

Subscription "Linux" is configured in client machines in client.json file and also in the dashboard memory check is visible for the client machines with old check status.

I have restarted sensu server, api from sensu server. Sensu client from client machines. When I restart or re-initiate the checks, the checks getting updated, after that no updates in the checks.

Please let me know what is wrong and  if any one faced such issues.

Thanks,
Muhammed Udhuman

**Comment by kobbe** [comment]
It is always good to start looking in the server and client logs.

**Comment by confiq** [comment]
This is more question than sensu issue. I would try stackoverflow instead...

**Comment by calebhailey** [comment]
@Udhuman there's not enough information here to suggest there is an issue with Sensu itself, so we're going to close this issue as "won't fix". If you need help learning Sensu, please consider signing up for Sensu Training, here: https://sensuapp.org/training 

Alternatively, have you tried visiting the #sensu channel on Freenode? There are usually lots of Sensu users there who can help resolve issues like this.
