### ISSUE TITLE
Long Check Durations

### ISSUE THREAD

**Issue by mnguyen1289** [sensu/sensu#1184]
I'm having a strange problem with Sensu check duration times.  Here's an example check result JSON output:

{
    "check": {
        "command": "/usr/lib/nagios/plugins/check_http -H example.com -I xx.xx.xx.xx -t 20",
        "dependencies": [
            "example.com/Ping_example.com",
            "sensu-probe/keepalive"
        ],
        "duration": 36.45,
        "executed": 1457385829,
        "handlers": [
            "techops",
            "flapjack"
        ],
        "high_flap_threshold": 25,
        "interval": 60,
        "issued": 1457385829,
        "low_flap_threshold": 10,
        "name": "HTTP_example.com",
        "occurrences": 3,
        "output": "HTTP OK: HTTP/1.1 302 Moved Temporarily - 342 bytes in 0.002 second response time |time=0.001837s;;;0.000000 size=342B;;;0\n",
        "refresh": 7200,
        "source": "example.com",
        "standalone": true,
        "status": 0,
        "timeout": 30,
        "ttl": 1800
    }
}

It shouldn't take the check 36 seconds to execute when the output of the check itself shows a < 1 second runtime.  Running this check on the command line yields a similar check execution time:

mnguyen@sensu-probe:~$ time /usr/lib/nagios/plugins/check_http -H example.com -I xx.xx.xx.xx -t 20
HTTP OK: HTTP/1.1 302 Moved Temporarily - 342 bytes in 0.002 second response time |time=0.001820s;;;0.000000 size=342B;;;0

real	0m0.005s
user	0m0.000s
sys	0m0.003s

The sensu client running this check processes hundreds of checks (400+) because it is also our primary check handler for the site's JIT clients.  I've tried adjusting the rabbitmq prefetch count on both the sensu client and servers, but the long check duration times remain the same.  The check duration times only return back to normal temporarily for about 5 minutes after I restart the sensu client process on that box.

I'm beginning to suspect this may be a limitation on the sensu client process and event machine because I'm not seeing a backlog of any rabbitmq messages in the sensu client queues.

Any insight would be greatly appreciated.

**Comment by mnguyen1289** [comment]
FYI - I'm seeing this problem across in both 19.2 and 20.6 versions.

After some digging, it turns out the limitation was on spawning additional sensu event machine processes.  By default, it was limited to 12 concurrent processes.  After bumping the threshold up, my check duration times returned back to normal.

I'm going to work on submitting a patch against the sensu spawn library and the sensu client library to update the config files to read in a "workers_concurrency" variable to spawn more than 12 workers if necessary.

Can we update this ticket to a feature request?

**Comment by calebhailey** [comment]
@mnguyen1289 thanks for submitting this, and for your PRs! We're going to tag this for implementation in the 0.24 release. \o/

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/1002

**Comment by portertech** [comment]
#1265 made the spawn limit configurable :+1:
