### ISSUE TITLE
Sensu API fails after start (Connection Refused)

### ISSUE THREAD

**Issue by mvelez83** [sensu/sensu#1189]
Hello,

I'm very new to sensu (version 0.20.3) and I wanted to delete some checks on a host that was removed yet still showed up when I clicked on the hostname. I did some googling and tried to remove the check by doing the following:

1. Log into Redis
2. Run the following -> del result:websql02.:disk_check_centos and del stash:silence/websql03/disk_check_centos
3. Exit Redis

After doing so, I got the following error in the Uchiwa UI: Connection error: Is the sensu API running?

When I checked it was not running. I started it and it started without any issues:

[root@sensu01 ~]# service sensu-api start
 * Starting sensu-api
[root@sensu01 ~]#

After a few minutes the error message returns in the Uchiwa interface as stated above. I checked the logs and found the following:

sensu-api.log:

{"timestamp":"2016-03-12T14:00:32.779324-0500","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2016-03-12T14:00:32.779701-0500","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2016-03-12T14:00:32.779914-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/redis.json"}
{"timestamp":"2016-03-12T14:00:32.780194-0500","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/redis.json","changes":{}}
{"timestamp":"2016-03-12T14:00:32.780377-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/api.json"}
{"timestamp":"2016-03-12T14:00:32.780548-0500","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/api.json","changes":{}}
{"timestamp":"2016-03-12T14:00:32.780713-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/mail_handler.json"}
{"timestamp":"2016-03-12T14:00:32.780916-0500","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/mail_handler.json","changes":{"handlers":{"mail":[null,{"type":"pipe","command":"mailx -s 'Sensu Event' alerts@aevtech.com"}]}}}
{"timestamp":"2016-03-12T14:00:32.781091-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2016-03-12T14:00:32.781254-0500","level":"warn","message":"config file must be valid json","file":"/etc/sensu/conf.d/client.json","error":"Yajl::ParseError"}
{"timestamp":"2016-03-12T14:00:32.781417-0500","level":"warn","message":"ignoring config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2016-03-12T14:00:32.781576-0500","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/rabbitmq.json"}
{"timestamp":"2016-03-12T14:00:32.781778-0500","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/rabbitmq.json","changes":{"rabbitmq":{"port":[5672,5671],"password":"REDACTED","ssl":[null,{"cert_chain_file":"/etc/sensu/ssl/cert.pem","private_key_file":"/etc/sensu/ssl/key.pem"}]}}}
{"timestamp":"2016-03-12T14:00:32.840917-0500","level":"info","message":"api listening","bind":"0.0.0.0","port":4567}
{"timestamp":"2016-03-12T14:00:33.554851-0500","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/stashes","request_body":""}
{"timestamp":"2016-03-12T14:00:33.567917-0500","level":"info","message":"GET /checks","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/checks","request_body":""}
{"timestamp":"2016-03-12T14:00:33.569924-0500","level":"info","message":"GET /clients","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/clients","request_body":""}
{"timestamp":"2016-03-12T14:00:33.573081-0500","level":"info","message":"GET /events","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/events","request_body":""}
{"timestamp":"2016-03-12T14:00:33.576482-0500","level":"info","message":"GET /info","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/info","request_body":""}
{"timestamp":"2016-03-12T14:00:33.580369-0500","level":"info","message":"GET /aggregates","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/aggregates","request_body":""}
{"timestamp":"2016-03-12T14:00:33.581798-0500","level":"info","message":"GET /results","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/results","request_body":""}
{"timestamp":"2016-03-12T14:00:33.584477-0500","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:19:in `load': Yajl::ParseError (MultiJson::ParseError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/api/process.rb:747:in `block (6 levels) in <class:Process>'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:434:in `process_cmd'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/api/process.rb:24:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-api:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-api:23:in `load'
	from /opt/sensu/bin/sensu-api:23:in `<main>'

uchiwa.log:

{"Date":"2016-03-12T14:01:23.544856308-05:00","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","Line":69},"Output":"API call to \"http://localhost:4567/stashes\" returned: Get http://localhost:4567/stashes: dial tcp 127.0.0.1:4567: connection refused"}
{"Date":"2016-03-12T14:01:33.542589179-05:00","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","Line":69},"Output":"API call to \"http://localhost:4567/stashes\" returned: Get http://localhost:4567/stashes: dial tcp 127.0.0.1:4567: connection refused"}
{"Date":"2016-03-12T14:01:43.542472136-05:00","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","Line":69},"Output":"API call to \"http://localhost:4567/stashes\" returned: Get http://localhost:4567/stashes: dial tcp 127.0.0.1:4567: connection refused"}

Not sure what else to do at this point. I can redo everything but I rather try and fix this. Thank you in advance for any and all help and if I'm missing some info etc let me know so I can provide it ASAP.

Thank You!

**Comment by calebhailey** [comment]
@mvelez83 it sounds like the Sensu API died because the data was corrupted (via manual data manipulation in Redis), and as a result the dashboard couldn't connect to the API because it wasn't running. Sensu provides API access to monitoring data stored in Redis - any manual intervention at the Redis level is likely to cause similar issues. Please see [the Checks API documentation](https://sensuapp.org/docs/latest/api-checks) for example. 

We're going to go ahead close this issue as "won't fix", but let us know if you continue to have any issues. 

#monitoringlove

**Comment by RahulMahale** [comment]
I am having same issue

**Comment by mvasilenko** [comment]
observed such issue, answer in this thread solved it
https://serverfault.com/questions/638629/sensu-delete-a-check-from-clients
