### ISSUE TITLE
Sensu client could not find a temporary directory

### ISSUE THREAD

**Issue by masterkorp** [sensu/sensu#1190]
Sensu clients fails to find a tmp directory. 

```
/opt/sensu/embedded/lib/ruby/2.0.0/tmpdir.rb:34:in `tmpdir': could not find a temporary directory (ArgumentError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-settings-3.1.0/lib/sensu/settings/loader.rb:336:in `create_loaded_tempfile!'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-settings-3.1.0/lib/sensu/settings/loader.rb:140:in `set_env!'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-settings-3.1.0/lib/sensu/settings.rb:27:in `load'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-settings-3.1.0/lib/sensu/settings.rb:38:in `get'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/daemon.rb:85:in `load_settings'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/daemon.rb:47:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:29:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:17:in `new'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:17:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:23:in `load'
```

```
$ /opt/sensu/bin/sensu-client --version 
0.20.3
```

**Comment by roobert** [comment]
Likely to be missing sticky bit on `/tmp`, to fix try: `chmod 1777 /tmp`.

**Comment by roobert** [comment]
Alternatively set `TMP`, `TEMP`, or `TEMPDIR`[1] values in the `sensu-client` environment to a writeable directory.

1. from the source for `tmpdir()` here: http://ruby-doc.org/stdlib-2.0.0/libdoc/tmpdir/rdoc/Dir.html#method-c-tmpdir

**Comment by masterkorp** [comment]
Hello @roobert thanks for the tips. The `/tmp` is with the correct `1777` mods.

Tried to run that method by hand and it  finds the tmp folder:
```
$ sudo -Hu sensu /opt/sensu/embedded/bin/ruby -e "require 'tmpdir'; puts Dir.tmpdir()"
/tmp/user/999
```
999 is the correct sensu user id.

Any ideas?

**Comment by masterkorp** [comment]
I also tried to to edit ``/etc/init.d/sensu-service`` and edit ``TMP=/opt/sensu/sv`` which is directory owned and writable by the ``sensu`` user with the same results.

**Comment by calebhailey** [comment]
@masterkorp what platform are you running Sensu on?

**Comment by grgizem** [comment]
Same problem on Ubuntu 14.04 with sensu-server 0.23.2, error message as follows,
`/opt/sensu/embedded/lib/ruby/2.3.0/tmpdir.rb:35:in `tmpdir': could not find a temporary directory (ArgumentError)`

**Comment by enriqueav** [comment]
chmod o+t /tmp
via:
https://blog.diacode.com/fixing-temporary-dir-problems-with-ruby-2

**Comment by freepenguins** [comment]
Ran into this issue on Ubuntu Trusty with sensu-0.25. Fixed after 'chmod o+t /tmp && chmod 1777 /tmp'

**Comment by abrahamrhoffman** [comment]
chmod o+t /tmp worked, thanks!
