### ISSUE TITLE
Ignoring metrics in the sensu server

### ISSUE THREAD

**Issue by afrozl** [sensu/sensu#1193]
I would like to use an alternative rabbitmq consumer process for the metrics being collected by sensu clients. Is there a way to configure sensu server to ignore all events of type 'metric'?

**Comment by calebhailey** [comment]
@afrozl Sensu is already designed to route metrics (or any other event data) to external consumers via [Handlers](https://sensuapp.org/docs/latest/handlers). 

Perhaps if you could provide more context we may be able to provide a more helpful response. In the interim, we're going to go ahead and close this issue as a "won't fix". 

#monitoringlove
