### ISSUE TITLE
Gem fails to install on OpenBSD 5.8 (-release)

### ISSUE THREAD

**Issue by rollcat** [sensu/sensu#1194]
One of Sensu's dependencies, [eventmachine](https://github.com/eventmachine/eventmachine) has recently released a new version (1.2.0) which [fixes a showstopper bug](https://github.com/eventmachine/eventmachine/pull/690) during installation. Sensu still currently relies on the 1.0.9 branch.

I have tested the following diff against eventmachine's `v1.0.9.1` and everything seems to work fine:

```
diff --git a/ext/ed.cpp b/ext/ed.cpp
index a3b23a4..12a4a20 100644
--- a/ext/ed.cpp
+++ b/ext/ed.cpp
@@ -874,6 +874,9 @@ void ConnectionDescriptor::_DispatchInboundData (const char *buffer, unsigned lo
                // If our SSL handshake had a problem, shut down the connection.
                if (s == -2) {
                        #ifdef OS_UNIX
+                       #ifndef EPROTO
+                       #define EPROTO EINTR
+                       #endif
                        UnbindReasonCode = EPROTO;
                        #endif
                        #ifdef OS_WIN32
```

Is there any chance to move to eventmachine 1.2.0 some time soon? Otherwise, if there were another 1.0.9.x release with this patch, would it be possible to bump Sensu's requirement?

**Comment by portertech** [comment]
The Sensu 0.23.0-3 packages in the repositories uses EM 1.2.0.1 :+1:
