### ISSUE TITLE
would like a unique key in event json to simplify ticketing/event aggregation system. 

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu#1196]
We are sending sensu events to sentry (getsentry.com) for logging/event aggregation. Something that would be useful for us (and I think other people if they try tying sensu into a ticketing system) is a unique value (stored as part of the event output) that is generated/stored on the sensu server on the first 1 or 2 status and remains the same until the status returns to 0. 
That way we can categorize/aggregate events based on this value so that a check disk usage % will have the same ticket associated with it from a warning state, to critica,l to resolved... 

 Thanks!

**Comment by CreativelyCloudy** [comment]
+1

**Comment by calebhailey** [comment]
Event IDs (uuid values) already exist (although they aren't documented anywhere), however not in a way that would be useful in this context. Currently event IDs are unique to each occurrence of the event, which isn't necessarily incorrect behavior, but it's also not very useful. Furthermore, event IDs are not used anywhere else in Sensu, so there's no reason we can't make event ids more useful by making them correspond to a specific event. 

:+1:

**Comment by portertech** [comment]
https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L447

Make it:

`:id => stored_event ? stored_event[:id] : random_uuid,`

**Comment by portertech** [comment]
![730147c4-7560-11e4-9375-fefd2f67563b](https://cloud.githubusercontent.com/assets/149630/14333470/ac2de950-fc03-11e5-8e14-9af033c856a9.gif)

**Comment by joshzitting** [comment]
Sweet! I cant wait for this one to be merged! Thanks guys!!

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/849

**Comment by portertech** [comment]
Just about time to merge https://github.com/sensu/sensu/pull/1248 :+1:

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1248 has been merged, the change will be available in the upcoming 0.24 release!
