### ISSUE TITLE
sensu-install without Internet connectivity

### ISSUE THREAD

**Issue by rvanantwerp** [sensu/sensu#1199]
Are there proposals/suggestions for how to use sensu-install on hosts behind firewalls that block outbound Internet connectivity? We have an RPM mirror, but having trouble understanding what 'sensu-install' *actually* does, and how to mimic this behavior via RPM packages.

I think this is a pretty common requirement of most enterprises, and curious how others are dealing with it.

**Comment by acsrujan** [comment]
I've done the following:
Adding this to an RPM mirror repo.. ```/etc/yum.repos.d/sensu.repo```
```
echo '[sensu]
name=sensu
baseurl=http://repositories.sensuapp.org/yum/$basearch/ 
#Change baseurl to your custom url where repo is downloaded instead of above. (S3 in our case)
gpgcheck=0
enabled=1' | sudo tee /etc/yum.repos.d/sensu.repo
```
Hope this helps.

**Comment by portertech** [comment]
You can run your own Rubygems mirror and specify it as a custom source, using `--source`.

```
$sensu-install -h
Usage: sensu-install [options]
    -h, --help                       Display this message
    -v, --verbose                    Enable verbose logging
    -p, --plugin PLUGIN              Install a Sensu PLUGIN
    -P, --plugins PLUGIN[,PLUGIN]    PLUGIN or comma-delimited list of Sensu plugins to install
    -s, --source SOURCE              Install Sensu plugins from a custom SOURCE
```

**Comment by rvanantwerp** [comment]
Thanks for the advice and insight - the missing feature that wasn't inherently obvious to me: sensu-install merely downloads a gem via the embedded rubygems. I didn't see this in the documentation (I may have missed it), but fortunately my enterprise's rubygems mirror sufficed by specifying the custom source.
