### ISSUE TITLE
Filters do not seem to be applied on keepalive checks.

### ISSUE THREAD

**Issue by dmsimard** [sensu/sensu#1204]
My filters are applying on my checks successfully without any problems but it doesn't look like I can get them to run on the keepalive notifications, resulting in me getting spammed every 20 seconds.

Am I doing something wrong or is this an actual issue ?

Given the following example client configuration:

    {
      "client": {
        "name": "hostname",
        "address": "192.168.0.10",
        "subscriptions": [
          "default"
        ],
        "safe_mode": false,
        "keepalive": {
          "thresholds": {
            "warning": 180,
            "critical": 300
          },
          "handlers": [
            "test",
          ],
          "occurrences": 3,
          "filters": [
            "some_filter",
          ]
        }
      }
    }

The handler "test" will be called on every event.
Here is what one of the events looks like:

    {
      "id": "fd5032c9-f8ca-488b-b18b-8bcb80bc9287",
      "client": {
        "name": "hostname",
        "address": "192.168.0.10",
        "subscriptions": [
          "default"
        ],
        "safe_mode": false,
        "keepalive": {
          "thresholds": {
            "warning": 180,
            "critical": 300
          },
          "handlers": [
            "test"
          ],
          "occurrences": 3,
          "filters": [
            "some_filter"
          ]
        },
        "version": "0.22.1",
        "timestamp": 1459607577
      },
      "check": {
        "thresholds": {
          "warning": 180,
          "critical": 300
        },
        "handlers": [
          "test"
        ],
        "occurrences": 3,
        "filters": [
          "some_filter",
        ],
        "name": "keepalive",
        "issued": 1459607765,
        "executed": 1459607765,
        "output": "No keepalive sent from client for 188 seconds (>=180)",
        "status": 1,
        "history": [
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "0",
          "1"
        ],
        "total_state_change": 6
      },
      "occurrences": 1,
      "action": "create",
      "timestamp": 1459607765
    }

**Comment by portertech** [comment]
Filters are applied to handlers, not checks.

**Comment by portertech** [comment]
https://sensuapp.org/docs/0.21/filters#what-are-sensu-filters

**Comment by dmsimard** [comment]
@portertech you're right, I got that mixed up in my different attempts to get this to work.

After doing some *exhaustive* debugging, I found out that the filter was silently crashing due to a bug in my extension. The filters are indeed run correclty. Closing this.

**Comment by arunkumar457** [comment]
David,

Can you please help me how you filtered keep alive checks. 
I am trying from past 3 days to filter keep alive messages and failed.
Appreciate if you can help me on this issue.

**Comment by arunkumar457** [comment]
Hi @dmsimard 

I am facing same issue. Can you please help me how you have resolved the issue.
