### ISSUE TITLE
Log api

### ISSUE THREAD

**Issue by kobbe** [sensu/sensu#1211]
The API should support access to the sensu (server) logs so that they can be displayed in uchiwa.

Scenario: You edit a check in sensu and restart, checking uchiwa to see that it worked but the check is not there. You now have to dig into the log files to find the error which is not very user friendly.

**Comment by portertech** [comment]
Not going to implement this. Log locations can be customized and they can be rotated. Logs are also distributed amongst one or more Sensu servers. There is no replacement for a proper log management solution.
