### ISSUE TITLE
Sensu API malfunctioning on Fedora 23

### ISSUE THREAD

**Issue by danpopp** [sensu/sensu#1212]
After upgrading to the latest version of Sensu (0.23), the Sensu API service is no longer responding to requests. When using cURL directly on http://localhost:4567/|endpoint-name| the response either times out or is returned empty. The Uchiwa dashboard also cannot access the Sensu API after upgrade and returns the following error message in console "http: request canceled (Client.Timeout exceeded while awaiting headers)". I've already ruled out SElinux and other external causes, and attempted to troubleshoot a number of different possible causes to no avail. The only way to restore functionality was to downgrade my version of Sensu.

The services (client, server, and API)  all start-up normally and are not producing any errors in any of the Sensu logs. The API seems to be the only service impacted. Both the server and client are functioning normally from all outward appearances and available log data.

**Comment by nhooey** [comment]
This problem is likely platform-agnostic, and this bug is very likely a duplicate of #1215.

**Comment by danpopp** [comment]
It's possible, however; I haven't experienced any problems so far on Ubuntu 12.04 LTS, Debian Wheezy, Debian Jessie, Fedora 20, Fedora 21, or Fedora 22... So far, I have only been able to replicate this particular failure with Fedora 23.

**Comment by nhooey** [comment]
You need to find out what versions of Sensu are running on those distributions. The distribution itself is much less important.

**Comment by danpopp** [comment]
Thanks for the protip. As stated, the issue is reproducible for me only on Fedora 23 and only when using the latest Sensu API (version 0.23). The issue is remedied by downgrading to a prior version.

**Comment by nhooey** [comment]
I'm probably incorrect, then. Sorry I hadn't read your issue thoroughly enough.

**Comment by mbregg1** [comment]
I'm seeing the same thing on CentOS 7.  Also tried disabling SELinux, and a couple of other things, but was forced to downgrade to restore functionality.

**Comment by danpopp** [comment]
Thanks for the info. I can concur that it's definitely not an SELinux-related issue. Haven't had time to investigate further, but as @nhooey suggests, using verbose/debug level logging might shed some additional light on what's happening under the hood.

**Comment by ulrith** [comment]
I face with the same issue after upgrade to 0.23 version: my Uchiwa dashboard can't connect to API still. Do I have any option besides downgrading to 0.22?

**Comment by danpopp** [comment]
No, unfortunately. Not yet. The bad packages are still in the vendor's repository, and no one from the project has commented on or even triaged this bug. Definitely not a good strategy if they are trying to get people to spring for the enterprise version. Thankfully I QA all my packages before deploying, a botched version like this could really cause a headache for an organization.

**Comment by chuqyang** [comment]
I'm having a similar issue on CentOS 6.7. Downgrading to 0.22 works for now.

**Comment by ulrith** [comment]
I have 0.23.1 version now and Uchiwa (0.14.2) still can't connect to the API (same machine). I have the following in the logs:
```
{"timestamp":"2016-04-21T13:38:00.076106951+03:00","level":"warn","message":"GET http://sensu.gustaff.eu:4567/stashes returned: Get http://sensu.mydomain.tld:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-04-21T13:38:00.076201324+03:00","level":"warn","message":"Connection failed to the datacenter Sensu"}
{"timestamp":"2016-04-21T13:38:00.076239578+03:00","level":"info","message":"Updating the datacenter Sensu"}
```

**Comment by rgardam** [comment]
I'm seeing the same thing on Centos7-1602

**Comment by ulrith** [comment]
@rgardam see https://github.com/sensu/uchiwa/issues/483

**Comment by calebhailey** [comment]
Hello all. Sorry for the radio silence from the Sensu team on this issue. I suspect these issues have been resolved by now (as we're now several releases beyond 0.23.x; latest being [0.28.4](https://sensuapp.org/docs/latest/overview/changelog.html#core-v0-28-4))? 

Barring any new updates to this issue indicating otherwise, we will look to close/resolve this issue due to inactivity at our next issue triage. :v:
