### ISSUE TITLE
Use a less ambiguous HTTP status code for the `/health` API 

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1216]
The `/health` API is currently [hard coded][1] to return a [503 (Service Unavailable) HTTP status code][2], which is often misleading for new users. It also has a potentially ambiguous meaning, in that the API could actually be under load or otherwise unavailable and return a 503. 

According to the HTTP response code specific (RFC2616), 5xx response codes should be used to indicate that the server has erred or is incapable of performing the request, which is not the case when the `/health` API returns a 503, because the server has successfully handled the request. 

> **Server Error 5xx**
> Response status codes beginning with the digit "5" indicate cases in which the server is aware that it has erred or is incapable of performing the request. Except when responding to a HEAD request, the server SHOULD include an entity containing an explanation of the error situation, and whether it is a temporary or permanent condition. User agents SHOULD display any included entity to the user. These response codes are applicable to any request method.

Perhaps a 412 "Precondition Failed" response code would be more appropriate? 

> **10.4.13 412 Precondition Failed**
> The precondition given in one or more of the request-header fields evaluated to false when it was tested on the server. This response code allows the client to place preconditions on the current resource metainformation (header field data) and thus prevent the requested method from being applied to a resource other than the one intended.

Alternatively, perhaps we should consider a custom response code? 

[1]: https://github.com/sensu/sensu/blob/ac3394fe8e2122269210f5e5a83e32c5d6504222/lib/sensu/api/process.rb#L155-L157
[2]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by amdprophet** [comment]
:+1: 

This is a breaking change for anyone who may be relying on a 503 status code. We'll need to make sure to document this well.

**Comment by analytically** [comment]
4xx are client errors, 5xx server errors.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/987

**Comment by calebhailey** [comment]
@analytically this was heavily debated yesterday within our team, but the definition for response code 412 seems to match up pretty well with the use case here. 

If we want to get super technical, we actually think a 2xx response code with a header or payload indicating that the condition was not met would be the most accurate/correct, because the server _is_ successfully responding to the request. Unfortunately, the entire purpose of the `/health` API endpoint is to provide an API for use with third-party services that are only capable of expecting a success/fail response code (i.e. that aren't able to parse headers or payload contents for success/fail), so a 2xx response code would defeat the purpose. 

We could implement a custom 5xx response code, but for the purposes of this API, we think a 412 code is better than 503, and still satisfies the basic requirement of providing success/fail responses to API queries.

Related: https://github.com/sensu/sensu/issues/987

**Comment by portertech** [comment]
Merged @calebhailey's PR! :+1:
