### ISSUE TITLE
DISCUSS: Subdue 2.0!

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1219]
Creating another meta ticket here, to aggregate all outstanding issues & PRs related to subduing checks and handlers (i.e. notification signal/noise) into a single location for discussion and eventual implementation. If you are aware of a related issue or PR – open or closed – please comment on this issue with a link, so we can take every scenario into consideration before designing Subdue 2.0.

Related issues:
- https://github.com/sensu/sensu/issues/777
- https://github.com/sensu/sensu/issues/958
- https://github.com/sensu/sensu/issues/997
- https://github.com/sensu/sensu/issues/999
- https://github.com/sensu/sensu/issues/1004 
- https://github.com/sensu/sensu/issues/1113

We'll update this ticket as we begin planning subdue improvements, so please stay tuned for updates – your feedback is important! #monitoringlove

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-extensions/pull/5

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/pull/847

**Comment by hprins** [comment]
Could we also use subdue feature to handle messages that are not required to be displayed on the dashboard?  We basically are looking for an option to filter messages.

**Comment by calebhailey** [comment]
Tagging https://github.com/sensu/uchiwa/issues/458 here as it may be related.

**Comment by calebhailey** [comment]
Hi friends! Please note the following proposed changes to how Sensu handles `subdue` scheduling: 

- For simplicity, Subdue rules will only be applied at the "scheduler" (i.e. the check requestor)
- Subdue rules will now be supported by subscription checks, _and standalone checks_
- Sensu Filters and Subdues will share a common specification for applying time-based rules (where Subdue rules will be applied at the "scheduler", and Filter rules will be applied at the handler)
- `subdue` attributes will only be referenced from check definitions (i.e. they will be removed from handler definitions)

The new Sensu monitoring flow will be visualized as follows: 

  > check definition => check request => subdue => check execution => check result => event => filters => mutators => handlers

The new Subdue specification (and corresponding time-based rule specification for Filters) is still a work in progress. Stay tuned for more updates on this issue.

**Comment by calebhailey** [comment]
Potentially related: #861

**Comment by RyanJarv** [comment]
Would like to see the use case in #940 be possible. I would think that this is a common enough scenario that it should be a built in, basically being able to subdue or stash something up to a given level. I think it would make sense to apply same thing to subduing checks so that you only get critical's between certain hours.

Another useful thing would be to optionally have stashes be removed when they recover.

**Comment by clev2k** [comment]
Hello, what's going on with https://github.com/sensu/sensu/pull/847 - this functionlity would be great for something I'm currently trying to do.

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1415 has been merged :+1:

**Comment by portertech** [comment]
Going to go through the issues/PRs listed in this description and update them accordingly.

**Comment by calebhailey** [comment]
@portertech I might have beat you to it on a few of them. :)
