### ISSUE TITLE
DISCUSS: API Improvements

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1220]
Creating another meta ticket here, to aggregate all outstanding issues & PRs related to Sensu API improvements (e.g. support for wildcard queries and/or url-parameter based filtering, etc) into a single location for discussion and eventual implementation. If you are aware of a related issue or PR – open or closed – please comment on this issue with a link, so we can take every scenario into consideration before designing the next round of API improvements.

Related issues:
- https://github.com/sensu/sensu/issues/1216 DONE
- https://github.com/sensu/sensu/issues/1211 NOT IMPLEMENTING
- https://github.com/sensu/sensu/issues/1203 DONE
- https://github.com/sensu/sensu/issues/1179 DONE
- https://github.com/sensu/sensu/issues/1161 NOT IMPLEMENTING
- https://github.com/sensu/sensu/issues/1143 DONE
- https://github.com/sensu/sensu/issues/1061 DONE
- https://github.com/sensu/sensu/issues/1004 NOT IMPLEMENTING
- https://github.com/sensu/sensu/issues/999 DONE
- https://github.com/sensu/sensu/issues/984 DONE
- https://github.com/sensu/sensu/issues/940 NOT IMPLEMENTING
- https://github.com/sensu/sensu/issues/935 NOT IMPLEMENTING
- https://github.com/sensu/sensu/issues/900 NOT IMPLEMENTING
- https://github.com/sensu/sensu/issues/838 DONE
- https://github.com/sensu/sensu/issues/550 NOT IMPLEMENTING

We'll update this ticket as we begin planning subdue improvements, so please stay tuned for updates – your feedback is important! #monitoringlove

**Comment by calebhailey** [comment]
In preparation for this discussion, the API has been completely rewritten over the past 2-weeks. So I would encourage anyone who's interested in participating in this conversation to review the new docs: 

- [API Overview](https://sensuapp.org/docs/latest/api-overview)
- [Client API](https://sensuapp.org/docs/latest/api-clients)
- [Checks API](https://sensuapp.org/docs/latest/api-checks)
- [Events API](https://sensuapp.org/docs/latest/api-events)
- [Results API](https://sensuapp.org/docs/latest/api-results)
- [Aggregates API](https://sensuapp.org/docs/latest/api-aggregates)
- [Stashes API](https://sensuapp.org/docs/latest/api-stashes) (and new [Stashes reference docs](https://sensuapp.org/docs/latest/stashes))
- [Health & Info API](https://sensuapp.org/docs/latest/api-health-and-info)
- [API Configuration](https://sensuapp.org/docs/latest/api-configuration)

I'd also love any feedback on the new docs as there's quite a bit of new content there, so any suggestions for improvements would be welcome. 

:shipit:

**Comment by nhooey** [comment]
I created this issue:
* #1253 API support for searching "custom attributes" of clients in client, check, event search

Which I think is relevant to this discussion on API improvements.

**Comment by portertech** [comment]
A generic API response object filter, boolean search, using dot notation, would be very handy.

**Comment by nhooey** [comment]
@portertech Could you clarify what you mean by "dot notation"?

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by calebhailey** [comment]
...though, having said that, it should be noted that we're laying the groundwork for these API improvements via a complete rewrite of the API in the 0.25 release. See: https://github.com/sensu/sensu/pull/1324
