### ISSUE TITLE
Unable to use sensu-install on Windows - bin not added to path in MSI

### ISSUE THREAD

**Issue by wbrodie** [sensu/sensu#1221]
C:\opt\sensu\bin\sensu-install.bat -p sensu-plugins-windows:0.0.10

[SENSU-INSTALL] installing Sensu plugins ...
[SENSU-INSTALL] provided Sensu plugins: ["sensu-plugins-windows:0.0.10"]
[SENSU-INSTALL] compiled Sensu plugin gems: ["sensu-plugins-windows:0.0.10"]
[SENSU-INSTALL] determining if Sensu plugin gem 'sensu-plugins-windows:0.0.10' is already installed ...
[SENSU-INSTALL] gem list -i sensu-plugins-windows --version '0.0.10'
[SENSU-INSTALL] Sensu plugin gem 'sensu-plugins-windows' has not been installed
[SENSU-INSTALL] Sensu plugin gems to be installed: ["sensu-plugins-windows:0.0.10"]
[SENSU-INSTALL] installing Sensu plugin gem 'sensu-plugins-windows:0.0.10'
[SENSU-INSTALL] gem install sensu-plugins-windows --version '0.0.10' --no-ri --no-rdoc --verbose
[SENSU-INSTALL] failed to install Sensu plugin gem 'sensu-plugins-windows'
[SENSU-INSTALL] please take note of any failure messages above
[SENSU-INSTALL] make sure you have build tools installed (e.g. gcc)
[SENSU-INSTALL] trying to determine the Sensu plugin homepage for sensu-plugins-windows ...
'gem' is not recognized as an internal or external command,
operable program or batch file.

C:\opt\sensu\embedded\bin should be added to %PATH% as part of the MSI

Why is mkdir conf.d not in the MSI either!!!??? :)

To Resolve:
$oldPath=(Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).Path
$newPath=$oldPath+’;C:\opt\sensu\embedded\bin\’
Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH –Value $newPath

**Comment by wbrodie** [comment]
@calebhailey  - should this be moved to the build repo as with my other issue?

**Comment by calebhailey** [comment]
@wbrodie yeah, I think so. Thanks! :+1:

**Comment by wbrodie** [comment]
Moved to here 
https://github.com/sensu/sensu-build/issues/157

**Comment by calebhailey** [comment]
thanks @wbrodie :+1:
