### ISSUE TITLE
Windows MSI installer creates path with double backslash

### ISSUE THREAD

**Issue by wbrodie** [sensu/sensu#1222]
```
C:\>echo %PATH%
C:\Program Files (x86)\Python35-32\Scripts\;C:\Program Files (x86)\Python35-32\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\Amazon\AWSCLI\;C:\Program Files\Git\cmd;C:\opt\sensu\\bin
```

`
C:\opt\sensu\\bin`

**Comment by calebhailey** [comment]
Nice catch! :) 

I think this belongs in https://github.com/sensu/sensu-build/issues (see: https://github.com/sensu/sensu-build/blob/0bd2a4334a5425997d4b98ea43f0e160b675e7e4/assets/msi/files/Sensu.wxs#L42).

**Comment by wbrodie** [comment]
Created an issue in the correct repo with your comment
https://github.com/sensu/sensu-build/issues/156
