### ISSUE TITLE
Sensu Server 0.23.0-3 crashes connecting to Redis with the Flapjack handler extension installed

### ISSUE THREAD

**Issue by CVTJNII** [sensu/sensu#1224]
```
{"timestamp":"2016-04-12T01:29:56.229693+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.3.0/lib/sensu/redis.rb:48:in `connect_direct': undefined method `call' for nil:NilClass (NoMethodError)
Did you mean?  caller
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.3.0/lib/sensu/redis.rb:67:in `connect'
        from /etc/sensu/extensions/handlers/flapjack.rb:61:in `post_init'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extension-1.5.0/lib/sensu/extension.rb:19:in `block in initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.0/lib/sensu/server/process.rb:29:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.0/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'
```

Reverting back 0.22.1-1 works as expected, so I don't believe this to be a redis issue.

**Comment by calebhailey** [comment]
It looks like this is an issue with the Flapjack extension, which might need to be updated to work with the latest `sensu-redis` release (or pinned to an older version) which is used by Sensu 0.23. 

```
from /etc/sensu/extensions/handlers/flapjack.rb:61:in `post_init'
```

There were a number of under-the-hood changes to Sensu's Redis implementation in order to enable native Redis Sentinel support, so any extensions that rely on sensu-redis will probably need to be updated accordingly.

**Comment by CVTJNII** [comment]
Aah, I didn't read the trace close enough.  This is an extension of https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/5, then  I'm assuming this is invalid as it isn't a Sensu server issue, then?  Perhaps some weight needs to be thrown behind https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/5?

**Comment by calebhailey** [comment]
@CVTJNII yeah, https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/5 definitely needs some attention. I commented there and I'll bring it up during our internal weekly Sensu sprint this week. Let's keep this open until we make a decision on that.

**Comment by CVTJNII** [comment]
@calebhailey Thanks!

**Comment by chuqyang** [comment]
+1

**Comment by gbolo** [comment]
+1

**Comment by zoran** [comment]
+1

**Comment by NiGame** [comment]
+1

**Comment by psyhomb** [comment]
Is there anything new on this?

**Comment by compuguy** [comment]
I can confirm that it is still broken with 0.25.3.

**Comment by eoly** [comment]
This updated Sensu Flapjack extension should work for you. 

https://gist.github.com/eoly/66f36b824bee93b4105db1cacea62c37

**Comment by zoran** [comment]
Working extension - slightly different from eoly's one:
https://gist.github.com/zoran/457bdac44cb93c3f2ff385ba085153d1

Maybe this issue can be closed?

**Comment by psyhomb** [comment]
This is already elaborated in this issue
https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/5
