### ISSUE TITLE
Unmatched token detection regression?

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1225]
I can't seem to get unmatched check command tokens to log in Sensu 0.23. If I understand the code correctly, it looks like [the `find_attribute_value` method always returns a value][1], so the [`substitute_tokens` method will never capture unmatched tokens][2]. 

Also, although it does look like [there are tests for token substitution non-matches][3], they obviously haven't caught this, so the tests might need to be fixed too. 

[1]: https://github.com/sensu/sensu/blob/master/lib/sensu/utilities.rb#L96 
[2]: https://github.com/sensu/sensu/blob/master/lib/sensu/utilities.rb#L113-L116
[3]: https://github.com/sensu/sensu/blob/master/spec/client/process_spec.rb#L114

**Comment by portertech** [comment]
@calebhailey nothing changed here, existing tests still pass, unmatched tokens (no `|` default value), are reported in the check output.

**Comment by calebhailey** [comment]
Oh, I see. I wasn't understanding this correctly. It doesn't log as long as it has _a value_ to use for the token. That makes sense. I'll close this now.
