### ISSUE TITLE
Sensu::API::Process can provide basic version and health information      Failure/Error: api_test do      RuntimeError:

### ISSUE THREAD

**Issue by Lily913** [sensu/sensu#1227]
I am running latest sensu's test cases in the container, I have started the redis and rabbitmq.
as follows it's the log:
bundle exec rspec -c -b --fail-fast spec/api/process_spec.rb
.F

Failures:

  1) Sensu::API::Process can provide basic version and health information
     Failure/Error: api_test do
     RuntimeError:
       test timed out
     # ./spec/helpers.rb:61:in `block (2 levels) in async_wrapper'
     # ./spec/helpers.rb:53:in`block in timer'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/timers.rb:56:in `fire'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in`call'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in`run'
     # ./spec/helpers.rb:59:in `async_wrapper'
     # ./spec/helpers.rb:72:in`api_test'
     # ./spec/api/process_spec.rb:48:in `block (2 levels) in <top (required)>'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:148:in`instance_exec'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:148:in `block in run'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:301:in`with_around_example_hooks'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:145:in `run'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:494:in`block in run_examples'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `map'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in`run_examples'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:457:in `run'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in`block (2 levels) in run_specs'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `map'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in`block in run_specs'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in`run_specs'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in`run'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
     # /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.0.4/exe/rspec:4:in`<top (required)>'
     # /opt/sensu/embedded/bin/rspec:22:in `load'
     # /opt/sensu/embedded/bin/rspec:22:in`<main>'

Finished in 15.01 seconds (files took 0.59355 seconds to load)
2 examples, 1 failure

**Comment by calebhailey** [comment]
Hi there @Lily913 - thank you for submitting this issue! 

We're giving this issue a new "Tests" label as part of an ongoing issues triage, as we're looking forward to improving the documentation around running the Sensu unit tests. We'll update this issue as soon as this work is scheduled, and again when it is completed.

**Comment by sandipmgiri** [comment]
Hi  @Lily913

I could able to reproduce the issue on x86/ppc64le and also was able to resolve it. 

Actually the issue is related to rabbitmq-server and reddis server, need to start both server before running the tests 

root@0bcafff3096a:/sensu# service rabbitmq-server start
 * Starting message broker rabbitmq-server

root@0bcafff3096a:/sensu# service redis-server start
Starting redis-server: redis-server.

now run your test cases -->

root@0bcafff3096a:/sensu# bundle exec rspec -c -b --fail-fast spec/api/process_spec.rb
...............................................................................................

Finished in 22.88 seconds (files took 0.31258 seconds to load)
95 examples, 0 failures
