### ISSUE TITLE
Unable to connect to redis after upgrade to 0.23.0

### ISSUE THREAD

**Issue by ball-hayden** [sensu/sensu#1229]
After upgrading to sensu 0.23.0, sensu fails to start properly (although the process doesn't exit). 
Downgrading to 0.22.0 fixes the problem.

The issue appears to be related to redis based on the following extracts from the `sensu-server` log.

```
{"timestamp":"2016-04-12T15:25:02.278173+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/redis.json"}
{"timestamp":"2016-04-12T15:25:02.278224+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/redis.json","changes":{"redis":[null,{"port":6379,"host":"localhost","reconnect_on_error":false,"db":0,"auto_reconnect":true}]}}
...
{"timestamp":"2016-04-12T15:25:02.310367+0000","level":"debug","message":"connecting to redis","settings":{"port":6379,"host":"localhost","reconnect_on_error":false,"db":0,"auto_reconnect":true}}
{"timestamp":"2016-04-12T15:25:02.381532+0000","level":"error","message":"redis connection error","error":"unable to connect to redis server"}
```

**Comment by calebhailey** [comment]
@ball-hayden see: https://github.com/sensu/sensu/issues/1209 

There are warnings in the new install docs to help avoid this issue; e.g.: https://sensuapp.org/docs/latest/install-redis-on-rhel-centos#example-standalone-configuration

**Comment by ball-hayden** [comment]
How on earth did I not find that issue when searching.

Sorry!

**Comment by calebhailey** [comment]
No worries!
