### ISSUE TITLE
Make subscriptions optional for client configuration and standalone able to be set

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu#1231]
Really enjoying sensu, like a breath of fresh air. Like using Ansible for the first time.

All my clients are standalone. It seems it would be more consistent with the check config if I didn't have to specify "subscriptions": [ "none" ] but instead could use the option "standalone": true for the client config.

If there is an issue of that being a required field, it could be populated with the string  'standalone' as it is set to true.

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by portertech** [comment]
0.26 is now stable, which includes an automatic client subscription. There is a known validation error, which is fixed by https://github.com/sensu/sensu-settings/pull/48 0.26.5 will include it.
