### ISSUE TITLE
API: support push/events

### ISSUE THREAD

**Issue by kaos** [sensu/sensu#1233]
Joining the discussion for #1220 

I'm hoping we can get to a state where events are pushed all the way from sensu out to the web UI (Uchiwa-web) without polling all data frequently. I've not yet run any benchmarks, but I just fear that it is going to be a bottleneck to refetch all data all the time when we get a large number of hosts and checks etc, apart from feeling just inefficient.

In case a websocket kind of endpoint is out of scope, perhaps the ability to add a query filter to only get objects changed since a given timestamp/revision. Or support both, for clients that don't like/can use a websocket kind of api.

**Comment by cwjohnston** [comment]
@kaos thanks for submitting this idea, we've flagged it for consideration as a future feature.

**Comment by kaos** [comment]
_If_ I were to find myself with some unexpected free time on my hands, would it be worth while investigating the feasibility to use https://github.com/igrigorik/em-websocket for this?

**Comment by portertech** [comment]
Sensu 2.x is a rewrite in Go and includes a new Web UI. We're not going to implement this in Uchiwa or the current Sensu Enterprise Dashboard. Thank you for the issue.
