### ISSUE TITLE
Long check result sent to the client TCP socket fails to be processed

### ISSUE THREAD

**Issue by moises-silva** [sensu/sensu#1235]
When sending a large check result buffer to the client TCP socket the client fails to parse the first received chunk but MultiJson.load() does not throw any exception and instead returns a half-baked object of type Symbol which then causes an exception in process_check_result() when trying to access its elements.

I saw that recently Sean dropped MultiJson in favor of sensu-json. I have not tested if the same problem exists.

The json data we're seding is kind of sensitive (billing info) so I cannot paste the full log. Suffice to say is a json struct of about 45KB, but this is the extra logging I've added to the client socket.rb file to debug this problem:

```
{"timestamp":"2016-04-16T02:35:48.321689-0400","level":"warn","message":"Parsing data with MultiJson"}
{"timestamp":"2016-04-16T02:35:48.321985-0400","level":"warn","message":"Adapter","adapter":"MultiJson::Adapters::Yajl"}
{"timestamp":"2016-04-16T02:35:48.323086-0400","level":"warn","message":"Successfully parsed data with MultiJson"}
{"timestamp":"2016-04-16T02:35:48.323189-0400","level":"warn","message":"Watchdog is now cancelled"}
{"timestamp":"2016-04-16T02:35:48.323272-0400","level":"warn","message":"check object_id","id":"857308"}
{"timestamp":"2016-04-16T02:35:48.324687-0400","level":"warn","message":"check class","class":"Symbol"}
{"timestamp":"2016-04-16T02:35:48.324785-0400","level":"warn","message":"check to_s","class":"output"}
{"timestamp":"2016-04-16T02:35:48.324863-0400","level":"warn","message":"Setting status"}
{"timestamp":"2016-04-16T02:35:48.325019-0400","level":"warn","message":"failed to process check result from tcp socket, waiting for more data ...","error":"no implicit conversion of Symbol into Intege
r"}
```

All of those messages are printed in process_check_result(), so the check is supposed to be already parsed by MultiJSON, but the check var is of type 'Symbol' instead of Hash, so the next line throws an exception:

``` ruby
check[:status] ||= 0
```

The exception text is, as expected, saying "no implicit conversion of Symbol into Integer".

I did more digging and this seems like a problem with the backend json parsing library Yajl or the ruby gem that wraps that C library. I was able to produce a small script that tries to parse the incomplete json string read from the tcp socket (I stored that in a file) and Yajl returns the Symbol "output" perhaps indicating that key is incomplete? anyways, I ended up patching sensu to be more generic and tolerant with errors when parsing TCP streams. Now instead of looking for a specific exception, I just keep trying to parse no matter what until either succeed or when the watchdog times out.

I did not open a PR because I wanted to discuss if this is a change you guys would accept at all given that you've moved to another JSON library and strictly speaking this is a work-around (or improved resiliency) for bugs on lower layers.

Here is the change: https://github.com/sangoma/sensu/compare/faf178deca0a...be075870e4aa

**Comment by portertech** [comment]
Hey @moises-silva, have you tried Sensu 0.23.0-3? Sensu switched to it's own JSON parser abstraction library, sensu-json, which uses Oj on CRuby.

**Comment by moises-silva** [comment]
@portertech Hey, yeah I noticed on the git logs you switched the json parser. I just finished tonight debugging this problem and didn't have a chance to try 0.23.0-3 yet. I will do so asap and let you know my findings.

**Comment by moises-silva** [comment]
@portertech I will be trying new sensu tomorrow, but I was wondering if you'd be open to accept a patch to include the length of the buffer first for tcp connections. This would be backwards compatible, so clients that are aware of this can use the extension by sending a little header first including the length, but existing clients would keep happily sending just a json string. This would make things more reliable than the current 'try and error' approach? I can appreciate the simplicity of it, but once you want something more reliable (e.g doesn't break if for whatever reason a network hiccup exceeds the 500ms watchdog and at the same time don't delay if not needed).

**Comment by portertech** [comment]
@moises-silva I would happily except a patch for buffer length :+1: As long as the implementation is backwards compatible and relatively clean :-)

**Comment by calebhailey** [comment]
Tagging this for the 0.24 release, assuming we get a PR in time. :)

**Comment by portertech** [comment]
@calebhailey we should target 0.25, but bump it up if we receive it in them :-)

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by moises-silva** [comment]
@portertech PR #1352 is what I came up with. I hope is not "too much".

**Comment by portertech** [comment]
We should test the original fix that @moises-silva provided (https://github.com/sangoma/sensu/compare/faf178deca0a...be075870e4aa) to fix the Sensu client TCP socket input, while implementing https://github.com/sensu/sensu/issues/1432 for HTTP.

**Comment by portertech** [comment]
The Sensu 0.26 client socket rescues `Sensu::JSON::ParseError, ArgumentError` when parsing check results. The Sensu JSON library now wraps the Oj parser exception, so we should be catching these errors. 

https://github.com/sensu/sensu/pull/1488 has been merged, which provides an HTTP socket :+1: 

@moises-silva thank you!
