### ISSUE TITLE
Sensu Redis authentication issue

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu/sensu#1238]
Can someone please confirm Sensu Redis AUTH is working fine for them.

Sensu Version: sensu-0.23.1-1.x86_64
Redis Version : redis-2.8.19-2.el7.x86_64

I am trying to get Sensu work with Sentinel clustered Redis instance, but sensu cannot seems to be able to authenticate to Redis. Enabling auth is a prerequisite for setting up Sentinel.

I have tried Sensu with Standalone Redis with AUTH as well as with Sentinel, both configuration fails with same errors.

Things work out fine if I disable Redis AUTH.

Tried both the following configurations, both configuration fails with same errors

```
{
   "redis": {
    "host": "10.xx.xx.xx",
    "port": 6379,
    "password": "abcd123",
    "reconnect_on_error": true
  }
}
```

Sentinel:

```
{
   "redis": {
    "reconnect_on_error": true,
    "password": "abcd123",
    "sentinels": [
      {
        "host": "10.xx.xx.xx",
        "port": 26379
      },
      {
        "host": "10.xx.xx.xx",
       "port": 26379
      }
    ]
  }
}
```

Both the above configuration are failing with 

sensu-api.log/sensu-server.log

```
{"timestamp":"2016-04-19T16:12:48.553912+0530","level":"error","message":"redis connection error","error":"redis returned error code: NOAUTH Authentication required."}
```

I have checked Redis as well, authentication works fine with redis-cli, doesn't seems to be the issue.

**Comment by calebhailey** [comment]
@jaykumar-jnpr that error is coming from Redis. I am able to reproduce this error if I enable the `requirepass` configuration in my `/etc/redis/redis.conf` (as follows) but don't provide Sensu with the password. 

```
################################## SECURITY ###################################

# Require clients to issue AUTH <PASSWORD> before processing any other
# commands.  This might be useful in environments in which you do not trust
# others with access to the host running redis-server.
#
# This should stay commented out for backward compatibility and because most
# people do not need auth (e.g. they run their own servers).
# 
# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
#
requirepass mysupersecurepassword
```

I wonder if perhaps your config isn't being picked up by Sensu. Please try using the new `--print_config` option in Sensu 0.23 to confirm that your password is being loaded by Sensu. Please refer to the [Sensu configuration reference documentation][1] for more information on how to do that. The `--print_config` output will include some log output which might provide some clues if you have conflicting config, or some bad json, etc. 

Let me know if this helps. #monitoringlove  

_NOTE: I edited the OP description to put config snippets in code blocks, for readability._

[1]:  https://sensuapp.org/docs/latest/configuration#sensu-command-line-interfaces-and-arguments

**Comment by jaykumar-jnpr** [comment]
Closing the issue. @calebhailey was correct, due to a typo, redis configuration was not being picked up by sensu (named the file .conf instead of .json)

Sensu print_config helped in identifying issue.

`sudo -u sensu /opt/sensu/bin/sensu-api -P -c /etc/sensu/config.json -d /etc/sensu/conf.d/`

**Comment by calebhailey** [comment]
@jaykumar-jnpr thanks for the follow-up and for closing the issue! 

#monitoringlove
