### ISSUE TITLE
"output":"", "status":null  Crashed sensu-server V20.3

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu#1241]
I had a client over the weekend for some unknown reason return an empty output status. '"output":""'
This cause my sensu-server to crash with the following error..

``` {"timestamp":"2016-04-24T08:41:08.185272-0700","level":"info","message":"pruning check result aggregations"}
{"timestamp":"2016-04-24T08:41:09.090853-0700","level":"info","message":"processing event","event":{"id":"6c9b2670-90ce-4461-b814-355953a9e17e","client":{"address":"192.168.20.30","subscriptions":["prod","base"],"name":"machine.name.was.here","version":"0.21.0","timestamp":1461512460},"check":{"command":"/etc/sensu/plugins/check_load.sh -w '48.0 40.0 32.0' -c '64.0 56.0 48.0'","standalone":true,"handlers":["default"],"interval":60,"notification":"Load issue","occurrences":1,"refresh":900,"event_description":"System Load Issues!","name":"check_load","issued":1461512468,"executed":1461512468,"duration":0.026,"output":"","status":null,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0",""],"total_state_change":6},"occurrences":1,"action":"create","timestamp":1461512469}}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/filter.rb:160:in `[]': no implicit conversion from nil to integer (TypeError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/filter.rb:160:in `handle_severity?'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/filter.rb:293:in `filter_event'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:144:in `block in process_event'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:142:in `each'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:142:in `process_event'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:409:in `block (4 levels) in process_check_result'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:327:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:327:in `block (2 levels) in update_event_registry'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:443:in `process_cmd'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:23:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:23:in `load'
	from /opt/sensu/bin/sensu-server:23:in `<main>'
```

This is the first and only time I have seen this but I was a little shocked that the server died from it.. I will look at the newer versions and see if the code is the same.

**Comment by joshzitting** [comment]
https://github.com/sensu/sensu/blob/master/lib/sensu/server/filter.rb#L158
It was cuased by this line of code and my output had `"status":null` 
I am not sure why that happened but should it happen again I hope it doesnt crash the sensu-server anymore.. Any thoughts??

**Comment by calebhailey** [comment]
@agoddard can you try to recreate this?

**Comment by portertech** [comment]
Odd, the child process (execution) bits haven't changed in a long time. Curious to see if this can be reproduced :+1: 

@joshzitting What platform is the client running on?

**Comment by portertech** [comment]
@joshzitting perhaps try upgrading to a recent version of Sensu, such as 0.23.2-1 :+1:

**Comment by joshzitting** [comment]
@portertech I would love to upgrade to a newer verison and it should happen on our next chef run... 
This is a smartOS platform running with a sensu gem installation (since no packages are available on pkgin yet )
Thanks guys..

**Comment by agoddard** [comment]
@joshzitting  I haven't been able to reproduce this on 0.20.3 with output: "" - however I'm confused about how you were able to get a status of NULL from the check, can you share the check you were using? I can replicate a blank output and confirm it doesn't crash the server (with and without the handler severities set & with/without filters).

Also, when you're upgrading to 0.23, don't miss that the repos moved around 0.20.*, so you'll need to make sure you're pulling from repositories.sensuapp.org now, where the latest packages are.

**Comment by joshzitting** [comment]
@agoddard we were a little surprised when it returned null too.. I think the VM timed out or something (it was very busy at the time) We are working on getting everything upgraded to a newer version of sensu.. if you cant reproduce it then Ill consider it a one time bug... Thanks for your help!
