### ISSUE TITLE
Feature Request - Add option to base keepalives timestamp on offset system time based on drift of ntp

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu#1247]
I had run into the common time sync issue with the keepalives.

Most of my sites this is not an issue, I just reconfigure ntpd however there are a few environments where for various reasons I am unable to change the system time. I currently disable the keepalives for these sites.

It would great if sensu could have an option to do the following:
cat </dev/tcp/time.nist.gov/13 (I'm sure there are better ways)

And then base keepalives on the offset of the drift of the above result on the system time. It's a bit hacky and wont be super accurate as it doesnt take into account latency but it may fix the keepalives

**Comment by cwjohnston** [comment]
@AirCombat as an alternative to disabling keepalives you may wish to consider setting per-client [keepalive thresholds](https://sensuapp.org/docs/0.25/reference/clients.html#thresholds-attributes) to combat the drift you are seeing. I'm closing this issue as I believe that the existing support for disabling keepalives and per-client keepalive thresholds is sufficient.
