### ISSUE TITLE
API support for searching "custom attributes" of clients in client, check, event search

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1253]
The API should support searching for a client's "custom attributes", which are arbitrary field values set by the user, when searching for clients, checks or events.

Given this feature, the following questions should be easily answerable:
1. What is the set of `CRITICAL` events matching name-pattern `load` for Clients with `country` set to `Canada`?
2. What is the set of Events matching check-name pattern `disk*` for clients with `> 4GB` of `memory`?
3. What is the set of Checks that clients with `> 4` `CPUs` are subscribed to?
4. What is the set of Clients with `< 20GB` of `disk_capacity`?

These particular questions not be the most useful to everyone, but they represent the degree of flexibility that the API search should have to satisfy anyone's search needs.

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1595 implements this :+1:
