### ISSUE TITLE
Feature request: different intervals depending on last status

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1255]
For some checks it may be useful to have different `interval`-values depending on the status of the last check. Something like:

```json
"intervals": {
    "ok": 3600,
    "warning": 1800,
    "fail": 90,
    "unknown": 90
}
```
The above will perform the check once an hour normally, but will try again in 30 minutes after a warning, and keep trying every minute-and-a-half in case of failure or unexpected result. This may help admins get their dashboards back to green sooner after they've corrected the problem :)

For example, I have a check verifying expiration of SSL-certificates. It normally runs once _per day_. But, if it begins alerting because a certificate gets too close to expiration, we are likely to respond the same day -- having Sensu calm down _automatically_ shortly thereafter would be nice.

**Comment by portertech** [comment]
Sensu uses a pub/sub model, checks target one or more Sensu clients via subscriptions. Sensu DOES NOT target individual clients, so this feature could not be applied to standard checks. Standalone checks (client execution scheduler) are not aware of check result history, this feature would require local state.

The Sensu API has `/request`, which can be used to trigger another check run, immediately. Exposing the API `/request` functionality on Uchiwa events would be pretty slick.

I am not a fan of multiple check execution intervals as a feature, as it does not align with Sensu's design and introduces scheduler complexity.

**Comment by cwjohnston** [comment]
@UnitedMarsupials thanks for taking the time to raise this issue and describe your use case, but I'm closing it as this isn't a feature we're ready to consider right now.
