### ISSUE TITLE
mutated event is not being passed child handlers in when handler is set

### ISSUE THREAD

**Issue by lgarciaaco** [sensu/sensu#1256]
If the handler type is *set*, and it has a mutators, the child handlers dont get the mutated event, but the original one.

For the following example, I would expect to see it the handler show the mutated event from notify:
```
{
  "handlers": {
    "notify": {
      "command": null,
      "type": "set",
      "handlers": [ "slack", "show" ],
      "mutator": "officehours"
    }
  }
}

{
  "handlers": {
    "show": {
      "command": "/etc/sensu/handlers/show.rb",
      "type": "pipe"
    }
  }
}
```

**Comment by portertech** [comment]
Mutators cannot be applied to a set. Mutators can only be applied to the individual handlers. It looks like you are using a mutator to accomplish the functionality/responsibility of a filter https://sensuapp.org/docs/latest/filters

**Comment by lgarciaaco** [comment]
@portertech: well, no, officehours is actually a mutator that add event['officehours'] = 'yes' or 'not'. Then I of course filter using that field but I omitted the filter config from the show handler to keep the example simple.

But I get the point, no mutators for set handlers. Does this also apply for filters?

**Comment by cwjohnston** [comment]
@lgarciaaco yes, the same limitation applies to filters, we've [updated the documentation on handler sets to call this out](https://sensuapp.org/docs/latest/reference/handlers.html#handler-sets).
