### ISSUE TITLE
/events/:client should return 404 for clients that do not exist

### ISSUE THREAD

**Issue by somic** [sensu/sensu#1258]
Right now it returns empty list and HTTP 200 OK.

Sensu 0.22

**Comment by portertech** [comment]
I think the current behaviour is correct, as it returns an empty array, which is data representing the current state for the client.

**Comment by xyntrix** [comment]
Agree.  404 to me means the server is not able to serve a request (web server problem), regardless of the content in the page. I'd expect a 200 and the body of the data is empty or the header contains application response information (no client found).

**Comment by cwjohnston** [comment]
Closing this issue as the present implementation is considered correct.
