### ISSUE TITLE
Scheduler Drift

### ISSUE THREAD

**Issue by dhdanno** [sensu/sensu#1260]
I have noticed a problem where checks may be drifting from the scheduled execution time.

In my environment I noticed that over a period of time our checks were running close together. Changing the interval seems to have stopped the issue from occurring.

I wrote up a summary here: http://stackoverflow.com/questions/37081935/sensu-scheduler-oddness/37082272 and Kobbe mentioned he noticed the execution of checks drifts over time and the checks end up getting "clumped" together and pegging the CPU for that moment. This is what we noticed too.

**Comment by portertech** [comment]
I have observed EM timer (periodic) drift, this is a valid issue. EM periodic timers need to account for drift, a quick search came up with a monkey patch http://soohwan.blogspot.ca/2011/02/fix-eventmachineperiodictimer.html I would prefer to fix it in upstream EM, at least adding an option to compensate.

**Comment by portertech** [comment]
https://github.com/suwanny/eventmachine/commit/0aee27bc9e2b09b66024c9b1e33d0cc034e0027f

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by portertech** [comment]
As EventMachine as a project tends to move very slow, we should implement something like `Sensu::PeriodicTimer` with the logic mentioned above https://github.com/suwanny/eventmachine/commit/0aee27bc9e2b09b66024c9b1e33d0cc034e0027f

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1577

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1577 fixed this :+1: will be in 0.28 later today.

**Comment by cwjohnston** [comment]
We're reverting #1577 due to issues raised in #1612. Will need an alternative implementation compensating for timer drift to properly address this issue.

**Comment by portertech** [comment]
Users can optionally use the `cron` syntax instead of `interval`, which is not affected by the EM periodic timer drift.

**Comment by portertech** [comment]
This is fixed in [Sensu 2.0](https://github.com/sensu/sensu-go).
