### ISSUE TITLE
Why i couldn't see any host in Uchiwa dashboard?

### ISSUE THREAD

**Issue by thinhduckhoi** [sensu/sensu#1262]
Hi everyone,
After installing sensu with uchiwa, i accessed the Uchiwa Dashboard but didn't see any information about my host i'm running on.
And here's the uchiwa configuration file.
{
  "sensu": [
    {
      "name": "Site 1",
      "host": "Ip of my host",
      "port": 4567,
      "timeout": 10
    },
    {
      "name": "Site 2",
      "host": "api2.example.com",
      "port": 4567,
      "ssl": false,
      "path": "",
      "user": "",
      "pass": "",
      "timeout": 10
    }
  ],
  "uchiwa": {
    "host": "0.0.0.0",
    "port": 3000,
    "refresh": 10

<img src="http://www.upsieutoc.com/images/2016/05/12/uchiwa.jpg" alt="uchiwa.jpg" border="0">

Can someone tell me the reason, please? I can't use Sensu to monitor my only server or Sensu is just used for client server?

**Comment by kobbe** [comment]
Read in the logs about why. Both uchiwa and sensu have logs.

**Comment by portertech** [comment]
Your screenshot suggest a Uchiwa "DC" error (probably failing to communicate with the Sensu API).

**Comment by cwjohnston** [comment]
@thinhduckhoi thanks for raising this issue but I'm going to close it due to inactivity and being opened against the wrong repo. Please feel free to work through the uchiwa repository if you are still having trouble.
