### ISSUE TITLE
API: Option for "additional" read-only user

### ISSUE THREAD

**Issue by rodriguesalex** [sensu/sensu#1264]
It would be great if the API could support multiple users such that we could provide our development team with read-only access to query the API

**Comment by sureshsubramaniam** [comment]
👍

**Comment by calebhailey** [comment]
@rodriguesalex, @sureshsubramaniam: this is an upcoming feature in the Sensu Enterprise Console API (i.e. the Sensu Enterprise Dashboard backend). Which will not only provide token-based RBAC against the Sensu API, it will also provide a single API endpoint for multiple Sensu installations. This feature is scheduled for the next release, to become available later this month (July 2016). 

There are no plans to implement these features in the Sensu Core API at this time, so I'm going to close this issue. Please feel free to visit the Sensu website to learn more about Sensu Enterprise, here: https://sensuapp.org/enterprise
