### ISSUE TITLE
Sensu client reporting "incompatible library version" when attempting to load a gem

### ISSUE THREAD

**Issue by trekr5** [sensu/sensu#1269]
Hi,

I have a situation in which in one of my sensu plugins requires the gem tiny_tds to connect to an SQL database and extract a value and output this to a graphite server. When I try to run the plugin at present and I check in my sensu-client.log to confirm that the values are being extracted, i see the following:-

`"metrics_donations_paypal","issued":1463472817,"executed":1463472817,"duration":0.191,"output":"/opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in` `require': incompatible library version - /opt/sensu/embedded/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/tiny_tds-0.7.0/tiny_tds/tiny_tds.so (LoadError)\n\tfrom /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/tiny_tds-0.7.0/lib/tiny_tds.rb:42:in `<top (required)>'\n\tfrom /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'\n\tfrom /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'\n\tfrom /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'\n\tfrom /opt/sensu/embedded/bin/metrics-donations-paypal.rb:1:in ``<main>'\n","status":1}}}`

I've ensured that the tiny_tds gem is installed using the following in chef cookbook that runs this sensu plugin:-

    sensu_gem 'tiny_tds' do
	action :install
    end

Can someone please tell me what could be causing this error?

Thanks

**Comment by portertech** [comment]
@trekr5 have you tried uninstalling the gem from the embedded ruby prior to letting chef reinstall it?

**Comment by trekr5** [comment]
Hi ,

Found a solution. 

The tiny_tds gem version 1.0.3 required a seperate freetds library to work with ruby 2.2 . The 0.7 version of tiny_tds had this library already bundled together so it was a question of installing the freetds library separately.

Thanks

**Comment by portertech** [comment]
@trekr5 great, glad you figured it out :+1:
