### ISSUE TITLE
(API) Feature request: Get real IP of clients

### ISSUE THREAD

**Issue by kobbe** [sensu/sensu#1276]
Currently in Uchiwa one can see the IP of a server. Unfortunately this is the IP that is configured in the client. Due to dynamic IP addresses in our environment it is impossible to use a fixed IP in the description. I would therefore like to see the actual IP address of each client. I guess there needs to be a new field in the client API like "real-ip-adress" or something.

Or current setup works since the server has a real domain name. It would be really nice if Sensu could help me with the task of keeping track of the clients IPs.

Thanks :)

**Comment by selbyk** [comment]
Don't know how the developers feel, but it doesn't seem like Sensu's job to do this.  We use a provisioning with Ansible to set the correct IPs in the sensu client config.  You could use a cron job and http://checkip.amazonaws.com/ to update the config and reload sensu client on IP change.

**Comment by cwjohnston** [comment]
Closing this as I agree that this is not Sensu's job to determine the canonical IP address of a system.

Here are a couple additional ideas:
* the [`SENSU_CLIENT_ADDRESS` environment variable](https://sensuapp.org/docs/0.25/reference/configuration.html#sensu-environment-variables) can be used to provide the value of the client `address` attribute
* #1362 describes auto-discovery of additional `client` attributes, so this may cover your use case in the future. 

Please feel free to comment on #1362 if you have any additional thoughts.
