### ISSUE TITLE
--print_config should output consumable json

### ISSUE THREAD

**Issue by mattyjones** [sensu/sensu#1277]
This is in reference to #1197 

I may be using this wrong so it may be a pebkac issue.  I am trying to consume the output from this and running into an issue. From the commandline I am seeing this:

```
sudo ./sensu-client -P
{"timestamp":"2016-05-22T15:18:19.321275+0000","level":"fatal","message":"invalid settings"}
{"timestamp":"2016-05-22T15:18:19.321414+0000","level":"fatal","message":"client must be a hash","object":null}
{"timestamp":"2016-05-22T15:18:19.321467+0000","level":"fatal","message":"SENSU NOT RUNNING!"}
```

```
sudo ./sensu-client -d /etc/sensu/conf.d -P    
{"timestamp":"2016-05-22T15:19:52.518087+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2016-05-22T15:19:52.518195+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/process-dnsmasq.json"}
{"timestamp":"2016-05-22T15:19:52.518273+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/process-consul.json"}
{"timestamp":"2016-05-22T15:19:52.518401+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/process-consul.json","changes":{"checks":{"process-consul":[null,{"command":"sudo -E /opt/sensu/embedded/bin/check-cmd.rb -c 'service consul status'","standalone":true,"handlers":["notification"],"interval":60,"subscribers":["all"],"type":"status"}]}}}
{"timestamp":"2016-05-22T15:19:52.518486+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/process-telegraf.json"}
{"timestamp":"2016-05-22T15:19:52.518594+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/process-telegraf.json","changes":{"checks":{"process-telegraf":[null,{"command":"sudo -E /opt/sensu/embedded/bin/check-cmd.rb -c 'service telegraf status'","standalone":true,"handlers":["notification"],"interval":60,"subscribers":["all"],"type":"status"}]}}}
```
This goes on for each configuration file I have in the directory then it spits out the valid json. Is my configuration borked or am I using the flag wrong.  Looking [here](https://github.com/sensu/sensu/pull/1197/files#diff-2a7cdd2fd11ac77dc3f35be73e06b7d0R84) I am also not seeing the warn message in either the client log or stdout. Looking [here](https://github.com/sensu/sensu/pull/1197/files#diff-2a7cdd2fd11ac77dc3f35be73e06b7d0R85) at the next line I do infact see the passwords redacted and the json is coming out formatted.

I understand why I am getting the log loading messages as those are std when the client loads but I am not able to output the json output any other way. The client is currently running when I am trying to use the flags. My config layout is 

```
conf.d/
  client.json
  checks/
    foo.json
    bar.json
    baz.json
  rabbitmq.json
```

FWIW here is what I have to do to get this to work:

```golang
	c1 := exec.Command("/opt/sensu/embedded/bin/sensu-client", "-d", "/etc/sensu/conf.d", "-P")
	c2 := exec.Command("grep", "-v", "timestamp")
```

I then 
```
err := json.Unmarshal(b2.Bytes(), jsonOut)
	if err != nil {
		panic(err)
	}
```

The issue with this beyond the ugly code is that I have a newline at the end of the grep that pisses off Go. I am assuming this is from the grep as the json output itself will lint just fine but my panic comes at the last line with is blank. 

The end result I need is a data structure with my running config that I can then use for a series of Sensu or Chef handlers that will automatically remove check results and prune redis using the Sensu api for check definitions that Chef has removed from the configuration directory.

**Comment by portertech** [comment]
@mattyjones Sensu `--print_config` available in >= 0.23, will output the usual configuration compilation log lines prior to a standard puts() https://github.com/sensu/sensu/blob/master/lib/sensu/daemon.rb#L86-L91 Are you not seeing `outputting compiled configuration and exiting`? On the correct release?

**Comment by mattyjones** [comment]
<img width="1275" alt="screen shot 2016-05-25 at 12 07 43 pm" src="https://cloud.githubusercontent.com/assets/672940/15547321/4aaea3ba-2271-11e6-9e3c-e82ae9962a48.png">

@portertech

**Comment by portertech** [comment]
@mattyjones Looks like you are not running it as the Sensu user (`sudo -u sensu`) and you are not running it with the runtime arguments.

**Comment by calebhailey** [comment]
@mattyjones: two thoughts here: first of all, you can achieve your desired output by following the suggested "PRO TIP" [in the documentation][1] and setting the logging level to `-L error` or `-L fatal`. 

Secondly, we probably could/should consider making `--print_config` output an array of hashes. For scripts where you're looking for the actual configuration object, you could always grab the last item in the array (e.g. `pring_config_output[-1]`). 

[1]: https://sensuapp.org/docs/0.23/reference/configuration.html#sensu-command-line-interfaces-and-arguments

**Comment by mattyjones** [comment]
@portertech  Changing the user had no effect. I was running with the runtime arguments.

To amend this issue and need. I want the **running** config that has already been compiled as is in the settings var. This will compile the config that I pass to it which may differ from the running config. After looking at the suggestions and code above this is is all set and I will close this out and create a new one with the feature request of the running config.

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by portertech** [comment]
0.27 will have a temporary file containing the running configuration (no redaction). We have no intention of changing `--print_config` at this time. Closing this issue.
