### ISSUE TITLE
Add a feature to warn/crit on Sensu client version compliance

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1279]
We recently experienced an issue where several thousand old clients (0.16.0) were connected to Sensu and a  network degradation event rolled through.   Due to challenges with that older version, we ended up with a flood of connections into RabbitMQ (n-thousand clients all doing 300-400 connections each).  

It would be great if there was a feature in Sensu-core to raise an alarm if the client version is less than a minimum supported version.  Perhaps something in-line with the keepalive check, but specifically for client version.

This might look like this:  If I have Sensu server v0.20.3 deployed and we pick up a 0.16.0 client, a warning is issues for the client under the "client_sensu_version" check name.

This might be configured on the Server as:
```
{
  "server":
     "global_settings": {
         "version_check": {
            "warn_minimum_version" => "0.19.0",
            "crit_minimum_version" => "0.16.0",
            "handler" =>  "foo_notification"
        }
    }
}

**Comment by portertech** [comment]
Sensu will be hitting a 1.0 release later this summer. 1.0 will represent a "stable system" (no breaking changes for 1.x.x). The Sensu documentation for older releases will soon only be available via https://github.com/sensu/sensu-docs, we are not going to introduce a feature like this for outdated/legacy releases, which have known security vulnerabilities etc.

**Comment by mattyjones** [comment]
@xyntrix  It is a pia but you could just do this with some simple bash foo. The real question though is how does this occur. Sensu works best when deployed via automation tools. This could easily be solved by them, I would think this is less of a Sensu issue (although a cool feature to have) and more of a Chef/Puppet/Ansible/foo issue IMHO.

The dirty way to solve this is to put the version of the client into the client.json using some automated tool. This will then get floated into the check result via the custom attribute functionality. You could simply modify your handlers to verfiy `client.version` against what is running on the server or against some sort of registry. If it detects an issue the handler itself could fire off a separate handler or send an email.

If this were me and I had a multi-thousand node setup I would have a check that verified the version of the client and if they were found to be a miss match then kick a remediation script that upgrade the remote client. Again, this is assuming you don't have some config management tool handling this for you, in which case I would send a notification to the operator saying the config tool is borked.

**Comment by xyntrix** [comment]
That's about what I'm going to do, more or less package an watered down version of yum-cron, but for Sensu related packages to help keep the client healthy.   In my case I provide monitoring as a service to a large enterprise, and we try to put guide rails around that service to make it flexible but also maintainable.  "Easy" is a matter of perspective, right?  With several 10s of thousands of clients in our set up, we don't always have centralized management over what people are doing on their clients. The client registration/keepalive blob already has the client version, so likely, i'll wrap my own handling of this into the Sensu server.   The gist is we need to keep old clients from connecting in as they can actually become hostile if the underlying network degrades, so, I need to deal with that.

**Comment by cwjohnston** [comment]
Closing as won't fix.
