### ISSUE TITLE
Option to suppress expired TTL events when keepalive is failing

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1282]
Currently when a check hasn't been run within the configured `TTL`, an event is generated with output: `Last check execution was X seconds ago`.

When a node is shut down, or otherwise disconnected from Sensu, a check result is generated for each check that hasn't been run within the `TTL`.

This information isn't really useful when the `keepalive` check failing is the real issue, so it would be helpful to be able to suppress expired `TTL` events when the `keepalive` check is failing.

**Comment by mattyjones** [comment]
I agree this is frustrating. I have a handler for dealing with this but I am waiting on a few other parts. A native solution would be best.

**Comment by nhooey** [comment]
@mattyjones Could you publish this handler so I can use it?

Before you do that, a couple of questions:

1. Is it a regular handler or an extension handler?
1. Does the handler make an API request to check the keepalive state of the node in question?

**Comment by nhooey** [comment]
Is it possible to create a filter that runs code to check if a client is currently failing a keepalive check?
@portertech, @calebhailey

**Comment by nhooey** [comment]
I went ahead and made an [TTL Keepalive Filter](https://github.com/nhooey/sensu-plugins-ttl-keepalive-filter/blob/master/ttl_keepalive_filter.rb) that is an extension filter.

It filters out failed results due to expired TTL, where the client is currently failing its keepalive check (the overarching issue). I just tested it in production and it works, with decent performance.

It also depends on my pull request: #1291

@mattyjones, @portertech, @calebhailey

**Comment by calebhailey** [comment]
Tagging this for consideration with the 0.25 release.

**Comment by selbyk** [comment]
+1

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by RyanJarv** [comment]
This seems to be a problem for us when Sensu thinks everything is down, the TTL event's push us over what our sensu servers can currently handle adding to the delay when actual results are processed. Running a flushall on redis and clearing the queues get's things running again as a temporary solution.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/861#issuecomment-130136052

**Comment by portertech** [comment]
I merged https://github.com/sensu/sensu/pull/1428 0.26 will have this functionality :+1:
