### ISSUE TITLE
Sensu emits "check interval must be an integer" when `interval` set to zero

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1284]
This error message should mention a positive integer.

I encountered this when trying to define a `standalone` check with an `interval` of `0`, since omitting either the `interval` or `command` is not allowed.

**Comment by portertech** [comment]
https://github.com/sensu/sensu-settings/pull/31

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1300

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1300 has been merged :+1:
