### ISSUE TITLE
Sensu Client exception on `standalone` check when `interval` omitted and `publish: false`

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1286]
When I have a check defined with `standalone: true`, `publish: false`, and `interval` omitted, I get a stack trace when restarting `sensu-client`.

There is no issue when including an arbitrary `interval`, but I don't want the check scheduled standalone on the client, I merely want it to exist so the check will fail when there are no results posted within the `TTL`.

**Check definition:**

```json
{
   "checks": {
    "ansible-pull": {
        "command": "false",
        "handlers": [
            "all"
        ],
        "publish": false,
        "standalone": true,
        "timeout": 1200,
        "ttl": 1800
    }
}
```

(Note that `"command": "false"` refers to the Linux command that always fails, not a JSON boolean value).

**Stack trace when restarting `sensu-client`:**
```
{"timestamp":"2016-05-25T22:06:47.311233+0000","level":"debug","message":"scheduling standalone checks"}
error reading event: A JSON text must at least contain two octets!
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:262:in `calculate_execution_splay': undefined method `*' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:279:in `block in schedule_checks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:274:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:274:in `schedule_checks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:300:in `setup_standalone'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:371:in `bootstrap'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:381:in `block in start'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/daemon.rb:230:in `block in setup_transport'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-5.0.0/lib/sensu/transport.rb:26:in `block in connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/deferrable.rb:151:in `set_deferred_status'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/deferrable.rb:191:in `succeed'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-5.0.0/lib/sensu/transport/rabbitmq.rb:195:in `block in setup_connection'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/deferrable.rb:151:in `set_deferred_status'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/deferrable.rb:191:in `succeed'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp/session.rb:682:in `connection_successful'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp/session.rb:1040:in `handle_open_ok'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp/session.rb:1136:in `block in <class:Session>'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp/session.rb:959:in `receive_frameset'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp/session.rb:933:in `receive_frame'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp/session.rb:671:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'
```

This happens with Sensu `0.23.2-2` from the Ubuntu repository.

This error contradicts the `interval` Check parameter documentation:

```
interval:
  description: The frequency in seconds the check is executed.
  required: true (unless publish is false)
  type: Integer
  example: "interval": 60
```

**Comment by nhooey** [comment]
Resolved by #1287.

**Comment by portertech** [comment]
@nhooey why use a standalone definition at all? Can just define a pubsub check on the client.

**Comment by nhooey** [comment]
@portertech How do I do that, exactly?

I still want a failed check result to be generated when the check result isn't sent within the `TTL`.

**Comment by portertech** [comment]
TTL monitoring is done via the Sensu server leader, after a result has been received for a client, with a defined TTL. TTL monitoring is NOT done by the Sensu client.

**Comment by portertech** [comment]
You could always push a check result to the client socket with a TTL, if that is what you're after.

**Comment by nhooey** [comment]
What if the first check result is never sent by the client, or received by the Sensu server? Then the check's `TTL` will never be set.

I think it makes sense to be able to define a `standalone` check with no `TTL`, but also no `interval`. This should be done by configuration in the server, not with the first check result sent by the client.

**Comment by portertech** [comment]
It's essentially a "dead man's switch", it needs to be initiated by the client. Clients are decoupled from the reset of the system via subscriptions, I do not see how another approach makes any sense.

**Comment by nhooey** [comment]
There's still nothing telling the server that it should be expecting a check result within a certain amount of time, unless hopefully the first check result with a defined `TTL` comes in. If that first check result fails to arrive, then the check will never be defined for that client.

Why do you say that the `TTL` and check result need to be initiated by the client?

**Comment by portertech** [comment]
Sensu servers are not directly aware of a client/check pair, until a client registers itself with the client registry, and then the client publishes a check result. We will probably add additional logic to `calculate_execution_splay()` to guard against this error.

**Comment by calebhailey** [comment]
It sounds like there are two issues here, one of which is workflow/training related (how to achieve the desired TTL effect), which isn't an issue with Sensu itself. 

However, we should make sure we understand what's causing the Sensu client to crash and address that as a bug.  

@portertech should I tag this as a bug fix for 0.26 to guard against publishing standalone checks that are set to `"publish":false`? It seems like a standalone check definition with `"publish":false` should never even get to the point where the client is trying to `calculate_execution_splay()` (although, in that case, a standalone check definition with `"publish":false` would never be used by Sensu at all as I believe you've noted in your previous comments).

**Comment by portertech** [comment]
@calebhailey `"publish": false` is an attribute only applied to pubsub checks. I'll make a minor change to support it in the client standalone scheduler, however, I believe this is more related to documentation and training, a.k.a things do no act as some may assume.

**Comment by portertech** [comment]
I have a solid alternative fix :+1:
