### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1292]
It seems that the web-site was rebuilt overnight with old documentation no longer available and updated pages not quite matching.

For example, we were discussing the check-dependencies feature, which I saw online _yesterday_. Unfortunately, the same link https://sensuapp.org/docs/0.16/checks#check-dependencies is useless today.

The current [checks-page](https://sensuapp.org/docs/0.23/reference/checks.html) makes no mention of dependencies.

Was the functionality removed? The only replacement I can see is the "Enterprise-only" [filter](https://sensuapp.org/docs/latest/enterprise/filters/check-dependencies.html). If the functionality is still available, please, restore access to the old pages -- until they are updated for 0.23 (and .24).

Thanks!

**Comment by calebhailey** [comment]
@UnitedMarsupials hi there! Check dependencies documentation was moved to the Plugins reference documentation page a few weeks ago. See here: https://sensuapp.org/docs/0.23/reference/plugins.html#check-definition-attributes

The reasoning for the move is explained in the [Plugin Configuration][1] documentation. Attributes like `refresh` and `occurrences` are not currently part of the [Sensu check specification][2], but rather [custom check definition attributes][3] provided by Sensu plugins that are based on the [Sensu Plugins gem][4]. 

I hope this helps! 

[1]: https://sensuapp.org/docs/0.23/reference/plugins.html#plugin-configuration
[2]: https://sensuapp.org/docs/0.23/reference/checks.html#check-definition-specification
[3]: https://sensuapp.org/docs/0.23/reference/checks.html#custom-attributes
[4]: https://sensuapp.org/docs/0.23/reference/plugins.html#the-sensu-plugin-gem
