### ISSUE TITLE
Use Chronic for time-parsing, if available

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1293]
We perform scheduled maintenance here monthly -- on the 3rd Thursday of every month.

It would make sense for us to disable a number of alerts during the day automatically. Unfortunately, Ruby's built-in `Time.parse` can not handle such complex examples.

But [Chronic](https://github.com/mojombo/chronic) can -- well, [almost](https://github.com/mojombo/chronic/issues/332). It would be nice, if Sensu would check at startup, whether Chronic is available, and use it for parsing things like `begin` and `end`.

**Comment by calebhailey** [comment]
Giving this the "feature" label as part of an ongoing issues triage. This will be considered for inclusion in a future release.

**Comment by portertech** [comment]
This could provide the date/time formats we would need for https://github.com/sensu/sensu/issues/1479

**Comment by portertech** [comment]
We will revisit for 1.1 :+1:

**Comment by portertech** [comment]
Date and Time are handled differently in Sensu 2.0, see https://docs.sensu.io/sensu-core/2.0/reference/filters/#handling-events-during-office-hours-only for an example. We are not going to implement this new feature in 1.x, given the syntax will not translate to 2.x. However, I would love to see this implement this in 2.x (in a different manner).

@grepory @palourde something to get on our radar/roadmap.
