### ISSUE TITLE
There should be a way for extensions to bind to privileged ports

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1303]
Sensu's startup script(s) should allow extensions to bind to port below 1024 before dropping superuser privileges.

One immediate use-case would be an SNMP-listener -- an extension such as [that](/warmfusion/sensu-extension-snmptrap) by @warmfusion, which needs to listen on port 162. Another would be a listener for syslog-datagrams (port 514).

Although different Operating Systems provide different mechanisms for such access to non-root processes, the OS-specific hackery should not be necessary.

An extension should be able to define a special method, which would be called by Sensu before the privileges are dropped.

**Comment by portertech** [comment]
Not sure if we are going to attack this one any time soon, due to the amount of platform complexity as you have mentioned. I am not a fan of Sensu ever operating with more privileges. 

@UnitedMarsupials What use cases are there where the source cannot be updated to point at a higher range port?

**Comment by UnitedMarsupials** [comment]
> platform complexity as you have mentioned.

Heh, the platform-specific complexity is required for people to allow Sensu to bind to privileged ports _after_ it dropped root-privileges. Doing it _before_ is quite straightforward.

> I am not a fan of Sensu ever operating with more privileges.

You are right to be concerned, but it needs to happen -- there are legitimate uses for it. Apache, for example, is doing it -- binding to 80 (and 443) before becoming a non-privileged user.

> What use cases are there where the source cannot be updated to point at a higher range port?

Some network gear only allows administrators to specify the IP-address for the SNMP traps (and informational messages). My HP-switch is one such piece of hardware. The _port_ is hardcoded at 162.

Similarly, some syslog-senders only support IP-addresses (or host-names) -- assuming the destination port to always be 514. Most of the older `syslogd` implementations are like that, for example -- you can specify the `loghost` in `/etc/syslog.conf`, but you can not specify the port-number.

It can be worked-around, but the work-arounds tend to be ugly...

**Comment by portertech** [comment]
@UnitedMarsupials forward the privileged port w/ something like iptables as a stop-gap?

**Comment by UnitedMarsupials** [comment]
> forward the privileged port w/ something like iptables as a stop-gap?

Yes, that'd be a work-around for network-listening extensions. And it is acceptable short-term. But long-term it should not be necessary. Thanks!

**Comment by calebhailey** [comment]
Adding the "feature" label here as part of an ongoing triage. This will be considered for potential inclusion in a future release.

**Comment by portertech** [comment]
We are not going to implement this.
