### ISSUE TITLE
Print running configuration to a temporary file

### ISSUE THREAD

**Issue by mattyjones** [sensu/sensu#1304]
I am looking for a language agnostic way to obtain the currently running config of a client. When using the new `-P` functionality it will compile the configuration that you pass into it. There should be a way to obtain the current configuration hash stored in the `settings` file.

There are a few ways to do this:
- When the client starts up dump it to /tmp/sensu_settings in machine readable json (perference)
- cmdline flag that will reach in and pull it out

**Comment by portertech** [comment]
This will require a minor change to https://github.com/sensu/sensu-settings

**Comment by portertech** [comment]
@mattyjones I am much more inclined to write the compiled/running configuration to a temp file :+1:

**Comment by mattyjones** [comment]
👍

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by moises-silva** [comment]
@mattyjones Could you check if PR #1352 is acceptable for your use case? you'd have to do this:

```bash
curl http://127.0.0.1:3030/settings > current-config.json
```

And you would get the client configuration as json

**Comment by portertech** [comment]
I have renamed this issue to "Print running config to temp file", as a temporary file containing the running Sensu configuration can also be utilized by Sensu plugins (instead of using SENSU_LOADED_FILES).

**Comment by portertech** [comment]
@mattyjones https://github.com/sensu/sensu/pull/1488 provides `/settings` with `&redacted=false`
