### ISSUE TITLE
Built-in client deregistration

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1305]
Move automated de-registration on graceful shutdown into Sensu Core. This currently exists as a handler in the `sensu-plugins-sensu` plugin, but it should become a built-in feature in Sensu Core. 

See: https://github.com/sensu-plugins/sensu-plugins-sensu/blob/master/bin/handler-sensu-deregister.rb 

There is already a PR for this, here: https://github.com/sensu/sensu/pull/1191

**Comment by cwjohnston** [comment]
@calebhailey I think #1191 looks pretty good. Moving the handler into core I am a little more fuzzy on. Currently `debug` handler is the only one we ship by default and it's implemented as an extension. Do we want to reimplement the deregistration handler as an extension in sensu-extensions ?  cc @portertech

**Comment by portertech** [comment]
@cwjohnston for client registration, the server is creating the check (& publishing the check result), when the client is first added to the registry https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L77 Note the client definition scope merge https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L80 Perhaps the client should support `"deregistration": {}` to configure the check result potentially created and published by the Sensu client for deregistration?

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1191 is pretty close, but I think it needs the same treatment as https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L77

**Comment by cwjohnston** [comment]
@portertech I have started to build on #1191 in `feature/client-deregistration` branch, any thoughts about timing the deregistration event before vs after calling `pause`? (see https://github.com/sensu/sensu/pull/1191/files#r57937238)

**Comment by portertech** [comment]
@cwjohnston will need to happen after pause to ensure no additional keepalives are sent after the deregistration check result.

**Comment by cwjohnston** [comment]
https://github.com/sensu/sensu/pull/1309 is awaiting review.

**Comment by calebhailey** [comment]
Looks like this has been merged, so I'm going to go ahead and close this issue. \o/ 

@cwjohnston will you submit a PR for the docs?
