### ISSUE TITLE
Windows Client Performance Issues

### ISSUE THREAD

**Issue by epsilon-jpage** [sensu/sensu#1311]
Our Windows clients are seeing a consistent CPU increase when they're running the Sensu Client.  This happens regardless of Windows Server version.  Depending on the size of the server, the base line CPU increase can be anywhere from 8% to 25% just from the Sensu Client alone.  The CPU levels will climb over time if left alone.  Restarting the Sensu Client does nothing.  Stopping it obviously fixes the issue but kills monitoring.

We've found that if we restart the RabbitMQ service on our Sensu Server, an Ubuntu Server, the CPU load will come down to normal levels.  We have a cron job that restarts the RabbitMQ service once a week to keep Windows CPU levels from creeping too high.

This does not affect our Linux client servers.  We're running Sensu Version 0.23.2.  This has been happening for at least version 0.18 and have been hoping with each new version it would resolve but hasn't.

It's rather frightening to see CPU levels drop sharply on 40 Windows servers after we restart the RabbitMQ service.  We've checked the server logs and everything seems fine but I could be missing something.

Thoughts?

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by portertech** [comment]
The 0.27 Windows MSI package will include several significant changes, namely Ruby 2.3.0 which will bring performance improvements to the Windows Sensu client.

**Comment by epsilon-jpage** [comment]
:heart: :+1:

**Comment by portertech** [comment]
0.27.0-1 is in the unstable repositories, it fixes this issue. Will soon be promoted to stable.
