### ISSUE TITLE
sensu-0.24 valid_config looking for a config.json

### ISSUE THREAD

**Issue by gmodules** [sensu/sensu#1312]
in my setup i only use /etc/sensu/conf.d/client.json etc.. but with the new version the valid_config is lookign for a /etc/sensu/config.json and the daemon won't restart because of this. I created an empty file and it worked.

**Comment by portertech** [comment]
@gmodules thank you for reporting :+1: We will get this into 0.24.0

**Comment by calebhailey** [comment]
Oh, nice catch :+1:
