### ISSUE TITLE
[DISCUSS]  Remove -c config.json

### ISSUE THREAD

**Issue by portertech** [sensu/sensu#1313]
I would like to discuss the possible removal of `-c /etc/sensu/config.json`, making `-d /etc/sensu/conf.d` the only means of configuration.

We are having to make exceptions for `config.json`, i.e. https://github.com/sensu/sensu/issues/1312

**Comment by calebhailey** [comment]
I'll weigh in with some feedback as a documentation maintainer and from people who've been through [Sensu Training][1] - it would be a LOT easier to explain how Sensu loads configuration if all configuration was loaded from the config directory. The `config.json` file is a red herring that confuses users into thinking that file names matter for Sensu configuration loading, [which is not the case][2]. 

I'm :+1: for deprecating `/etc/sensu/config.json`. 

[1]: https://sensuapp.org/training
[2]: https://sensuapp.org/docs/0.23/reference/configuration.html#configuration-scopes

**Comment by hurrycaine** [comment]
I also agree on deprecating /etc/sensu/config.json ....

**Comment by calebhailey** [comment]
Let's get this into 0.27 (if not 0.26). /cc @portertech

**Comment by portertech** [comment]
We are going to investigate the Chef cookbook, Puppet module, and Ansible runbook and plan/make the appropriate changes to get them off of config.json.

**Comment by portertech** [comment]
We are not going to remove this, [Sensu 2.x](https://github.com/sensu/sensu-go) object configuration is done via the Backend API 😀
