### ISSUE TITLE
Run now api call for check debugging

### ISSUE THREAD

**Issue by selbyk** [sensu/sensu#1316]
A simple 'run now' ability that has sensu run a check immediately for check/remediation debugging would be very useful

**Comment by portertech** [comment]
@selbyk you can issue a check request with the current API, POST /request https://sensuapp.org/docs/0.23/api/checks-api.html#the-request-api-endpoint

**Comment by runningman84** [comment]
But it isn't possible to run a check on a specific client if the client does not subscribe to itself?

**Comment by portertech** [comment]
We could add a base/included client subscription, named after the client name. This would enable this functionality while maintaining Sensu's model.

**Comment by runningman84** [comment]
@portertech that would be great but please filter them out in the Uchiwa subscription list. Otherwise the subscription filter would become useless because of too many entries.

**Comment by selbyk** [comment]
@portertech That would be great.  I was actually thinking about doing that with our setup or maybe using the port 3030 to manually check check requests. Opening up port 3030 for WAN access seems like a bad idea, though.

**Comment by calebhailey** [comment]
This will be fixed by https://github.com/sensu/sensu/issues/1327 (adding a `client:NAME` subscription to all clients by default).

**Comment by calebhailey** [comment]
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by selbyk** [comment]
Thanks for the update, @calebhailey

**Comment by selbyk** [comment]
I'm going to close this issue since Caleb's more concise and accurate issue covers it.
