### ISSUE TITLE
Sensu checks not working

### ISSUE THREAD

**Issue by mohamadx** [sensu/sensu#1318]
Hi all

I've installed sensu in my server for testing this product  

Any thing is good but i have a bad problem with sensu! my checks successfully added to the dashboard but not auto refreshed based on interval time! but when i clicked on "Issue checked Request" action that checks working very fine!!  

In below image you can see my checks list, i define a check for a invalid domain and this check must be a return CRITICAL status  

<img width="1277" alt="screen shot 2016-06-07 at 18 23 55" src="https://cloud.githubusercontent.com/assets/15182195/15860201/5f7105ba-2cdd-11e6-86fc-8443194ea000.png">  

But my checks not auto-refreshing! and based on below image i clicked on Issue checked Request

<img width="701" alt="screen shot 2016-06-07 at 18 25 23" src="https://cloud.githubusercontent.com/assets/15182195/15860200/5f6fcd44-2cdd-11e6-9ce0-81e3cd17499e.png">  

and finally you can see after i clicked on Issue checked Request my checks works! and i get a CRITICAL status

<img width="1280" alt="screen shot 2016-06-07 at 18 26 03" src="https://cloud.githubusercontent.com/assets/15182195/15860199/5f6d55aa-2cdd-11e6-9f1c-049db6dc85a8.png">  

Where is the problem? please help me  
and if you need any data (server specs, os, logs and etc.) please let me know

**Comment by cwjohnston** [comment]
Hello @mohamadx, thanks for reporting your issue. Unfortunately github issues for this project are not the best format for us to diagnose your problem. From your screenshots I infer that you're using Sensu Enterprise. 

Will you please open an issue with our Sensu Enterprise support team via https://helpdesk.sensuapp.com/  and include the output of `/opt/sensu/bin/sensu-client --print_config` on both your test client and the Sensu Enterprise server? Thanks!
