### ISSUE TITLE
Investigate using different path for tmp files

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu#1319]
Sensu is currently using `/tmp` to store certain files such as `sensu_client_loaded_files`. Some people have been running into issues on hardened systems and systems running a tmp reaping process. We should investigate storing these files in a Sensu-specific location such as `/var/cache/sensu`.

**Comment by cwjohnston** [comment]
Addressed by https://github.com/sensu/omnibus-sensu/pull/12

**Comment by portertech** [comment]
0.27.0-1 is in the unstable repositories, it fixes this issue. Will soon be promoted to stable.
