### ISSUE TITLE
Keepalive events are always filtered 

### ISSUE THREAD

**Issue by neizmirasego** [sensu/sensu#1326]
I am trying to filter keepalive noise and handle only 5th and 10th.
My filter:
{
  "filters": {
    "recurrence": {
      "attributes": {
        "check": {
          "interval": 60
        },
        "occurrences": "eval: value == 5 || value % 10 == 0"
      }
    }
  }
}

Client:
﻿{
  "client": {
    "name": "del-me-dz-sensutest02-test",
    "address": "192.168.100.196",
      "subscriptions": [
    "common"
],
    "keepalive": {
      "handlers": ["slack"],
      "thresholds": {
        "warning": 60,
        "critical": 120
      }
    }
  }
}
But even on 5th and every 10ts occurrences the event is filtered and not being handled.

df7-ae74ed6d99fc","client":{"name":"del-me-dz-sensutest02-test","address":"192.168.100.196","subscriptions":["common"],"keepalive":{"handlers":["slack"],"thresholds":{"warning":60,"critical":120}},"version":"0.24.1","timestamp":1465486821},"check":{"thresholds":{"warning":60,"critical":120},"handlers":["slack"],"name":"keepalive","issued":1465487078,"executed":1465487078,"output":"No keepalive sent from client for 257 seconds (>=120)","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","1","1","2","2","2","2","2"],"total_state_change":11},"occurrences":5,"action":"create","timestamp":1465487078}}

{"timestamp":"2016-06-09T15:44:38.679738+0000","level":"info","message":"event was filtered","handler":{"type":"pipe","command":"handler-slack.rb","channel":"alerts-sensu","severites":["critical","unknown","warning"],"filters":["recurrence"],"name":"slack"},"event":{"id":"64c6e92b-4d88-45ba-9df7-ae74ed6d99fc","client":{"name":"del-me-dz-sensutest02-test","address":"192.168.100.196","subscriptions":["common"],"keepalive":{"handlers":["slack"],"thresholds":{"warning":60,"critical":120}},"version":"0.24.1","timestamp":1465486821},"check":{"thresholds":{"warning":60,"critical":120},"handlers":["slack"],"name":"keepalive","issued":1465487078,"executed":1465487078,"output":"No keepalive sent from client for 257 seconds (>=120)","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","1","1","2","2","2","2","2"],"total_state_change":11},"occurrences":5,"action":"create","timestamp":1465487078}}

Slack handler:
{
    "handlers": {
        "slack": {
            "type": "pipe",
            "command": "handler-slack.rb",
            "channel": "alerts-sensu",
            "severites": ["critical", "unknown", "warning"],
            "filters": ["recurrence"]
        }
    },
    "slack": {
        "webhook_url": "https://hooks.slack.com/services/......../B1EQ6UFQ9/pUrItUfEKXLrwNvd29tV9PZZ",
        "template" : "",
        "bot_name": "Sensu",
        "icon_url": "https://sensuapp.org/img/logo-flat-white.png"
    }
}

**Comment by cwjohnston** [comment]
Hi @neizmirasego!

I've read your filter and I think this pseudo-code describes the logic it is applying:
`(interval == 60) && (occurrences == 5 || occurrences % 10 == 0)`

My first thought here is that the keepalive event you've provided from your logs doesn't seem to have an interval attribute (this may be normal) so it's failing to match your filter.

**Comment by neizmirasego** [comment]
Hi @cwjohnston!
Thanks for your reply! Ok, I have added an interval attribute (60) to my keepalive event, so now it looks better, but still there is no handled alerts

{"timestamp":"2016-06-09T18:31:17.559668+0000","level":"info","message":"processing event","event":{"id":"779e1d4f-6189-4ac2-9c9e-606138be6e47","client":{"name":"del-me-dz-sensutest02-test","address":"192.168.100.196","subscriptions":["common"],"keepalive":{"handlers":["slack"],"interval":60},"version":"0.24.1","timestamp":1465496760},"check":{"thresholds":{"warning":120,"critical":180},"handlers":["slack"],"interval":60,"name":"keepalive","issued":1465497077,"executed":1465497077,"output":"No keepalive sent from client for 317 seconds (>=180)","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","1","1","2","2","2","2","2"],"total_state_change":11},"occurrences":5,"action":"create","timestamp":1465497077}}
{"timestamp":"2016-06-09T18:31:17.825173+0000","level":"info","message":"pruning check result aggregations"}

{"timestamp":"2016-06-09T18:31:17.942639+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"handler-slack.rb","channel":"alerts-sensu","severites":["critical","unknown","warning"],"filters":["recurrence"],"name":"slack"},"output":["only handling every 30 occurrences: del-me-dz-sensutest02-test/keepalive\n"]}

Why 30 and how can I change it?

**Comment by neizmirasego** [comment]
Ok, I have figured it out. I have set refresh parameter in the check to 60. 
Cameron, thanks again for your help.
