### ISSUE TITLE
Automatically create per-client subscriptions

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1327]
The Sensu client should automatically create a subscription called `client:client-name` (e.g. `client:i-424242`) for every client. This will allow for other features in Sensu to target specific clients or groups of clients using subscriptions.

**Comment by calebhailey** [comment]
We'll need to coordinate w/ @palourde on this to make sure these subscriptions don't show up in the list of subscriptions for filtering views; h/t: https://github.com/sensu/sensu/issues/1316#issuecomment-224005599

**Comment by troyready** [comment]
For transport methods that don't allow the client to connect to queue (e.g. the excellent [sensu-transport-snssqs](https://github.com/SimpleFinance/sensu-transport-snssqs)), would be nice to be able to optionally disable this or allow some other way of not [connecting to the transport for each subscription](https://github.com/sensu/sensu/blob/v0.25.6/lib/sensu/client/process.rb#L264).

**Comment by cwjohnston** [comment]
Opened sensu/sensu-settings#40 to implement this feature.

@troyready I am not familiar with the SQS transport internals beyond my reading of the source code in [Sensu client](https://github.com/sensu/sensu/blob/master/lib/sensu/client/process.rb#L260-L282) and the [SQS transport](https://github.com/SimpleFinance/sensu-transport-snssqs/blob/master/lib/sensu/transport/snssqs.rb#L79-L103), but my interpretation of these two methods leads me to believe that this change will have no impact on SQS users.

Feel free to test this for yourself by adding a subscription to one or more of your clients, e.g. assuming client name i-424242

```json
{ "client": { "subscriptions": ["client:i-424242"] } }
```

**Comment by cwjohnston** [comment]
@troyready actually as I dig deeper it seems to me that this `subscribe()` method defined in SQS transport is intended to be accessed only by the server process. SQS transport should probably add logic making `subscribe()` a no-op for clients.

**Comment by troyready** [comment]
@cwjohnston what we're trying to do is avoid the [`@transport.subscribe`](https://github.com/sensu/sensu/blob/v0.25.6/lib/sensu/client/process.rb#L269) calls on sensu-clients. We can do that currently (at least as of 0.23, I haven't tested the newer releases but I think it's the same) by not defining any subscriptions on the clients.

Open to whatever the best way to handle it is.

**Comment by portertech** [comment]
@troyready I believe that the SQS transport only needs to no-op subscribe() calls when the pipe type is fanout.

**Comment by troyready** [comment]
@portertech got it. Thanks (same to @cwjohnston ) for troubleshooting and pointing me in the right direction!

**Comment by portertech** [comment]
https://github.com/sensu/sensu-settings/pull/40

**Comment by cwjohnston** [comment]
Closed by #1411
