### ISSUE TITLE
All requests are returned with internal server error?

### ISSUE THREAD

**Issue by ehrenwert-it** [sensu/sensu#1332]
I freshly installed sensu on CentOS 7 using puppet.

I also tried to get uchiwa working - the panel itself works, but I'm getting this error:

    ALERT
    Datacenter sensu returned: Connection error. Is the Sensu API running?

Well - it is:

    /etc/init.d/sensu-api status
    sensu-api (pid 19363) is running

Let's have a look to the logs:

sensu-server.log:

    {"timestamp":"2016-06-11T15:21:57.969716+0200","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/redis.json","changes":{"redis":[null,{"port":6379,"host":"127.0.0.1","reconnect_on_error":false,"db":0,"auto_reconnect":true}]}}
    {"timestamp":"2016-06-11T15:21:57.969798+0200","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/rabbitmq.json"}
    {"timestamp":"2016-06-11T15:21:57.969916+0200","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/rabbitmq.json","changes":{"rabbitmq":[null,{"port":5672,"host":"localhost","user":"sensu","password":"REDACTED","vhost":"sensu","reconnect_on_error":false,"prefetch":1}]}}
    {"timestamp":"2016-06-11T15:21:58.013315+0200","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
    {"timestamp":"2016-06-11T15:21:58.013438+0200","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
    {"timestamp":"2016-06-11T15:21:58.013519+0200","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
    {"timestamp":"2016-06-11T15:21:58.013602+0200","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
    {"timestamp":"2016-06-11T15:21:58.013691+0200","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
    {"timestamp":"2016-06-11T15:21:58.014050+0200","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
    {"timestamp":"2016-06-11T15:21:58.109223+0200","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}

sensu-api.log:

    {"timestamp":"2016-06-11T15:25:57.413022+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:02.413057+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:07.413149+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:12.413150+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:17.413120+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:22.413180+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:27.413048+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:32.413016+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:37.413138+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
    {"timestamp":"2016-06-11T15:26:42.413228+0200","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}

A CURL-Request is returned with internal server error:

    curl -I http://localhost:4567/clients
    HTTP/1.1 500 Internal Server Error
    Content-Type: application/json
    Access-Control-Allow-Origin: *
    Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
    Content-Length: 59
    Connection: keep-alive
    Server: thin

So I do not get the reason for this right now - I checked the connection:
```
curl -i -u sensu:secretpassword http://127.0.0.1:15672/api/whoami
HTTP/1.1 401 Unauthorized
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Sat, 11 Jun 2016 14:02:52 GMT
Content-Length: 57

{"error":"not_authorised","reason":"Not management user"}
```
Any ideas here?

**Comment by octogeek** [comment]
Hello, @ehrenwert-it 
Are you can connect to your redis? 
Btw, redis listens only ipv4 port, but sensu try to connect on ivp6 (because resolve localhost return ipv6 address)

Show your config file, please.

**Comment by ehrenwert-it** [comment]
Hello @octogeek ,

thanks for your reply. Yes, I think I can connect:
```
redis-cli
127.0.0.1:6379> 
```
Ruby should use 127.0.0.1:
```
/opt/sensu/embedded/bin/ruby -rresolv -e 'puts Resolv.getaddress "localhost"'
127.0.0.1
```

I added the ghost for sensu:
```
rabbitmqctl add_vhost /sensu
Creating vhost "/sensu" ...
Error: vhost_already_exists: /sensu
```

I added the user:
```
add_user sensu sensu
```
set a password and set the permissions like this:
```
set_permissions -p /sensu sensu ".*" ".*" ".*"
```

This is the tree of configuration-files:
```
├── conf.d
│   ├── api.json
│   ├── checks
│   ├── client.json
│   ├── extensions
│   ├── filters
│   ├── handlers
│   ├── mutators
│   ├── rabbitmq.json
│   └── redis.json
├── config.json.example
├── dashboard.d
├── extensions
│   └── handlers
├── handlers
├── mutators
├── plugins
└── uchiwa.json
```

This is the api.json:

```
{
  "api": {
    "port": 4567,
    "host": "127.0.0.1",
    "user": "sensu",
    "bind": "127.0.0.1",
    "password": "xxxx"
  }
}
```

This is rabbitmq.json:

```
{
  "rabbitmq": {
    "port": 5672,
    "host": "127.0.0.1",
    "user": "sensu",
    "password": "xxxx",
    "vhost": "sensu",
    "reconnect_on_error": false,
    "prefetch": 1
  }
}
```

and redis.json:

```
{
  "redis": {
    "port": 6379,
    "host": "127.0.0.1",
    "reconnect_on_error": false,
    "db": 0,
    "auto_reconnect": true
  }
}
```

**Comment by octogeek** [comment]
Hello @ehrenwert-it.
Can you make tcpdump rabbitmq connect?
`tcpdump -i lo port 5672 -w out.file`
or connect on sensu-api using strace
`ps -ef |grep sensu-api`
`strace -p number_of_api_process`

And show me your output

**Comment by portertech** [comment]
@ehrenwert-it  your vhost is `/sensu`, so your rabbitmq config should look like:

```
{
  "rabbitmq": {
    "port": 5672,
    "host": "127.0.0.1",
    "user": "sensu",
    "password": "xxxx",
    "vhost": "/sensu",
    "reconnect_on_error": false,
    "prefetch": 1
  }
}
```

**Comment by ehrenwert-it** [comment]
Hello @portertech ,

changing the vhost to /sensu worked just fine! I changed the default conf in my puppet master and now it also works if I deploy it via puppet.

**Comment by portertech** [comment]
:+1:

**Comment by ROunofF** [comment]
I had the exact same issue. But @agareev puts me on the right track. My redis config was using 
host: "localhost" and I switched to host: "127.0.0.1" to solve the issue.

The strace put me on the right track : 

connect(9, {sa_family=AF_INET6, sin6_port=htons(6379), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EINPROGRESS (Operation now in progress)
