### ISSUE TITLE
Sending SIGTERM to `ansible all` doesn't kill shell on nodes

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1338]
When I run `ansible all apt-get install something` on a series of nodes, if I cancel that request early with CTRL+C, that shell instance isn't properly terminated and leaves an instance of Apt running that jams any further use of apt-get.

I'm not sure what the right solution is, but `ansible all` should clean up when terminated.

**Comment by portertech** [comment]
@nhooey wrong repo?

**Comment by nhooey** [comment]
haha oops, sorry @portertech!

**Comment by portertech** [comment]
No worries :+1:
