### ISSUE TITLE
Broken plugins dependencies after updating sensu to 0.25.0

### ISSUE THREAD

**Issue by ttarczynski** [sensu/sensu#1339]
After updating sensu to version 0.25.0 some plugins stopped working due to missing `'sensu-plugin' (= 1.2.0)` dependency.
Here's an example:

```
# /opt/sensu/embedded/bin/gem list | egrep 'sensu-plugin |sensu-plugins-cpu-checks '
sensu-plugin (1.3.0)
sensu-plugins-cpu-checks (0.0.4)

# /opt/sensu/embedded/bin/check-cpu.rb 
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'sensu-plugin' (= 1.2.0) - did find: [sensu-plugin-1.3.0] (Gem::MissingSpecVersionError)
```

I think this issue is caused by:
- `sensu-plugin` is updated to version 1.3.0 in  sensu 0.25.0
- some checks have a fixed version dependency to `'sensu-plugin' (= 1.2.0)`

So it's probably something to be fixed in plugins. 
These are the plugins that stopped working in my setup after update:

```
sensu-plugins-cpu-checks (0.0.4)
sensu-plugins-disk-checks (1.1.3)
sensu-plugins-docker (1.1.1)
sensu-plugins-entropy-checks (0.0.3)
sensu-plugins-load-checks (0.0.4)
sensu-plugins-process-checks (0.0.6)
sensu-plugins-puppet (0.0.2)
```

**Comment by ttarczynski** [comment]
Here's a workaround that worked for me:
```
# /opt/sensu/embedded/bin/gem install sensu-plugin --version '=1.2.0'

# /opt/sensu/embedded/bin/gem list | egrep 'sensu |sensu-plugin |sensu-plugins-cpu-checks '
sensu (0.25.0)
sensu-plugin (1.3.0, 1.2.0)
sensu-plugins-cpu-checks (0.0.4)
```

I've installed `sensu-plugin (= 1.2.0)` gem and now all checks work OK again.

**Comment by Galitskiy** [comment]
I can confirm, that after upgrade to 0.25.0-1 version (Ubuntu Trusty) some plugins (like check-ntp, metrics-uptime, etc) stopped working:

```# /opt/sensu/embedded/bin/check-ntp.rb
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'sensu-plugin' (= 1.2.0) - did find: [sensu-plugin-1.3.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.3.0:/opt/sensu/embedded/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `block in activate_bin_path'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `synchronize'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `activate_bin_path'
	from /opt/sensu/embedded/bin/check-ntp.rb:22:in `<main>'```

Another temporary fix, downgrade to '0.24.1-1' version.

**Comment by zbintliff** [comment]
This seems more of an issue with the sensu-plugins than with sensu.

**Comment by cwjohnston** [comment]
Thanks for reporting this issue. The problem you are experiencing is specific to sensu-plugin gems which have dependency on `sensu-plugin = 1.2.0` instead of allowing for newer versions, e.g. `sensu-plugin ~> 1.2`. 

Sensu 0.25 ships with sensu-plugin 1.3.0. [Installing sensu-plugin 1.2.0 into your Sensu embedded Ruby environment](https://github.com/sensu/sensu/issues/1339#issuecomment-225839956) should be a usable workaround. 

The Sensu Plugins team is working to issue new versions of the affected plugins to resolve this; it would be helpful if you would open issues on the specific affected projects under the [sensu-plugins](https://github.com/sensu-plugins) organization.

**Comment by portertech** [comment]
We are going to ship sensu-plugin 1.2.0 AND 1.3.0 in the Sensu 0.25.1-1 package, later today :+1:

**Comment by Salamek** [comment]
@portertech Maybe move 0.25.1 package to main from unstable... cos 0.25.0 is totaly "broken" (well it is not but sensu withnout working plugins is useless)

**Comment by Salamek** [comment]
@portertech all green, thx

**Comment by ttarczynski** [comment]
I've just updated to 0.25.1 which includes both sensu-plugin 1.2.0 and 1.3.0 ([Support multiple versions of sensu-plugin #166](https://github.com/sensu/sensu-build/pull/166)).
Checks works OK, and the above [workaround](https://github.com/sensu/sensu/issues/1339#issuecomment-225839956) is no longer needed. So I think it solves this issue.

@portertech @amdprophet thank you for fixing this right away.

**Comment by ttarczynski** [comment]
@cwjohnston I've looked into the code in [sensu-plugins](https://github.com/sensu-plugins) organization.
I've searched for: [org:sensu-plugins "add_runtime_dependency sensu-plugin"](https://github.com/search?utf8=%E2%9C%93&q=org%3Asensu-plugins+%22add_runtime_dependency+sensu-plugin%22&type=Code&ref=searchresults) and it seems that many plugins already have corrected dependency on master:
```
s.add_runtime_dependency 'sensu-plugin', '~> 1.2'
```
but haven't been released since the correction.
Here is one such example: [sensu-plugins-cpu-checks – New release needed #14](https://github.com/sensu-plugins/sensu-plugins-cpu-checks/issues/14)
