### ISSUE TITLE
Since the API use EM, I sometimes get an EOF

### ISSUE THREAD

**Issue by Seraf** [sensu/sensu#1340]
Hello,

I upgraded to 0.25 this morning (with the debian package), and Uchiwa has sometimes troubles to query API.

```
{"timestamp":"2016-06-14T13:05:01.744723597+02:00","level":"warn","message":"GET http://monitoring.mycompany.com:4567/info returned: Get http://monitoring.mycompany.com:4567/info: EOF"}
{"timestamp":"2016-06-14T13:05:06.724457236+02:00","level":"warn","message":"GET http://monitoring.mycompany.com:4567/aggregates returned: Get http://monitoring.mycompany.com:4567/aggregates: EOF"}
```

It does not happens everytime, I would say 1 time per minute.
I tried a `watch curl` on the API and didn't get an EOF yet, but on uchiwa, there's an error.

Of course, I get nothing in the logs about this error :(

According to the changelog, it seems to be related to the rewrite of the api with EM as I didn't have this behavior before. https://github.com/sensu/sensu/issues/1317

Is there a way to have more informations ?

Thanks

**Comment by xlr-8** [comment]
In case that could be useful, a notification warning on the dashboard also appears:
*"Datacenter company returned: Connection error. Is the Sensu API running?"*

**Comment by portertech** [comment]
Thank you for reporting. We are investigating and working on a fix :+1: Expect a 0.25.1-1 build later today.

**Comment by portertech** [comment]
@Seraf what version of Uchiwa are you running?

**Comment by Seraf** [comment]
The last version, 0.15, upgraded this morning at the same time

**Comment by portertech** [comment]
@Seraf thanks!

**Comment by portertech** [comment]
We are working on a few other minor changes for 0.25.1, we will have the release cut before lunch (PST) :+1:

**Comment by Seraf** [comment]
Thanks a lot for your reactivity Sean ! :D

**Comment by portertech** [comment]
@Seraf 0.25.1-1 is now available in the Linux repositories :+1:
