### ISSUE TITLE
High plugin handler load

### ISSUE THREAD

**Issue by CVTJNII** [sensu/sensu#1341]
I'm attempting to use the plugin handlers from sensu-plugins, which run as a pipe handler, and I'm noticing excessive system load when many events are being handled:

```
top - 15:55:48 up 3 days,  4:22,  1 user,  load average: 12.43, 12.47, 12.41
Tasks: 246 total,   8 running, 238 sleeping,   0 stopped,   0 zombie
%Cpu(s): 80.4 us, 11.3 sy,  0.0 ni,  7.7 id,  0.0 wa,  0.0 hi,  0.6 si,  0.0 st
KiB Mem:   4046992 total,  2945880 used,  1101112 free,   220128 buffers
KiB Swap:  3903484 total,     6528 used,  3896956 free.   539416 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                               
17885 915       20   0  108028  32920   7104 D  32.9  0.8   0:01.00 handler-mailer.                                                                                                                                                                       
17878 915       20   0  177704  34876   7024 R  32.2  0.9   0:01.08 handler-mailer.                                                                                                                                                                       
17896 915       20   0  105980  30696   7052 D  30.9  0.8   0:00.93 handler-mailer.                                                                                                                                                                       
17900 915       20   0   95928  18612   7204 D  18.3  0.5   0:00.55 handler-hipchat                                                                                                                                                                       
17904 915       20   0   85296  16264   6864 D  16.9  0.4   0:00.51 handler-mailer.                                                                                                                                                                       
17908 915       20   0   88856  19468   6788 R  15.9  0.5   0:00.48 handler-hipchat                                                                                                                                                                       
17915 915       20   0   81936  15068   6904 R  12.9  0.4   0:00.39 handler-mailer.                                                                                                                                                                       
17941 915       20   0   65884  11464   4536 R  11.0  0.3   0:00.33 handler-hipchat                                                                                                                                                                       
17945 915       20   0   43360   9204   4048 R   7.0  0.2   0:00.21 handler-mailer.                                                                                                                                                                       
17949 915       20   0   43376   9232   4076 D   5.6  0.2   0:00.17 handler-hipchat                                                 
```

This is due to the expense of starting a new Ruby process for each handler.  Looking at the plugins they handle a fair amount of filtering themselves: https://github.com/sensu-plugins/sensu-plugin/blob/bc28967c2c1e9244b3466c19c3ffc87d0438e72a/lib/sensu-handler.rb#L30-35
Now, looking over the documentation I believe I can drop this load by using a filter in the Sensu config as that will filter in the long-lived Sensu process and prevent the handlers from forking unless needed.  However, I consider this dangerous as if I don't match the filtering done in sensu-handler.rb from the plugin I could create a situation where all events are filtered and no events are handled.  So it seems to me that the safest option is to allow the plugin to filter, which still leaves the load problem.

So my question, and the spirit of this issue, is: is my interpretation of the scenario correct?  I find the decision to filter in sensu-handler.rb from the plugin repo an interesting one architecturally, and I'm curious what the official answer to this load problem is.  In searching around I haven't found a good answer though it seems like it would be a common problem.

**Comment by cwjohnston** [comment]
@CVTJNII thanks for raising this issue. I think you are on the right track, with the idea of using filters to prevent handlers from running unnecessarily. The filtering behaviors in sensu-plugin pre-date the existence of filters as a configuration primitive in Sensu. 

I have been looking into the filtering behavior in the sensu-plugin library and I've come to the conclusion that the best way forward is to deprecate, and eventually remove, filtering behaviors in the Sensu::Handler class. Please see sensu-plugins/sensu-plugin#134 for some additional detail on that proposal; your feedback will be helpful.

**Comment by CVTJNII** [comment]
Aah, okay.  The handler filters predating Sensu filters makes much more sense.  I commented on sensu-plugins/sensu-plugin#134 for the long term solution.  My current solution is to have a long-lived listener that sits between Sensu and the handlers which runs the handler filter logic.  This drastically reduces system load as processes are only forked on active alerts and it leverages the same filter code the handlers will run so I'm not worried about creating a impervious combination of filters.  I'm still load testing this solution, though.

**Comment by cwjohnston** [comment]
I'd also like to point out that the native silencing implementation added in Sensu 0.26 also helps to improve the performance of event handling. Unlike the older stash-based implementation, native silencing prevents handlers from executing at all if the event is silenced.

It's been seven months since the last update here, so I'm going to close this issue.
