### ISSUE TITLE
Multiple aggregate groups per check

### ISSUE THREAD

**Issue by RyanJarv** [sensu/sensu#1342]
I was thinking Aggregates 2.0 was going to allow for this, but looking at the documentation "aggregate" only accepts a string. Is there a way to have the same check show up in multiple aggregates? If not any plans on supporting this?

**Comment by portertech** [comment]
@RyanJarv "Aggregates 2.0" made it possible to add multiple checks to an aggregate. We could potentially introduce "aggregates": [] as a check definition attribute, allowing a check to be added to multiple aggregates.

**Comment by calebhailey** [comment]
This is a cool idea!

**Comment by RyanJarv** [comment]
My main use for this would be to avoid spam during major issues. Things could be grouped per cluster, zone, datacenter and if any one is say over 50% down it would trigger a single check that would silence everything that is a member of it, so everything in that group would be a dependent on that aggregate check. I think this would work anyways.. might need to think it over again just because this was my plan a while ago but put it on hold.

**Comment by portertech** [comment]
We can do something like https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L249

**Comment by cwjohnston** [comment]
Implemented by #1379, to be released in Sensu 0.26.
