### ISSUE TITLE
Sensu v0.25 broke gem sensu-plugin? Could not find 'sensu-plugin' (=1.2.0) - did find 1.3.0

### ISSUE THREAD

**Issue by pwn777** [sensu/sensu#1343]
Let me know if anyone else is getting this error:

/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'sensu-plugin' (= 1.2.0) - did find: [sensu-plugin-1.3.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.3.0:/opt/sensu/.gem/ruby/2.3.0', execute `gem env` for more information
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `block in activate_bin_path'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `synchronize'
    from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `activate_bin_path'
    from /opt/sensu/embedded/bin/check-cpu.rb:22:in `<main>'

**Comment by cwjohnston** [comment]
@pwn777 thanks for reporting this problem. I believe the issue you have described duplicates #1339. Please see [my comment](https://github.com/sensu/sensu/issues/1339#issuecomment-225939895) in that issue for more detail.
