### ISSUE TITLE
Sensu in Golang: Does it make sense?

### ISSUE THREAD

**Issue by chiriaev** [sensu/sensu#1346]
Sean, Hi. I hope you are well. Do you think that there ever be an official/sponsored version of Sensu (client) written in Golang? 

Is there any interest from the community? Would a low(er) footprint agent make sense in scenarios where size matters? (i.e.: memory, disk, etc..)

Thanks in advance, 

Regards, Andrei

P.S.: I know about a port that hasn't been update for about 10 moths now; is that valid?

**Comment by portertech** [comment]
@chiriaev several languages are currently under evaluation by Sensu's team at @heavywater. Sensu 1.0 will be cut later this summer, 1.x.x will remain on the Ruby runtime. We are actively working Sensu's 2.0 design, which will undoubtedly use another runtime ;-)

I am not aware of an active port of Sensu in golang.

**Comment by chiriaev** [comment]
Thanks, Sean. Looking forward to give it a go! :) Regards, Andrei

**Comment by mrasmus** [comment]
I've been lightly working on a sensu client in golang for a bit now, forking upfluence/sensu-client-go, though mostly my modifications have been focused on the needs of my organization, rather than attempting to reach feature parity with the official sensu client. The changes and adjustments will be in [our repo](https://github.com/imvu-open/sensu-client-go), once they've become cleaned up and substantial/useful. As of yet there's nothin in there.

**Comment by chiriaev** [comment]
Hi, Mat. Great stuff! Thanks for sharing. Regards, Andrei

**Comment by thebenwaters** [comment]
anything that lowers cpu load please!

**Comment by portertech** [comment]
Sensu 2.0 is a golang rewrite :+1: The repository (https://github.com/sensu/sensu-go) will remain private for the next few months as the Sensu Inc team develops a base (alpha) for the Sensu community to build upon. We very excited to have the opportunity to do this! I hope to publish a high level architecture document to the public in the near future, taking information from our private engineering wiki.

**Comment by johntdyer** [comment]
@portertech  Any eta when an alpha release will be made public ?

**Comment by shurshun** [comment]
@portertech the same question like @johntdye

**Comment by cwjohnston** [comment]
@johntdyer @shurshun please see our recent blog post here https://blog.sensuapp.org/the-road-ahead-for-sensu-ad1f4243e72b which covers the roadmap for Sensu
