### ISSUE TITLE
Sensu Event ID should stay the same through warn>crit>resolved

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu#1349]
So. let me start by saying that I love this feature in V24 of sensu! I upgraded today and watched the workflow on one of our ticketing systems and it was almost like they were made for each other.. But only almost.... Here is why.
I stopped a client on a machine to trigger a keepalive. My handler created a ticket on our system with the event id etc for warn. Then moved it to critical. But when I resolved it (by starting the client again) the ID changed.. :( 
from keepalive 1466524721
to keepalive 1466525012
so I have a ticket stuck in critical then a new ticket with only a resolution.. 
Is this something that can be fixed?
Thank you guys very much for the hard work!! 
Josh

**Comment by joshzitting** [comment]
Im sorry guys! I was still using the wrong value!! i changed it to event[:id] and it works wonderfully!!! thanks!

**Comment by calebhailey** [comment]
@joshzitting glad you figured it out! Let me know if you think there's a way to make this more obvious in the documentation. 👍
