### ISSUE TITLE
Timeout when hitting /info on the Sensu API

### ISSUE THREAD

**Issue by MattHodge** [sensu/sensu#1351]
Hello,

We have tried with Sensu 0.24 and 0.25 to use uchiwa,  which is hitting the sensu api on /info.

Uchiwa keeps spitting out these logs: 

`{"timestamp":"2016-06-28T11:07:30.853573884+02:00","level":"warn","message":"GET http://127.0.0.1:4567/info returned: Get http://127.0.0.1:4567/info: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}`

Trying to hit the api using a browser does the same thing - allows authentication but just endlessly tries to load.

We have ensured RabbitMQ and Redis connectivity and cannot work out why it just hangs.

Any ideas would be helpful..

**Comment by palourde** [comment]
Did you tried to clear your redis data (`redis-cli FLUSHALL`)?

**Comment by calebhailey** [comment]
@MattHodge we're trying to reproduce this but so far we have been unable to. Can you try @palourde's suggestion, above, and let us know the results?

**Comment by MattHodge** [comment]
The redis flush fixed the problem :)

**Comment by davidfox2** [comment]
I now have the same problem using Sensu 24.1 and uchiwa 16.0. 

Uchwia.log shows:
` {"timestamp":"2016-07-23T01:10:17.930468574Z","level":"warn","message":"GET http://127.0.0.1:4567/info returned: Get http://127.0.0.1:4567/info: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"} `

this also stops Uchiwa from returning information and with the web interface stating it cant connect to sensu datacenter, even though the logs are showing the events being transmitted by clients and captured by the server.

I have tried the ( `redis-cli FLUSHALL` ) which worked for about half an hour then broke for about 4 minutes then continued to work.

May be related to another issue where results for clients aren’t being refreshed in uchiwa, uchiwa issue https://github.com/sensu/uchiwa/issues/512 

As a note I do currently have a broken handler, so a bunch of events are returning an error message which may be why my clients aren’t updating. 

Going to fix the handler first then try and change the version numbers see if it fixes.
