### ISSUE TITLE
Please release 0.25.4 in apt repo

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1355]
From time to time git releases do not appear in the apt repo. Is this a known problem?

**Comment by cwjohnston** [comment]
Hi @runningman84, I think this is unintentional but as I have not yet been on-boarded to the build system, I'm not sure I can address this presently. Will follow up after the holiday weekend.

**Comment by RiRa12621** [comment]
+1 on putting it in the repo
and usually this just takes some time but it should not

**Comment by portertech** [comment]
The changes in 0.25.4 have actually been reverted on master - https://github.com/sensu/sensu/pull/1358 Sensu 0.25.5 will be cut early next week.

**Comment by cwjohnston** [comment]
Sensu 0.25.5 packages are now available in the repositories https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0255---2016-07-12
