### ISSUE TITLE
Make sensu-client bulletproof: ignore invalid checks

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1357]
It looks like some local check is invalid in my system. I would expect sensu-client to omit this check and write an error message to the logfile.

But I get an error like this:

```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:184:in `definition_exists?': undefined method `to_sym' for nil:NilClass (NoMethodError)
Did you mean?  to_s
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:62:in `block (2 levels) in create_category_methods'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:211:in `process_check_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:273:in `block (2 levels) in setup_subscriptions'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.1/lib/sensu/transport/snssqs.rb:95:in `block (3 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.1/lib/sensu/transport/snssqs.rb:59:in `statsd_time'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.1/lib/sensu/transport/snssqs.rb:91:in `block (2 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:138:in `block in each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:231:in `block in spawn_workers'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:18:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-client:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-client:22:in `load'
    from /opt/sensu/bin/sensu-client:22:in `<main>'
```

The full story can be found here:
https://github.com/SimpleFinance/sensu-transport-snssqs/issues/3

This error crashes the whole sensu-client. I image some code/chef deployment can easily stop the whole monitoring by creating an invalid check?

Btw. right now I am unsure which check is the problem here, feel free to verify my cookbook containing all checks:
https://github.com/runningman84/chef-monitor

The funny thing is that this problem only occurs using the snssqs transport, redis/rabbitmq transport does not seem to have this problem.

**Comment by portertech** [comment]
Somehow a check request is published without a check name, which suggests it did not originate from a Sensu server that performs configuration validation.

**Comment by portertech** [comment]
It could be that the payload is malformed.

**Comment by portertech** [comment]
To double check that the check definition name validation works, I pushed https://github.com/sensu/sensu-settings/pull/60

**Comment by portertech** [comment]
@runningman84 unfortunately, there are just too many ways a malformed transport payload can cause failures in Sensu services (client included). In this case, the check name is nil, which should not be possible given Sensu uses very strict configuration validation. I'm closing this Sensu Core issue, as the source of the failure is elsewhere. Sorry.
