### ISSUE TITLE
Include custom check definition attributes in the check request payload

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1360]
The Sensu check request payload has historically only contained [the minimum number of check definition attributes needed][1] to execute the request on a `sensu-client`: the `command`, `source`, and `extension` attributes. 

Example: 

~~~ json
{
  "name": "example_check",
  "issued": 1234567890,
  "command": "check-http.rb -u https://sensuapp.org",
  "source": "sensuapp.org"
}
~~~

_NOTE: the other half of this legacy check request "shaping" behavior happens during check result processing. The Sensu server [merges check result data w/ the original check definition][2] when processing check results, thus restoring any custom check definition attributes to the event context and making them available for handlers, and in the Sensu API (i.e. for dashboards like Uchiwa to display)._

With the introduction of "extended check token substitution" in [Sensu Core 0.24][1] (i.e. allowing for [token substitution on any check definition attribute][4] – not just the `command` field), this check request payload "shaping" behavior is resulting in some confusion for Sensu users who are appropriately expecting to be able to perform token substitution on custom check definition attribute fields. 

For example, if a check definition contains a custom attribute called `graph` that has a client `:::name:::` token in it, this `graph` attribute is not being included in the check request, and is thus not available for the sensu-client to perform token substitution on. The exception to this rule – further adding to the confusion – is that the `sensu-client` process will merge check requests with local check definitions of the same name prior to executing the request, potentially restoring custom check definition attributes to the check request payload and making them available for the `sensu-client` to perform token substitution on – so a `sensu-client` process running on the Sensu server will always have access to the check definition, thus applying the token substitution to all the fields in the check (and seemingly exhibiting a different behavior than a `sensu-client` running on a remote system).  

PR #1359 will change this behavior to make the new extended token substitution behave as expected, now including all check definition attributes in the check request payload (including custom definition attributes, but excluding `interval` and `subscribers` which are only used by the server to publish the request). 

[1]: https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L657-L659 
[2]: https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L576
[3]: https://sensuapp.org/docs/0.24/overview/changelog.html#core-v0-24-0 
[4]: https://sensuapp.org/docs/latest/reference/checks.html#check-token-substitution

**Comment by calebhailey** [comment]
It should also be noted that it _is_ possible to "resolve" this issue by deploying check definitions to all Sensu clients, thus making them available to be merged with incoming check requests (making custom attributes available for token substitution). This workflow requires the use of some configuration management or other automation tooling to ensure that changes are kept in sync between the client and server, which is a popular workflow for many Sensu users, but not ideal for every user.

**Comment by calebhailey** [comment]
Fixed by #1360

**Comment by Gillingham** [comment]
Is this supposed to get into 25.5? Running the official RPM, `sensu-0.25.5-1.x86_64` and I'm getting `Unmatched client token(s): checker.user, checker.password`
With a config of:
```
 "checker_sample": {
      "source": "foobar",
      "handlers": ["mailer"],
      "command": "foo -user :::checker.user::: -password :::checker.password:::",
      "subscribers": [
        "foobar"
      ],
      "checker": {
          "user": "foo",
          "password": "bar"
      },
      "interval": 60
    }
```

or am I mis-understanding what this issue was/was fixed?

**Comment by cwjohnston** [comment]
@Gillingham The change in question here is to allow check definition attributes other than `command` to make use of token substitution. In your case, the token substitution routine is looking for `checker.user` and `checker.password` attributes under the `client` scope and not finding them there as they are actually under `checks.checker_sample.checker`. 

Try placing the custom `checker` attributes under the `client` scope, i.e. outside the check definition. See https://sensuapp.org/docs/latest/reference/checks.html#check-token-substitution for more details.

**Comment by Gillingham** [comment]
@cwjohnston aw dang, these checks all run on proxy clients, so getting the client substitution is a bit harder, since a client may be running checks that have differing values for the proxy.
Unfortunately using the HTTP API to set the proxy client values is a bit harder, since those values tend to get reset/lost when the sensu server restarts.
