### ISSUE TITLE
Add support for configuring Redis Sentinels via environment variable

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1361]
The recent improvements that introduced [native Redis Sentinel support in Sensu Core 0.23][1] are not configurable via Sensu's supported [environment variables][2] (used in container-based environments). 

[1]: https://sensuapp.org/docs/0.23/overview/changelog.html#core-v0-23-0
[2]: https://sensuapp.org/docs/0.25/reference/configuration.html#sensu-environment-variables

**Comment by cwjohnston** [comment]
@portertech I think the combination of sensu/sensu-redis#5 and sensu/sensu-settings#41 will satisfy the requirements for this feature. Let me know what you think?

**Comment by cwjohnston** [comment]
Closed by #1411
