### ISSUE TITLE
Support auto-discovery for client definition defaults

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1362]
If the sensu-client could derive more client configuration default values from the running system (e.g. use the hostname as the default client name), it could greatly simply monitoring in highly ephemeral environments (e.g. container-based environments). 

Minimum requirements:

- [ ] Auto discover/set the client name
- [ ] Auto discover/set the client `address`

**Comment by calebhailey** [comment]
Ideally, the minimum configuration required for a Sensu client should be a transport connection definition (which may be provided via configuration or environment variables).

**Comment by calebhailey** [comment]
Somewhat related: #1276

**Comment by cwjohnston** [comment]
Implemented auto-discovery of client name and address in sensu/sensu-settings#37, shipped in sensu-settings 6.0.0. 

https://github.com/sensu/sensu/pull/1379 adds dependency on sensu-settings 6.0.0, so this feature will ship with 0.26.
