### ISSUE TITLE
pubsub checks not running on interval after 0.22.0 --> 0.25.3

### ISSUE THREAD

**Issue by robertlabrie** [sensu/sensu#1366]
We upgraded from 0.22.0 to 0.25.3 and now the pubsub checks aren't running on the interval. I can issue a manual re-check from uchiwa and it works, standalone checks work (that is, I get results posted back), but the scheduled checks don't run. There is nothing blatant in the logs, just a bunch of configs and extensions loaded. Not really sure where to go from here, redis and rabbit are running, and obviously working if my standalone checks are coming in. 

Any suggestions appreciated.

**Comment by portertech** [comment]
@robertlabrie are there any configuration errors logged on process start?

**Comment by robertlabrie** [comment]
Hi @portertech no errors logged during startup. We see the configs load, then the extensions, then configuring sensu spawn, then that's it.

**Comment by portertech** [comment]
@robertlabrie try stopping sensu-server and sensu-api, and then flush redis, there the upgrade path may be too much of a jump.

**Comment by robertlabrie** [comment]
@johntdyer ^^^^

**Comment by robertlabrie** [comment]
So we downgraded both nodes to sensu 0.22.0 and it appeared to work for a while, but the problem has re-surfaced. I've literally put this into a cron job to get our checks to work.
https://gist.github.com/robertlabrie/d9939a78079afefff403cf7323c98ab3

And it does work! But not how it should...

**Comment by portertech** [comment]
@robertlabrie have you tried messaging users on IRC #sensu to see if anyone else is experiencing this issue? This is not one I have seen elsewhere. Have you tried the tried and true redis flush-all step as part of the upgrade process?

**Comment by robertlabrie** [comment]
@portertech Is there a document for upgrading? redis flushall did it. I backed up my stashes first through the API, can I recreate them easily (maybe by posting the JSON file)?

**Comment by portertech** [comment]
A Redis flushall was/is the way to handle specific version transitions. It seems we lost the upgrading documentation along the way (refactor), I've created a sensu-docs issue - https://github.com/sensu/sensu-docs/issues/541
