### ISSUE TITLE
Add ability to define proxy clients in the server configuration

### ISSUE THREAD

**Issue by Gillingham** [sensu/sensu#1371]
I have a fairly fixed set of proxy clients to represent a service that can be run on several servers in a cluster. It would be nice if I could statically define the client attributes for those proxy clients in a config file on the sensu server.

Right now the only way to do this to execute serveral HTTP API calls, and make sure they gets run every time the sensu-server or api gets restarted since that can and does sometimes lose the client data. Having to do that especially after some cases where sensu may crash or the server gets rebooted is far from ideal, thus my request for the ability to declare them in a static config file.

**Comment by sstarcher** [comment]
The possibility to define the JIT source configuration statically would simplify some of my configuration.   Currently I define alerting at the JIT check level, but we have a static set of JIT sources that would simplify our setup.

**Comment by cwjohnston** [comment]
In #1555 we're proposing to implement "proxy check requests", a new feature allowing a pubsub check definition to generate a unique check request for each client matching a defined set of client attributes.

Please have a look and share your thoughts?

cc: @Gillingham @sstarcher

**Comment by portertech** [comment]
[Sensu 2.x](https://github.com/sensu/sensu-go) supports creating Entities via the Backend API 🎉  See https://docs.sensu.io/sensu-core/2.0/reference/entities/#how-do-entities-work to learn more about Entities!
