### ISSUE TITLE
Guide to Check/Handler Performance?

### ISSUE THREAD

**Issue by thebenwaters** [sensu/sensu#1373]
Is there anyway to see how one should handle large amounts of checks and/or handlers. I'm getting insane cpu load values and would love some tips on how to handle this.

**Comment by majormoses** [comment]
@thebenwaters are these custom checks you (your org) has written or community ones?

**Comment by thebenwaters** [comment]
Community plugins. Was running around 130 -> 140 checks every minute/5minutes. Cpu Load was sitting around 3/4

**Comment by majormoses** [comment]
Are these standalone checks or subscription based? Is the load on the server or the clients. Are 130-140 checks per client or overall?

**Comment by thebenwaters** [comment]
Per client around 6/7. And subscription based. 130-140 in total

**Comment by majormoses** [comment]
Is the load on the server or the clients? 6/7 per host should not cause the clients to be slow. I would also say 130-140 should not be enough to bog down a sensu server. What "hardware" did you give sensu server?
