### ISSUE TITLE
Consider signing sensu gems

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1374]
Unlike the RPMs in Sensu yum-repo, Sensu gems aren't currently signed. Please, consider signing them (perhaps even with the same key) to ease the mind of administrators downloading the gems from the Internet...

Thank you!

**Comment by portertech** [comment]
This is a great idea and is absolutely something we should do :+1: I'll put it on our team planning board.

**Comment by portertech** [comment]
Added to the board, will discuss and schedule :+1:
