### ISSUE TITLE
Hybrid metric and standard check

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu#1376]
Currently, I use nagios' check_http check to check a URL. This also emits nagios perf data.

```
HTTP OK: Status line output matched "200" - 224 bytes in 0.523 second response time |time=0.522641s;;;0.000000 size=224B;;;0
```
What i'd like to be able to do is perform this query once, and ship this data to graphite.

Is this currently possible? According to the docs, a check is either a metric check or standard check. if I add a handler and make type an array, will that worl?

**Comment by portertech** [comment]
@jaxxstorm you can use "type": "metric" in your check definition and use handler "severities": ["warning", "critical", "unknown"] for your notification handlers to drop the OK results ;)

**Comment by jaxxstorm** [comment]
@portertech is it possible to leave the handlers set as normal.

Essentially what I'm looking for (sorry if I wasn't clear enough)

The check to operate normally, so alert if critial/warning and recover if ok, with a standard handler like pagerduty.

I want the same execution of the check to ALSO ship the perfdata back to graphite.

So essentially,

```
{
  "checks": {
    "http_check": {
      "command": "/usr/lib64/nagios/plugins/check_http -H healthcheck.service.discover -u /check_data.php?customer=testing -p 9000 -e 200 -s PASSED",
      "handlers": [
        "default",
        "graphite"
      ],
      "type": ["metric", "whatever"],
      "high_flap_threshold": 50,
      "interval": 60,
      "occurrences": 10,
      "low_flap_threshold": 15,
      "create_ticket": false,
      "standalone": true,
      "aggregate": false
    }
  }
}
```

Resulting in both the normal operation of the check, and also collecting perf_data

**Comment by portertech** [comment]
@jaxxstorm configuring `"severities": ["warning", "critical", "unknown]` for your pagerduty handler in the default set will stop non resolve OK events from triggering it, there's really no downside, this should do the trick :+1:
