### ISSUE TITLE
Support request: Could someone give me some pointers how to store sensu metrics in graphite or provide an alternative

### ISSUE THREAD

**Issue by 030** [sensu/sensu#1377]
* Graphite is running and the carbon agent shows metrics in graphite
* sensu is running and the clients are shown in uchiwa

Problem: I cannot integrate both

* no rabbitmq log, while sensu is working
* sending data using nc command stores data in graphite
* configuring the graphite handler does not help

I cannot figure it out. Could someone give me some advice please?

**Comment by runningman84** [comment]
Just use an extension like wizardvan
https://github.com/opower/sensu-metrics-relay

**Comment by syepes** [comment]
@030 Alternatively you can also use Crate.IO

https://groups.google.com/forum/m/#!topic/sensu-users/riLsoaTiCHs

**Comment by portertech** [comment]
@030 I recommend using a Sensu TCP handler (https://sensuapp.org/docs/0.25/reference/handlers.html#tcpudp-handlers) with the "only_check_output" built-in mutator. Then you can use any sensu-plugin that outputs Graphite plain-text metrics :+1: 

The Wizardvan extension that @runningman84 suggested is also great.

The Sensu IRC channel (#sensu) is a great place to ask questions like this, just be sure to stick around for an answer :-)
