### ISSUE TITLE
Standalone mode for clients

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1383]
The idea is to have a special model like the safe mode which forbids the client to receive anything from the queue. The subscriptions are only used for a better handling in uchiwa.
https://github.com/sensu/sensu/pull/1364

Unfortunately nobody has responded to my pull request.

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1364 was closed as the SQS transport now includes a fix https://github.com/SimpleFinance/sensu-transport-snssqs/pull/8
