### ISSUE TITLE
sensu-client only attempts to connect to rabbitmq using IPv6

### ISSUE THREAD

**Issue by lp0** [sensu/sensu#1387]
When a hostname is configured for the rabbitmq server, sensu should attempt to connect using all available IP address families instead of only attempting to connect using IPv6.

If IPv6 connectivity to the server is unavailable it doesn't currently retry using IPv4.

**Comment by portertech** [comment]
Should address this while attacking https://github.com/sensu/sensu-transport/issues/39

**Comment by portertech** [comment]
Transport hostname resolution has been changed - https://github.com/sensu/sensu-transport/pull/42

It is possible the newer Sensu releases resolve your IPv4 address.

I have created a sensu-transport issue to improve the new hostname resolution to support multiple addresses - https://github.com/sensu/sensu-transport/issues/47
