### ISSUE TITLE
Add a "when" attribute to subdue definitions

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu#1390]
Add support for inverting subdue logic by adding a new `when` attribute (optional values: `during` and `outside`; default value: `during`). This would effectively allow users to subdue check executions and/or handling _during_ certain hours, or _outside_ of certain hours. Making the `when` attribute optional and setting a default value of `during` would make this a backwards compatible change. 

## Example

```
"subdue": {
  "at": "publisher",
  "when": "outside",
  "days": [
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday"
  ],
  "begin": "9AM PT",
  "end": "5PM PT"
}
```

## Scenario

Currently, without the ability to toggle subdue functionality, to subdue check requests/handlers outside of 9-5 M-F (for example) would require a combination of a subdue configuration (on a check definition) + a filter definition + applying the filter definition to one or more handlers.

### Example Subdue configuration

```
"subdue": {
  "at": "publisher",
  "days": [
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday"
  ],
  "begin": "12:00AM PT",
  "end": "11:59PM PT",
  "exceptions": {
    "begin": "9AM PT",
    "end": "5PM PT"
  }
}
```

### Example Handler Filter

```
"filters": {
  "weekends": {
    "attributes": {
      "timestamp": "eval: [1,2,3,4,5].include?(Time.at(value).wday) && ((Time.at(value).hour > 9 && Time.at(value).hour < 17))"
    }  
  }
}
```

**Comment by cwjohnston** [comment]
Is this closed by #1415?
