### ISSUE TITLE
Sensu results API - Adding more information

### ISSUE THREAD

**Issue by absolutejam** [sensu/sensu#1398]
Hey guys,

Is it possible to add more information/fields to a result passed in via the REST API?

I've got a check that runs a PowerShell script, which checks a list of contracts expiration dates and sends the results to the Sensu API, creating a single check per contract (and obviously providing a status depending upon how long is left).

Currently I'm passing in a check name, status, output and source (they all come from the source 'contract-checks' for tidiness in Uchiwa). I would like to pass in other fields, such as 'supplier', 'cost' but j get a 400 Bad Request because I assume the results via. API only accommodate the bare minimum fields?

Is there any way around this currently, or could it be a consideration for the future?

Thanks!

**Comment by portertech** [comment]
@absolutejam that's odd, as POST /results does support custom check result attributes https://github.com/sensu/sensu/blob/master/lib/sensu/api/routes/results.rb#L14-L26

**Comment by portertech** [comment]
Is it possible that you are also providing an attribute that overlaps with one that Sensu is validating?

**Comment by absolutejam** [comment]
Apologies, you're right!

It looks like my actual check name had a space in it when I'd tried adding other fields, so it gave me a 400 error. I'd later sanitized the check field but not tried adding extras again, thinking there was an issue with those!

Thanks for reaffirming my stupidity and helping out so quickly.
