### ISSUE TITLE
Timezone notation in handler subdue documentation does not work

### ISSUE THREAD

**Issue by spang** [sensu/sensu#1403]
Hi folks!

Not sure if this is the right place to report documentation bugs—let me know if I should post this elsewhere. I created a handler subdue rule using the "PT" timezone notation indicated in the documentation, assuming that meant "Pacific Time", and found that that did not work correctly. The timezone was instead interpreted using the default system time, which was UTC, and the handler was invoked within the subdue time range. Changing the timezone to "PST" made the handler be suppressed correctly.

I don't know enough about how Ruby handles timezone data to know why this is, but I would suggest you remove the "PT" suggestion from your documentation as it does not work correctly on some systems.

Docs were here:

https://sensuapp.org/docs/latest/reference/handlers.html#subdue-attributes

Debugging info:

```
2.2.2 :004 > Time.now
 => 2016-08-04 11:45:36 +0000 
2.2.2 :027 > condition = {:begin => "9PM PT", :end => "8am PT"}
 => {:begin=>"9PM PT", :end=>"8am PT"} 
2.2.2 :028 > subdue_time? condition
 => false 
2.2.2 :029 > begin_time = Time.parse('9PM PT')
 => 2016-08-04 21:00:00 +0000 
2.2.2 :030 > end_time = Time.parse('8AM PT')
 => 2016-08-04 08:00:00 +0000 
2.2.2 :031 > end_time < begin_time
 => true 
2.2.2 :032 > Time.now < end_time
 => false 
2.2.2 :033 > Time.parse('9PM PST')
 => 2016-08-04 21:00:00 -0800 
2.2.2 :034 > condition = {:begin => "9PM PST", :end => "8AM PST"}
 => {:begin=>"9PM PST", :end=>"8AM PST"} 
2.2.2 :035 > subdue_time? condition
 => true 
```

**Comment by cwjohnston** [comment]
Hi @spang, thanks for raising this issue. I think what happened here is that the "PT" timezone designation is honored out-of-the-box by MacOS systems but not on most Linux distributions. I will ensure that we update the documentation to provide an example timezone which works on as expected on Linux platforms.

**Comment by spang** [comment]
@cwjohnston Awesome, thank you so much!

**Comment by spang** [comment]
(My example is in fact from a Linux system.)

**Comment by balajik1992** [comment]
Hi..can we execute a handler after certain duration of time likeevery 10 minutes?
