### ISSUE TITLE
Question: When should we be expected to restart sensu services?

### ISSUE THREAD

**Issue by absolutejam** [sensu/sensu#1404]
After updating subscriptions and checks, I find myself restarting services on the server and client at random until the checks start and Uchiwa updates.

I'd like to build it into I my workflow to restart the right pieces - can anyone let me know which service to restart when?

Thanks!

**Comment by fessyfoo** [comment]
in the open source version,   clients need to be restarted when their subscriptions are updated.  (or any of their local config, such as standalone checks safemode checks)   servers need to be restarted when  their config is changed. (such as non standalone check definitions)

> NOTE: Sensu services must be restarted in order to pick up configuration changes. Sensu Enterprise can be reloaded.

https://sensuapp.org/docs/0.25/guides/getting-started/intro-to-checks.html

**Comment by portertech** [comment]
@absolutejam the answer provided by @fessyfoo is correct :+1: Thanks @fessyfoo.
