### ISSUE TITLE
/health is returning incorrect HTTP status message

### ISSUE THREAD

**Issue by brian-brazil** [sensu/sensu#1405]
Hi,

On https://sensuapp.org/docs/0.25/api/health-and-info-api.html#health-get-specification `/health` is specified to return `204 (No Content)` however it has started returning the HTTP status `204 No Response`.

I believe this regression occurred in https://github.com/sensu/sensu/pull/1329/files#diff-38423adbb0ff4c5247b34ed86ea83dbcR254 as part of the 0.25 release.

**Comment by cwjohnston** [comment]
Hi @brian-brazil, thanks for opening this issue. HTTP 204 is well documented elsewhere as "No Content" response, so I agree that this is a regression. We'll work to address this shortly.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by cwjohnston** [comment]
Fix for this has been in Sensu 0.25.7
