### ISSUE TITLE
Sensu sent only one email 

### ISSUE THREAD

**Issue by david-strejc** [sensu/sensu#1407]
I got this message repeated:

`{"timestamp":"2016-08-09T16:28:28.539539+0200","level":"info","message":"handler output","handler":{"type":"pipe","command":"cat","name":"stdout"},"output":["{\"client\":{\"name\":\"n2.client.io\",\"address\":\"138.201.127.97\",\"subscriptions\":[\"etcd\",\"openshift-node\",\"default_rhel\",\"default\"],\"load\":{\"warning\":\"1,1,1\",\"critical\":\"2,2,2\"},\"version\":\"0.20.3\",\"timestamp\":1470720441},\"check\":{\"thresholds\":{\"warning\":120,\"critical\":180},\"name\":\"keepalive\",\"issued\":1470752908,\"executed\":1470752908,\"output\":\"No keepalive sent from client for 32467 seconds (>=180)\",\"status\":2,\"type\":\"standard\",\"history\":[\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\"],\"total_state_change\":0},\"occurrences\":1074,\"action\":\"create\",\"timestamp\":1470752908,\"id\":\"c2b54e25-79fc-415f-bb0f-429279fbdac5\",\"last_state_change\":null,\"last_ok\":null}"]}`

But sensu only sent message on first occurrence of this event. 

I went through configuration (which was done via ansible scripts) and I don't know where to look at.

I am using standard sensu-plugin-mailer handler.

Can there be a problem that some checks has defined refresh interval to one day? (which I will see tomorrow)?

**Comment by david-strejc** [comment]
I've wirtten refresh interval like this:

    "keepalive": {
      "thresholds": {
        "warning": 60,
        "critical": 300
      },
      "handlers": ["mailer"],
      "refresh": 1800
    },

Into client.json file and it seems that everything is working from now.

**Comment by portertech** [comment]
This looks to be an issue related to the event handler doing it's own event filtering (not in Sensu core). Event handlers built on the sensu-plugin library do support occurrence filtering, using the check definition attributes `occurrences` and `refresh`. It looks like you have figured this out, by changing the refresh value to 30 minutes :+1:
