### ISSUE TITLE
Server issues keepalives should not assert if the messages queues are above a certain threshold

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1408]
Hi!   We've noticed that we sometimes end up passing the event horizon for our Sensu servers ability to process messages if the keepalive queue gets too high, and this has a cascade failure due to behavior of the Sensu servers.

It would be awesome if there was a feature on Sensu server, before adding keepalive messages on behalf of clients, an inspection of the keepalive/result queues was done and if the queue totals were over a specific amount or if the rate in vs rate out over time is not in a happy place, we suppress shoveling new keepalive messages out onto an already over-board queue.

Does this sound useful and/or align with design patterns going forward?

**Comment by portertech** [comment]
@xyntrix I think a better solution would be to utilize the transports ability to set per message TTLs. For example, RabbitMQ supports this https://www.rabbitmq.com/ttl.html - doing so would allow old/stale keepalive messages to expire, freeing up the queue for fresh keepalives to be consumed.

**Comment by portertech** [comment]
Ideally, the consumers should NEVER let the queue length continue to grow, additional consumers should be provisioned in this case.

**Comment by cwjohnston** [comment]
> I think a better solution would be to utilize the transports ability to set per message TTLs. 

@portertech does https://github.com/sensu/sensu-transport/pull/37 seem germane?

**Comment by xyntrix** [comment]
We've taken in suggestions on this and had a few of our own ways to deal with this.  It would still be great to better understand transport state and handle that distinctly.  Closing this, can open new issue if there's enough merit around an improvement idea.
