### ISSUE TITLE
Feature: sensu message processing rates in api /info call

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1409]
It would be awesome to see some extended details in the /info about message.  If we run into a message processing issue (sometimes an artifact of a network outage/degradation), we often go directly to RabbitMQ to inspect the transport message rates.

It'd be great to add these metrics into the /info api call, which could also then be used by Sensu internals to make decisions about the state of the Sensu transport (ex: should I add more messages to an underwater keepalive queue?)

Specific metrics that might be nice:
- Messages published in last 60s/300s/3600s
- Messages delivered in last 60s/300s/3600s
- Messages acked in last 60s/300s/3600s
- Messages unacked in last 60s/300s/3600s

![image](https://cloud.githubusercontent.com/assets/1305762/17567118/ea828a10-5ef2-11e6-8e2e-8f1332c1fa0a.png)

**Comment by portertech** [comment]
@xyntrix these statistics are provided by a RabbitMQ management plugin and are not available via the AMQP protocol/library. AFAIK these metrics are only available via the RabbitMQ management HTTP API.

Sensu supports other Transports (via sensu-transport), which do not support these metrics or a method of accessing them. We are not going to implement  this, the RabbitMQ management remains the best way of accessing this information.

@xyntrix you could use a RabbitMQ management plugin to collect these metrics, send them to your TSDB of choice, and then embedded the graphs in Uchiwa for a more streamlined experience. You could also monitor these metrics with set thresholds to trigger notifications etc :+1:
