### ISSUE TITLE
subdue filtering out resolve events

### ISSUE THREAD

**Issue by fessyfoo** [sensu/sensu#1410]
_If I'm reading things right_   subdue at the handler `at: handler` as it's currently implemented will prevent resolution events from being handled when the create events start outside the subdue windows  but the resolution event ends in the subdue window. 

in `lib/sensu/server/process.rb`, for the resolution event:

1.  `process_check_result` [calls `#create_event`](https://github.com/sensu/sensu/blob/v0.25.7/lib/sensu/server/process.rb#L584)  which [sets the `event[:action] = :resolve`]  (https://github.com/sensu/sensu/blob/v0.25.7/lib/sensu/server/process.rb#L490-L492)  
based on there being a `stored_event` and ` check[:status] == 0`  
2. it then calls [`#update_event_registry`](https://github.com/sensu/sensu/blob/v0.25.7/lib/sensu/server/process.rb#L586)  which [deletes the event if it's `event[:action] == :resolve`](https://github.com/sensu/sensu/blob/v0.25.7/lib/sensu/server/process.rb#L439-L443) 
3. next [process_event is called](https://github.com/sensu/sensu/blob/v0.25.7/lib/sensu/server/process.rb#L587) which in turns [calls `#filter_event`](https://github.com/sensu/sensu/blob/v0.25.7/lib/sensu/server/process.rb#L253)   which is where subdue happens.   If the resolve event is in a subdue window then it will not call the handlers for that resolve event.  Having removed the stored event in step 2 there will be no future resolve event. 

this is mostly an issue for those of us using standalone checks.   subdue at the publisher subdues any events from ever happening, and thus the resolution event will only happen outside the subdue window. 

fortunately [the proposal](https://github.com/sensu/sensu/issues/1219#issuecomment-225245100)  in https://github.com/sensu/sensu/issues/1219 for subdue 2.0  actually will solve this issue as well. 

@calebhailey [wrote](https://github.com/sensu/sensu/issues/1219#issuecomment-225245100): 
> The new Sensu monitoring flow will be visualized as follows:
> ```
check definition => check request => subdue => check execution => check result => event => filters => mutators => handlers
```

hope this explanation helps.

**Comment by fessyfoo** [comment]
note: similar resolution event filtering issue in [occurrence filtering](https://github.com/sensu/sensu-extensions/pull/11#issuecomment-234463087) to be resolved here https://github.com/sensu-extensions/sensu-extensions-occurrences/issues/1

**Comment by calebhailey** [comment]
@fessyfoo thanks for submitting this! I think @portertech is beginning to work on the new Subdue 2.0 this week, so he should be able to comment on this pretty soon. #monitoringlove

**Comment by portertech** [comment]
@fessyfoo the standalone scheduler has never supported subdue, so standalone checks could only have ever use `"at": "handler"`. Many of the existing methods of reducing event notifications do not allow resolution event notifications if there was never a notification for create, i.e. nobody cared about the creation of an event so why let them know it was resolved. Subdue is currently getting a complete overhaul, I look forward to working this out on a WIP PR :+1:

**Comment by fessyfoo** [comment]
@portertech  thanks. :)  I noted that subdue 2.0 would resolve this,  but I felt compelled to write it out once I understood it.   

veering off topic: 
> Many of the existing methods of reducing event notifications do not allow resolution event notifications if there was never a notification for create, i.e. nobody cared about the creation of an event so why let them know it was resolved

any pointers to these 'existing methods' ?

**Comment by fessyfoo** [comment]
closing this,  as I believe it is resolved with sensu > 0.26  as a result of subdue 2.0

**Comment by calebhailey** [comment]
@fessyfoo \o/
