### ISSUE TITLE
migration plan for built in silencing?

### ISSUE THREAD

**Issue by fessyfoo** [sensu/sensu#1412]
so now that [built in silencing](https://github.com/sensu/sensu/issues/1328) will be in sensu 0.26  I'm wondering if anyone's had any thoughts on the migration path. 

I suppose one would [update uchiwa](https://github.com/sensu/uchiwa/issues/539)  and any other tools that do silencing to use the new apis,   and use some tool to copy current silenced things from old api to new api.    or just delete old silences and start over? 

i'm still trying to think how best to get through this, any thoughts are appreciated.

**Comment by portertech** [comment]
@fessyfoo I have a meeting with @palourde tomorrow, to discuss our options and plan the transition. We may need to go as far as having a minimal Sensu version constraint for the next Uchiwa release, I believe this would be the most swift and clean transition. WDYT?

**Comment by fessyfoo** [comment]
a hard cutover of uchiwa from stash based to built in silencing is probably easiest for uchiwa.   
a stash to built in converter might be useful for such a cutover.  (_we have too much stuff silenced_ 😞 )   

then this might work: 
  1. upgrade sensu
  1. copy old stashes to new builtins.
  1. upgrade uchiwa
  1. upgrade anything other silencing mechanism.  (we have a downtime cli script, pagerduty webhooks, ... ) 
  1. recopy stashes to builtins just to be sure.  (catching updates,  though losing any deletes and living with it... ) 
  1. delete old stashes. 


though I still don't think I've got my head around it yet. :)

**Comment by cwjohnston** [comment]
@fessyfoo in publishing the [silencing reference documentation]( https://sensuapp.org/docs/latest/reference/silencing.html ), I added an appendix to describe the steps we think are necessary for migrating. It would be helpful to have you feedback on this, especially if you've already gone through this yourself.

**Comment by cabecada** [comment]
We had a issue where the older clients/proxy clients which did not have subscriptions, the handlers bypassed silencing and went on triggering alerts. The new sensu clients had built in client subscription, and only here the handler was silenced :(

**Comment by portertech** [comment]
Closing this, as https://sensuapp.org/docs/latest/reference/silencing.html#migrating-from-stash-based-silencing and the Sensu 0.28 fix to add missing client subscriptions seem sufficient.
