### ISSUE TITLE
Need documentation - Sensu client signature

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu/sensu#1414]
Except for some sparse information on Sensu client signature in [changelog](https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0220---2016-01-29), I cannot seem to find any other reference to **client signatures** anywhere else.

Even the official [Reference documentation](https://sensuapp.org/docs/latest/reference/clients.html) does not have any mention.

**Comment by runningman84** [comment]
see https://github.com/sensu/sensu-docs/issues/393

**Comment by jaykumar-jnpr** [comment]
Duplicate of sensu/sensu-docs#393, closing.
