### ISSUE TITLE
Sensu events not triggering handlers on every check

### ISSUE THREAD

**Issue by peterfraedrich** [sensu/sensu#1418]
I don't know if there's something I'm just completely missing, but from all of my research into setting up Sensu to send metrics to an external DB like Influx or Elasticsearch it seems that Sensu is supposed to trigger handlers on every check result. If that is the case, my Sensu install isn't doing that, its only triggering handlers on state changes (ok, crit, warn, etc.). 

I can see the check results in the `sensu-server.log` when log level is set to `debug` and everything else is working as expected, however this one thing is really limiting me from bringing this online in our non-prod environments.

## My Environment
* Sensu version used: 0.25.3
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.2 x64 (selinux disabled)
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Redis 2.8.19-2

Any help is appreciated!

**Comment by runningman84** [comment]
You should define checks as metrics if you want to get a event every time.

**Comment by peterfraedrich** [comment]
I am officially, and rather publicly, an idiot. 
Thanks @runningman84 !!!
