### ISSUE TITLE
Feature Request: client attribute tokens

### ISSUE THREAD

**Issue by Craigeous** [sensu/sensu#1420]
I apologize if this is currently a capability and I missed it, but I don't believe it to be the case.

Command tokens in checks are a really nice feature.  I think having a similar feature for client configs would be valuable as well.  Finding ways to be more dynamic is never a bad thing in my mind.

## I'll use the command token format as my example, but it doesn't have to be that way.

```
{
"client": {
       "name": :::hostname::: (or :::fqdn::: to display the full name),
       "address": :::ipaddr:::, (:::int::: would give you the IP in the clients screen and all the information about the interface when you go into the client itself... you could also go as far as :::int.ipv4/6::: or whatever property of that interface you want to display on the clients screen) 
        "environment": "south bend",
       "subscriptions": [ ],
       "socket": {
            "bind": "0.0.0.0",
             "port": 3030
    }
  }
}
```

## Current Behavior
To my knowledge, it's just a string that you enter that is not dynamic in any way.

## Context
Deploying the client to my environment without an automation platform is more time consuming and if an IP or hostname changes for one reason or another it's not reflected in Sensu.

**Comment by portertech** [comment]
@Craigeous 0.26, soon to be released, defaults the Sensu client name to the system hostname and the client address to the system IP :-) https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/loader.rb#L42 Going to close this issue, as I believe this functionality should suffice. Sensu tokens currently represent attributes in a configured definition, we wouldn't want to create confusion by adding magic tokens :P Thank you for creating the issue!

**Comment by Craigeous** [comment]
I'm happy with this.  Thank you!
