### ISSUE TITLE
"event was filtered" log messages should provide filter name context

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu#1422]
## Expected Behavior

Messages indicating an event was filtered should include the name of the acting filter.

## Current Behavior

Currently when an event is filtered by Sensu, the log message indicates that the "event was filtered", providing handler and event detail but not the name of the acting filter.

## Possible Solution

Update Sensu::Server::Filter method `event_filtered?` to return the filter name in addition to the boolean. 

Update Sensu::Server::Filter method `filter_event` to merge the filter name into the logged details.

## Steps to Reproduce (for bugs)
1. Configure Sensu with one or more filters
2. Generate some events which match the filters
3. Observe that the log file does not provide needed context

## Context

Without additional context, i.e. the name of the filter which caused the event to be filtered out (dropped), it is difficult to troubleshoot the inadvertent filtering of events. 

## Your Environment
* Sensu version used: 0.25.7
* Operating System and version: Ubuntu 14.04
* Transport and runtime versions: Redis

**Comment by cwjohnston** [comment]
I think it would also be helpful if filters could optionally specify a message which would be logged with the event filter message.

**Comment by portertech** [comment]
Let's have `native_filter()` and `extension_filter()` yield the filter name with filtered.

**Comment by cwjohnston** [comment]
Opened #1467 to add this feature.
