### ISSUE TITLE
Allow TTL exit code to be configurable

### ISSUE THREAD

**Issue by pauloconnor** [sensu/sensu#1423]
As discussed in https://github.com/sensu/sensu/pull/971, not everyone uses warnings, and would prefer criticals to be default. Making this configurable would be useful.
## Expected Behavior

When a check expires due to TTL, a critical should be sent.
## Current Behavior

When a check expires due to TTL, a warning is sent.
## Possible Solution

Add a configuration item to sensu.conf which allows for ttl_expiry_exit_code (or similar) to be configured. 
## Context

https://github.com/sensu/sensu/pull/971 explains the reasoning behind this.
## Your Environment

- Sensu version used: 0.25.3
- Operating System and version (e.g. Ubuntu 14.04): Ubuntu 14.04
- Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): 3.3.4 on 17.5

**Comment by portertech** [comment]
Perhaps `ttl_status` to match w/ the Sensu check language? :+1:

**Comment by portertech** [comment]
Merged into release/0.27
