### ISSUE TITLE
FreeBSD packages are corrupt

### ISSUE THREAD

**Issue by inferiorhumanorgans** [sensu/sensu#1425]
Per https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212022

`seems like the package was made via fpm somehow, and the manifest is missing lots of entries. anyway pkg should not segfault but yell at the missing fields, I will fix it (via yelling)`

**Comment by portertech** [comment]
@amdprophet ping

**Comment by amdprophet** [comment]
@inferiorhumanorgans I'll look into this - in the mean time please use `pkg add` to install the package. Can you please open this issue against the https://github.com/sensu/sensu-build repository?
