### ISSUE TITLE
FreeBSD rc scripts should be properly formatted for sensu-api and sensu-server

### ISSUE THREAD

**Issue by inferiorhumanorgans** [sensu/sensu#1429]
The way they are structured now, the services do not come up at boot.  Documentation is available here:

https://www.freebsd.org/doc/en/articles/rc-scripting/

https://www.freebsd.org/doc/en/books/porters-handbook/rc-scripts.html

**Comment by amdprophet** [comment]
Hi @inferiorhumanorgans,

As this is a build-specific issue, I've opened another issue against the sensu-build repo (https://github.com/sensu/sensu-build/issues/175).
