### ISSUE TITLE
Add check via API

### ISSUE THREAD

**Issue by david-strejc** [sensu/sensu#1431]
I've proposed this about a year ago.

But both issues were closed and this feature for me is so important I try to recreate it.

I've read through discussions in both issues regarding adding checks via API and what I've found is that this is not implemented due to security risk.

Solutions:

1) Implement it anyway but with !!!! IMPORTANT !!!! note in documentation - this feature can cause critical damage to your system - or something similar - for those who don't want to use it just don't use it - or explicitly disable this feature in config.

2) Not implement it but this makes Sensu less useful - I have to combine it with tools like Ansible to achieve checks distribution.

I am just an DevOps guy but I can imagine check distribution as follows:

1) I got check scripts specified in .json file
2) Sensu server waits for sensu client to connect and sensu client ensures it has all the checks (physical files) available - otherwise it "gets them (don't know how to exactly do that - which channel to use)" and puts them into "checks" folder specified.
3) Checks can be added via API in the form of .json file with check filename and check file payload

This will complete Sensu solution - it will have all which is needed in dynamic environment - I won't be distributing checks in other channel which makes monitoring more complex as I am using many tools - at least Sensu and Ansible and something which is triggering checks distribution.

**Comment by fessyfoo** [comment]
I find this issue report a  tiny bit unclear,  can you link to the previous discussions you've mentioned?

Are you asking for sensu to distribute check commands  (executables/scripts)  to clients?   Or simply check definitions?

If the former I find that to be an extreme amount of scope creep for sensu moving it into the realm of configuration management, and I would strongly advise against it.  You obviously get other software on your clients that aren't check executables including sensu-client itself, use the same mechanisms to get your check executables there, they are "part of the system".

If the later I think sensu can accommodate this need as is because the check definitions can be placed on the server and grouped by subscriptions  the client definitions then just subscribe to the groups of checks they should run.

**Comment by portertech** [comment]
Any sort of check configuration and runtime dependency management requires either a centralized and consistent source of truth or proper consensus, along with some form of an asset store. The current design and iteration of Sensu (nearly 1.0) relies heavily on configuration management for its capabilities and workflow. Bolting on definition creation via the API is a non-starter as it would create an absolute mess, configuration conflicts and confusion. If this is something that Sensu needs to do, a complete rewrite of how configuration is loaded, validated, and managed would need to happen.

That said, I have begun to design and work on Sensu 2.0, which leverages gossip and consensus protocols to remove Sensu's reliance on configuration management. I plan to release these designs for review, after spending some time validating/testing them.

I do not think that implementing this functionality is a good idea with the current design of Sensu.

**Comment by david-strejc** [comment]
OK - I am completely satisfied by Sensu 2.0 

I know it will take time but I consider Sensu as industry standard for monitoring for next decade or two - and if Sensu 2.0 will have such a feature I can wait.

Let us please know when those design documents will be issued and I will go through them and see if my request is satisfied.

Many thanks @portertech.

**Comment by shakycode** [comment]
Looking forward to the new design and potential 2.0 release @portertech. If you need any help I'm happy to sprint and do a bunch of PRs

**Comment by david-strejc** [comment]
@portertech where can be found those design documents?

**Comment by portertech** [comment]
I am hoping to publish a high level 2.0 design/architecture document to the community in the near future, pulling information from the Sensu Inc internal engineering wiki. We're actively developing and changing the design, with plans to have an alpha ready in a few months time.
