### ISSUE TITLE
sensu dies if redis host can't be resolved

### ISSUE THREAD

**Issue by lobeck** [sensu/sensu#1433]
## Expected Behavior

if the hostname can't be resolved, it shall be retried until it works (if `auto_reconnect`/`reconnect_on_error` are set)
## Current Behavior

```
{"timestamp":"2016-09-05T16:26:13.142121+0000","level":"warn","message":"reconnecting to redis"}
{"timestamp":"2016-09-05T16:26:13.142278+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-09-05T16:26:15.159285+0000","level":"warn","message":"reconnecting to transport"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:794:in `connect_server': unable to resolve server address: Success (EventMachine::ConnectionError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:794:in `reconnect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/connection.rb:686:in `reconnect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:90:in `block (2 levels) in reconnect!'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:40:in `determine_address'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:89:in `block in reconnect!'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.6/lib/sensu/server/process.rb:31:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.6/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'
```
## Context

We've built a fully automatic solution to provide a redis master/slave cluster. Sentinel is not an option, as we treat our machines as cattle and therefore don't know who the master will be and sentinel requires the master/slave replication to be already in place.

However, during failover the hostname of the redis might not be available for up to 10 seconds but the resulting `NXDOMAIN` is causing sensu to crash.
## Your Environment

sensu 0.25.6-1 (embedded ruby) on Ubuntu 12.04

**Comment by lobeck** [comment]
I've build a hotfix now to catch it in `client.rb` of `sensu-redis`. As i'm not familiar with eventmatchine and ruby in particular, i'm not sure on wether this is is a good place/way to mitigate it:

I've just surrounded the `reconnect()` call in `client.rb:90`

    begin
      reconnect(host, port)
    rescue RuntimeError => boom
      if boom =~ /unable to resolve server address/
        error(ConnectionError, boom)
      else
        raise RuntimeError, boom
      end
    end

**Comment by portertech** [comment]
New Sensu releases resolve the Redis hostname prior to making a connection attempt and handle it appropriated.
