### ISSUE TITLE
Check token substitution with integers

### ISSUE THREAD

**Issue by rholloway** [sensu/sensu#1434]
It appears that there is no way to make a valid check substitution for integer fields within a check. For example, if I want to override "interval" or "refresh" fields for a specific client, I cannot. This is because sensu-server will not load if the value is set to `:::custom_attribute|60:::` without quotes because it is not valid JSON, but if wrapped in quotes such as `":::custom_attribute|60:::"` then it fails because it expects an integer and not a string.
## Expected Behavior

One of the following checks should work and allow sensu-server to start.

```
{
  "checks": {
    "metrics_cpu": {
      "type": "metric",
      "command": "metrics-cpu.rb",
      "subscribers": [
        "ubuntu"
      ],
      "interval": :::custom_interval|60:::,
      "handlers": ["graphite_tcp"]
    }
  }
}
```

```
{
  "checks": {
    "metrics_cpu": {
      "type": "metric",
      "command": "metrics-cpu.rb",
      "subscribers": [
        "ubuntu"
      ],
      "interval": ":::custom_interval|60:::",
      "handlers": ["graphite_tcp"]
    }
  }
}
```
## Current Behavior

Neither solution above works. Both are rejected as invalid checks. This means we cannot create client overrides or utilize check-tokens for non-string fields. It would be possible to create separate checks (complete checks) and utilize subscriber field to control who subscribes to which checks (such as a check metrics_cpu_60 or metrics_cpu_120), but this is not ideal - it would be better to be able to use defaults and override certain fields as needed from client custom attributes.
## Possible Solution

If we need to provide valid JSON to sensu-server to load up a check, it should be less restrictive on integer vs. string values for JSON key values and instead if an integer is expected try to cast the string to an integer after loading JSON.
## Context

The goal is to override check intervals frequencies where needed. For example, when utilizing t2.nano instances on AWS EC2, it is desirable to check less frequently than on some other node due to burst/cpu credit limits. However, on other nodes where processing is less restrictive, it may be useful to gather data with more granularity.

**Comment by portertech** [comment]
Revisit this for 1.1

**Comment by raffraffraff** [comment]
FYI: This appears to work for 'occurrences', but not 'interval'.

**Comment by portertech** [comment]
Tokens can work in "occurrences" because it's a custom attribute, that's not validated, and can be consumed by code that does the appropriate type conversion, string -> integer.

Configured attribute values that use tokens must be a string, in order to have valid JSON, and support Sensu setting validation. Not using the correct value type will not only cause validation to fail, but could potentially cause one or more Sensu components to crash. Because of these reasons, tokens cannot be used for integer values (unless the token is used in an event filter eval statement).
