### ISSUE TITLE
Sensu mishandles subdue days in handler

### ISSUE THREAD

**Issue by bahner** [sensu/sensu#1438]
## Expected Behavior
Specifying a check with subdue days, the doc clearly state that days should be an array of weekdays. This has worked before. https://sensuapp.org/docs/latest/reference/handlers.html#subdue-attributes

## Current Behavior
Sensu now tries to ensure that subdue days is a hash:
{"timestamp":"2016-09-08T00:27:18.293006+0200","level":"fatal","message":"check subdue days must be a hash","object":{"command":"sudo /usr/lib/nagios/plugins/check_apt -t 60","handlers":["slack","inonit"],"interval":3600,"standalone":true,"timeout":60,"subscribers":["Debian","Ubuntu"],"refresh":3600,"subdue":{"at":"handler","days":["saturday","sunday"]},"name":"check_apt"}}

## Possible Solution
For now I just comment out the subdue hash, and let the check let the handler run also in the weekends.

## Steps to Reproduce (for bugs)
/etc/sensu/conf.d/checks/check_apt.json:
{
  "checks": {
    "check_apt": {
      "command": "sudo /usr/lib/nagios/plugins/check_apt -t 60",
      "handlers": [
        "slack",
        "inonit"
      ],
      "interval": 3600,
      "standalone": true,
      "timeout": 60,
      "subscribers": [
        "Debian",
        "Ubuntu"
      ],
      "refresh": 3600,
      "subdue": {
        "at": "handler",
        "days": [
          "saturday",
          "sunday"
        ]
      }
    }
  }
}

This will not allow sensu to start, but removing the subdue statement will.

## Your Environment
* Sensu version used: 0.26.1
* Operating System and version (e.g. Ubuntu 14.04): Debian 8.5 "jessie"

**Comment by calebhailey** [comment]
@bahner [Subdue got a major overhaul in the 0.26 release][1], including deprecating support for applying subdue to handlers. Although documentation for the new subdue behavior was added (see [check definition `subdue` attributes][2]), and we did document [warnings about the changes in the changelog][3], we clearly missed removing the subdue example from the handler reference docs (sorry!). 

Please note that, in preparation for the impending version 1.0 release) the terminology around "Subdue" has been changed in Sensu Core version 0.26. Subdue will now only refer to _subduing_ check requests (i.e. formerly referred to as `"at": "publisher"`). Subduing at the handler has been replaced with a new ["when" attribute for filter definitions][4]. _NOTE: the new `subdue` and filter `when` attributes both share the same specification, so Sensu retains a shared model for describing time-based filtering._

In this way, the Sensu monitoring pipeline can more easily be described as follows: 

    check definition => SUBDUE => request => result => event => filter(s) => mutator => handler(s)

...as opposed to the old pipeline in which subdue could occur in two places: 

    check definition => SUBDUE => request => result => SUBDUE => event => filter(s) => mutator => handler(s)

I hope this helps! 

I've gone ahead and opened up a pull-request for removing the misleading handler subdue documentation. See: https://github.com/sensu/sensu-docs/pull/437 

/cc @portertech 

[1]: https://sensuapp.org/docs/0.26/overview/changelog.html#core-v0-26-0
[2]: https://sensuapp.org/docs/0.26/reference/checks.html#subdue-attributes
[3]: https://sensuapp.org/docs/0.26/overview/changelog.html#core-v0-26-0-important
[4]: https://sensuapp.org/docs/0.26/reference/filters.html#when-attributes

**Comment by calebhailey** [comment]
I'm going to go ahead and close this issue in favor of https://github.com/sensu/sensu-docs/pull/437
