### ISSUE TITLE
Per-client silencing doesn't work for proxy clients

### ISSUE THREAD

**Issue by Gillingham** [sensu/sensu#1439]
I created a silence for a check on a specific client, however I still then get notifications for that check/client combinations.

## Expected Behavior
The silence silenced notifications for the check and client.

## Current Behavior
` curl -s http://localhost:4567/silenced | jq`
```json
[
 {
    "id": "client:foo:check_chrony",
    "subscription": "client:foo",
    "check": "check_chrony",
    "reason": null,
    "creator": null,
    "expire_on_resolve": true,
    "expire": -1
  }
]
```
Yet I still get email alerts for UNKNOWN events.

## Your Environment
* Sensu version used: 0.26.1
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7

**Comment by Hydrochoerus** [comment]
Have you tried making expiring silences? For me all non-expiring silences are broken (do not have the time to open a proper issue for now).

**Comment by Gillingham** [comment]
Changing the title since I have a silence that is not check specific but rather for an entire client showing up in /silenced API:
```json
 {
    "id": "client:ctt:*",
    "subscription": "client:ctt",
    "check": null,
    "reason": null,
    "creator": null,
    "expire_on_resolve": true,
    "expire": -1
  }
```
but I still get alerts from it.

Doing a test right now to see if setting an expire value works per @Hydrochoerus suggestion.

**Comment by amdprophet** [comment]
Client silencing requires that a "client:client_name" subscription exists (in your example this would be "client:ctt"). This happens automatically in Sensu 0.26.0 and higher. Please ensure that the client you're silencing has been upgraded and shows the "client:ctt" subscription.

**Comment by Gillingham** [comment]
For the ctt example, that client is a proxy client, so no client:ctt subscription, perhaps that use case needs to be investigated more. If the creation on the clientside is automatic, it sounds like perhaps the subscription should also be automatic when a proxy client exists/is created.
