### ISSUE TITLE
Handler attributes on handler sets

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu#1445]
Currently we do not propagate any handler attributes on a `set` handler down to the member handlers (members of the set). One advantage of allowing handler attributes to propagate to their member handlers would be effectively creating multiple configurations of handlers for different uses.

For example, a handler set `alert_critical` could contain the members `slack` and `email` and have the attribute `severities` set to `['critical']` and then any check could use `alert_critical` for its handler, which would not prevent the `slack` or `email` handler bring used directly without the `severities` config.

**Comment by barryorourke** [comment]
I would love to see this implemented too.

**Comment by portertech** [comment]
This goes against Sensu's explicit configuration model. The functionality would be rad, however, some work would be required to create merged handler definitions on the fly. We are not going to implement this.
