### ISSUE TITLE
Sense client error "previous check command execution in progress"

### ISSUE THREAD

**Issue by WayneYe** [sensu/sensu#1446]
I am using latest sensu core version 0.26.1, set up sensu server on one CentOS machine, set up one sensu client on another.

## The issue
There are about 500 checks in one sensu client, I keep seeing `"previous check command execution in progress"` in sensu-client.log, but each check actually finishes very fast (most of them less than 0.1 seconds and interval is 60 seconds)
, i can confirm this by running it under `sensu` user `sudo su sensu -c "{run my check}"`.

However, the actual situation was, in the uchiwa dashboard, it shows **many of my checks were running more than 1 minute**, seems the sensu client got seriously stuck/slow, i tried the following approaches:

## Resolve attempts
1. Remove several long running checks and restart sensu server/client
2. Add [timeout][1] definition to my checks, limit timeout to 10, then resulted in many of the checks **"Execution timed out"**.
3. I tried only run 1, 10, 50 checks, seems everything was working normally, however, as soon as the count of the checks reaches certain number maybe 200-300, the issue occurred.
4. Change the transport from rabbitmq to redis

## Environment
* Sensu version used: 0.26.1
* OS: CentOS 6.6
* Transport: RabbitMQ 3.6.2 and Redis 2.4.10

**Comment by WayneYe** [comment]
One more found, i reduced my checks to about 90, and I found all the check which actually finishes within 0.x seconds (I have a print statement with duration), however, in uchiwa dashboard, I saw the  actual duration was 10-20 seconds.

**Comment by portertech** [comment]
@WayneYe hello, it seems that you are exceeding the Sensu Spawn limit, which limits the number of concurrent check executions. When you approach 200-300 checks, the Sensu Spawn thread pool is exhausted, causing executions to be queued, increasing the observed/recorded execution duration. 

To fix this, please add the following configuration snippet to the Sensu client in question:

`/etc/sensu/conf.d/spawn.json`:

```
{
  "sensu": {
    "spawn": {
      "limit": 100
    }
  }
}
```

You may need to tweak the limit if you still see long check durations. It's important to not set the limit too high, as it will cause the creation of excess Ruby threads.

**Comment by WayneYe** [comment]
@portertech Many thanks for the answer!  I googled and searched in sensu docs and didn't see anything related to this, could you share some links if there were? But anyway I will give it a try, thank you again!

**Comment by cwjohnston** [comment]
Hi @wayneye, you're right that there's no real documentation for this as of yet. 

I've opened https://github.com/sensu/sensu-docs/issues/451 to track the need for documentation on this aspect of Sensu's configuration.

**Comment by WayneYe** [comment]
@cwjohnston may i know the default limit value please? I did a search in sensu source code but didn't find this information.

**Comment by cwjohnston** [comment]
@WayneYe see sensu-spawn codebase, specifically https://github.com/sensu/sensu-spawn/blob/master/lib/sensu/spawn.rb#L27-L38

**Comment by WayneYe** [comment]
Awesome, default is 12, thank you!
