### ISSUE TITLE
proxy server option for sensu-install

### ISSUE THREAD

**Issue by GazzaC** [sensu/sensu#1447]
I am in an environment that uses a proxy to internet
## Expected Behavior

$ sensu-install -v -p cpu-checks
$ sensu-install -h
Usage: sensu-install [options]
    -h, --help                       Display this message
    -v, --verbose                    Enable verbose logging
    -p, --plugin PLUGIN              Install a Sensu PLUGIN
    -P, --plugins PLUGIN[,PLUGIN]    PLUGIN or comma-delimited list of Sensu plugins to install
    -e, --extension EXTENSION        Install a Sensu EXTENSION
    -E, --extensions EXTENSION[,EXT] EXTENSION or comma-delimited list of Sensu extensions to install
    -s, --source SOURCE              Install Sensu plugins from a custom SOURCE

[SENSU-INSTALL] gem install -p http://f.q.d.n:# sensu-plugins-cpu-checks --no-ri --no-rdoc --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=sensu-plugins-cpu-checks
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/sensu-plugins-cpu-checks-1.0.0.gemspec.rz
302 Moved Temporarily
.
.
.
## Current Behavior

Time out
## Possible Solution

Add code in rb file which takes cmdline option
## Steps to Reproduce (for bugs)

timeout
ERROR:  Could not find a valid gem 'sensu-plugins-process-checks' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
[SENSU-INSTALL] failed to install Sensu gem 'sensu-plugins-process-checks'
[SENSU-INSTALL] please take note of any failure messages above
[SENSU-INSTALL] make sure you have build tools installed (e.g. gcc)
[SENSU-INSTALL] trying to determine the Sensu plugin homepage for sensu-plugins-process-checks ...
ERROR:  No gem matching 'sensu-plugins-process-checks (>= 0)' found
## Context

I modified the code in /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.0/exe/sensu-install line 65 to gem_command = "gem install -p http://f.q.d.n:x #{gem_name}"
## Your Environment

- Sensu version used: 0.26.0
- Operating System and version (e.g. Ubuntu 14.04): CentOS release 6.7 (Final)
- Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by Cepxio** [comment]
Hi GazzaC, 

I did the same change. I leave my e.g on sensu 0.28.0 version.

`gem_command = "gem install --http-proxy http://xx.xx.xx.xx:port #{gem_name}`

**Comment by portertech** [comment]
The sensu-install `-x` `--proxy` argument(s) will be in 0.29 :+1: https://github.com/sensu/sensu/pull/1629
