### ISSUE TITLE
keepalive issues with 0.23.1

### ISSUE THREAD

**Issue by calvinx408** [sensu/sensu#1451]
## Current Behavior
when deleting a client; the client get's re-registered. i renamed the client name to be something unique and ntp is fine.  

sensu-server logs:
`
{"timestamp":"2016-09-19T13:29:42.539352-0700","level":"debug","message":"received result","result":{"client":"sfx-calvin.corp.calvintest.net","check":{"thresholds":{"warning":700,"critical":800},"occurrences":3,"handlers":["ioc"],"name":"keepalive","issued":1474316976,"executed":1474316976,"output":"Keepalive sent from client 76 seconds ago","status":0},"signature":""}}
{"timestamp":"2016-09-19T13:29:42.539443-0700","level":"debug","message":"processing result","result":{"client":"sfx-calvin.corp.calvintest.net","check":{"thresholds":{"warning":700,"critical":800},"occurrences":3,"handlers":["ioc"],"name":"keepalive","issued":1474316976,"executed":1474316976,"output":"Keepalive sent from client 76 seconds ago","status":0},"signature":""}}
{"timestamp":"2016-09-19T13:29:42.539866-0700","level":"debug","message":"updating client registry","client":{"name":"sfx-calvin.corp.calvintest.net","address":"unknown","subscriptions":[],"keepalives":false,"version":"0.26.1"}}
`

redis shows:
`
1474321584.761509 [0 127.0.0.1:60883] "setnx" "client:sfx-calvin.corp.calvintest.net:signature" ""
1474321584.762543 [0 127.0.0.1:60883] "get" "client:sfx-calvin.corp.calvintest.net:signature"
1474321584.763093 [0 127.0.0.1:60883] "set" "client:sfx-calvin.corp.calvintest.net" "{\"name\":\"sfx-calvin.corp.calvintest.net\",\"address\":\"unknown\",\"subscriptions\":[],\"keepalives\":false,\"version\":\"0.23.1\"}"
1474321584.763116 [0 127.0.0.1:60883] "sadd" "clients" "sfx-calvin.corp.calvintest.net"
1474321584.764259 [0 127.0.0.1:60883] "sadd" "result:sfx-calvin.corp.calvintest.net" "keepalive"
1474321584.764269 [0 127.0.0.1:60883] "set" "result:sfx-calvin.corp.calvintest.net:keepalive" "{\"thresholds\":{\"warning\":700,\"critical\":800},\"occurrences\":3,\"handlers\":[\"ioc\"],\"name\":\"keepalive\",\"issued\":1474321578,\"executed\":1474321578,\"output\":\"No keepalive sent from client for 4678 seconds (>=800)\",\"status\":2}"
1474321584.764301 [0 127.0.0.1:60883] "rpush" "history:sfx-calvin.corp.calvintest.net:keepalive" "2"
1474321584.764315 [0 127.0.0.1:60883] "ltrim" "history:sfx-calvin.corp.calvintest.net:keepalive" "-21" "-1"
1474321584.764768 [0 127.0.0.1:60883] "lrange" "history:sfx-calvin.corp.calvintest.net:keepalive" "-21" "-1"
1474321584.765896 [0 127.0.0.1:60883] "hget" "events:sfx-calvin.corp.calvintest.net" "keepalive"
1474321584.766553 [0 127.0.0.1:60883] "hset" "events:sfx-calvin.corp.calvintest.net" "keepalive" "{\"id\":\"389f7d82-c5de-4985-a51e-21e7e1f27143\",\"client\":{\"name\":\"sfx-calvin.corp.calvintest.net\",\"address\":\"unknown\",\"subscriptions\":[],\"keepalives\":false,\"version\":\"0.23.1\"},\"check\":{\"thresholds\":{\"warning\":700,\"critical\":800},\"occurrences\":3,\"handlers\":[\"ioc\"],\"name\":\"keepalive\",\"issued\":1474321578,\"executed\":1474321578,\"output\":\"No keepalive sent from client for 4678 seconds (>=800)\",\"status\":2,\"history\":[\"2\"],\"total_state_change\":0},\"occurrences\":1,\"action\":\"create\",\"timestamp\":1474321584}"
1474321586.091276 [0 127.0.0.1:60885] "get" "client:sfx-calvin.corp.calvintest.net"
1474321586.418763 [0 127.0.0.1:60885] "hgetall" "events:sfx-calvin.corp.calvintest.net"
1474321586.708047 [0 127.0.0.1:60885] "get" "client:sfx-calvin.corp.calvintest.net"
1474321586.715074 [0 127.0.0.1:60885] "smembers" "result:sfx-calvin.corp.calvintest.net"
1474321586.715273 [0 127.0.0.1:60885] "lrange" "history:sfx-calvin.corp.calvintest.net:keepalive" "-21" "-1"
1474321586.715420 [0 127.0.0.1:60885] "get" "result:sfx-calvin.corp.calvintest.net:keepalive"
1474321587.336803 [0 127.0.0.1:60885] "get" "client:sfx-calvin.corp.calvintest.net"
1474321587.926114 [0 127.0.0.1:60885] "hgetall" "events:sfx-calvin.corp.calvintest.net"
`

## Steps to Reproduce (for bugs)

1. Stop sensu-client on the sensu-server (I’m running sensu-client on the server)
2. Edit client.rb name to something unique
3. Start sensu-client so it’s gets registered
4. Stop sensu-client
5. Use the api/uchiwa to delete the client
6.  Host will be re-registered with keepalive false. (tried it on 5 different client)

## Context

i was trying to figure why i have a bunch of host that keeps flapping for keepalive then i stumbled upon this. 

## Your Environment

* Sensu version used: 0.23.1
* Operating System and version (e.g. Ubuntu 14.04): redhat 6.8
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): 3.61 rabbitmq with 18.2 erlang

**Comment by cwjohnston** [comment]
Hi @calvinx408,

The way you've described the behavior you're observing, particularly this sentence:
> Host will be re-registered with keepalive false. (tried it on 5 different client)

leads me to believe that the deleted client is being recreated as a [proxy client](https://sensuapp.org/docs/latest/reference/clients.html#proxy-clients). Proxy clients are created automatically when processing a check result which is not attributable to an existing client in the registry.

One possibility is that your Sensu server is significantly behind in processing the results queue at the time you delete the client. Any check results still pending in the results queue from the now-deleted client will create a proxy client with the same name.

If you aren't already monitoring the queue size and/or delivery rates of your RabbitMQ transport, the [RabbitMQ management plugin](https://www.rabbitmq.com/management.html) provides means to view queue details via the web browser.

Please have a look and let me know if you think this makes sense?

**Comment by calvinx408** [comment]
That totally makes sense. I added 2 lines to /etc/sensu/config.json for all 3 of my servers:
     "heartbeat": 30,
     "prefetch": 50

I also changed keepalive to false for now. Everything is good now, but i wasn't able to delete those proxy clients. I had to stop sensu-client on my server and add the proxy client name. Started sensu-client and once it got changed from proxy client to regular client. I stopped sensu-client and i was able to delete.  Is that a bug or we are not supposed to delete the proxy client? Thanks again for the help and fast reply.

**Comment by cwjohnston** [comment]
@calvinx408 glad to hear that you were able to mitigate the problem with configuration changes. 

The expectation is that proxy clients can be deleted via the API just like any other client. If you find that this isn't so, will you please open an issue specific to that behavior including steps to reproduce? Thanks!

**Comment by calvinx408** [comment]
I have 20 host that still have keepalive and 2-3 keep going off every hour and recovering. The keepalive queue show messages/messages unacknowledge at 20 and quickly to zero. The results queue are always at zero. Any ideas? 

I was not able to re-produce the deleting problem i had. It's pretty weird, but i'm glad that is resolved. The keepalive is pretty annoying though.

**Comment by calvinx408** [comment]
i got my problem resolved.  I switched keepalive to false for all linux machines, but my windows machine still had it.  The windows machine kept flapping even though NTP was correct.  I split the sensu cluster to reduce the number of queues, but my windows machines was still flapping. i changed sensu-handler.rb default occurrences from 1 to 3 and my flapping issues are gone. I could have changed occurrences in keepalive in client.cfg, but it would have taken longer.
