### ISSUE TITLE
Possible feature regression: new silenced API for clients

### ISSUE THREAD

**Issue by cgeers** [sensu/sensu#1453]
I've been reviewing the new silenced API documentation and code in sensu core, and I believe I have found a feature regression.  I do not see a way to support a client level silence.  With the stash & path implementation of silencing, this is a feature we use extensively.

## Context
I'd like to silence a named client regardless of what it is subscribed to or checks it has.

## Your Environment
0.26.X

## Expected Behavior
I'd like to silence a client by silencing any event it submits, including the keepalive

## Current Behavior
Only subscriptions and/or checks can be silenced

## Possible Solution
On the API side, for creation, I'd image the POST to /silenced will accept a new key named `client`.  The behavior would add to the existing behavior as follows:

* if only `client` is specified, then all checks submitted by that client are silenced
* if `client` and `check` are specified, then only an event from that named check, on that named client are silenced
* all other behavior regarding `subscription` and `check` keys remain the same

For GET, I'm not sure if it makes more sense to introduce a new endpoint similar to `/silenced/checks`, say `/silenced/clients`, or something else.

On the Server side, the code [here](https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L447-L449) seems to govern what events are considered to be silenced.  I'd like to add `silence:*:#{client_name}` and `silence:*:#{client_name}/#{check_name}`

**Comment by cwjohnston** [comment]
Hi @cgeers,

I think you're describing functionality that we have implemented but apparently not sufficiently documented. In reviewing our documentation for the `/silenced` API it looks like we lack an explicit example of silencing a client, so perhaps adding that will be helpful for others facing the same question.

Sensu 0.26 automatically adds a per-client subscription for `client:#{client.name}`. This is the mechanism by which silencing all events for a particular client is implemented with the `/silenced` API. 

Here's an example, assuming your API process is listening on localhost port 4567:

``` bash
$ curl -s -i -X POST \
-H 'Content-Type: application/json' \
-d '{"subscription": "client:my-sensu-client"}' \
http://127.0.0.1:4567/silenced

HTTP/1.1 201 Created
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Connection: close
Content-length: 0

$ curl -s http://127.0.0.1:4567/silenced
[
  {
    "id": "client:my-sensu-client:*",
    "subscription": "client:my-sensu-client",
    "check": null,
    "reason": null,
    "creator": null,
    "expire_on_resolve": false,
    "expire": -1
  }
]
```

With this silencing entry in place, you should be able to observe that events for this client, visible via the API or server logs, contain attributes indicating `"silenced": true` and `"silenced_by": ["client:my-sensu-client:*"]`

**Comment by cgeers** [comment]
Hi @cwjohnston 

Thank you for the prompt response.  I see the subscription code you're referring to [here](https://github.com/sensu/sensu-settings/commit/f831c3817552be59c7fcd2f6f3119f7f772e0378#diff-05f7aa4e7392adcf6c5c2e657f22c50cR183). This is great news, as I have been wanting to his automatic subscription functionality for different reasons.

This should work just fine for my needs.  Thanks!
