### ISSUE TITLE
Sensu 0.26.x  - armv6 openssl library issue

### ISSUE THREAD

**Issue by MarcinU** [sensu/sensu#1459]
Hello,
After updating sensu on my RPI 1 devices from 0.25.7 to 0.26.1 I get a openssl library error in the embedded ruby package: 

`Sep 24 16:56:24 jh sensu-client[8458]: Starting sensu-client:/opt/sensu/embedded/lib/ruby/2.3.0/armv7l-linux-eabihf/openssl.so: [BUG] Illegal instruction at 0xb6509cc4
Sep 24 16:56:24 jh sensu-client[8458]: ruby 2.3.0p0 (2015-12-25 revision 53290) [armv7l-linux-eabihf]`

I had no issues on other architectures. 

[Full log](http://pastebin.com/QH8QsXwK)

When I downgrade to 0.25.7 it works without any problems. 

Did someone else encounter any problems? I use OpenSSL 1.0.1t

**Comment by amdprophet** [comment]
I'll see if I can replicate this. What distribution are you running?

**Comment by MarcinU** [comment]
Debian 8.0 
Linux 4.4.13+ #894 Mon Jun 13 12:43:26 BST 2016 armv6l GNU/Linux

**Comment by amdprophet** [comment]
I've run into a different but related issue when trying to run 0.26.3 on a RPI 1. I'm working towards a fix.

**Comment by amdprophet** [comment]
We've recently migrated to a new build pipeline which does not currently support non-i386/amd64 architectures. I am working towards using qemu to build Sensu packages for arm, mips, powerpc, etc. as we currently cannot release new packages for these platforms.

**Comment by amdprophet** [comment]
I'm actually going to close this ticket out as it's related to the build environment in the previous build pipeline. Support for other platforms including armhf will be tracked here: https://github.com/sensu/sensu-omnibus/issues/82
