### ISSUE TITLE
An old failure never ends

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1461]
Due to a local misconfiguration, the simple check performed by the `sensu-plugins-mailq` was failing -- the Sendmail's `mailq` could not run.

Unfortunately, even after the misconfiguration was rectified, Uchiwa continues to claim there is a problem with the check:
![uchiwa-mailq-check](https://cloud.githubusercontent.com/assets/1486340/18934760/a038fa10-85a9-11e6-80dd-8830c35d378f.png)

Looking in the `sensu-client.log` on the host, I see the following _two_ records -- a warn and an info -- every time the check is attempted:
```json
{"timestamp":"2016-09-28T18:28:27.691911-0400","level":"warn","message":"previous check command execution in progress","check":{"command":"check-mailq.rb -w 5 -c 10","name":"mailq","issued":1475101707}}
{"timestamp":"2016-09-28T18:28:27.777854-0400","level":"info","message":"publishing check result","payload":{"client":"dev12","check":{"command":"check-mailq.rb -w 5 -c 10","name":"mailq","issued":1475101707,"executed":1475101707,"duration":0.086,"output":"CheckMailQueue OK: Mail queue is empty\n","status":0}}}
```
It would seem, an unexpected exit status of an _earlier_ check causes it to, somehow, remain stuck in the "execution in progress" state. And yet, it is still attempted again. And yet, the success of that attempt does not clear the past failure(s).

Just in case, I checked for stuck "check"-processes with `ps` -- there aren't any.

**Comment by mariusv** [comment]
Check the RabbitMQ queue also check the redis DB for that host..had the same issue few weeks back and was caused by us doing a failure test which fired 2k+ alerts and few of them got stuck in alerting state till I cleared the queue. This has been causes by low memory/CPU on the sensu server.

**Comment by UnitedMarsupials** [comment]
There is no RabbitMQ involved in our setup -- we use Redis directly. I found that explicitly clearing the supposedly recent event through Uchiwa dashboard new ones from appearing again. Seems like  an Uchiwa bug.

However, the `sensu-client.log` on the host is still showing repeated check-requests milliseconds apart:
```json
{"timestamp":"2016-09-29T10:47:31.520544-0400","level":"info","message":"received check request","check":{"command":"check-mailq.rb -w 5 -c 10","name":"mailq","issued":1475160451}}
{"timestamp":"2016-09-29T10:47:31.520907-0400","level":"info","message":"received check request","check":{"command":"check-mailq.rb -w 5 -c 10","name":"mailq","issued":1475160451}}
{"timestamp":"2016-09-29T10:47:31.520946-0400","level":"warn","message":"previous check command execution in progress","check":{"command":"check-mailq.rb -w 5 -c 10","name":"mailq","issued":1475160451}}
{"timestamp":"2016-09-29T10:47:31.521953-0400","level":"info","message":"received check request","check":{"command":"check-mailq.rb -w 5 -c 10","name":"mailq","issued":1475160451}}
{"timestamp":"2016-09-29T10:47:31.522005-0400","level":"warn","message":"previous check command execution in progress","check":{"command":"check-mailq.rb -w 5 -c 10","name":"mailq","issued":1475160451}}
```
I'll file two separate bug-reports instead of this one...
