### ISSUE TITLE
Retain the reasons for a particular check-request

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1469]
Some of the checks can be involved and heavy, but even the light ones could make think of a DOS-attack, when requested _frequently_ (see #1462, for example).

In order to be able to track/investigate/account for check-requests, information explaining _why_ a particular check was requested is necessary. These data, if available, should also be copied into the check's results.

In particular, when checks are triggered manually -- via Uchiwa -- it would be most useful to have the username and/or the IP-address of the person requesting a check-run. But, as Uchiwa crew are explaining in sensu/uchiwa#547, it can not be implemented with the current Sensu...

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1578 has been merged :+1:
