### ISSUE TITLE
Sensu Server Process will not stop/restart

### ISSUE THREAD

**Issue by dcrawkstar** [sensu/sensu#1470]
The server process gets stuck after it receives the "TERM" signal.

## Expected Behavior
TERM Signal should tell EventMachine to stop_event_loop and halt the process after unsubscribing from keep alive and result queues.

## Current Behavior
The process never finishes, the in_progress queue never clears. Shutdown/restart never happens. The only way to clear the proc is to issue a "kill -9" to the proc id. Clear the pid, then start the service again.

## Possible Solution
Something in the "def complete_in_progress" is not removing the stuck events to get to 0 in the hash. Or @in_progress is forever retrying and never dumping on "TERM". 
Thoughts of adding a "--skip-complete-on-term" option?
Also, if the service is request to "STOP" aka (TERM), why would be waiting for events to finish matter; unsubscribe and kill off the service. 

## Steps to Reproduce (for bugs)
1. service sensu-server stop

## Context
$# service sensu-server stop
Timed out waiting for sensu-server to stop     [FAILED][FAILED]

## Sensu Server Log: 
{"timestamp":"2016-10-17T16:37:06.904865+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-10-17T16:37:06.904924+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-10-17T16:37:06.904967+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-10-17T16:37:06.905084+0000","level":"warn","message":"resigning as leader"}
{"timestamp":"2016-10-17T16:37:06.905150+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":0,"events":2028755}}

## Your Environment
* Sensu version(s) used: 0.26.2, 0.26.3, 0.26.4 - The issue persists in all versions
* Operating System and version: CentOS release 6.7 (Final)
* Transport and runtime versions: Redis server v=2.8.20 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=6e82beee8ef1a9bc (Redis is the Transport)

**Comment by cwjohnston** [comment]
Hi @dcrawkstar,  

With this very high number of events in progress, we need to know if you have other extensions installed in order to know where to begin. 

When the sensu-server process starts you should see log messages indicating that extensions have been loaded. By default you'll see something like this:

```
{"timestamp":"2016-10-18T21:10:49.489152+0000","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
```

The log indicates the name, type, description, etc. of each extension as it loads. The `occurrences`, `ruby_hash`, `json`, `only_check_output` and `debug` extensions ship with Sensu by default.  Any others you see loaded here are of interest to debugging this issue.

Will you please specify whether you are running any Sensu extensions?

**Comment by dcrawkstar** [comment]
@cwjohnston 
Outside of the base, I have added a custom/modified InfluxDB following the patterns described by docs. Which I literally just resolved. At the end of the `def run` in the extension

did not notice that it was expecting `yield flush_buffer, 0`
Lets close this out and I will apologize for even bringing this up :)

-Chris
