### ISSUE TITLE
Events not being marked as silenced correctly

### ISSUE THREAD

**Issue by nevins-b** [sensu/sensu#1471]
We're seeing checks with "silenced: false" in their data but we can verify that there are silences in redis which should match.

## Expected Behavior
checks should have silenced attribute set to true

## Current Behavior
Check data: 
```"check": {
  "name": "check-blarg",
  "output": "CheckWinService CRITICAL: blarg.exe is not running\r\n",
  "status": 2,
  "type": "standard",
},
"action": "create",
"silenced": false,
"silenced_by": []
}```

Redis:
```redis 127.0.0.1:6379> KEYS "silence:*:check-blarg"
1) "silence:client:client1:check-blarg"```

EDIT: I'm wondering if this is related to older client versions. It looks like newer clients include "client:hostname" in thier subscriptions.

## Possible Solution

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code or configuration to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context (e.g. links to configuration settings or log data) helps us come up with a solution that is most useful in the real world -->
This is causing events which should be silenced to generate pagerduty alerts for things which do not need to be investiaged.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Sensu version used: 0.26.4
* Operating System and version (e.g. Ubuntu 14.04): CentOS 6.8
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): rabbitmq

**Comment by mariusv** [comment]
Heya,

Seeing the same thing here too with version: `0.26.5-2`

**Comment by cwjohnston** [comment]
@mariusv @nevins-b can you please confirm that the clients in question are running sensu 0.26 or later and show a "client:$CLIENT_NAME" subscription, either in the client registry or your dashboard?

**Comment by nevins-b** [comment]
They are not, these are older clients. 

Am I correct in now thinking that the newer silence logic isn't backwards compatible with older clients?

**Comment by cwjohnston** [comment]
@nevins-b that's correct. We've just recently published a reference document for the new silencing feature at https://sensuapp.org/docs/0.26/reference/silencing.html which describes how the `client:$CLIENT_NAME` subscription is automatically added by clients running Sensu 0.26 or later.

You can also specifically configure such a subscription on older clients in order to take advantage of silencing without updating the client itself. Of course I recommend upgrading whenever possible. :)

**Comment by nevins-b** [comment]
@cwjohnston Thanks, I'll close this issue then though it may be good to mention this is in the changelog
