### ISSUE TITLE
Feature request: Subscription or tokens for proxy clients via real client

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1472]
Hello,

monitoring hundreds off network devices could be supported by more out of box approach.
Would be interesting if proxy clients could "virtually" subscribe to checks as well.
Now, there seems to be only option do define "source" attribute in the check or resulting event.
This is bit messy when handling hundreds of network devices.

Option could be to subscribe real client for the check - which is working but then when using tokens, those take data from real client and not from proxy client. If tokens could take data from proxy clients, the "command" and "source" attribute could benefit of it. At the end etc. Sensu server could be used for executing the checks itself, however the check would appear as from proxy client.
(for now, "source" field does not even support tokens)
Does this make sense to think about?

Thank you very much

**Comment by portertech** [comment]
We acknowledge the difficulties in monitoring a large number of network devices with Sensu, beyond leveraging configuration management to create the appropriate round-robin checks to monitor known devices, creating proxy clients from check executions. We are working on this problem, however, treating Sensu proxy clients as anything more than a external source identifier is not possible with how Sensu works and operates. We hope to create a document/issue soon with our proposed solution(s) to this problem.
