### ISSUE TITLE
sensu-install error on CentOS 7

### ISSUE THREAD

**Issue by adam820** [sensu/sensu#1474]
Trying to follow docs and set up Sensu on two VMs, a server/client, and a client. In both instances, they're minimal CentOS 7 installs, set up as per the Sensu docs. However, when trying to set up checks, and install a plugin via sensu-install, the download of the plugin fails with:

```
[SENSU-INSTALL] installing Sensu plugins ...
[SENSU-INSTALL] determining if Sensu gem 'sensu-plugins-process-checks' is already installed ...
false
[SENSU-INSTALL] Sensu plugin gems to be installed: ["sensu-plugins-process-checks"]
[SENSU-INSTALL] installing Sensu gem 'sensu-plugins-process-checks'
ERROR:  While executing gem ... (ArgumentError)
    IPv4 address expects 4 bytes but 0 bytes
[SENSU-INSTALL] failed to install Sensu gem 'sensu-plugins-process-checks'
[SENSU-INSTALL] you can run the sensu-install command again with --verbose for more info
[SENSU-INSTALL] please take note of any failure messages above
[SENSU-INSTALL] make sure you have build tools installed (e.g. gcc)
[SENSU-INSTALL] trying to determine the Sensu plugin homepage for sensu-plugins-process-checks ...
ERROR:  While executing gem ... (ArgumentError)
    IPv4 address expects 4 bytes but 0 bytes

```

This happens on both machines; couldn't find any similar bug-posting. Based on reading https://github.com/rubygems/rubygems/issues/1274, I applied a similar fix to the embedded ruby, by editing `host = uri.host` to `host = uri` in `/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb` . This seems to fix the problem, at least until an RPM update which wipes the change out (which I noticed today). For testing, I did switch SELinux off, but it seemed to have no effect.

## Expected Behavior
Plugins install without issue via sensu-install.

## Current Behavior
Currently, the installs bomb out with the noted error message above.

## Possible Solution
Not so much a solution, but the workaround above seems to resolve the issue until an update.

## Steps to Reproduce (for bugs)
1. Do a default install of CentOS 7, fully patch/reboot.
2. Install and config Sensu based on docs.
3. Use `sensu-install -p {PLUGIN NAME}`, hit error

## Context
As mentioned in the summary, trying to get a testing/dev environment off the ground for eval purposes.

## Your Environment
* Operating System and version (e.g. Ubuntu 14.04): **CentOS Linux release 7.2.1511 (Core)**
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): **rabbitmq-server-3.6.5-1 on erlang-R16B-03.17**

Sensu 0.26.5-2

**Comment by cwjohnston** [comment]
Hi @adam820, thanks for opening this issue. I've opened https://github.com/sensu/sensu-omnibus/issues/44 to track this in the repo where we integrate Ruby, Rubygems and so on. Once there's an upstream fix we'll be sure to pull it in.
