### ISSUE TITLE
Sensu RPM package is broken: remove + reinstall does not update directory ownership in /var/run

### ISSUE THREAD

**Issue by larsks** [sensu/sensu#1478]
If you uninstall sensu and then re-install sensu, the package will create a new `sensu` user with UID that differs from the `sensu` user created by the earlier package install.  However, the package does not update the ownership of `/var/run/sensu`, leading to this:

    # ls -ld /var/run/sensu
    drwxr-xr-x. 2 983 root 40 Oct 31 12:01 /var/run/sensu/

And ultimately this:

    {"timestamp":"2016-10-31T12:09:33.651781-0400","level":"fatal","message":"could not write to pid file","pid_file":"/var/run/sensu/sensu-api.pid"}

## Expected Behavior

I expect to be able to successfully start sensu services after re-installing the package.

## Current Behavior

See above.

## Possible Solution

The package should remove `/var/run/sensu` when the package is removed.  The directory will be re-created with correct permissions when the service starts.

## Steps to Reproduce (for bugs)

1. Install, configure, and start sensu-server and sensu-api
2. Remove sensu (`yum remove sensu`)
3. Reinstall sensu (`yum install sensu`)
4. Attempt to start `sensu-api` (`systemctl start sensu-api`).

## Your Environment

* Sensu version used: sensu-0.26.5-2.x86_64
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by amdprophet** [comment]
This is fixed and will be available in the upcoming 0.27 release. The new package scripts run `chown` against the pid directory with each postinstall: https://github.com/sensu/sensu-omnibus/blob/master/package-scripts/sensu/postinst
