### ISSUE TITLE
weird sensu statuscode and history data

### ISSUE THREAD

**Issue by cabecada** [sensu/sensu#1480]
for certain check results, i see weird data and it is screwing up the entire handler action

![image](https://cloud.githubusercontent.com/assets/20220560/19906692/cc9b8790-a0a1-11e6-9766-7f284b5bd058.png)

sensu version 0.26.0 (windows 2012R2)
and this is only on windows machines.

**Comment by portertech** [comment]
@cabecada is the system clock on the Windows machines correct?

**Comment by cabecada** [comment]
yes, system clock is all good.
also i run the check manually and it is giving correct status code.

we have had vague issues with multiple sensu clients (0.21.1 and 0.26.0) getting installed on windows machines (sensu-puppet) while trying to do an update to 0.26.0. not sure how windows even allows that for same folder path.
we are trying to cleanup multiple windows and ensuring only 0.26.0 exists.

also we saw some sensu-clients timing out when they are restarted on config change etc in a puppet run, as a result the some ruby checks still keep running, and when sensu client is restarted no noitfy we have another list of checks rerun, as a result we have two instances of same check running on windows. this may/may not be the reason, but windows 0.26.0 gave us nightmare for sure.

 we do not see these issues on linux machines.

**Comment by portertech** [comment]
The upcoming Sensu 0.27 MSI package has significant changes & improvements, hopefully addressing this issue.

**Comment by portertech** [comment]
It seems that the exit status is valid, http://stackoverflow.com/questions/25153262/getting-the-the-application-failed-to-initialize-properly-3221225794-error-exe and Uchiwa or the Sensu Enterprise Dashboard displays it as a date/time value. Sensu 0.27 will hopefully fix the runtime issues while Uchiwa has already merged a fix https://github.com/sensu/uchiwa-web/pull/127.

**Comment by cabecada** [comment]
thanks @portertech. will test, but it is not reproducible, although one thing is for sure that once this issue occurs, it remains for long time.

**Comment by portertech** [comment]
Uchiwa status formatting fix has been merged. https://github.com/sensu/uchiwa-web/pull/127

**Comment by portertech** [comment]
The Sensu >= 0.27 MSI and https://github.com/sensu/uchiwa-web/pull/127 seem to have addressed these issues.
