### ISSUE TITLE
Feature Request: Bind RabbitMQ Routing Keys to Queues Created

### ISSUE THREAD

**Issue by elirei72** [sensu/sensu#1481]
When the Sensu client or server connect up to a rabbitmq instance it creates two default queues ('keepalives' and 'results') under the virtual host you create. It would be nice  to have the default binding that is does currently as well as a binding from it's exchange with the routing key of the exchange name. 

Examples:
Current - Results Exchange -> Results Queue (no Routing Key)
Added Feature - Results Exchange -> Results Queue (no Routing Key) 
and  
Results Exchange -> Results Queue ('results' routing key)

This would help facilitate third part apps connecting to the message bus to post to the needed queue. 

## Environment

* Sensu version used: 0.26.3
* Active Sensu extensions (e.g. WizardVan 0.1.0): N/a
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions: RabbitMQ 3.6.2 on Erlang 18.2

**Comment by portertech** [comment]
Is there a reason you cannot create a separate queue and just bind it to the result or keepalive exchanges for the third party service? Can you not use a Sensu transport handler to send data to the third party service? Sensu assumes that it does not share the transport with other services, beyond what the transport event handler provides.

**Comment by elirei72** [comment]
That would work. Closing ticket. Thanks
