### ISSUE TITLE
Installed plugins with gem method (embedded ruby), Sensu gives command not found

### ISSUE THREAD

**Issue by virtualdxs** [sensu/sensu#1484]
## Expected Behavior
After I `sudo /opt/sensu/embedded/bin/gem install [somePluginGem]`, I should be able to include ruby files from that gem in a check without an absolute pathname.

## Current Behavior
Check returns `sh: check-http.rb: command not found`

## Context
As far as I can tell this is the recommended way to install plugins. Am I doing something wrong?

## Your Environment

* Sensu version used: 0.26.1
* Operating System and version (e.g. Ubuntu 14.04): Arch Linux
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Redis 3.2.5

**Comment by virtualdxs** [comment]
When I specify the absolute path, it tries to execute with system ruby because of `#!/usr/bin/env ruby`. When I install ruby, it complains with:

    /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-plugin/check/cli (LoadError) from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-http-1.0.0/bin/check-http.rb:42:in `<main>'

**Comment by walterj89** [comment]
If I remember correctly there is an environment variable that specifies where to Ruby binary is and the PATH to look for executables.  This is normally set when the Sensu service starts.  If you are starting Sensu with a SystemD init script or just as a process the enviroment variables may not be set correctly.
http://serverfault.com/questions/66363/environment-variables-of-a-running-process-on-unix

**Comment by virtualdxs** [comment]
That fixed it! Thanks! Closing because issue resolved. I just have one further question: Why is it that despite the plugins' bin folders not being in $PATH you can still run them directly as checks?
