### ISSUE TITLE
Missing "Date" in repository Release files

### ISSUE THREAD

**Issue by mheiland** [sensu/sensu#1485]
When using the Sensu Core Debian repository at https://sensu.global.ssl.fastly.net, newer apt versions complain about missing "Date" information at the release file. This seems to be an issue with various repositories lately as distros start to upgrade "apt", for example with Debian Stretch. I understand that his requires a minor change/fix on the repo side.

To reproduce, install Sensu on Debian Stretch, which will become stable as soon as its done.
$ apt-get update
... 
Ign:3 https://sensu.global.ssl.fastly.net/apt sensu InRelease 
Hit:4 https://sensu.global.ssl.fastly.net/apt sensu Release
Get:6 https://sensu.global.ssl.fastly.net/apt sensu Release.gpg [473 B]
...
Reading package lists... Done
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/sensu.global.ssl.fastly.net_apt_dists_sensu_Release
W: The repository 'https://sensu.global.ssl.fastly.net/apt sensu Release' provides only weak security information.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by portertech** [comment]
We plan to overhaul the Sensu repositories in order to address this and many other of the repository related issues. A possibility is a move to packagecloud.

**Comment by matelukas** [comment]
I am seeing this issue on Ubuntu 16.04 when trying to install sensu packages.

```
~# apt-get update
Hit:1 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                     
Ign:3 http://repositories.sensuapp.org/apt sensu InRelease                                                      
Get:4 http://repositories.sensuapp.org/apt sensu Release [10.1 kB]                                                                    
Get:5 http://repositories.sensuapp.org/apt sensu Release.gpg [473 B]                                                                            
Get:6 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                  
Get:7 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                      
Fetched 317 kB in 1s (239 kB/s)                      
Reading package lists... Done
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repositories.sensuapp.org_apt_dists_sensu_Release
E: Failed to fetch http://repositories.sensuapp.org/apt/dists/sensu/Release  Invalid 'Valid-Until' entry in Release file /var/lib/apt/lists/partial/repositories.sensuapp.org_apt_dists_sensu_Release
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Is there any chance that sensu release files will be updated to sort out this issue ?

Thanks.

**Comment by portertech** [comment]
@matelukas the repository has just been upgraded, should be good to go :+1:

**Comment by mheiland** [comment]
@portertech Thanks a lot, can confirm that it works with Debian Stretch.

**Comment by matelukas** [comment]
@portertech It works on Ubuntu 16.04.

Thanks !
