### ISSUE TITLE
Bad config file causes sensu-client to not start

### ISSUE THREAD

**Issue by dwagon** [sensu/sensu#1487]
If there is a config file that the sensu client cannot read (a dangling symlink in our case) then the client doesn't start instead of starting and ignoring that config file.

## Expected Behavior
I would expect that the client would ignore unreadable config files. 
Log them as failures but try and keep going if it can.
Bad contents of config files should be fatal, but not the readability of the config files themselves.

## Current Behavior
Currently an unreadable config file is a fatal error
```
{"timestamp":"...","level":"fatal","message":"config file does not exist or is not readable","file":"/etc/sensu/conf.d/checks/foo.json"}
```

In our case the config file is symlinked to a location that doesn't exist.

## Possible Solution
Make an unreadable config file a warning not a fatal error.

## Steps to Reproduce (for bugs)
1. Symlink a config file in the conf.d directory to somewhere that doesn't exist
2. Restart sensu-client

## Context
Having this as a fatal error meant that a minor change in our config took out our monitoring. All the rest of the configs were perfectly fine.

## Your Environment
* Sensu version used: sensu-0.26
* Operating System and version (e.g. Ubuntu 14.04): CentOS 5.8

**Comment by portertech** [comment]
Hello @dwagon,

Sensu makes the choice to stop in the event of configuration loading errors, to ensure an expected run state. 

The recent changes to configuration validation and handling were in response to the discussion on this topic @ https://github.com/sensu/sensu/issues/1244

Sean.
