### ISSUE TITLE
Deregistration Event "Status" code is 1  (WARN)

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu/sensu#1491]
## Expected Behavior

Sensu client Deregistration generate event with Status 1, which is WARN exit status.  I think this is inaccurate representation of true nature of event state.

## Current Behavior

{"timestamp":"2016-10-25T23:10:55.076633+0530","level":"info","message":"publishing check result","payload":{"client":"myserver","check":{"handler":"deregistration","interval":1,"name":"deregistration","output":"client initiated deregistration","status":1,"issued":1477417255,"executed":1477417255}}}

## Possible Solution
I am not sure what would be the correct exit status, could be 3 (UNKNOW) or any arbitrary status number. 

## Steps to Reproduce (for bugs)
Deregister a client, check client logs.

## Context
Status of Warning for deregister events.

## Your Environment

* Sensu version used: 0.26.3
* Operating System and version: Ubuntu 14.04
* Transport and runtime versions: RabbitMQ 3.6.5

**Comment by portertech** [comment]
For the purpose of client deregistration, the meaning of the event check status is arbitrary (non-zero). Using the well define/understood status 1 seems more appropriate. Are you having troubles with deregistration because of the current event check status, or is this just a preference?

**Comment by jaykumar-jnpr** [comment]
In my Sensu environment, I am filtering all WARN events due to operational requirement. Now that causes filtering of all reregistration events as well.  Which to me don't fall into category of warning events.

**Comment by jaykumar-jnpr** [comment]
👍 

Closing issue. This solution works.
