### ISSUE TITLE
Feature request: Allow check data to be ingested on the client socket for other hosts

### ISSUE THREAD

**Issue by CVTJNII** [sensu/sensu#1499]
In our infrastructure we have many "pseudo-clients" which represent entities in our infrastructure that do not map to a host running a Sensu client instance.  For example this could be an aggregate entity which represents a group of servers, or a cluster of microservices which provide a services but do not correlate to any specific client.  To feed this data into Sensu I currently need to queue messages into RabbitMQ directly.  This is suboptimal for several reasons:

- It requires my check to know all the Rabbit configuration settings, which includes usernames, passwords, and SSL certs
- It requires my check to know the Sensu RabbitMQ message format

It would be very nice if I could send a message to the client socket with a message for a different client.  This is currently blocked by sensu-client hard setting the client in the message: [/lib/sensu/client/socket.rb#L147](https://github.com/sensu/sensu/blob/caf798528af9e9cab1e1d05ea7059d6c165b60e5/lib/sensu/client/socket.rb#L147)

Looking at the RabbitMQ payload I'm not sure how to best address this, as the format appears to be:

```json
{
   "client": "Client name in question",
   "check": "validated socket payload"
}
```

As the field in question is a level above the current data structure accepted on the socket it makes this a difficult proposition.  As the socket supports commands like 'ping' perhaps a command that specifies the payload is the full message to be verified and sent to the transport, not just the check block?  That will allow this flexibility while allowing bare JSON to behave the same for backwards compatibility.  Please let me know your opinions and if Sensu is open to this approach, I'd like to discuss before starting a PR.  Thanks.

EDIT: Been coding too much Ruby, used single quotes in my JSON

**Comment by cwjohnston** [comment]
Hi @CVTJNII, thanks for opening this issue. If I understand your request correctly, I believe that [proxy client] (https://sensuapp.org/docs/latest/reference/clients.html#proxy-clients) functionality -- already present in Sensu -- provides what you are describing. By specifying a `source` attribute in the check result sent to the Sensu client socket, those results will be correlated with the specified `source`.

Please have a look at the client reference documentation linked above and let me know if this doesn't meet your needs?

**Comment by CVTJNII** [comment]
Oh, so it is.  Sorry I missed that.  One thing I'm not clear on from that, though, is where is that payload sent?  The Sensu API?

**Comment by CVTJNII** [comment]
I'm sorry, but I'm still not clear.  When I send the following payload to the socket:

```bash
echo '{"client": "sensu-docs", "check": {"name": "test", "output": "Test", "status": 0}}' | nc localhost 3030
```

Sensu logs the following error:

```
{"timestamp":"2016-11-21T17:36:08.978424+0000","level":"error","message":"failed to process check result from socket","data":"{\"client\": \"sensu-docs\", \"check\": {\"name\": \"test\", \"output\": \"Test\", \"status\": 0}}\n","error":"check name must be a string and cannot contain spaces or special characters"}```

This makes sense, as looking over the socket code in https://github.com/sensu/sensu/blob/caf798528af9e9cab1e1d05ea7059d6c165b60e5/lib/sensu/client/socket.rb#L200-L219 I don't see any handling of proxy clients, just the normal socket handling.  This error is coming from https://github.com/sensu/sensu/blob/caf798528af9e9cab1e1d05ea7059d6c165b60e5/lib/sensu/client/socket.rb#L122-L124 which fails as the name key isn't set in the proxy payload base scope.

So I'm not clear at all on how to use Proxy clients, please advise.

**Comment by CVTJNII** [comment]
I was reading but not comprehending.  The "source" key in the socket payload apparently overrides the "client" key I've been referencing in the code.  The following seems to be doing what I want:

```bash
echo '{"source": "test", "name": "test", "ttl": 30, "output": "Test", "status": 0}' | nc localhost 3030
```

Thanks for the pointer!
