### ISSUE TITLE
API /settings endpoint

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu#1503]
## Expected Behavior

HTTP GET against API /settings endpoint should return a JSON representation of Sensu's running configuration.

## Current Behavior

HTTP GET against API /settings endpoint returns 404

## Possible Solution

Implement /settings route, mirroring functionality implemented in #1488

## Context

#1488 provides an http API on the Sensu Client which offers a /settings endpoint, guarded by Basic Auth, for viewing the client's running settings. This HTTP API endpoint provides a useful alternative to the `--print_config` command line option, as its output indicates the current running state.

I think an analog for this client feature should be added to the sensu-api service in the interests of feature parity and increasing the ease of accessing running settings for our support team.

**Comment by portertech** [comment]
I would like to see the client HTTP API and the Sensu API sharing the same route modules when possible.

**Comment by portertech** [comment]
It looks like sharing is not a possibility, however, the client HTTP socket code structure should match that of the API https://github.com/sensu/sensu/tree/master/lib/sensu/api/routes

**Comment by portertech** [comment]
#1626 implements this :+1:
