### ISSUE TITLE
Sensu-Server crashes on `split': invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by mehmood-007** [sensu/sensu#1504]
## Current Behavior

Sensu-Server Crashes 

## Possible Solution

 "redis": {
    "password": "xxxxxxx",
    "master": "xxxxx",
    "sentinels": [
      {
        "host": "10.80.2.1",
        "port": 26379,
        "auto_reconnect": true,
        "reconnect_on_error": true
      },
      {
        "host": "10.80.2.2",
        "port": 26379,
        "auto_reconnect": true,
        "reconnect_on_error": true
      },
      {
        "host": "10.80.2.3",
        "port": 26379,
        "auto_reconnect": true,
        "reconnect_on_error": true
      }
    ],
    "auto_reconnect": true,
    "reconnect_on_error": true
  },

## Context

#Logs:
{"timestamp":"2016-11-23T02:54:00.693425+0100","level":"warn","message":"reconnecting to redis"}
#Backtrace
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.3/lib/sensu/server/process.rb:322:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.3/lib/sensu/server/process.rb:322:in `truncate_check_output'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.3/lib/sensu/server/process.rb:348:in `store_check_result'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.3/lib/sensu/server/process.rb:659:in `block in process_check_result'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.3/lib/sensu/server/process.rb:612:in `block in retrieve_client'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis/client.rb:315:in `dispatch_response'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis/client.rb:337:in `parse_response_line'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis/client.rb:365:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.3/lib/sensu/server/process.rb:31:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.3/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'
		

## Your Environment

* Sensu version used:
* Operating System and version (e.g. Centos 7.2):
* Transport and runtime versions (e.g. RabbitMQ 3.6.5 on Erlang 19):

**Comment by portertech** [comment]
@mehmood-007 thank you for reporting this issue :+1: I have put together a fix in https://github.com/sensu/sensu/pull/1505

**Comment by portertech** [comment]
The "reconnecting to redis" is a red herring.
