### ISSUE TITLE
Sensu has no defaults around client check execution hard timeout

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1506]
When running checks on client, by default, checks can execute forever without a forced stoppage.   This leads to this issue, where sensu-client cannot be killed in a sane or consistent manner:
- https://github.com/sensu/sensu/issues/1052

We ran into several clients with children that had been running for weeks/months.  At some point, someone tried killing the parent pids on each server via kill -9.  As this didn't kill the transport socket handle, and the child processes are forks of the parent -- the children took over that socket once the parents were killed.  Trying to start a new Sensu client has a port conflict from the orphaned processes.

This has led to being unable to just run "service sensu-client restart" or "service sensu-client stop".

We are currently adding in hard timeouts to each check, but doing this across many checks is a bit painful.  It would be awesome if there was some global default set at the client.

Thus far, we have only seen this behavior for checks written as shell and python commands.

## Expected Behavior
Sensu check execution should be force-killed after some default time,   
Sensu client should honor the MAX_EXECUTION_TIME and die off after that interval.

## Current Behavior
Sensu checks, by default, can runaway forever.

## Possible Solution
Add a default timeout for child process spawns to the Sensu client check execution, if not already set. Maybe 1 minute or even 5 minutes would suffice.  This would be a breaking change for checks that currently take longer than that default.

Another option might be to set a global default timeout per client, such as via the json config "default_check_timeout": "300".  This would help, at the cost of having to configure each client with some default -- but would also be easier for us, than having to re-tool each check definition.

## Context
This prevents admins from being able to stop the Sensu server if the child process becomes wedged.

Relevant code in sensu project where timeout is used, if set in the check definition:
https://github.com/sensu/sensu/blob/bb91fea7797d2402349a3e86b7cd3f43b78621c8/lib/sensu/client/process.rb#L151

Relevant code in sensu-spawn where timeout is used, if set in options:
https://github.com/sensu/sensu/blob/bb91fea7797d2402349a3e86b7cd3f43b78621c8/lib/sensu/client/process.rb#L151

An example where we have hung up child processing.

Log where client unable to stop, as it is waiting on child proc to finish work:
```
{"timestamp":"2016-11-23T10:13:41.524739-0700","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-11-23T10:13:41.524961-0700","level":"warn","message":"stopping"}
{"timestamp":"2016-11-23T10:13:41.525324-0700","level":"info","message":"completing checks in progress","checks_in_progress":["nova_host_aggregates","glance_api_map"]}
{"timestamp":"2016-11-23T10:13:48.145813-0700","level":"info","message":"publishing check result","payload":{"client":"someserver.example.com","check":{"name":"glance_api_map","issued":1479921215,"command":"n=0; until [ $n -ge 2 ]; do /etc/sensu/conf.d/team/plugins/check_glance params 1 2>/dev/null; x=$?; if [ $x -eq 0 ]; then break; fi; n=$[$n+1]; done; exit $x","executed":1479921215,"duration":12.731,"output":"OK - more than 1 images found\n","status":0}}}
{"timestamp":"2016-11-23T10:13:51.201999-0700","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-11-23T10:13:51.202300-0700","level":"warn","message":"stopping"}
{"timestamp":"2016-11-23T10:13:51.202555-0700","level":"info","message":"completing checks in progress","checks_in_progress":["nova_host_aggregates"]}
{"timestamp":"2016-11-23T10:13:58.751836-0700","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-11-23T10:13:58.752164-0700","level":"warn","message":"stopping"}
{"timestamp":"2016-11-23T10:13:58.752505-0700","level":"info","message":"completing checks in progress","checks_in_progress":["nova_host_aggregates"]}
{"timestamp":"2016-11-23T10:14:09.503163-0700","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-11-23T10:14:09.503476-0700","level":"warn","message":"stopping"}
{"timestamp":"2016-11-23T10:14:09.503715-0700","level":"info","message":"completing checks in progress","checks_in_progress":["nova_host_aggregates"]}
{"timestamp":"2016-11-23T10:14:22.491986-0700","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-11-23T10:14:22.492628-0700","level":"warn","message":"stopping"}
{"timestamp":"2016-11-23T10:14:22.493085-0700","level":"info","message":"completing checks in progress","checks_in_progress":["nova_host_aggregates"]}
```
Process listing:
```
sensu      3959  0.1  0.0 1621776 27780 ?       Sl   Jul01 274:40 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sens /sensu-client.pid -l /var/log/sensu/sensu-client.log -L info
sensu     24378  0.0  0.0 113120   540 ?        S    Jul18   0:00  \_ sh -c /etc/sensu/conf.d/team/plugins/check_nova_aggregates xxxl
sensu     24379  0.0  0.0 259140  2620 ?        S    Jul18   0:00      \_ python /etc/sensu/conf.d/team/plugins/check_nova_aggregates xxxx
```
Child pid 24379 is hung on doing a read from a https socket.

## Your Environment
- Sensu 0.20.3

**Comment by portertech** [comment]
Hey @xyntrix,

Introducing a default command execution timeout is not a compelling solution, as it would mean a breaking change for users, as you are aware. Not a fan of this.

A global configurable default would be useful, but we have avoided global definition attribute defaults in several cases, as it breaks Sensu's explicit configuration definition model. There's a fence and we're hanging off of the side.

Are you not able to set a default timeout value in your CM tool that's driving Sensu? This is the most common approach. Also, it's time to upgrade! :P 

Sean.

**Comment by xyntrix** [comment]
Good news!  We are on latest now. :)

We have our own validation framework (sensu-validatior) that we use to warn/error along our CI/CD path for deploying Sensu config updates -- we will continue to bake this in from that angle.  Thanks for the response!  Closing as design change has been discussed -- if further feature is desired, we can submit a PR for review.
