### ISSUE TITLE
Sensu remained silent during Redis cluster failure

### ISSUE THREAD

**Issue by warmfusion** [sensu/sensu#1507]
# Scenario

## Environment

* Sensu-server 0.26. 5 on 4 servers
* Redis 2.8.17 on 3 servers
* Redis-Sentinel configured to balance requests
    * Sensu Server configured to use sentinels

## Incident

Redis Cluster was restarted concurrently, causing the sentinels and redis nodes to lose quorum and revert to read-only states. The redis-sentinel was unable to promote any nodes to master.

# Impact

No Sensu-servers were able to write any changes to the redis nodes, filling the logs with the following message;

```
{"timestamp":"2016-11-25T05:00:00.025415+0000","level":"error","message":"redis connection error","error":"redis returned error code: READONLY You can't write against a read only slave."}
```

Meanwhile, *NO ALERTS* were emitted from the servers, resulting in a multi-hour outage before we spotted sensu being 'a little too quiet'

All status checks and even keepalives were showing stale results, but still reported as 'ok'.

## Note

We run checks for the sensu-servers being operational as a 'watchdog', we also check our RabbitMQ queue sizes to ensure messages are being consumed. However, both of these were showing as OK as the servers were reading messages, trying to write to redis, failing, and then throwing away messages and continuing.

# Query

* Are there methods to check if sensu's connection to Redis is operational?
* Can Sensu have an 'emergency handler' that fires if it can't handle events
* Are there other options for preventing this kind of failure mode occuring again?

**Comment by portertech** [comment]
@warmfusion the Sensu API /health and /info endpoints provide the information needed to monitor the Sensu installation as a whole - https://sensuapp.org/docs/0.26/api/health-and-info-api.html. Users commonly use something like Pingdom to monitor the monitor in this fashion.

**Comment by portertech** [comment]
As Sensu is a distributed system, a combination of monitoring the Sensu server logs for "redis connection error" and monitoring via the Sensu API is recommended. Sensu servers immediately go into a paused state when they encounter a Redis error and stop consuming/processing check results and events. I am reluctant to have individual Sensu servers alerting on their connection states, I could see regular incidents causing more noise vs signal.

**Comment by warmfusion** [comment]
Sounds sensible - We're building another sensu-cluster[-cluster] in the office to deal with a new DC topology so i'll see if we can adjust how we monitor the services a bit more.

Thanks

**Comment by lobeck** [comment]
Can't sensu to a reconnect for this case? We're using consul, so our redis host is `sensu-redis-master.query.consul` which *always* points to the correct master node. I had hoped, that sensu would reconnect if it gets that readonly message.

**Comment by portertech** [comment]
@lobeck it should reconnect https://github.com/sensu/sensu/commit/021049a4d928ec4bc436f52f820a4a16d95705b4

**Comment by lobeck** [comment]
@portertech doesn't look like it (sensu 0.29.0-7)

{"timestamp":"2017-04-27T16:28:59.713241+0000","level":"error","message":"redis connection error","error":"redis returned error code: READONLY You can't write against a read only slave."}
    {"timestamp":"2017-04-27T16:28:59.713311+0000","level":"error","message":"redis connection error","error":"redis returned error code: READONLY You can't write against a read only slave."}
    {"timestamp":"2017-04-27T16:28:59.713341+0000","level":"error","message":"redis connection error","error":"redis returned error code: READONLY You can't write against a read only slave."}
{"timestamp":"2017-04-27T16:29:01.884637+0000","level":"info","message":"api response","request":{"remote_address":"127.0.0.1","user_agent":"Ruby","method":"GET","uri":"/    info","query_string":null,"body":""},"status":200,"content_length":292,"time":0.002}
    {"timestamp":"2017-04-27T16:29:01.885108+0000","level":"error","message":"redis connection error","error":"redis returned error code: READONLY You can't write against a read only slave."}
    {"timestamp":"2017-04-27T16:29:01.885168+0000","level":"error","message":"redis connection error","error":"redis returned error code: READONLY You can't write against a read only slave."}
    {"timestamp":"2017-04-27T16:29:01.885199+0000","level":"error","message":"redis connection error","error":"redis returned error code: READONLY You can't write against a read only slave."}

Hasn't reconnected since 13:11, so 3 hours.

Will take a look into this and create another bug/PR if necessary.
