### ISSUE TITLE
New build sensu, start a problem.

### ISSUE THREAD

**Issue by NotesFire** [sensu/sensu#1510]
#  hey,bro:
    The new build a sensu, now unable to start, the log error as follows
"loading config file","file":"/etc/sensu/config.json"}
"loading config files from directory","directory":"/etc/sensu/conf.d"}
"warn","message":"loading config file","file":"/etc/sensu/conf.d/my_filter.json"}
"/etc/sensu/conf.d/my_filter.json","changes":{"filters":{"recurrence":[null,{"attributes":{"occurrences":"eval: value > 5"}}]}}}
loading config file","file":"/etc/sensu/conf.d/my_handler.json"}
"config file applied changes","file":"/etc/sensu/conf.d/my_handler.json","changes":{"handlers":{"file":[null,{"type":"pipe","command":"/etc/sensu/plugins/event-file.rb","timeout":10,"filter":"recurrence"}]}}}
"loading config file","file":"/etc/sensu/conf.d/rabbitmq.json"}
"config file applied changes","file":"/etc/sensu/conf.d/rabbitmq.json","changes":{"rabbitmq":[null,{"host":"127.0.0.1","vhost":"/ sensu","user":"sensu","password":"REDACTED"}]}}
"loading config file","file":"/etc/sensu/conf.d/mem_check.json"}
"config file applied changes","file":"/etc/sensu/conf.d/mem_check.json","changes":
“”checks":"/etc/sensu/plugins/check-mem.sh -w 102400 -c 10240 -p","subscribers":["production","test"],"interval":10,"handler":"file"}]}}}
"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
"configuring sensu spawn","settings":{"limit":12}}
"could not write to pid file","pid_file":"/var/run/sensu/sensu-server.pid"}
"SENSU NOT RUNNING!"}

I know I have a problem with the configuration file, but not sure where it is.
thx,very much.

**Comment by cabecada** [comment]
"could not write to pid file","pid_file":"/var/run/sensu/sensu-server.pid"}
..
checks perms  on /var/run/sensu/sensu-server.pid and verify if sensu user can write to this file.

**Comment by NotesFire** [comment]
thank you,solved.
