### ISSUE TITLE
sensu-client consuming a lot of memory

### ISSUE THREAD

**Issue by fragpit** [sensu/sensu#1515]
Hi guys,

Is it normal that sensu-client consumes 1.2-1.6 GiB of virtual memory?

root       5166  5.8  0.5 1227936 22264 ?       Sl   15:52   0:01 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client

Env:
Linux  3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 04:13:05 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux
Scientific Linux release 7.2 (Nitrogen)

sensu-client --version
0.26.5

**Comment by portertech** [comment]
Hi @fragpit, your sensu-client RSS is ~ 21MB, the virtual memory is allocated but not necessarily representing real memory used. Linux memory management ¯\_(ツ)_/¯

**Comment by fragpit** [comment]
ok, thanks. seems that there is too much overhead for sensu-client process in my environment.
