### ISSUE TITLE
Windows Client - Detected TCP Connection Failure 

### ISSUE THREAD

**Issue by kwright5150** [sensu/sensu#1517]
Hello I have a Sensu server (Ubuntu 14.04) and a Sensu client (different Ubuntu 14.04) set up in a test environment. I am trying to connect Windows clients to RabbitMQ running on the Sensu server. I have tested the latest Windows build (26.3-1) on Windows 7 32-bit, 64-bit, and Windows server 2008.

I have:

client.json
rabbitmq.json
transport.json - RabbitMQ as the transport.

in the C:\opt\sensu\conf.d directory.

I can verify that I have communication from my Ubuntu Sensu client via RabbitMQ logs, Uchiwa and so on, so I know Rabbit is set up right.

There are no firewalls included in this set up, and SSL is not enabled at the moment either. 

I would like to know if I am missing something here with the Windows client. Any help or feedback is appreciated.

**Comment by portertech** [comment]
@kwright5150 RabbitMQ "TCP Connection Failure" can identify one of many things, e.g. unable to reach or authentication. Sensu 0.27 is expected to drop any day now, it has better RabbitMQ/transport logging capabilities, hopefully it will shed light on this issue. You may be able to find help via the IRC channel on Freenode #sensu, just be sure to stick around for an answer (asynchronous).

**Comment by cwjohnston** [comment]
0.27.0-1 is in the unstable repositories, it adds better logging around connection issues and will soon be promoted to stable. Check out http://repositories.sensuapp.org/msi-unstable/2012r2/sensu-0.27.0-1-x64.msi for the unstable MSI.
