### ISSUE TITLE
sensu-install doesn't work in windows

### ISSUE THREAD

**Issue by jjasghar** [sensu/sensu#1520]
It seems that attempting to install `process-checks` it fails.

![image](https://cloud.githubusercontent.com/assets/810824/21195911/61a7b5be-c1fb-11e6-92ec-31f77030f7e9.png)

**Comment by portertech** [comment]
@jjasghar powershell?

**Comment by jjasghar** [comment]
Yep, i was running it in powershell cli.

**Comment by jjasghar** [comment]
Ran it in `cmd.exe` too

![image](https://cloud.githubusercontent.com/assets/810824/21241543/b39e1e32-c2d5-11e6-8b11-fb191c4fa854.png)

**Comment by cwjohnston** [comment]
I believe this is fixed in 0.27.0 which is now available via our unstable channel: http://repositories.sensuapp.org/msi-unstable/2012r2/sensu-0.27.0-1-x64.msi

![2017-01-27 at 12 17 pm](https://cloud.githubusercontent.com/assets/148017/22384210/93c7e666-e48a-11e6-988a-50fe721cd972.png)

**Comment by jjasghar** [comment]
Awesome, I'll spin up a box and give it a shot ASAP.
