### ISSUE TITLE
curl tags except "HTTP/1.1 400 Bad Request "

### ISSUE THREAD

**Issue by phoppe93** [sensu/sensu#1521]
Hi Support Team,

i try to send tags as json via curl to localhost an got an bad request 400.

my command:

` curl -s -i -X POST -H 'Content-Type: application/json' -d '{"name":"DEV-SENSU-SensuAutoScalingGroup-1BFF5Z5Q2O2SW","launchconfigurationname":"DEV-SENSU-SensuLaunchConfiguration-11LHF61BB9S4D","subscriptions":["aws:asg","provider:asg","stack_name:DEV-SENSU"],"region":"eu-central-1","stack_id":"arn:aws:cloudformation:eu-central-1:001579709704:stack/DEV-SENSU/409bf2a0-6aac-11e6-ae89-50a68ad4f2c6","stack_name":"DEV-SENSU","desired_capacity":1,"health_check_grace_Period":600,"min_size":1,"max_size":2,"created_time":"2016-08-25T10:17:27.273Z","health_check_type":"ELB","tags":{"ChefEnv":"dev","ChefOrg":"asy-cloud","Name":"sensu_node","aws:cloudformation:logical-id":"SensuAutoScalingGroup","aws:cloudformation:stack-id":"arn:aws:cloudformation:eu-central-1:001579709704:stack/DEV-SENSU/409bf2a0-6aac-11e6-ae89-50a68ad4f2c6","aws:cloudformation:stack-name":"DEV-SENSU"}}' http://127.0.0.1:4567/clients && touch /tmp/asg_DEV-SENSU-SensuAutoScalingGroup-1BFF5Z5Q2O2SW.txt 
`

The Request:

`HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Connection: close
Content-length: 0
`

logs in debug mode show´s no issues.

**Comment by portertech** [comment]
@phoppe93 you are missing `"address": ""` from the post body data.

**Comment by portertech** [comment]
@phoppe93 let me know if this fixes your POST :)

**Comment by phoppe93** [comment]
@portertech 

thanks, it works !!!!
