### ISSUE TITLE
Sensu handler only works with non-0 exit code

### ISSUE THREAD

**Issue by johnseekins** [sensu/sensu#1522]
I've written a small handler to forward specific data to OpenTSDB. When the check that produces this data exits with a non-0 code (e.g. `exit 2`), the data is forwarded correctly. However, when the check returns success (i.e. the data was collected and no errors found), the OpenTSDB handler doesn't seem to pick up the data.

Current handler config:
```
[/etc/sensu/conf.d]: cat handlers/opentsdb.json 
{
    "handlers": {
        "opentsdb": {
            "type": "pipe",
            "command": "python /etc/sensu/handlers/opentsdb.py -H localhost -P 4242",
            "severities": ["ok", "warning", "critical", "unknown"]
        }
    }
}
```

Is this something you've seen before? I'm completely lost on why this isn't working.

## Your Environment
* Sensu version used: 0.26.5
* Operating System and version (e.g. Ubuntu 14.04): CentOS 6
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ 3.1.5 on erlang R14B

**Comment by cwjohnston** [comment]
Hi @johnseekins! Is your check configured with `"type": "metric"`? This tells Sensu to handle events even when the status is OK.

**Comment by johnseekins** [comment]
Bah! I'm an idiot! Just a complete "didn't actually read the docs" idiot.

Thank you @cwjohnston, that was (in retrospect) obviously what was wrong.

And generally, thank you guys for a genuinely great monitoring system!
