### ISSUE TITLE
Schedule checks

### ISSUE THREAD

**Issue by axos88** [sensu/sensu#1523]
Related to #749

I would love to see a way to schedule a standalone check immediately, at the end of a chef run for example.

**Comment by portertech** [comment]
Sensu 0.27 adds an HTTP socket to the Sensu client. We could continue the theme of adding Sensu API routes (w/ feature parity) to the Sensu client HTTP socket, route code re-use.

**Comment by axos88** [comment]
I like this idea. So basically a POST to a specific route would trigger the check?

**Comment by portertech** [comment]
@axos88 yes, only if defined locally as a standalone check :+1:

**Comment by axos88** [comment]
Sounds good to me. Any roadmap on when 0.27 is going to be released?

**Comment by calebhailey** [comment]
This happened; see: https://sensuapp.org/blog/2017/01/31/sensu-core-v0-27-0.html 

#monitoringlove
