### ISSUE TITLE
Sensu service not running in the background

### ISSUE THREAD

**Issue by melton14** [sensu/sensu#1524]
I tried Installing and running sensu on a amazon linux machine. 

service sensu-server start command should run it on the background but instead the logs are showing on the screen. I tried removing it and reinstalling it still no luck.

`[root@ip-10-1-11-10 ec2-user]# service sensu-server start
Starting sensu-server{"timestamp":"2017-01-03T07:00:06.817699+0000","level":"error","message":"log file is not writable","log_file":"/var/log/sensu/sensu-server.log"}
{"timestamp":"2017-01-03T07:00:06.818309+0000","level":"warn","message":"config file does not exist or is not readable","file":"/etc/sensu/config.json"}
{"timestamp":"2017-01-03T07:00:06.818364+0000","level":"warn","message":"ignoring config file","file":"/etc/sensu/config.json"}
{"timestamp":"2017-01-03T07:00:06.818499+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2017-01-03T07:00:06.835246+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2017-01-03T07:00:06.835337+0000","level":"warn","message":"loaded extension","type":"filter","name":"occurrences","description":"filter events using event occurrences"}
{"timestamp":"2017-01-03T07:00:06.835380+0000","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2017-01-03T07:00:06.835453+0000","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2017-01-03T07:00:06.835505+0000","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2017-01-03T07:00:06.835553+0000","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2017-01-03T07:00:06.835674+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
                                                           [  OK  ]
[root@ip-10-1-11-10 ec2-user]# {"timestamp":"2017-01-03T07:00:08.928600+0000","level":"info","message":"i am now the leader"}`

* Sensu version used:  sensu-0.26.5-2.x86_64 
* OS: Amazon Linux AMI release 2016.09

**Comment by cabecada** [comment]
"level":"error","message":"log file is not writable","log_file":"/var/log/sensu/sensu-server.log"

This message from the log should help you.
ensure /var/log/sensu/sensu-server.log is writable by sensu user.
