### ISSUE TITLE
Silencing specific checks still results in hipchat notification

### ISSUE THREAD

**Issue by nishlo** [sensu/sensu#1525]
Using Uchiwa silence a specific check but it still results in a hipchat notifiaction

## Expected Behavior
No hipchat notification is issued

## Current Behavior
Hipchat handler issues a notification

## Your Environment
* Sensu version used: 0.26.5-2 (both clients and sensu server)
* Uchiwa version: 0.21.0-1
* Operating System and version: CentOS 6.8 
* Transport and runtime versions: erlang-17.5.3-1 & redis-2.4.10-1
* hipchat gem 1.5.4

## Relevant configuration files
The check:
`{ "checks": {
    "prod1-book-12-healthcheck": {
        "command": "/etc/sensu/plugins/check-healthcheck.sh prod1-book-01",
        "handlers": [
            "default",
            "hipchat_monitoring"
        ],
        "interval": 120,
        "occurrences": 5,
        "refresh": 60,
        "subscribers": [
            "prod1-book-12"
        ]
    },`

Client info:
`  {
    "timestamp": 1483670651,
    "version": "0.26.5",
    "subscriptions": [
      "os_checks",
      "os_metrics",
      "prod2-book-12",
      "client:chhxbookhrm006"
    ],
    "hipchat_room": "2668713",
    "address": "EDITED",
    "name": "chhxbookhrm006"
  }`

Silenced entry that Uchiwa created:
`{
    "expire": -1,
    "expire_on_resolve": false,
    "creator": null,
    "reason": null,
    "check": "prod2-book-12-healthcheck",
    "subscription": "client:chhxbookhrm006",
    "id": "client:chhxbookhrm006:prod2-book-12-healthcheck"
  }`

Silenced entry that I POST to silenced api, targeted at the subscription: prod2-book-12
`{
    "expire": -1,
    "expire_on_resolve": false,
    "creator": null,
    "reason": null,
    "check": "prod2-book-12-healthcheck",
    "subscription": "prod2-book-12",
    "id": "prod2-book-12:prod2-book-12-healthcheck"
  }`

## Relevant Log files
Sensu Api:
`{"timestamp":"2017-01-05T18:05:12.789405-0600","level":"info","message":"api response","request":{"remote_address":"172.17.42.1","user_agent":"Go-http-client/1.1","method":"POST","uri":"/silenced","query_string":null,"body":"{\"id\":\"\",\"dc\":\"Sensu\",\"subscription\":\"client:chhxbookhrm006\",\"check\":\"prod2-book-12-healthcheck\"}\n\n"},"status":201,"content_length":0}`

Sensu Server:
`{"timestamp":"2017-01-05T20:51:35.784363-0600","level":"info","message":"processing event","event":{"client":{"name":"chhxbookhrm006","address":"EDITED","hipchat_room":"2668713","subscriptions":["os_checks","os_metrics","prod2-book-12","client:chhxbookhrm006"],"version":"0.26.5","timestamp":1483671091},"check":{"command":"/etc/sensu/plugins/check-healthcheck.sh prod2-book-12","handlers":["default","hipchat_monitoring"],"interval":120,"occurrences":5,"refresh":60,"subscribers":["prod2-book-12"],"name":"prod2-book-12-healthcheck","issued":1483671095,"executed":1483671095,"duration":0.054,"output":"prod2-book-12 - HealthCheck CRITICAL - Status Code: 000 (Could not connect)","status":2,"type":"standard","history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":24,"occurrences_watermark":24,"action":"create","timestamp":1483671095,"id":"e4346e1b-890b-466d-965c-1eebde8d23f8","last_state_change":1483668335,"last_ok":1483659815,"silenced":true,"silenced_by":["prod2-book-12:prod2-book-12-healthcheck","client:chhxbookhrm006:prod2-book-12-healthcheck"]}}
`

`{"timestamp":"2017-01-05T20:51:35.784902-0600","level":"info","message":"handler is silenced","handler":{"type":"pipe","command":"cat","name":"default"},"event":{"client":{"name":"chhxbookhrm006","address":"EDITED","hipchat_room":"2668713","subscriptions":["os_checks","os_metrics","prod2-book-12","client:chhxbookhrm006"],"version":"0.26.5","timestamp":1483671091},"check":{"command":"/etc/sensu/plugins/check-healthcheck.sh prod2-book-12","handlers":["default","hipchat_monitoring"],"interval":120,"occurrences":5,"refresh":60,"subscribers":["prod2-book-12"],"name":"prod2-book-12-healthcheck","issued":1483671095,"executed":1483671095,"duration":0.054,"output":"prod2-book-12 - HealthCheck CRITICAL - Status Code: 000 (Could not connect)","status":2,"type":"standard","history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":24,"occurrences_watermark":24,"action":"create","timestamp":1483671095,"id":"e4346e1b-890b-466d-965c-1eebde8d23f8","last_state_change":1483668335,"last_ok":1483659815,"silenced":true,"silenced_by":["prod2-book-12:prod2-book-12-healthcheck","client:chhxbookhrm006:prod2-book-12-healthcheck"]}}`

## Other info

- This behaviour started after upgrading sensu server and uchiwa
- Confirm have restarted rabbitmq, redis, sensu server/client and uchiwa
- Have attached the hipchat ruby script (renamed the extension to .txt)

**Comment by agoddard** [comment]
Hi @nishlo, can you please point me to the handler script? Is this issue still occurring?

**Comment by nishlo** [comment]
Apologies, I should have revisited this post when i found out the problem:
Our sensuserver install is deployed quite easily, through a docker container. Someone had deployed another docker image of sensuserver. So while the silencing was working on the instance thats connected to uchiwa, the other instance was responsible for issuing the handled event. 
I had to locate the erroneous deployment through netstat connections on a client. 

Would be nice for the client to log the "remote host" it received the event from. 

I'll close the ticket. Thanks for the awesome job/support with Sensu!
