### ISSUE TITLE
"Invalid 'Valid-Until' entry in Release file" error on Ubuntu Xenial 16.04.1

### ISSUE THREAD

**Issue by law** [sensu/sensu#1526]
On Ubuntu Xenial 16.04.1 hosts with the latest 'apt' package of 1.2.18, an 'apt update' against the Sensu repo `"http://repositories.sensuapp.org/apt sensu main"` errors out with the message, `"Invalid 'Valid-Until' entry in Release file".`  A 'curl' against the Release file shows: 

```
 # curl -q http://repositories.sensuapp.org/apt/dists/sensu/Release | grep Valid
 Valid-Until: Tue, 30 Nov 2038 00:00:00 JST
```
  This seems to not bother apt version 1.2.15ubuntu0.2, but apt 1.2.18 is most cranky about it.  

## Expected Behavior
With a defined Sensu repo of
`"deb http://repositories.sensuapp.org/apt sensu main" `

I would expect 'apt update' to succeed and not throw any errors
## Current Behavior
With the latest apt (1.2.18) package, an 'apt update' throws the following error: 
```
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/repositories.sensuapp.org_apt_dists_sensu_Release
E: Failed to fetch http://repositories.sensuapp.org/apt/dists/sensu/Release  Invalid 'Valid-Until' entry in Release file /var/lib/apt/lists/repositories.sensuapp.org_apt_dists_sensu_Release
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

## Possible Solution
Googling the error message shows older versions of 'apt' having issues with the 'JST' tz designator, perhaps have your repo maintainer regenerate the Release file in UTC?  

## Steps to Reproduce (for bugs)
With an Ubuntu Xenial 16.04.1 host: 
1. verify it currently has 'apt' version 1.2.15ubuntu0.2 or earlier
2. `echo 'deb http://repositories.sensuapp.org/apt sensu main' > /etc/apt/sources.list.d/sensu.list`
3. `apt update # verify this completes successfully`
4. `apt upgrade apt # verify this installs 'apt' version 1.2.18`
5.` apt update # verify the repo is no longer successfully queried
`
## Context
I am unable to install Sensu packages from your .deb repo.  In a much larger context, my CM system doesn't like apt returning a non-zero exit-code, which causes other issues outside the scope of this ticket.  

## Your Environment
* Sensu version used: 0.26.5-2 
* Active Sensu extensions (e.g. WizardVan 0.1.0): none
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04.1

**Comment by law** [comment]
Further context:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819697

it appears that only UTC should be used in date-parsing anyway.

**Comment by law** [comment]
While we're at it, might as well update those MD5 hashes to something like SHA256 or SHA512 ;-)

**Comment by Galitskiy** [comment]
The same issue.
```
# cat /etc/issue.net
Ubuntu 16.04.1 LTS

# apt --version
apt 1.2.18 (amd64)

# apt-get update
...
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repositories.sensuapp.org_apt_dists_sensu_Release
E: Failed to fetch http://repositories.sensuapp.org/apt/dists/sensu/Release  Invalid 'Valid-Until' entry in Release file /var/lib/apt/lists/partial/repositories.sensuapp.org_apt_dists_sensu_Release
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Tried downgrade to 1.2.15ubuntu0.2, clean apt cache, apt-get update - didn't help, issue persist.
Any solutions to solve this issue?

Thanks.

**Comment by law** [comment]
I had to downgrade the libapt-* packages as well: 
`apt install libapt-pkg5.0=1.2.15ubuntu0.2  libapt-inst2.0=1.2.15ubuntu0.2  apt=1.2.15ubuntu0.2`

**Comment by sniperd** [comment]
Confirmed, I can reproduce the same issue. Calling @portertech 😄

**Comment by amdprophet** [comment]
A fix for this should be coming soon. An upgrade to our APT repositories is needed to support the `Valid-Until` field.

**Comment by amdprophet** [comment]
I've upgraded the APT repositories and `Valid-Until` is now using UTC. Can someone please confirm that this resolved the issue?

**Comment by law** [comment]
Works like a champ for me, thank you very much!
