### ISSUE TITLE
RFE: First class VMware vSphere checks

### ISSUE THREAD

**Issue by jflemer-ndp** [sensu/sensu#1527]
*Request For Enhancement*: Provide a (public or enterprise) extension or plugin with first class monitoring of vSphere.

## Expected Behavior
`sudo sensu-install -p vsphere`

## Current Behavior
Maybe use Nagios plugins, pulling in associated dependencies, and JIT/Proxy checks:
-    https://github.com/jjasghar/esxi_health (Ruby)
-    https://github.com/rogerlz/nagios-check-vcenter (Python)
-    https://www.claudiokuenzler.com/nagios-plugins/check_esxi_hardware.php (Python)
-    https://github.com/lgeeklee/pyvinga (Python)

These are less desirable due to having to use JIT/Proxy and the need to deal with Python environment & deps in addition to Ruby.

## Possible Solution
- VMware provides a capable Ruby interface to the vSphere API (https://github.com/vmware/rbvmomi)
- Implement a CLI check plugin that can be used as a JIT/Proxy check using rbvmomi
- Implement an extension using rbvmomi that supports subscription based checks (but not actually requiring sensu-client on a ESXi/vSphere/VCSA node)

## Context
Monitoring of hybrid infrastructure necessitates monitoring of the virtualization infrastructure to include:
 - hypervisor health (cpu, memory, uptime)
 - hypervisor networks
 - data stores
 - etc

## Your Environment
- Sensu 0.26
- vSphere & vCenter 6.5 with VCSA

**Comment by portertech** [comment]
@jflemer-ndp thanks for the issue, a valid. This is however the wrong place for it, I have gone ahead and created https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/13
