### ISSUE TITLE
Distinguish proxy clients in the registry

### ISSUE THREAD

**Issue by portertech** [sensu/sensu#1532]
Proxy clients in the registry should be distinguished, e.g. `"type": "proxy"`.

## Current Behavior

There is no real way to determine if a client in the registry is a proxy client.

## Possible Solution

Update `retrieve_client()` to add a attribute to the newly created proxy client. Optionally, the method can be updated to only create a client if check result "source" is provided.

**Comment by calebhailey** [comment]
Should we document the change in behavior here, in this PR (in addition to the Sensu documentation)?

**Comment by portertech** [comment]
The current behaviour was implemented without mention, it's a side-effect of implementing "JIT clients".

**Comment by portertech** [comment]
We currently do set `"keepalive": false`, which can be used to identify them.

**Comment by portertech** [comment]
I merged https://github.com/sensu/sensu/pull/1539 into release/0.28, closing this one :+1:
