### ISSUE TITLE
Feature Request: Ability to override check names in check config

### ISSUE THREAD

**Issue by CVTJNII** [sensu/sensu#1533]
If I understand things correctly currently the only way to specify a name for a check is as the key in the checks hash:

```json
{
  "checks": {
    "some-check": {
      "type": "standard",
      "host": "some-host",
      "command": "some-command"
    }
  }
}
```

This will result in a check called **some-host/come-check**.  This is fine if the check name is unique, however in our infrastructure we schedule per host, which results in hundreds of duplicate check names.  Take, for example, DNS, which we define for every host in our infrastructure:

```json
{
  "checks": {
    "dns": {
      "type": "standard",
      "host": "some-host",
      "command": "check-dns"
    },
    "dns": {
      "type": "standard",
      "host": "some-other-host",
      "command": "check-dns"
    },
    "dns": {
      "type": "standard",
      "host": "some-third-host",
      "command": "check-dns"
    }
  }
}
```

That is, of course, illegal as you can't have 3 blocks under the same key.

My workaround thus far has been to prefix the name with the host:
```json
{
  "checks": {
    "some-host-dns": {
      "type": "standard",
      "host": "some-host",
      "command": "check-dns"
    },
    "some-other-host-dns": {
      "type": "standard",
      "host": "some-other-host",
      "command": "check-dns"
    },
    "some-third-host-dns": {
      "type": "standard",
      "host": "some-third-host",
      "command": "check-dns"
    }
  }
}
```

This is 100% functional but a little unweildly as I then wind up with checks named **some-host/some-host-dns** instead of **some-host/dns** which would be preferred.

So, what I would like to see is the ability to set the check name as an override in the hash, so that uniqueness of the keys can be maintained:

```json
{
  "checks": {
    "some-host-dns": {
      "name": "dns",
      "type": "standard",
      "host": "some-host",
      "command": "check-dns"
    },
    "some-other-host-dns": {
      "name": "dns",
      "type": "standard",
      "host": "some-other-host",
      "command": "check-dns"
    },
    "some-third-host-dns": {
      "name": "dns",
      "type": "standard",
      "host": "some-third-host",
      "command": "check-dns"
    }
  }
}
```

This will result in the checks being named **[host]/[name]**, which is much more user-friendly, while allowing me to set appropriately unique keys.

I looked over the 0.26 docs (which I am running) but didn't see an existing solution for this.  It seems like Sensu is mature enough that this should already be solved, so apologies if I missed it in the docs.

**Comment by portertech** [comment]
I may not fully understand the issue/problem that you are experiencing, creating/using unique check names is not hard. I believe this will cause more confusion when introducing Sensu configuration to new users and creates unnecessary code complexity.

@CVTJNII thank you for taking the time to put together this issue. I am going to close it, as it is not something that we are interested in pursuing.

**Comment by CVTJNII** [comment]
So what is the recommended naming for a check that runs on 2000 hosts?  My solution is clunky.

**Comment by amithrh** [comment]
is there a way we can dynamically update the check name based on a result ? i have a check-couch-base-bucket cluster check running , which checks for all the buckets and then get me results for all buclkets configured , so in my case if any bucket fails i get a result that check-couchbase-bucket-quota has failed ,
i would exepect sensu to update a check name based on sensu result
