### ISSUE TITLE
Sensu crashes immediately if network/DNS is unavailable

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#1534]
In Sensu 0.26.5, if we start the client and network isn't available, the DNS lookup for RabbitMQ will fail and the client exits.  

I'd like an option for the client to keep retrying DNS/connection by default or perhaps as a client configuration parameter (ex: retry_initial_connnect_dns = true).

Would prefer to not have to wrap additional daemon management tools around this (ex: runit).

"timestamp":"2017-01-18T16:17:36.146787-0700","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `connect_server': unable to resolve server address: Success (EventMachine::ConnectionError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `bind_connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:653:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:457:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp.rb:242:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-6.0.0/lib/sensu/transport/rabbitmq.rb:188:in `setup_connection'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-6.0.0/lib/sensu/transport/rabbitmq.rb:218:in `connect_with_eligible_options'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-6.0.0/lib/sensu/transport/rabbitmq.rb:20:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-6.0.0/lib/sensu/transport.rb:24:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/daemon.rb:253:in `setup_transport'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:451:in `start'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:19:in `block in run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'

**Comment by cwjohnston** [comment]
Hi @xyntrix,

We're preparing to release Sensu Core 0.27 which will include the changes in https://github.com/sensu/sensu-transport/pull/42. I believe these changes will better address the condition you're describing, putting Sensu into a retry loop on DNS lookups before attempting a connection.

**Comment by portertech** [comment]
The 0.27.0-1 is available in the unstable repositories :+1: https://sensuapp.org/docs/0.27/platforms
