### ISSUE TITLE
Sensu Client not starting on Windows Server 2012 R2

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1535]
## Expected Behavior
Sensu-Client should switch to running state after starting the service.

## Current Behavior
After plain installation of Windows Server 2012 R2 and Sensu (following recommended official steps), Sensu-Client service is not starting.
Compatibility modes do not help.
However, same Sensu installation on Windows 7 Enterprise 64bit is running OK.

Error from CLI (manual execution):
Program 'sensu-client.exe' failed to run: The specified executable is not a valid application for this OS platform.
Error from Services:
Error 216: 0xd8

## Possible Solution
No solution found yet.

## Steps to Reproduce (for bugs)
1. Plain install - Windows Server 2012 R2 64bit
2. Install Sensu, following recommended official steps
3. Run Sensu-Client service

## Context
Monitoring of Windows Servers not possible.

## Your Environment
* Sensu version used: 0.26.5
* Active Sensu extensions (e.g. WizardVan 0.1.0): None
* Operating System and version (e.g. Ubuntu 14.04): Windows Server 2012 R2 Standard 64bit
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ 3.3.5

!Working on Windows 7 Enterprise 64bit!

**Comment by amdprophet** [comment]
There's a chance that using the new 0.27 unstable build may resolve this. If you'd like to give it a shot you can grab it from the repositories (http://repositories.sensuapp.org/msi-unstable/2012r2/sensu-0.27.0-1-x64.msi)

**Comment by amdprophet** [comment]
Sensu 0.27.0 is now available in the stable repositories. Can you please confirm whether or not this issue is still occurring for you with the new release?

You can find the new release here: https://sensu.global.ssl.fastly.net/msi/2012r2/sensu-0.27.0-2-x64.msi

#monitoringlove

**Comment by mcbsdEU** [comment]
Hi,

sorry for delay. I tested 0.27.0 on the same machine and now it is working without any errors. Client is registered by Sensu Server.

Thanks and keeping going in good work.
