### ISSUE TITLE
Allow different leaders for different roles

### ISSUE THREAD

**Issue by gwagner** [sensu/sensu#1537]
Currently when a sensu server is a leader, it is tasked with publishing checks for subscriptions, running keepalives cleanup against clients, and finally if you have ttls, looking for checks failing TTL.  This makes sensu server leader extremely busy (in a large setup) and causes backups to happen in either check processing or check creation for subscriptions.  

## Expected Behavior
Each role should be able to be a leader on a different server.  Elect the leader for publishing, a different server for leader on keepalives, and finally a different leader for ttl processing.  Should be able to use the same leader logic, just check for leader on the different roles.  This may require a redis sensu-server machine registry to be created to managed if a single machine can have more than one role, or maybe just a config which defaults to yes on a single machine deployment.

## Current Behavior
One machine takes all roles.  In an environment with 881 machines and 17k checks, this takes the primary too its knees in misery

## Possible Solution
Leader elections per role

## Steps to Reproduce (for bugs)
1. Get a butt load of machines
1. Have that but load of machines have a butt-loadier number of checks
1. Set every check with a TTL
1. Watch things MELT

## Your Environment
Logical flaw in the code, not environment specific.  Needs a big cluster

**Comment by gwagner** [comment]
Extend this code for multiple leader election types, with a single box being able to either have multiple roles or only a single role: https://github.com/sensu/sensu/blob/bb91fea7797d2402349a3e86b7cd3f43b78621c8/lib/sensu/server/process.rb#L1112

**Comment by portertech** [comment]
Having a server registry would also allow Sensu to provide more information via the API. For example, which Sensu server is currently doing each leader role, CPU utilization, etc. We could name them "server role", dropping the idea of a leader entirely.

**Comment by portertech** [comment]
Proposed role grabbing algo: Sensu servers shuffle roles list, each server attempts to lock their first role, servers able to lock a role wait a random amount of time before attempting to lock another. Smaller installations will experience a bit of delay for all roles to be locked.

Example server roles: [check_publisher, client_keepalive_monitor, check_ttl_monitor]

**Comment by gwagner** [comment]
That should work well IMO.  I also like the idea of being able to expose that kind of thing via the API

**Comment by portertech** [comment]
#1621 implements this :+1:
