### ISSUE TITLE
Prevent race condition on host deletion

### ISSUE THREAD

**Issue by baweaver** [sensu/sensu#1541]
There is currently a race condition in which a host deleted through the API may recommission itself if a check of any type fires an event after the host deletion is processed.

## Expected Behavior

`DELETE base_url/clients/$hostname` deletes a host fully

## Current Behavior

If an event is fired after the deletion of a host, it will be recommissioned. 

## Possible Solution

On `DELETE` of a client, create a new Redis key: `clients:$hostname:deleted = true`. This will indicate that a host has been deleted and can be used as a flag against recommissioning of an explicitly deleted host.

## Steps to Reproduce (for bugs)

1. Delete any client
2. Fire an event for the client
3. Host is back in commission

## Context

This is particularly relevant in an automated monitoring pipeline where a delete request may process before a server is terminated or an event could be delayed just enough to cause issue.

A race condition of this nature cannot be fixed fully. It'd be continually adding a wait to the deletion until it starts interfering with the intended use of Sensu.

Currently we have a default handler that looks for the instance in AWS, and if it's terminated it resolves the event. This feels like a very dirty hack.

## Your Environment

I'll have to double check this later, but all versions are up to date except for Sensu itself.

* Sensu version used:
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): 
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

## Additional Details

I would more than happily do this feature for you if it's something that you would like to see. I've heard that this is something solved potentially in enterprise (using a similar handler approach) but I believe that it should be core.

**Comment by cwjohnston** [comment]
> On `DELETE` of a client, create a new Redis key: `clients:$hostname:deleted = true`. This will indicate that a host has been deleted and can be used as a flag against recommissioning of an explicitly deleted host.

It seems to me that there's a potential conflict here with the client `deregister` feature. Some operators make use of graceful client deregistration with the assumption that the client can re-register again later, potentially under the same client name.

Perhaps the conflict could be avoided if the  `clients:$hostname:deleted` key expired automatically?

> Currently we have a default handler that looks for the instance in AWS, and if it's terminated it resolves the event. This feels like a very dirty hack.

FWIW, this is the approach used by several integrations in Sensu Enterprise, e.g. treating EC2, Puppet or Chef APIs as the source of truth.

**Comment by fessyfoo** [comment]
FWIW we thought we had this same issue,  but in our case the race condition was because we were deleting the host from sensu before the agent was shutdown at all.   Fixing that in our infra we haven't hit this issue again.

**Comment by xyntrix** [comment]
Ran into the same thing as fessyfoo and realized in was our own self-inflicted issue.    On the possibility of tagging a client in the registry with deleted:  We have an often used case where servers are removed and rebuilt with the same host names a few minutes later.  I like cwjohnston's suggestion of being able to provide some ttl around the client-deleted state, or at least, making the whole thing an optional state.  Perhaps a new function or parameter to existing delete function.  Ex:  force_delete&ttl=120s /  delete;force=true;ttl=120s

**Comment by baweaver** [comment]
The danger of the AWS query is that AWS has hard limits on API requests and any sufficiently large shop will hit them fast.

**Comment by flowerysong** [comment]
> It seems to me that there's a potential conflict here with the client `deregister` feature. Some operators make use of graceful client deregistration with the assumption that the client can re-register again later, potentially under the same client name.
>
> Perhaps the conflict could be avoided if the `clients:$hostname:deleted` key expired automatically?

Perhaps instead of a true/false flag, client deletion could store a timestamp that invalidates all check results or keepalives with earlier timestamps? I think this would fix the races I've seen, while still allowing immediate re-registration (which happens fairly often in our environment.)

**Comment by Evesy** [comment]
> Perhaps instead of a true/false flag, client deletion could store a timestamp that invalidates all check results or keepalives with earlier timestamps? I think this would fix the races I've seen, while still allowing immediate re-registration (which happens fairly often in our environment.)

I believe this would fix the race conditions we come across too. Since the client deregistration process is immediate we quite often have check results that are published prior to the client shutting down, however are only processed by Sensu after the client has been degregistered, due to small delays in transport.

It's only a small issue however it can cause some noise in Uchiwa since we're throwing away probably ~100 servers a day, so quite a few end up reregistering with TTL failures

**Comment by portertech** [comment]
Considering adding a query parameter(s) to DELETE `/clients/:client`, e.g. `?decommission=true&decommission_expire=180`, although using "decommission" may cause some confusion with client decommission. I am concerned this feature will have a significant performance impact, as it will add a Redis call/command for every check result and keepalive received.

It may be possible to combine this feature with client signatures, effectively setting/changing the stored signature to invalidate further keepalives and check results. Would need to log appropriately to not cause confusion.

**Comment by portertech** [comment]
We could use a parameter like "?invalidate=true".

**Comment by portertech** [comment]
I am going to put together a PR, DELETE `/clients/:client?invalidate=true`, utilizing the client signature feature to invalidate further keepalives and check results from the client until it has been deleted from the registry (then the signature is deleted/reset).

**Comment by portertech** [comment]
Using the client signature works, however, we need to change how the signature is removed, i.e use redis expires.

**Comment by portertech** [comment]
I have pushed https://github.com/sensu/sensu/pull/1640 as a possible solution. It only introduces an additional Redis operation when creating JIT/proxy clients :+1:

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1640 was merged, the upcoming 0.29 release will have it :+1:
