### ISSUE TITLE
systemd Centos7 Startup

### ISSUE THREAD

**Issue by alexwbaule** [sensu/sensu#1543]
Hi Guys.

Using Centos 7 withe the new Sensu 0.27, with systemd the sensu(api, server, client) dont start because the /var/run/sensu directory don't exist. Looking into /opt/sensu/bin/sensu-service script, there is a "ensure_dir", but the user that is running this script is the sensu. (I Edit the script and put some echo's to a file in /tmp)
uid=996(sensu) gid=994(sensu) groups=994(sensu) -- |/var/run/sensu| -- |sensu| 

Doing this manually, i got the error:

[root@sensuapp ~]# su -s /bin/sh sensu
sh-4.2$ 
sh-4.2$ mkdir -p /var/run/sensu
mkdir: cannot create directory ‘/var/run/sensu’: Permission denied

The Solution that i found is doing what the rabbitmq-server do, putting a configuration to systemd creates this directory.
Create a file in  /usr/lib/tmpfiles.d/sensu.conf 
With this content:
D /var/run/sensu 0755 sensu sensu -

I dont know if is needed to cal some command to put this conf to run, because i reboot my centos to test if the sensu starts at boot. But i think is call a systemd-tmpfiles-setup.

There is 2 appends to do in Sensu Docs, about the rabbitmq-server and redis server using systemd, in the configuration text said to edit "/etc/defaults/redis" and "/etc/defaults/rabbitmq-server" to increase the "ulimit -n" value, but in systemd the correct way to do this is:

Redis:
edit the file "/etc/systemd/system/redis.service.d/limit.conf" and alter the LimitNOFILE to 65536.

RabbitMQ:
Create the file "/etc/systemd/system/rabbitmq-server.service.d/limits.conf" and put this lines inside:
[Service]
LimitNOFILE=65536

That's it !

**Comment by amdprophet** [comment]
We've just released Sensu 0.27.0-2 which addresses this issue. Please let us know if it resolves the issue for you.

#monitoringlove

**Comment by alexwbaule** [comment]
ok ! My installation was made today, tomorrow i will update it.

**Comment by alexwbaule** [comment]
Today i make the update, but doing a "yum update" erase all itens in /opt/sensu.
