### ISSUE TITLE
server version 26 clients <26 backwards compatibility issues

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu#1545]
I upgraded my servers to version 26 a few days ago and also my uchiwa dashboards, I did not upgrade my clients right away but was going to allow them to update as chef runs were needed. 
However, when I tried to silence a check on one of my clients it continued to be handled. Upon some digging I noticed the "silenced":false attribute that was coming in on the check that uchiwa and the sensu server said was silenced, I played with one of my clients that had been updated to trigger the same alert and then silenced it and notice it said "silenced":true. After some help on IRC someone pointed out this nice note in the docs. 

NOTE: Starting with version 0.26, Sensu clients automatically add a subscription containing their client name prefixed with the string client:. For example, client i-424242 will automatically add subscription client:i-424242. Silencing checks at the individual client level requires clients to run Sensu 0.26+, or be manually configured with a client: subscription.

Was there not a way to have the server check the version of the clients and handle them differently for a few versions? This requires a pretty big change to upgrade all clients, servers, and uchiwas all within the same period to keep things running smoothly? 

I also found this in the changelog too, it just didnt catch my eye till I knew what I was looking for :(

**Comment by fessyfoo** [comment]
I had a similar incident. I  misread sensu will automatically add client subscription as something the server would do.  not the clients,  and we updated our servers before our fleet of clients were updated. 

as a workaround we ended up using puppet to add the client subscription in the client config, until we got all the clients updated. 

though from some perspective it is `v0` software, and could be forgiven.

**Comment by joshzitting** [comment]
It is definitely forgiven. It has been great software so far. I just wish there had been more red flags for breaking changes. Maybe a nice big warning at the top of the docs with Version compatibility listed?

**Comment by portertech** [comment]
I agree, https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0260---2016-09-06 should mention this under "Important" is it's not technically non-backwards compatible.

**Comment by cwjohnston** [comment]
@joshzitting @fessyfoo mea culpa! Sometimes realizing the fully impact of changes requires the benefit of hindsight. I've opened https://github.com/sensu/sensu-docs/pull/510 to make the importance of this more obvious.

We may also want to ensure that client subscriptions are added when [updating the client registry](https://github.com/sensu/sensu/blob/v0.27.0/lib/sensu/server/process.rb#L136).

**Comment by cwjohnston** [comment]
I've opened #1554 to ensure per-client subscriptions are added to the client when updating the registry on the server side.
