### ISSUE TITLE
Sensu client keeps stopping with Argument error in log

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1548]
Sensu version: 0.26.5-2
OS: CentOS 6.6 

Sensu Client keeps failing with the error message below in the log. After a start from the client everything is back to normal and runs fine for days.

> /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/utilities.rb:110:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/utilities.rb:110:in `substitute_tokens'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:124:in `object_substitute_tokens'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:114:in `block in object_substitute_tokens'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:113:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:113:in `object_substitute_tokens'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:146:in `execute_check_command'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:232:in `process_check_request'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:283:in `block (2 levels) in setup_subscriptions'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:162:in `block in on_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `block in exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:294:in `handle_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:348:in `block in <class:Consumer>'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:959:in `receive_frameset'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:933:in `receive_frame'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'

**Comment by cwjohnston** [comment]
Hi @ChrisOnToure, thanks for reporting this issue. We addressed a similar UTF-8 encoding issue in #1505 but I think this is a different section of code that needs similar treatment.

**Comment by portertech** [comment]
@ChrisLundquist are you also using the SQS transport?

**Comment by portertech** [comment]
Er, sorry, just saw the occurrences of AMQ in the trace.

**Comment by portertech** [comment]
#1566 was merged, it will be in 0.27.1 :+1:
