### ISSUE TITLE
Sensu Stashes Disappear

### ISSUE THREAD

**Issue by dkinon** [sensu/sensu#1551]
When I stash both client and/or check-specific alerts with no expiration via uchiwa, some time later (seems to be arbitrary but always within1-2 days) the stashes just disappear and alerts start flowing again.  So far I haven't been unable to correlate this to any specific log entries.

## Expected Behavior
Sensu stashes with no expiration should last forever.

## Current Behavior
Sensu stashes with no expiration only last from 1-2 days before disappearing.

## Possible Solution
No ideas.

## Steps to Reproduce (for bugs)
These steps are 
1. In uchiwa, stash a client or client check with no expiration.
2. Wait 1-2 days
3. Watch for stashes to disappear

## Context
Using stashes the standard way to keep alerts notifications from spewing (using slack plugin).  So far I've only tested/reproduced this issue on stashes with no expiration so I'm not certain this would affect stashes with a defined expiration.

## Your Environment

* Sensu version used: 0.26.5-2 (rpm from http://repositories.sensuapp.org/yum/el/7/x86_64/)
* Active Sensu extensions: None
* Operating System and version: CentOS Linux release 7.2.1511
* Transport and runtime versions: RabbitMQ 3.6.5-1 (rpm from https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.5/) on Erlang R16B-03.18 (rpm from epel7) and Redis 2.8.19-2 (rpm from epel7)

**Comment by dkinon** [comment]
For confirmation, the sensu api does report the stashes correctly when they are created:
`# curl -s http://localhost:4567/stashes | jq
[
  {
    "path": "silence/research.XXXXX.XXX",
    "content": {
      "reason": "Disable Alerts",
      "source": "uchiwa",
      "timestamp": 1486830179
    },
    "expire": -1
  },
  {
    "path": "silence/qa.XXXXX.XXX",
    "content": {
      "reason": "Disable Alerts",
      "source": "uchiwa",
      "timestamp": 1486830174
    },
    "expire": -1
  }
]`

**Comment by dkinon** [comment]
I put a script in place to notice when the stashes disappear and may have found the cause of this issue.  My script checks once a minute and alerted at 2017-02-14T09:53:01, there was nothing interesting in the sensu-api logs but in the sensu server logs I found these unexpected logs occurring within the previous minute:
```{"timestamp":"2017-02-14T09:52:16.473481+0000","level":"warn","message":"another sensu server has been elected as leader"}
{"timestamp":"2017-02-14T09:52:16.473590+0000","level":"warn","message":"resigning as leader"}
{"timestamp":"2017-02-14T09:52:26.474388+0000","level":"info","message":"i am now the leader"}```

As you can see a brief leader election takes place which may look completely normal except that there is no other sensu-server running, I only run a single instance (and I reconfirmed this in my environment just to be 100% sure).  What could be causing this phantom leader election and does a leader election cause stashes to be cleared from wherever they are stored?

**Comment by cwjohnston** [comment]
@dkinon from my perspective, both disappearing stashes and unexpected leader election are consistent with the Sensu data store being wiped out (e.g. Redis `flushdb` or similar. Is some scheduled or automated process performing maintenance on your Redis server?

**Comment by dkinon** [comment]
@cwjohnston thanks for the perspective, I don't have any redis maintenance jobs that I know of but I'll comb through the environment to see if I find anything.  In the mean time here are the redis logs surrounding the last occurrence:
```[7720] 14 Feb 09:49:20.073 * 10 changes in 300 seconds. Saving...
[7720] 14 Feb 09:49:20.073 * Background saving started by pid 638
[638] 14 Feb 09:49:20.078 * DB saved on disk
[638] 14 Feb 09:49:20.078 * RDB: 0 MB of memory used by copy-on-write
[7720] 14 Feb 09:49:20.174 * Background saving terminated with success
[7720] 14 Feb 09:52:12.789 * DB saved on disk
[7720] 14 Feb 09:52:13.808 * DB saved on disk
[7720] 14 Feb 09:57:14.045 * 10 changes in 300 seconds. Saving...
[7720] 14 Feb 09:57:14.045 * Background saving started by pid 1864
[1864] 14 Feb 09:57:14.049 * DB saved on disk
[1864] 14 Feb 09:57:14.050 * RDB: 0 MB of memory used by copy-on-write
[7720] 14 Feb 09:57:14.146 * Background saving terminated with success```

The 2 successive `DB saved on disk` entries right before the stashes are lost doesn't seem normal (based on the other saves I'm seeing in the logs) but I don't see any evidence of an error or a flush.  I'm using the redis-2.8.19-2.el7.x86_64 rpm from epel7.  I don't have much experience with access redis data, is there an easy way for me to watch the stashes programmatically in redis?

**Comment by cwjohnston** [comment]
@dkinon Redis has a [MONITOR](https://redis.io/commands/monitor) command, which streams the commands being executed on your Redis database.

**Comment by dkinon** [comment]
thanks @cwjohnston, I've got a script logging the output of `redis-cli monitor` and am waiting for another occurrence.

**Comment by agoddard** [comment]
Hi @dkinon have you seen this issue again after setting up the monitoring?

**Comment by portertech** [comment]
Closing this issue.
