### ISSUE TITLE
sensu-client will not start after update to 0.27.1

### ISSUE THREAD

**Issue by Craigeous** [sensu/sensu#1569]
updated all my linux clients from 0.26.5 to 0.27.1 on CentOS 7 and the client would no longer start

## Expected Behavior
update sensu-client via yum repo
run systemctl daemon-reload
restart sensu-client service
service should start up fine
systemctl status sensu-client
```
● sensu-client.service - sensu client
   Loaded: loaded (/etc/systemd/system/sensu-client.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2017-02-19 14:09:37 CST; 18s ago
 Main PID: 18812 (sensu-client)
   CGroup: /system.slice/sensu-client.service
           └─18812 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-cli.
```

## Current Behavior
update sensu-client via yum repo
run systemctl daemon-reload
restart sensu-client service
service service fails to start
```
sensu-client.service - sensu client
   Loaded: loaded (/etc/systemd/system/sensu-client.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2017-02-19 14:06:36 CST; 6s ago
  Process: 18707 ExecStart=/opt/sensu/bin/sensu-service start client (code=exited, status=1/FAILURE)
 Main PID: 18707 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/sensu-client.service
           └─9132 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-cli.
```
## Possible Solution
performed netstat -tulpn and saw ruby was still listening on port 3030
killed the PID of ruby
started sensu-client and it was working successfully
This happened to me on every CentOS box I upgraded today, which is about 13 servers.

## Your Environment
```
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-514.2.2.el7.x86_64
```

`Embedded Ruby`

```
Name        : erlang
Arch        : x86_64
Version     : R16B
Release     : 03.18.el7
```

```
Name        : rabbitmq-server
Arch        : noarch
Version     : 3.3.5
Release     : 31.el7
```

```
Name        : redis
Arch        : x86_64
Version     : 2.8.19
Release     : 2.el7
```

**Comment by cwjohnston** [comment]
Hi @Craigeous, thanks for reporting this issue. 

I suspect this has relation to the transition from sysv init scripts to systemd unit files between 0.26 and 0.27, where the Sensu process running under sysv init is not stopped before the init script is removed and new systemd unit files are installed/started. 


I know that @amdprophet and I discussed this possibility while working on the new release but I can see that we've not clearly described it in the 0.27 changelog. I apologize for the inconvenience this has caused you and I will update the changelog to describe this scenario in hopes that other folks may avoid it.

I think this condition can be avoided by stopping Sensu services prior to upgrading Sensu from a version prior to 0.27. Perhaps if you have more upgrades planned you could help me to validate this workaround?

**Comment by rgeniesse** [comment]
Confirmed the same behavior on my CentOS 7 test box. I have a few others out there on 7 and I'll see if stopping the Sensu client first on my next upgrades is a workaround.

**Comment by Craigeous** [comment]
Thanks for the response.  I did see the note about transitioning from sysv init to systemd.  Just didn't occur to me to stop the services first.  After I figured out what was going on my first thought was that I should have stopped the services prior to the upgrade.  Hindsight...

**Comment by cwjohnston** [comment]
I've opened https://github.com/sensu/sensu-docs/pull/518 to make this more explicit in the changelog
