### ISSUE TITLE
Sensu-server apt upgrade broken in 0.27.1-2

### ISSUE THREAD

**Issue by dalesit** [sensu/sensu#1570]
## Expected Behavior
Upgrade should work as normal

## Current Behavior

Automated weekly upgrade failed (output from /var/log/apt/history.log):
```
Start-Date: 2017-02-20  07:56:08
Commandline: /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install sensu
Upgrade: sensu:amd64 (0.27.0-2, 0.27.1-2)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2017-02-20  07:56:24
```
Manually uninstalling and re-installing works fine.

Manually upgrading:
```
[root@ggh-d-logapp01:~]# apt-get upgrade 
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  erlang-asn1 erlang-corba erlang-crypto erlang-diameter erlang-edoc
  erlang-eldap erlang-erl-docgen erlang-eunit erlang-ic erlang-inets
  erlang-inviso erlang-mnesia erlang-odbc erlang-os-mon erlang-parsetools
  erlang-percept erlang-public-key erlang-runtime-tools erlang-snmp erlang-ssh
  erlang-ssl erlang-syntax-tools erlang-tools erlang-webtool erlang-xmerl
  linux-generic linux-headers-generic linux-headers-server linux-image-generic
  linux-server
The following packages will be upgraded:
  sensu
1 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
Need to get 0 B/37.2 MB of archives.
After this operation, 7,605 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 94701 files and directories currently installed.)
Preparing to unpack .../sensu_0.27.1-2_amd64.deb ...
 * Stopping sensu-client                                                                                                      [ OK ]
 * Stopping sensu-server                                                                                                      [ OK ]
 * Stopping sensu-api                                                                                                         [ OK ]
Unpacking sensu (0.27.1-2) over (0.27.0-2) ...
Sensu has been uninstalled!
Processing triggers for ureadahead (0.100.0-16) ...
Setting up sensu (0.27.1-2) ...
chown: cannot access â/opt/sensuâ: No such file or directory
dpkg: error processing package sensu (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 sensu
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

## Possible Solution
Workaround - manually uninstall and re-install

## Steps to Reproduce (for bugs)

1. Manually downgrade:
`apt-get install sensu=0.27.0-2`

2. Upgrade: 
`apt-get upgrade`

## Your Environment

* Sensu version used: 0.27.0-2 -> 0.27.1-2
* Operating System and version: Ubuntu 14.04
* Transport and runtime versions: RabbitMQ 3.6.2, Erlang 19.0

**Comment by dalesit** [comment]
Appears linked to #1569 - however, no ruby process is running, and /opt/sensu no longer exists.

**Comment by cwjohnston** [comment]
Hi @dalesit, thanks for reporting this. I believe you're experiencing the issue described in https://github.com/sensu/sensu-omnibus/issues/121, fixed in https://github.com/sensu/sensu-omnibus/pull/116. 

The fix in https://github.com/sensu/sensu-omnibus/pull/116 was included in 0.27.0-3, so now that you've upgraded to 0.27.1-2, I believe you should no longer experience this error.

**Comment by dalesit** [comment]
Ah, OK @cwjohnston  - all the references to Yum in the other tickets obscured the fact it affected Ubuntu/Debian installs as well. If I have systems that are still on 0.26 and previous, will they be affected? Or just systems that have already moved to 0.27.0-1 or 0.27.0-2?

**Comment by cwjohnston** [comment]
@dalesit my understanding is that this condition only affects those systems where the package has been upgraded to 0.27.0-1 or 0.27.0-2. Systems being upgraded from package versions prior to 0.27.0-1 to 0.27.0-3 or later should not encounter this scenario.
