### ISSUE TITLE
Enhanced publishing of JIT client checks

### ISSUE THREAD

**Issue by mjhuber** [sensu/sensu#1571]
## Expected Behavior
The ability to specify a host group that sensu would then publish a check for each of those hosts as JIT clients.

## Current Behavior
A check config must be maintained for each metric and each JIT client.  This can become burdensome when monitoring a large number of network devices or other JIT clients.

## Possible Solution
1.  Create an optional field in a check config to place a host group for jit clients.  Ex:
```
	"cisco-freeMem": {
		"command": "check-snmp.rb -o 1.3.6.1.4.1.9.2.1.58.0 -h :::source:::",
        "jit_subscribers": [ "cisco-devices" ],
        "interval": 60
    }
```
2.  For each host in the host group cisco-devices from above, a check is published with the hostname in the source property of the check.
```
	"cisco-freeMem": {
		"command": "check-snmp.rb -o 1.3.6.1.4.1.9.2.1.58.0 -h :::source:::",
        "jit_subscribers": [ "cisco-devices" ],
        "interval": 60,
        "source": "cisco1.foo.com"
    }

    "cisco-freeMem": {
		"command": "check-snmp.rb -o 1.3.6.1.4.1.9.2.1.58.0 -h :::source:::",
        "jit_subscribers": [ "cisco-devices" ],
        "interval": 60,
        "source": "cisco2.foo.com"
    }
```
3.  Enable token substitution for the source field, so JIT clients can use the hostname in command args.

## Context
This feature would allow easier monitoring of network devices at scale.  It is currently difficult because of the large amount of check configs that would need to be maintained.

**Comment by cwjohnston** [comment]
Hi @mjhuber, thanks for sharing your thoughts. I think we've merged an implementation similar to what you're asking for in #1555, using client attributes to select targets instead of a static list of JIT clients.
