### ISSUE TITLE
Sensu Client with SSL on Windows - runtime_error

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1579]
## Expected Behavior
Sensu Client on Windows should be SSL ready.

## Current Behavior
Sensu Client on Windows works with no problems when SSL is not used.
When rabbitmq.json config is enhanced with ssl directives, Sensu Clients throws:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Encryption not available on this event-machine

Linux Clients are working OK with same Rabbitmq, SSL enabled.

## Possible Solution
stunnel - but this is very last resort due to fact that Sensu Client should have native implementation.

## Steps to Reproduce (for bugs)
1. To use rabbitmq with ssl option on Windows Sensu Client

## Context
Gap in security.

## Your Environment
* Sensu version used: 0.27.0
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): Windows Server 2016
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): N/A

**Comment by mcbsdEU** [comment]
Just small update: same with Windows Server 2012

**Comment by cwjohnston** [comment]
We are tracking this in https://github.com/sensu/sensu-omnibus/issues/124

**Comment by mcbsdEU** [comment]
Thanks, I am closing this one.
