### ISSUE TITLE
Sensu 0.28 was released without relevant documentation for new features

### ISSUE THREAD

**Issue by rankink** [sensu/sensu#1581]
https://sensuapp.org/docs/ does not even list documentation for 0.28 and it was released four days ago.  If it's not documented, it shouldn't be released.

And for what very little there is, I would like to include a sample to consider.  I understand it, but I suspect that it's not understood how few users are likely to:
  "Added proxy check requests to improve Sensu's ability to monitor external resources that have an associated Sensu proxy client. Publish a check request to the configured subscribers (e.g. ["round-robin:snmp_pollers"]) for every Sensu client in the registry that matches the configured client attributes in client_attributes on the configured interval (e.g. 60). Client tokens in the check definition (e.g. "check-snmp-if.rb -h :::address::: -i eth0") are substituted prior to publishing the check request. The check request check source is set to the client name."

This feature is a very big deal and begins to address a major failing in Sensu as a monitoring platform.  It should have absolutely included appropriate documentation.

**Comment by mcbsdEU** [comment]
Hi,

I am of same opinion as OP. Specially for this big feature.
Anyway, thanks to Sensu guys for doing great improvements!:)

**Comment by kshep** [comment]
While there's a GitHub 'release' for 0.28, is that just the first step in some more comprehensive release process? The deb repo still has 0.27.1 as the latest version.

**Comment by portertech** [comment]
The 0.28 release hasn't yet been packaged, documentation efforts are underway:

https://github.com/sensu/sensu-docs/issues/523

https://github.com/sensu/sensu-docs/issues/522

https://github.com/sensu/sensu-docs/issues/521

https://github.com/sensu/sensu-docs/issues/520

**Comment by portertech** [comment]
Deploying the doc updates.

**Comment by portertech** [comment]
Documentation will undoubtedly need to be improved, as it seems many users are chomping at the bit.

**Comment by mcbsdEU** [comment]
Thank You
