### ISSUE TITLE
RPMS for 0.27 and 0.28

### ISSUE THREAD

**Issue by robertlabrie** [sensu/sensu#1583]
Please package and distribute RPMs for the latest releases.

Thanks!

**Comment by amdprophet** [comment]
Sensu 0.27 RPMs are already available in the yum repositories; 0.28 has not yet been released. Please make sure you are using the new repository structure as detailed by our blog post: https://sensuapp.org/blog/2017/01/31/sensu-core-v0-27-0.html

Additionally, the downloads page is currently being restructured for the new, distribution-specific releases. If you'd like to download the RPMs via a direct URL, you may find the files in the yum repository: http://sensu.global.ssl.fastly.net/yum/.

**Comment by johntdyer** [comment]
@amdprophet -   Does this mean .28 is released ?  

https://github.com/sensu/sensu/blob/master/CHANGELOG.md

**Comment by amdprophet** [comment]
@johntdyer - CHANGELOG.md is updated prior to a release and typically (but not always) means a release is imminent.

Sensu 0.28 has been released since this issue was closed.
