### ISSUE TITLE
Feature request for Proxy requests: client_attributes match on array members

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1585]
## Expected Behavior
We are using proxy clients where we still use "subscriptions" field even you can't work with this directly. However, it is handy in combination with custom back-end. 

client_attributes are used to identify for which proxy client to generate request.
Seems it is working based on exact match.

It would be handy if the match could be configured on array members.
Etc. proxy client has subscriptions ["net_generic", "cisco_ios", "..."].
Check could be configured as:
.........
      "proxy_requests": {
        "client_attributes": {
          "subscriptions": ["cisco_ios"]
        }
.........

## Current Behavior
By example above, client attributes must have exact match:
.........
      "proxy_requests": {
        "client_attributes": {
          "subscriptions": ["net_generic", "cisco_ios", "..."]
        }
.........

This makes the usage bit less practical.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
* Sensu version used: 0.28
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

Thanks!

**Comment by portertech** [comment]
You can do:

`"subscriptions": "eval: value.include?('cisco_ios')"`

AND/OR

`"subscriptions": "eval: ["net_generic", "cisco_ios"].all? {|sub| value.include?(sub)}"`

**Comment by mcbsdEU** [comment]
Thanks a lot!
