### ISSUE TITLE
support redis database other than 0

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1587]
It would be cool if sensu server would support database selection:
http://www.rediscookbook.org/multiple_databases.html

My usecase is havig mutiple sensu-servers (for different projects or customers) using a single redis cluster on AWS.

**Comment by portertech** [comment]
@runningman84 you can configure `{"redis": {"db": 1}}`

**Comment by portertech** [comment]
See https://sensuapp.org/docs/0.28/reference/redis.html#redis-attributes for documentation.
