### ISSUE TITLE
Add support for sensu-install to utilize a proxy server

### ISSUE THREAD

**Issue by seifer44** [sensu/sensu#1588]
The `sensu-install` command does not have support for a proxy server. This should be added, since not all servers have direct access to download plugins.

## Expected Behavior
A switch for `sensu-install` to provide a proxy server to use for the download.

## Current Behavior
A switch to use a proxy server is not present.

## Possible Solution
Add in an option for gem to use a proxy server, since this is already supported.

## Context
I have servers that must use a proxy server to download sensu plugins, and are not able to utilize this tool like I had hoped.

## Your Environment

* Sensu version used: 0.27.0
* Active Sensu extensions (e.g. WizardVan 0.1.0): disk-checks, memory-checks
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ 3.6.2

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1589 implements this :+1: Thank you!
