### ISSUE TITLE
Proxy Requests: Silencing Capability

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1596]
## Expected Behavior
I was dealing with this in past when proxy requests were not available and workarounds were only option. However, situation is same also for proxy requests.
This is applicable not only to "proxy requests" itself but all checks which are created "ad-hoc" when using Results API.

Proxy check is executed by real Sensu Client _on behalf_ of source, which is for instance generic network device communicating just with SNMP.
Proxy check is created out of result, where source attribute is replaced by name of network device.
All look good at this time. Proxy client has its own "proxy check".

It is possible to create silencing (via API, etc. by Uchiwa) for particular check@device, however, it is being ignored and handler is executed anyway.

Silencing should be possible also for results delivered by Results API / proxy requests.

## Current Behavior
Silencing is ignored.

## Possible Solution
If POST request to Results API had option to include "silenced": true, this could work at least from manual perspective.

## Steps to Reproduce (for bugs)
1. Create proxy request or do POST request to Results API
2. Create silencing for just created check
3. Observer handler execution

## Context
If this was fixed, proxy requests would be shifted to fully usable alternative to real Sensu Clients.

## Your Environment
* Sensu version used: 0.28
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by Hydrochoerus** [comment]
Related to this issue, if I am not mistaken: Proxy checks cannot be issued currently through the API (they are not registered, /checks does not list them). I would love to have proxy-whatevers to be treated as close to standard checks/clients/etc. as possible in the future, as this would make Sensu much usable/user-friendly in my opinion.

**Comment by portertech** [comment]
@Hydrochoerus good point. The API should list them via `/checks` (after a restart), however, the API is not currently capably of issuing proxy check requests. I'll create an issue to track this and add to the 0.29 milestone.

**Comment by portertech** [comment]
@mcbsdEU see ^^, the API `/request` endpoint doesn't currently support publishing proxy check requests.

**Comment by portertech** [comment]
I have created https://github.com/sensu/sensu/issues/1597

**Comment by cwjohnston** [comment]
@mcbsdEU I suspect that part of what you're experiencing here is that clients created by posting to `/clients` API are not getting per-client subscriptions added automatically, which makes it impossible to silence them individually. Silencing is expected to work for both real and proxy clients, so this seems like a bug.

**Comment by portertech** [comment]
@cwjohnston ah snap! :+1:

**Comment by mcbsdEU** [comment]
@cwjohnston: Indeed, thanks for opening separate thread for tracking this "bug".
I must say that all you guys are reacting very fast and to the point. Not seen often so keep going because you are making motto of Sensu real.

**Comment by portertech** [comment]
Sensu 0.28.3-1 includes this fix and the client in progress check execution fix.
