### ISSUE TITLE
Proxy Requests: Possible bug when check executed via API

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1599]
## Expected Behavior
See reference [#1584](https://github.com/sensu/sensu/issues/1584).

When proxy check is defined as in the reference, now, after fixing the bug, proxy requests are correctly generated with tokens replaced by client variables.

However, when the same check is requested manually via Checks API/request (etc. by Uchiwa), check itself is _also_ executed on helper itself (Sensu Client which is executing command on behalf of proxy client). In my setup, Sensu Client is same machine as Sensu Server.

As a result, event is created for helper like this:
...............
"message":"publishing check result","payload":{"client":"sensu01","check":{"type":"standard","handlers":["default"],"command":"/opt/sensu/embedded/bin/check-graphite-data.rb -v -s https://xyz -u user -p userpass -t 'nPercentile(:::environment:::.:::name:::.cpu.cpu1.5min,90)' -w 70 -c 80 -f '-60min'"
...............
1) with tokens names instead of variables
2) but the main issue is that it is executed at all.

Proxy check should not be executed on helper level when triggered manually via API.
Generation of proxy requests should be done only for proxy clients matching client_attributes.

## Current Behavior
When proxy check is triggered manually via API, two executions are done:
a) for proxy clients matching client_attributes - OK
b) for sensu client itself responsible for execution on behalf of proxy clients - NOT OK

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. create proxy check as defined in reference issue above
2. manually issue check request for given check - etc. by Uchiwa
3. observe event created for sensu client/helper with tokens names only (when used)

## Context
N/A

## Your Environment
* Sensu version used: 0.28.1
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

Thanks

**Comment by mcbsdEU** [comment]
Hi,

any update on this? Could you reproduce this issue?
Thx

**Comment by portertech** [comment]
We have reproduce this issue. We have added support for issuing proxy check requests via API /request to the upcoming 0.29 release https://github.com/sensu/sensu/pull/1609, which we expect to ship next week :+1:
