### ISSUE TITLE
Proxy requests: Sensu Client/Helper is blocking multiple execution of command

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1600]
## Expected Behavior
When proxy check is created, it generates proxy requests to all proxy clients matching client_attributes.

Sensu Client/Helper (executing check on behalf of proxy clients) receives check request, however the command is executed only for the first proxy client, for other client it throws:

"warn","message":"previous check command execution in progress"

As a result, output is sent to Sensu Server only for first proxy client. Rest is ignored.
Sensu Client/Helper should execute command for all proxy clients and deliver respective outputs to Sensu Server.

## Current Behavior
Command is not executed for all proxy clients, only for one, the rest is ignored.

I also tested check with command:
sleep `shuf -i 1-5 -n 1`; /some/path/to/script

-to introduce some delay into execution but result is same. I also tested with very simple bulk command without any attributes or tokens but also same.

In my test set-up, Sensu Client/Helper runs on same machine as Sensu Server.
## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Create proxy check in way that more than one proxy client will be matched
2. Observer sensu-client.log of given Sensu Client/Helper to which real check is subsribed
3. Search for message "previous check command execution in progress"
4. Observe Uchiwa for all involved proxy clients if they have given proxy request registered.
Only one of them should have it, the rest not.

## Your Environment
* Sensu version used: 0.28.1
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

Thank You

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1608 implements an improvement to in progress check execution tracking :+1:
