### ISSUE TITLE
Keepalive declared thresholds do not override the default ones

### ISSUE THREAD

**Issue by valeriujieanu** [sensu/sensu#1603]
## Expected Behavior

The warning/critical thresholds should override the defaults 120/180 seconds ones.

## Current Behavior

The default 120/180 seconds thresholds are used.

## Steps to Reproduce (for bugs)

1. Add this configuration in /etc/sensu/conf.d/client.json.
```
    "keepalive": {
      "handler": "notify_all",
        "warning": 40,
        "critical": 60
      }
```
2. Restart sensu-client.
3. Stop sensu-client.
4. Check the Uchiwa interface or a handler expected to be executed (eg. Slack).
![image](https://cloud.githubusercontent.com/assets/18589491/23656040/b019f082-0340-11e7-9664-6b51c2e075c4.png)
![image](https://cloud.githubusercontent.com/assets/18589491/23656063/c9bf7714-0340-11e7-93c7-1fbcd026339c.png)

## Context

I am trying to have keepalive alarms triggering the handlers while using custom thresholds.

## Your Environment

* Sensu version used: `sensu-0.26.5-2.x86_64`
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): Red Hat Enterprise Linux Server release 6.4 (Santiago)
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): `rabbitmq-server-3.6.0-1.noarch` on `erlang-19.2-1.el6.x86_64`

**Comment by valeriujieanu** [comment]
The `notify_all` handler contains all the handlers in our Sensu configuration (Slack is used as an example).

**Comment by mcbsdEU** [comment]
Working for me...
values must be enclosed into thresholds:
Etc.:
    "keepalive": {
      "thresholds": {
        "warning": 60,
        "critical": 60
      },
      "auto_resolve": false
    }

**Comment by valeriujieanu** [comment]
Hello,

I messed up with the json while copy-pasting. I am sorry about this.
I am testing with this:
```
    "keepalive": {
      "handler": "notify_all",
      "thresholds": {
        "warning": 40,
        "critical": 60
      }
    }
```
Also, here are the docs. https://sensuapp.org/docs/0.27/reference/clients.html#keepalive-attributes
I did not find the `auto_resolve` attribute in them.

Thanks !

**Comment by mcbsdEU** [comment]
auto_resolve is not directly documented as keepalive attribute, however I found it working same as check attribute.

**Comment by valeriujieanu** [comment]
It works fine. I close the issue. Thanks.
![image](https://cloud.githubusercontent.com/assets/18589491/23659917/6d7a5e1e-0350-11e7-9012-78c47ef1a825.png)
