### ISSUE TITLE
Feature: Stashes API sub-path endpoint

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1604]
## Expected Behavior
Stashes are perfect to store dynamic client data.
Paths may look like:
<name_of_client_1>/DynamicData1
<name_of_client_1>/DynamicData2
<name_of_client_2>/DynamicData3
<name_of_client_2>/<component_name>/DynamicData4
...

Stashes API could support providing partial path returning output just for supplied path and further.

By example given above it could look like:
/stashes/<name_of_client_1> - returning DynamicData1&DynamicData2
/stashes/<name_of_client_2> - returning DynamicData3&<component_name>/DynamicData4
/stashes/<name_of_client_2>/<component_name> - returning DynamicData4

## Current Behavior
Only full path is supported or endpoint "/stashes" for all stashes

## Possible Solution
Scripting.
With hundreds of structured stashes, endpoint "/stashes" is unnecessarily "heavy" when used frequently.

## Steps to Reproduce (for bugs)
N/A

## Context
Just an idea about handy enhancement.

## Your Environment
* Sensu version used: 0.28.2
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by portertech** [comment]
The upcoming 0.29 release will include API response content filtering - https://github.com/sensu/sensu/pull/1595, allowing you to do things like GET `/stashes?filter.content.some.stash.key=foo`, only displaying matching stashes.

**Comment by portertech** [comment]
We are not going to implement this feature as described in this issue.

**Comment by mcbsdEU** [comment]
Filtering is also good idea.
