### ISSUE TITLE
Feature: Setting to split result processing from scheduling

### ISSUE THREAD

**Issue by gwagner** [sensu/sensu#1605]
This is an offshoot of this ticket, but a different use case: https://github.com/sensu/sensu/issues/1537

The way sensu works today, Scheduling is a function of the leader.  The leader can also do result processing.  

Scenario one: after adding the aforementioned "butt load" of servers, if there is any kind of monitoring event [massive outage, massive set of new checks to be scheduled] and result processing becomes overwhelmed, scheduling of new checks on the system will start to suffer / be delayed / stop. 

The second scenario impacted by this design is the way Handlers are implemented.  From a plugable interface POV, handlers are perfect.  From a large system POV, handlers are overwhelming and can cause catastrophic failure of a BIG environment quickly.

The third scenario impacted by this design is the way config reload are performed.  Doing a graceful shutdown of a sensu server that is overwhelmed by result processing (docker or physical) will cause checks to not get scheduled.  This is extremely problematic when it comes to metrics and loss of metrics due to checks not getting scheduled.

I would like to see a setting get implemented where the scheduling leader can be setup so it will never process results.  The only thing that leader ever does is schedule checks to go out > systems will process > results will hit the rest of the cluster.  In an HA configuration, this should be part of the election process and not pinned to a specific node.  The registry you just built should be a perfect mechanic for tracking this kind of thing and making sure something is always scheduling.

This  could be expanded even farther to the queue / redis database.  Any result that has a status change gets a new message thrown into the queue / redis.  A role could be elected as a percentage of the entire server pool - 1 that are handler processors for events.  This would cut down any events of any single part of the system getting overwhelmed and having GLOBAL impact to the entire server environment.  

If there is only a single server int he cluster, then obvi, it holds all the roles anyway and this logic goes out the window.

## Expected Behavior
Better segmentation of roles for larger environments will lead to more stability and more consistent check scheduling.

## Current Behavior
When the leader is overwhelmed, EVERYTHING MELTS

## Possible Solution
Scheduler should not be a result processor

## Steps to Reproduce (for bugs)
1. Get a butt load of machines
1. Have that but load of machines have a butt-loadier number of checks
1. Have a ton of handlers fire all at once
1. Watch things MELT

## Context
This is a scaling issue for larger environments.  We are going to be eclipsing 1000 machines currently split between 2 sensu environments to mitigate this flaw.  We will need to continue to spin up new environments to mitigate this impact.

## Your Environment

1000 machines running 16M checks / metrics per day

**Comment by portertech** [comment]
We intend to split up the Sensu server leader tasks, allowing multiple Sensu servers to contribute, spreading the load amongst them https://github.com/sensu/sensu/issues/1537

**Comment by gwagner** [comment]
@portertech The spirit of this ticket is centered around more than pure splitting.  Today, scheduling can be compromised by result processing / TTL processing / keepalive processing.  This ticket takes role splitting a bit more granular by requesting that: Scheduling can be siloed off to its own server & result processing (in a multi server environment) cannot happen on the box scheduling checks.  Today, at scale, there are many scenarios we face where parts of the system can obliterate functionality on other parts of the system.  This is forcing us into situations where we need to have multiple sensu implementations running simultaneously rather than taking the benefits of the core ideals of sensu (horizontal scalability).

I would be happy to have a more in depth conversation about what we are seeing if we can get together on something like slack (or the dreaded telephone...).

**Comment by gwagner** [comment]
@portertech any update on this?

**Comment by gwagner** [comment]
@portertech are you going to be at the conference?  Can we chat there about this ticket?

**Comment by portertech** [comment]
@gwagner I am going to be at the Sensu Summit in August 👍 The team at Sensu Inc is making significant progress on the next generation of Sensu (2.0), which stays true to the core principles and features of Sensu, but takes a very different approach (particularly with the distribution of work). I am reluctant to make these sorts of changes with Sensu 1.x, as they will be superseded by the upcoming version. I recently published a blog post about Sensu 1.0 and the 1.x roadmap, here: https://blog.sensuapp.org/sensu-core-version-1-0-is-now-available-c93b61977933. I hope to publish a blog post about 2.0 and what we are building, very soon! Will I see you at the Sensu Summit? I would love to show you what we're building and have this conversation under its light 👍

**Comment by gwagner** [comment]
I will be there and i am speaking :)

**Comment by portertech** [comment]
Closing this issue as Sensu 2.x is a complete rewrite and fully distributes these tasks 👌 https://github.com/sensu/sensu-go
