### ISSUE TITLE
Upgrade to sensu 0.28.2 - Handlers not found

### ISSUE THREAD

**Issue by petecheslock** [sensu/sensu#1606]
Greetings!

## Expected Behavior
Putting handlers into `/etc/sensu/handlers` should allow them to be found when you setup the handler config like
```
{
  "handlers": {
    "slack": {
      "type": "pipe",
      "filters": [
        "force_resolve",
        "actions",
        "occurrences"
      ],
      "command": "slack.rb"
    }
  }
}
```
## Current Behavior
With the upgrade to 0.28.2 - You will get the following error instead
```
{"timestamp":"2017-03-08T17:22:43.644999+0000","level":"error","message":"handler output","handler":{"type":"pipe","filters":["force_resolve","actions","occurrences"],"command":"slack.rb","name":"slack"},"event":{"id":"299ad095-8b97-4e84-
9441-d91f92c49428"},"output":["sh: 1: slack.rb: not found\n"]}
```
## Possible Solution
In the handler config - if you change the command to the full path - it handler will execute properly.

## Context
I didn't see anything in the changelogs that might be related to this - i've confirmed in the init scripts that the env vars are set correctly.
in the `/etc/init.d/sensu-server`
```
HANDLERS_DIR=/etc/sensu/handlers
```

## Your Environment
* Sensu version used: 0.28.2
* Ubuntu 14.04

**Comment by cwjohnston** [comment]
Hi @petecheslock, thanks for opening this issue. I can see that `PATH` set in `/etc/init.d/sensu-server` is not being properly passed along in the environment when `sensu-server` is ultimately started. 

This seems like a bug to me, so I've opened https://github.com/sensu/sensu-omnibus/issues/153 to track this in the project where those scripts live.

**Comment by petecheslock** [comment]
@cwjohnston Cool - lemme know - I also checked out a 16.04 sensu server i had running and that also seems similarly affected.  Although with systemd i'm not sure where the env vars are being sent anyway.

**Comment by cwjohnston** [comment]
@petecheslock I agree, systemd is similarly affected. I opened https://github.com/sensu/sensu-omnibus/issues/154 for that.

In the sysv case, environment variables aren't being passed along when calling `sensu-service` and in the systemd case, `sensu-server` simply doesn't configure HANDLER_DIR as it should.

**Comment by portertech** [comment]
Sensu 0.28.4-1 has this fix :+1:
