### ISSUE TITLE
streaming results and events out of sensu

### ISSUE THREAD

**Issue by cabecada** [sensu/sensu#1613]
We need a feature to be able to stream both results and events data to a tcp/http for storage.
We need this feature to be able to push both results and events to logging framework to be able to make dashboards and also to go back in history to check when a particular check started failing etc.

I know this is available only in the enterprise version for now, but we need this feature in open source version too.

**Comment by mcbsdEU** [comment]
What about creating handler for this purpose?

**Comment by cabecada** [comment]
Results are not exposed to handlers

**Comment by mcbsdEU** [comment]
You can pass results with return code "0" to handler as well - which means every result.

**Comment by cabecada** [comment]
Not sure if I get you correctly.
Only events trigger handlers, iirc when I looked at source.
I'll check again later.
But if u are referring to event resolved to simulate result, this is not what I wanted.
It would never give me those checks which never failed.

Thanks
Vijay

Sent from my iPhone

On 10-Mar-2017, at 8:03 PM, mcbsdEU <notifications@github.com<mailto:notifications@github.com>> wrote:


You can pass results with return code "0" to handler as well - which means every result.

**Comment by mcbsdEU** [comment]
Event is created from result with return code !=0 by default.
By using filters you can make it happen for 0 as well I guess.
Similarly from doc:
"Setting type to metric will cause OK (exit 0) check results to create events. "
Which is bit wrong because event as it is not created, it just enables passing through handler.

**Comment by cabecada** [comment]
I hope it does not break existing handlers but will check.
Thanks @mcbsdEU

Thanks
Vijay

Sent from my iPhone

On 10-Mar-2017, at 8:17 PM, mcbsdEU <notifications@github.com<mailto:notifications@github.com>> wrote:


Event is created from result with return code !=0 by default.
By using filters you can make it happen for 0 as well I guess.
Similarly from doc:
"Setting type to metric will cause OK (exit 0) check results to create events. "
Which is bit wrong because event as it is not created, it just enables passing through handler.

**Comment by mcbsdEU** [comment]
Just don't use "metric" type without a reason - it was just example of similar situation where you need to pass OK results to handler.
Play with filters and assign filter to handler.

**Comment by portertech** [comment]
@cabecada you could write a bridge extension to send every event somewhere (every result creates an event), like https://gist.github.com/portertech/a4624f6c0f1760c0726b802eafb6ffce, and drop it into /etc/sensu/extensions on your sensu server machine.

**Comment by portertech** [comment]
@cabecada keep in mind that the bridge extension cannot use blocking IO, so it must either use EventMachine libraries or an `EM.defer {}` to wrap IO. Sensu Enterprise uses a bridge extension for its event stream integrations.
