### ISSUE TITLE
Windows - Large sensu-client.log file - Log rotation?

### ISSUE THREAD

**Issue by dzeleski** [sensu/sensu#1617]
Sensu agent version 26.5.1 on server 2012 R2 is fairly large at 400MB, log starts at install date and does not rotate. 

## Expected Behavior
I would expect the log to be truncated every so often or rotated every 24 hours.

## Current Behavior
Log does not rotate, keeps logging to one file. Client installed on 2/27/17 and the log file was created on 2/6/17 (agent was upgraded). [Screenshot](http://imgur.com/a/TVTs1)

Is this fixed in a newer version of the sensu agent? I looked through the change logs and couldnt find anything pertaining to this issue.

**Comment by jothoma1** [comment]
:+1:  Same for me

**Comment by dzeleski** [comment]
https://github.com/sensu/sensu-puppet/issues/618 FYI ive solved this here, im letting it run for a few days to make sure it works but I think this is the solution. @jothoma1

**Comment by cwjohnston** [comment]
@dzeleski @jothoma1 thanks for bringing this to our attention. I believe a fix for this issue will need to land in the sensu-omnibus project so I've opened https://github.com/sensu/sensu-omnibus/issues/165 to track it there.
