### ISSUE TITLE
[Bug] Sensu not calling custom handlers

### ISSUE THREAD

**Issue by ppanucool** [sensu/sensu#1618]
Hi,

I have created custom mail handler using python. (Which uses amazon ses and sends a mail in a different format)

{
  "handlers": {
    "email": {
      "type": "pipe",
      "command": "echo $(/bin/cat) | /usr/bin/python /home/ubuntu/roshan_scripts/test.py &>> /home/ubuntu/someFile.txt",
      "severities": [    
        "critical",
        "unknown"
      ]
    }
  }
}

My test.py is a python script, which will send a mail to few people.
But my problem is, Sensu don't call this handler on check execution.

Note: i have already placed this handler "email" on multiple checks

**Comment by dzeleski** [comment]
Are you sure its not calling it? I would look at the sensu-server.log file. I would guess that sensu does not have permissions to the script itself, or access to a system resource that your script is calling as the sensu user.

**Comment by portertech** [comment]
You command should look like:

`"/home/ubuntu/roshan_scripts/test.py &>> /home/ubuntu/someFile.txt"`

Be sure to make `test.py` executable, e.g. `chmod +x test.py`.

**Comment by ppanucool** [comment]
Thanks @portertech .
can you please help me with this issue : https://github.com/sensu/sensu/issues/1673
