### ISSUE TITLE
[Bug] - /etc/defaults/sensu being overwritten on update

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1622]
## Expected Behavior
Content of the  /etc/defaults/sensu should be preserved, etc. when using
LOG_LEVEL=error

## Current Behavior
Whole file is being replaced on update.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Enter some parameter into  /etc/defaults/sensu
2. Update Sensu
3. Check the content of /etc/defaults/sensu

## Context
N/A

## Your Environment
* Sensu version used: 0.28.4
* Operating System and version (e.g. Ubuntu 14.04):
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by amdprophet** [comment]
Hi @mcbsdEU, this is an issue with the packaging process handled by `https://github.com/sensu/sensu-omnibus`. Can you please open this issue against that repo?

#monitoringlove
