### ISSUE TITLE
2 sensu client instances same machine

### ISSUE THREAD

**Issue by macdutra** [sensu/sensu#1625]
## Expected Behavior

I have 2 sensu instances in same machine, until upgraded it to the version 0.28.4 it was working normally, but after sensu-client process open 2 ports 3030 and 3031 and the other confguration doesn't up and the sensu log shows me tcp port is in use. I guess the second configuration try to start bind port 3035 and 3031, but last one it was open by first instance.

Below my configuration:

#/etc/sensu/conf.d/config.json
{
  "client": {
    "name": "sensu_monitoring",
    "address": "192.168.1.83",
    "subscriptions": [ "SNMP" ]
  }
}

#/home/sensu/config.d/config.json
{
  "client": {
    "name": "sensu",
    "address": "192.168.1.83",
    "subscriptions": [ "OS" ],
        "socket": { "bind": "127.0.0.1", "port": 3035 }
  }
}

     

## Steps to Reproduce (for bugs)

1. Start first sensu-client instance
2. Start second sensu-client instance
3. Sensu-client doesn't start

## Context

Sensu Log

{"timestamp":"2017-03-17T13:00:26.863056-0300","level":"warn","message":"config file does not exist or is not readable","file":"/home/sensu/config.json"}
{"timestamp":"2017-03-17T13:00:26.863144-0300","level":"warn","message":"ignoring config file","file":"/home/sensu/config.json"}
{"timestamp":"2017-03-17T13:00:26.863171-0300","level":"warn","message":"loading config files from directory","directory":"/home/sensu/conf.d"}
{"timestamp":"2017-03-17T13:00:26.863193-0300","level":"warn","message":"loading config file","file":"/home/sensu/conf.d/config.json"}
{"timestamp":"2017-03-17T13:00:26.863211-0300","level":"warn","message":"loading config file","file":"/home/sensu/conf.d/rabbitmq.json"}
{"timestamp":"2017-03-17T13:00:26.863233-0300","level":"warn","message":"config file applied changes","file":"/home/sensu/conf.d/rabbitmq.json","changes":{"rabbitmq":[null,[{"host":"sensu-cluster-01","port":5672,"vhost":"/sensu_rabbit","user":"sensu_rabbit","password":"mypass","heartbeat":30,"prefetch":50},{"host":"sensu-cluster-02","port":5672,"vhost":"/sensu_rabbit","user":"sensu_rabbit","password":"mypass","heartbeat":30,"prefetch":50},{"host":"sensu-cluster-03","port":5672,"vhost":"/sensu_rabbit","user":"sensu_rabbit","password":"mypass","heartbeat":30,"prefetch":50}]]}}
{"timestamp":"2017-03-17T13:00:26.863286-0300","level":"warn","message":"applied sensu client overrides","client":{"name":"sensu","address":"192.168.1.83","subscriptions":["OS","client:sensu"],"socket":{"bind":"127.0.0.1","port":3035}}}
{"timestamp":"2017-03-17T13:00:26.866870-0300","level":"warn","message":"loading extension files from directory","directory":"/home/sensu/extensions"}
{"timestamp":"2017-03-17T13:00:26.866962-0300","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2017-03-17T13:00:27.002178-0300","level":"warn","message":"transport connection error","reason":"tcp connection lost"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:530:in `start_server'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/client/process.rb:423:in `setup_http_socket'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/client/process.rb:435:in `setup_sockets'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/client/process.rb:511:in `block in start'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/daemon.rb:278:in `block in setup_transport'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-7.0.2/lib/sensu/transport.rb:26:in `block in connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/em/deferrable.rb:151:in `set_deferred_status'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/em/deferrable.rb:191:in `succeed'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-7.0.2/lib/sensu/transport/rabbitmq.rb:222:in `block in setup_connection'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/em/deferrable.rb:151:in `set_deferred_status'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/em/deferrable.rb:191:in `succeed'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:682:in `connection_successful'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:1040:in `handle_open_ok'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:1136:in `block in <class:Session>'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:959:in `receive_frameset'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:933:in `receive_frame'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/client/process.rb:19:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'

## Your Environment

* Sensu version used: 0.28.4-1
* Operating System and version: Ubuntu 16.04.2 LTS

**Comment by cwjohnston** [comment]
Hi @macdurta, I think the behavior you describe has to do with the HTTP client socket, added in version 0.27, which listens on 3031 by default. 

Please see https://sensuapp.org/docs/latest/reference/clients.html#http-socket-attributes for information on reconfiguring the default port using client HTTP socket configuration attributes.
