### ISSUE TITLE
Sensu-client cannot restart

### ISSUE THREAD

**Issue by uojiaku** [sensu/sensu#1627]
Expected Behavior:
I tried to restart sensu-client with service sensu-client restart as a root user but I ended up getting this error.

[root@myserver ~]# service sensu-client restart
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `initialize': Permission denied @ rb_sysopen - /opt/sensu/embedded/lib/ruby/gems/2.3.0/specifications/sensu-plugins-filesystem-checks-0.2.0.gemspec (Errno::EACCES)
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `open'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `data'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:202:in `valid?'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:749:in `select'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:749:in `gemspec_stubs_in'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:774:in `block in map_stubs'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `each'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `flat_map'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `map_stubs'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:763:in `installed_stubs'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:831:in `stubs'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1036:in `find_by_path'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:209:in `try_activate'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from <internal:gem_prelude>:6:in `<internal:gem_prelude>'

Log:
I've checked the sensu-client log and this is what it says:

{"timestamp":"2017-03-17T15:59:19.256871-0400","level":"info","message":"received check request","check":{"command":"/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-fs-writable.rb -d /tmp","handlers":["uoemail","mjemail"],"name":"fs-writable","issued":1489780759}}
{"timestamp":"2017-03-17T15:59:19.449217-0400","level":"info","message":"publishing check result","payload":{"client":"myserver.newbeginnings.com","check":{"command":"/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-fs-writable.rb -d /tmp","handlers":["uoemail","mjemail"],"name":"fs-writable","issued":1489780759,"interval":10,"subscribers":["condor","production","qa"],"executed":1489780759,"duration":0.192,"output":"/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `initialize': Permission denied @ rb_sysopen - /opt/sensu/embedded/lib/ruby/gems/2.3.0/specifications/sensu-plugins-filesystem-checks-0.2.0.gemspec (Errno::EACCES)\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `open'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:111:in `data'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:202:in `valid?'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:749:in `select'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:749:in `gemspec_stubs_in'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:774:in `block in map_stubs'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `each'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `flat_map'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:771:in `map_stubs'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:763:in `installed_stubs'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:831:in `stubs'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1036:in `find_by_path'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:209:in `try_activate'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'\n\tfrom <internal:gem_prelude>:6:in `<internal:gem_prelude>'\n","status":1}}}

My attempt to fix issue:
Sensu-client was initially running so I killed the process with 'kill -9' since then sensu-client hasn't started back up and as a result the keepalive alert is at critical on uchiwa.

Environment:
* Sensu version used: 0.26.5
* Operating System and version (e.g. Ubuntu 14.04): CentOS 6.8
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ server 3.1.5; Erlang R14B

**Comment by cwjohnston** [comment]
Hi @uojiaku, sounds like file permissions may be causing an error at startup. Are the `/opt/sensu/embedded/lib/ruby/gems/2.3.0/specifications/sensu-plugins-filesystem-checks-0.2.0.gemspec` file and its parent directories readable by the `sensu` user?

**Comment by uojiaku** [comment]
Ok so I made sure that the permissions were changed; it turns out that many of the files in that /specifications directory only had read permissions for root.

So this what I got now:

[root@myserver specifications]# service sensu-client restart
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
configuration is valid
Stopping sensu-client/etc/init.d/sensu-service: line 260: kill: (86926) - No such process
                                                           [FAILED]
[root@myserver specifications]# gem pristine unf_ext --version 0.0.7.2
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gem unf_ext = 0.0.7.2
[root@myserver specifications]# gem install unf_ext --version 0.0.7.2
Building native extensions.  This could take a while...
ERROR:  Error installing unf_ext:
	ERROR: Failed to build gem native extension.

/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/ruby.h


Gem files will remain installed in /usr/lib/ruby/gems/1.8/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /usr/lib/ruby/gems/1.8/gems/unf_ext-0.0.7.2/ext/unf_ext/gem_make.out

**Comment by cwjohnston** [comment]
@uojiaku this seems like another permissions issue -- the` unf_ext` gem should be trying to load native extensions from somewhere under `/opt/sensu/embedded/lib` and likely doesn't have sufficient file or directory permissions.  Your invocation of `gem` appears to be using your system Ruby. The error coming from starting sensu-client relates to Sensu's embedded Ruby, so the `gem` command should be invoked as `/opt/sensu/embedded/bin/gem`instead.

Because we can't account for what has modified file permission under `/opt/sensu`, I recommend that you remove and reinstall the Sensu package to definitively address these permissions errors.
