### ISSUE TITLE
proxy check requests: subscriptions attributes

### ISSUE THREAD

**Issue by exeral** [sensu/sensu#1631]
in feature proxy check requests: cannot filter on client subscriptions

## Expected Behavior
using this conf in a check
```
      "proxy_requests": {
        "client_attributes": {
          "subscriptions": "physical"
        }
      }
```

All the clients that subscribes to the "physical" subscriptions should be matched.

## Current Behavior
No clients are matched, the check fallback to the attributes of the poller

## Possible Solution
the subscriptions should not be an exact match
it should match if client **contains** the specified subscriptions.

## Steps to Reproduce (for bugs)
create clients:
```
{
  "client": {
    "subscriptions": [
      "default",
      "physical",
      "application1"
    ],
    "safe_mode": false,
    "address": "10.1.2.3",
    "fqdn": "hostname1.mynetwork",
    "socket": {
      "bind": "127.0.0.1",
      "port": 3030
    },
    "shortname": "hostname1",
    "keepalive": {
    },
    "name": "hostname1.mynetwork",
    "redact": [

    ]
  }
}
```

create check
```
{
  "checks": {
    "ilo": {
      "occurrences": 2,
      "subscribers": [
        "poller"
      ],
      "interval": 300,
      "standalone": false,
      "low_flap_threshold": 20,
      "command": "PATH=/opt/sensu/embedded/bin/:$PATH check-http.rb -k -u https://:::shortname:::.ilo/xmldata?item=all",
      "high_flap_threshold": 60,
      "proxy_requests": {
        "client_attributes": {
          "subscriptions": "physical"
        }
      },
      "handlers": [ "debug" ],
      "refresh": 600
    }
  }
}
```

## Context
In my example, I want an external poller to check all physical servers HP iLO card with http

I tried various config:
if I set
```
      "proxy_requests": {
        "client_attributes": {
          "shortname": "hostname1"
        }
      }
```
the attributes are well replace by the source attributes of hostname1

if I set
```
      "proxy_requests": {
        "client_attributes": {
          "subscriptions": "[\"default\", \"physical\", \"application1\", \"client:hostname1.mynetwork\"]"
        }
      }
```
the attributes are well replace by the source attributes of hostname1.
it makes me think the code do an exact match of attrbiutes.

As a workaround, I could add a custom attribute like: "type": "physical" to all the clients with pysicial subscriptions.
but I'm duplicating data, it's bad :(

I bet we have the same problem for other attributes which are arrays.

## Your Environment
sensu: 0.28.2 (clients + server)
Centos 6

**Comment by mcbsdEU** [comment]
Hi,

please refer to [#1585](https://github.com/sensu/sensu/issues/1585).
You can use ruby's eval.

**Comment by exeral** [comment]
thanks !
I'm not able to get it working now but it seems another story.

This tip should be referenced somewhere :)

**Comment by portertech** [comment]
@exeral try `"subscriptions": "eval: value.inlcude?('physical')"`

**Comment by portertech** [comment]
I've mentioned this issue in the sensu-doc issue https://github.com/sensu/sensu-docs/issues/528 :+1:
