### ISSUE TITLE
Token substitution with aggregates

### ISSUE THREAD

**Issue by betorvs** [sensu/sensu#1635]
Hi all, I try to use aggregates with token and works.
But in aggregates view in uchiwa and in api GET too, the custom attribute appeared.

curl -s -X GET http://localhost:4567/aggregates
[...{"name":"**:::cluster:::**"},{"name":"healthcheck"}...]

## Expected Behavior
Creates aggregates with some names, like webserver and :::custom_attribute:::, and in aggregates GET, see webserver and a lot of new aggregates from custom_attribute (like linux, application but from sensu clients).

## Current Behavior
This works, but in aggregates api GET show the custom attribute not the substitute from custom attribute.

## Steps to Reproduce (for bugs)
1. Create a check with aggregates like "[":::cluster:::","healthcheck"]"
```
{
  "checks": {
    "healthcheck": {
      "command": "check-http-json.rb -u :::url_healthcheck::: -q :::query:::",
      "subscribers": [
        "healthcheck"
      ],
      "aggregates": [
        ":::cluster:::",
        "healthcheck"
      ],
      "handlers": [
        "default"
      ]
    }
  }
}
```
2. List api aggregates: curl -s -X GET http://localhost:4567/aggregates

## Context
Tried to organize my aggregates with custom attribute in sensu client.

## Your Environment
* Sensu version used: 0.28.2
* Active Sensu extensions (e.g. WizardVan 0.1.0): -
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): -

**Comment by portertech** [comment]
@betorvs what version of Sensu is/are the clients? I wonder if they are just not substituting because they are too old.

**Comment by betorvs** [comment]
@portertech all clients are 0.28.2.

**Comment by portertech** [comment]
@betorvs I followed your steps to reproduce, but it successfully creates a named aggregate for the client cluster name. I wonder if it is Uchiwa.

**Comment by portertech** [comment]
Ah, you've already confirmed that it's not.

**Comment by betorvs** [comment]
@portertech The sensu creates 3 aggregates: **linux** from cluster attribute, **healthcheck** from check, and "**:::cluster:::**". 
How to I delete this aggregate ":::cluster:::"?

```
# cat /etc/sensu/conf.d/client.json
{
  "client": {
    "address": "10.0.0.21",
    "subscriptions": [
      "linux",
      "healthcheck"
    ],
    "name": "linux-sensu",
    "cluster": "linux"
    }
}

# curl -s -X GET http://localhost:4567/aggregates
[{"name":"linux"},{"name":":::cluster:::"},{"name":"healthcheck"}]

# curl -i -s -X DELETE http://localhost:4567/aggregates/:::cluster:::
HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Connection: close
Content-length: 0
```

**Comment by portertech** [comment]
@betorvs API DELETE `/aggregates/:::cluster:::` should work, although the colons could be an issue (might need to url encode?). Alternatively, you could stop the Sensu server(s) and API(s) and flush Redis.

**Comment by betorvs** [comment]
Thanks @portertech . I clean via redis flush.
