### ISSUE TITLE
sensu server switch to validate checks and exit

### ISSUE THREAD

**Issue by robertlabrie** [sensu/sensu#1636]
This is a feature request. For CI, it'd help a lot of I could have sensu-server validate all the check definitions and exit 0 or 1. It's gotten a bit stale finding out the check definitions don't work when we try to restart the server and have to grep the logs when it fails to start

**Comment by cwjohnston** [comment]
Hi @robertlabrie, this validation feature is already available in Sensu 0.24 and later. This flag can be used with both sensu-client and sensu-server processes. Please see description of the `--validate_config` flag in our [configuration reference documentation][1].

[1]: https://sensuapp.org/docs/latest/reference/configuration.html

**Comment by robertlabrie** [comment]
Hi Cameron,

`--validate_config` validates the config.json file, but not the checks themselves. A totally broken check definition still returns `configuration is valid`

When we upgraded last, we had all these subdues which weren't right anymore, validate_config found none of them

**Comment by portertech** [comment]
@robertlabrie you still have to run `--validate_config` with the other arguments, e.g. `-d /etc/sensu/conf.d`, or it wont pick up those configuration files.

**Comment by robertlabrie** [comment]
TYVM
