### ISSUE TITLE
Use HTTP status code 405 if no route matches request

### ISSUE THREAD

**Issue by EvaSDK** [sensu/sensu#1641]
## Expected Behavior
When a matching route is found but not for a given request's method, API should return `405 Method Not Allowed` with a list of supported methods for the route if possible, not a 404.

## Current Behavior
Returns a `404 Not Found`

## Possible Solution
Based on my comment in https://github.com/sensu/sensu/commit/28e2ccebb5815023a877ccaf720095dd194d74cd, a method should be added to generate a proper 405 response. I did a sample implementation here: https://github.com/EvaSDK/sensu/commit/638ef67efb905b9f0b8e4d7838f832f7a2d88555 but it is probably just plain wrong as I am no ruby dev.

## Context
405 is the conventional response for such problems.

## Your Environment
* Sensu version used: 0.26.5
* Active Sensu extensions: None
* Operating System and version: Debian 8
* Transport and runtime versions: RabbitMQ 3.3.5 on Erlang 17.3

**Comment by EvaSDK** [comment]
Also please note that while I understand why you might feel the need for your current procedure for PR submission, it feels very repulsive to fill in so many "papers" before anything can be done.

**Comment by portertech** [comment]
@EvaSDK thank you for the issue :+1: #1643 has been merged, the 0.29 release will have this functionality.

**Comment by EvaSDK** [comment]
Perfect, thanks.
