### ISSUE TITLE
Override check command when requesting check via API

### ISSUE THREAD

**Issue by Evesy** [sensu/sensu#1645]
I'd like to open a discussion around the possibility of allowing the overriding of a checks command when issuing a check via the API, so that 'custom' commands can be ran for a pre-configured check; even if the answer is a straight no :)

 A couple of practical examples:

-  I want to run a disk usage check one time to warn anything over 75%, rather than the 85% currently configured.
- I want to override the email attribute in this command and run one time to send somewhere else.

## Expected Behavior
I'd like to be able to request a check via the API with the below payload and have the host in question execute the specified command
```
{
  "check": "system_disk_usage",
  "command": "/opt/sensu/embedded/bin/check-disk-usage.rb -w 5 -c 10",
  "subscribers": [
    "client:host1"
  ],
  "creator": "Mike",
  "reason": "Test check"
}
```
Currently as per [https://github.com/sensu/sensu/blob/65e98d303d5ef2327dc49480e9cbdf7a1ffb3cfa/lib/sensu/api/routes/request.rb#L19-L35](url) only select attributes are subbed in to the copy of the check definition.

## Current Behavior
Only the name, subscribers & reason/created attributes from the request payload are used in the check request. All other attributes, including the commands to be ran, are taken from the check definition already in memory.

## Possible Solution
Adding the below into the read_data method in https://github.com/sensu/sensu/blob/65e98d303d5ef2327dc49480e9cbdf7a1ffb3cfa/lib/sensu/api/routes/request.rb successfully allows the check command to be modified:
```
check[:command] = data[:command] if data[:command]
```

However as per https://github.com/sensu/sensu/issues/935 this has already been discussed and rightfully dismissed as a massive security issue, due to the nature that this would allow _any_ command to be ran on _any_ client, given a compromised client or compromised API credentials.

Perhaps the below two options would help with narrowing this attack vector:

- When publishing a check request via the API the check name must already exist (As is the case now) & the actual executable portion of the command (e.g. /opt/sensu/embedded/bin/breakallthethings.rb) must match what is already defined for that check) -- Essentially only allowing the overriding of the CLI options. Not exactly how you'd perform this validation though.
- If the CLI options on a given command could still present a significant security risk if modified add an additional safe_mode option to the _check_ that prevents it being overridden full stop.

## Context
We have a check in our environment that runs on a weekly basis that collects a bunch of diagnostic information from some services and mails it off to a third party. On occasion we would like to run this ourselves against a host/subscription and have it instead email to ourselves (i.e. override the --mail_to CLI option).
It would be nice to be able to override the command, and an extension of that would then to provide a user friendly method in Uchiwa to do this, for non tech users.

This is very much a nice to have, and not something I'd be fussed about if it was never implemented -- The use case could easily be considered as something that is beyond the scope of a monitoring tool, and we do have other means to perform such actions.
Just thought I'd throw it out there to see general thoughts.

**Comment by portertech** [comment]
Thank you for the comprehensive issue. We have and continue to avoid the customization of check commands via the API, as they are executed on one or more systems in a Sensu installation, posing a significant security risk. The current "solution" is to create a separate check definition with the desired command and `"publish": false`, so it can be only issued by the API POST `/request` endpoint.

Closing this issue, as the requested feature would introduce a security risk that we and many others are not comfortable with.
