### ISSUE TITLE
orphaned events in sensu

### ISSUE THREAD

**Issue by cabecada** [sensu/sensu#1646]
Not sure if i should be taking this in sensu-puppet or here, but this is a concern.

Every time a user creates a check lets it stay for some months, 
then suddenly deletes this check via puppet, the events stay lingering around in sensu.
and then pollute the uchiwa event dashboard.

I know there is a valid use case of using stale events are actually a genuine issue, but if it is via puppet and check getting removed, there has to be some recon happening.

because of the complexity(or rather support :) ) of having checks being pushed from anywhere, i am not really sure of the way forward here, (i am not considering housekeeping jobs as an option here)

need to know your inputs.

also if there is any option to manage the checks (enabling/disabling) without a puppet repo commit, i would like to know the options. (one is [sensu-wrapper](https://github.com/jaxxstorm/sensu-wrapper))

This is not really an sensu issue, so feel free to close this, but i wanted this discussion to explore options beyond puppet that is scalable and auditable too :)

sensu: 0.26.5
ubuntu 14

**Comment by portertech** [comment]
I believe this comes down to the specifics of the deployment, there is no canonical way to determine if a orphaned/stale event is no longer relevant or an important actionable thing. As Sensu supports a variety of check execution methods and inputs, it's difficult or nearly impossible to solve this problem for everyone as part of the Sensu Core framework.

@cabecada I see a mixture of Puppet interaction with the Sensu API and a custom cron script as a possible path for you. Thank you for the issue :+1:
