### ISSUE TITLE
Support for Suse Enterprise

### ISSUE THREAD

**Issue by juancherrera** [sensu/sensu#1647]
Hello,
We are currently in the process of testing/deploying Sensu across our enterprise. We are mostly a windows shop but our main system runs on Suse. All other linux hosts are ubuntu/etc. 

Is there a plan to also include Suse in the near future?

Thank you,

JH

**Comment by portertech** [comment]
We've created an internal issue to track this. We plan to implement repository rewrites in order to support Suse Enterprise. We will announce support when it becomes available in the coming weeks. Thank you for the issue :+1: Closing it.

**Comment by juancherrera** [comment]
Thank you for your feedback, look forward to the announcement!
