### ISSUE TITLE
sensu-api dies with pure virtual methods called

### ISSUE THREAD

**Issue by arianf** [sensu/sensu#1648]
```
service sensu-api status
/etc/init.d/sensu-api: line 296: kill: (30499) - No such process
sensu-api dead but pid file exists
```

tail -3 /var/log/sensu/sensu-api.log
```
{"timestamp":"2017-04-03T09:16:07.307850-0700","level":"info","message":"api response","request":{"remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","method":"GET","uri":"/aggregates","query_string":null,"body":""},"status":200,"content_length":2}
pure virtual method called
terminate called without an active exception
```
Sensu-api dies randomly over time, and the error that it dies with is random

## Your Environment

* Sensu version used: sensu-0.28.4-1.el6.x86_64.rpm
* Active Sensu extensions (e.g. WizardVan 0.1.0): uchiwa-0.22.2-1.x86_64.rpm
* Operating System and version (e.g. Ubuntu 14.04):  Oracle Linux Server release 6.4
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): {rabbit,"RabbitMQ","3.1.5"},  Erlang: R14B04

**Comment by portertech** [comment]
@arianf "error that it dies with is random" so are there errors other than "pure virtual method called"? Can you please provide more context, e.g. traces or even more proceeding sensu log events? Thank you.

**Comment by arianf** [comment]
@portertech Sorry, I guess I phrased that poorly, I meant to say it dies randomly with the "pure virtual method called". Randomly as I can't predict a certain action that makes it happen, and it seems to happen after running healthy for a week a more. Is there a way I can turn on deeper logging for sensu-api?

**Comment by arianf** [comment]
Nevermind, I figured out how to set the debug logging level... If it happens again, I'll add more logs here.

**Comment by portertech** [comment]
@arianf did this happen again?

**Comment by arianf** [comment]
@portertech No, but I figured out what it was... some random malformed request killed the server. However, because of the way the default logging works, you can only see requests that were completed.. if the request kills the `sensu-api` it won't be logged. Instead of testing this more, I just turned off access externally to that port.
