### ISSUE TITLE
Sensu API says "reconnecting to redis" without doing so

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1653]
## Expected Behavior
As by documentation, it says "Only the Sensu server and API processes require access to Redis...", API process should connect to Redis.

## Current Behavior
API is connecting just to transport.
It says "level":"warn","message":"reconnecting to redis", however there is no sign on socket layer that it tries to do so.

NOTE: Sensu Server + Redis is running on server A and Sensu API is running on server B.
Hopefully this is supported set-up. At least I have such feeling when reading doc.
## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Install Sensu Server and Redis on one server
2. Install Sensu API on second server
3. Run both and observer API logs

## Context
Distributed environment. Sensu API running on separate machine.
Is it actually supported to have API running separately?
As doc. says ""Only the Sensu server and API processes require access to Redis..." - I have feeling that it should be possible.

## Your Environment
Sensu Server and Redis separated from Sensu API.
* Sensu version used: 0.29
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by cwjohnston** [comment]
@mcbsdEU running API on a compute node separate from the Sensu Server and/or Redis is supported. Can you please turn on debug level logging (e.g. set `LOG_LEVEL=debug` in /etc/default/sensu and then restart) to provide additional context regarding this issue?

**Comment by mcbsdEU** [comment]
Hi,

after enabling debug:
``
{"timestamp":"2017-04-10T17:42:50.859170+0200","level":"debug","message":"connecting to redis","settings":{"host":"192.168.*.*","port":6379,"password":"****"}}
{"timestamp":"2017-04-10T17:42:50.859588+0200","level":"debug","message":"connecting to transport","name":"rabbitmq","settings":{"host":"*","port":5672,"vhost":"/sensu","user":"sensu","password":"****"}}
{"timestamp":"2017-04-10T17:42:50.891604+0200","level":"info","message":"api listening","protocol":"http","bind":"*","port":4567}
{"timestamp":"2017-04-10T17:42:50.892535+0200","level":"warn","message":"reconnecting to redis"}
{"timestamp":"2017-04-10T17:42:50.900183+0200","level":"debug","message":"transport connection open"}
``

**Comment by mcbsdEU** [comment]
Right after the restart I execute "ss -anp | grep 6379", actually several times and I would expect at least some SYN sent or whatever sign that connection went through network stack. But nothing like that.

**Comment by mcbsdEU** [comment]
Completely my fault. Redis was always used on same machine and therefore Redis's bind was not configured on "external" IP, just loopback.
This is really beginners fault and really sorry. Sometimes you overlook the very essential things by thinking too complex.
Again sorry and thanks
