### ISSUE TITLE
Checks running while client being restarted -> status == 15?

### ISSUE THREAD

**Issue by ctheune** [sensu/sensu#1654]
## Expected Behavior

Shutting down a client shut not cause "weird" status in checks.

## Current Behavior

I'm seeing checks that have _no_ output and a status of 15. This seems to happen around the time when the client is being restarted.

## Possible Solution

Suppress sending out this message at all - is there any value in this?

## Steps to Reproduce (for bugs)

This isn't deterministic. 

1. have (standalone) checks that might be running a bit longer
2. keep restarting the client
3. see if the check turns into "no output" and status 15

## Context

I'm trying to reliably rely on a few checks that are very important but have very low occurrences (basically 1). I'm going to ignore status code 15 for now, but I guess there is a slight design improvement potential around here somewhere.

## Your Environment

* Sensu version used: old. :) sensu 0.22
* Active Sensu extensions (e.g. WizardVan 0.1.0): - 
* Operating System and version (e.g. Ubuntu 14.04): NixOS 15.09
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Rabbitmq 3.6.5 Erlang 18.0

**Comment by portertech** [comment]
@ctheune curious, if you run one of checks/plugins manually and send it a SIGTERM, does it return status 15?

**Comment by ctheune** [comment]
I'm sorry, I didn't take enough info to reproduce this and can't find the logs any longer. I'll reopen this if that happens again ... :/
