### ISSUE TITLE
Init scripts missing since 0.27.0

### ISSUE THREAD

**Issue by rlindner** [sensu/sensu#1656]
Since version 0.27.0 the packages from the debian repository
`deb https://sensu.global.ssl.fastly.net/apt jessie main`
are missing the init scripts.

## Expected Behavior
Init script present under /etc/init.d

## Current Behavior
Init scripts missing under /etc/init.d

## Steps to Reproduce (for bugs)
1. `apt-get install sensu=0.26.5-2`
2. `ls /etc/init.d/sensu-*`
```
/etc/init.d/sensu-api  /etc/init.d/sensu-client  /etc/init.d/sensu-server  /etc/init.d/sensu-service
```
3. `apt-get install sensu=0.27.0-1`
4. `ls /etc/init.d/sensu-*`
```
ls: cannot access /etc/init.d/sensu-*: No such file or directory
```

## Context
I've installed updates to 0.29.0-7 recently and tried to restart sensu-client and realized that the init scripts are missing.

## Your Environment
* Sensu version used: > 0.27.0
* Operating System and version: Debian 8.7

**Comment by cwjohnston** [comment]
@rlindner as of Sensu 0.27 we provide systemd unit files for platforms like Debian Jessie where systemd is the default init. This change is described in the [Sensu 0.27 changelog](https://sensuapp.org/docs/0.27/overview/changelog.html#core-v0-27-0-important).

If you prefer to use sysv init scripts, I believe you can choose to install Wheezy packages instead.

**Comment by rlindner** [comment]
Thanks for pointing me to the right documentation! I've read the [changelog here on GitHub](https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0270---2017-01-26) were this wasn't mentioned.
