### ISSUE TITLE
Support 'clearer' application of filters in handlers

### ISSUE THREAD

**Issue by gcymbalski** [sensu/sensu#1658]
Some folks, using more and more complex filters, wind up in situations where they need a handler to fire like so:
- Always with a certain attribute (environment == prod)
OR
- Another attribute matches (environment == dev) and it is within business hours (9-5 M-F)

The confusion arises due to the various ways of implementing this.

One way would be to have the same handler invoked twice (with different names), using two different filters, which would also mean two complete runs through the filter chain. This is not possible right now with e.g. the Puppet module.

Another, possibly easier to conceptualize method would be to allow for filter chains were ANY of them can match. As it is, it's possible to functionally OR filters together by using negation that gets ANDed, but this usually causes confusion when matching multiple attributes/other criteria since Boolean algebra can get unintuitive when negations start flying around.

Anyway, while it's certainly possible to achieve this behavior as is, it has- and can- cause a barrier in terms of understandability and maintainability when more and more complex filters are needed.

(Sorry for not using the template, but hopefully this addresses the intent of it)

**Comment by cabecada** [comment]
Filters in extensions if you are using sensu-plugin >= 2.0.0, are already deprecated.
https://github.com/sensu-plugins/sensu-plugin/issues/134

you can write your own filters as sensu extensions, and example to help you get started
https://github.com/sensu-extensions/sensu-extensions-occurrences

you are free to write your logic, but make sure the stuff is non blocking, and has exception handling if any, else it will impact the sensu server.

**Comment by cabecada** [comment]
Sorry I meant filters in handlers are kind of deprecated depending on the sensu plugin version (2.0.0) you are using.

**Comment by cwjohnston** [comment]
We're not planning to change how filters are applied in Sensu 1.0 but this may change in a future version.
