### ISSUE TITLE
`silenced` API entries should provide timestamps

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu#1659]
## Expected Behavior

When querying the `/silenced` API endpoint, operators should be able to determine the date and time at which a silencing entry was created or last updated.

## Current Behavior

Silencing entries do not provide a timestamp to indicate when they were created or last updated.

## Possible Solution

Enhance API code to add a timestamp attribute indicating epoch time when creating or updating silencing entries.

## Context

Feature requested via Sensu Enterprise helpdesk; seems like a "no-brainer". 🙃 

## Your Environment
* Sensu version used: 0.29.0-1

**Comment by portertech** [comment]
0.29 does this https://github.com/sensu/sensu/commit/7148304cc7fa905e8b0c647c888a9ec958c502fd

**Comment by cwjohnston** [comment]
![](http://media1.giphy.com/media/FGTVmzksb2j0k/200.gif)
