### ISSUE TITLE
Sensu API running standalone returns empty list of checks

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1660]
## Expected Behavior
Sensu API, when running standalone should return content for all endpoints.
[#1653](https://github.com/sensu/sensu/issues/1653) - using just as reference that API is supported to run separated from Sensu-Server and Redis (ignore the content of the issue).

## Current Behavior
Sensu API, when running standalone, when asked for list of checks, it returns empty list:
```
...
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
< Access-Control-Allow-Origin: *
< Connection: close
< Content-length: 2
< Content-type: application/json
<
* Closing connection 0
[]
```
When requesting "info" endpoint, it is visible that sensu is connected to redis and transport:
```
...
"transport":{"name":"rabbitmq","keepalives":{"messages":0,"consumers":1},"results":{"messages":0,"consumers":1},"connected":true},"redis":{"connected":true}
...
```
When displaying configuration on sensu-server by "/opt/sensu/bin/sensu-server --print_config" it shows checks as expected.

I tested to configure and run sensu-api on same machine as sensu-server and redis - ***all works as expected in such (standard?) setup.***

## Possible Solution
It seems to be a bug.

## Steps to Reproduce (for bugs)
1. Run sensu-server and redis on server A
2. Run sensu-api on server B
3. Configure some checks on server side
3. Request "checks" endpoint - you should see empty return
4. Configure sensu-api on server A as well
5. Request "checks" endpoint from api on A server - all is OK

## Context
Sensu is practically not usable when behaving like this (etc. Uchiwa shows no checks...)...

## Your Environment
* Sensu version used: 0.29
* Active Sensu extensions (e.g. WizardVan 0.1.0): N/A
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by mcbsdEU** [comment]
FYI: /events and /clients endpoints are working

**Comment by portertech** [comment]
@mcbsdEU API GET /checks only displays locally defined standard checks (from configuration). The API is only able to issue check requests via POST /request that are locally defined. Sensu checks are not stored in Redis, like the event and client registries.

**Comment by mcbsdEU** [comment]
@portertech Thanks for getting this clear. 
Maybe I missed something but I didn't find in documentation what you just wrote, that's why I made wrong assumption on how it works.
There is sentence in reference doc/checks - 
**"Sensu checks which are centrally defined and scheduled by the Sensu server"...**
It says centrally defined but maybe worth to mention that defined where the sensu-api is being active.
Just my 5 cents....anyway, now it is clear to me.
Thanks a lot for being active on this perfect project.

**Comment by mcbsdEU** [comment]
Actually, maybe I got the point - it's like sensu-server needs to have checks defined but it is actually sensu-api which displays them but in order to do so, they must be defined also on instance with sensu-api.
Hm, isn't it contra-productive to maintain same definitions on two separate machines to make them being scheduled _and_ visible? At the end, one end up with sensu-api running on same machine as sensu-server...
