### ISSUE TITLE
Eventmachine: integer 2558122467 too big to convert to `int'

### ISSUE THREAD

**Issue by Evesy** [sensu/sensu#1665]
Possibly one for https://github.com/sensu/sensu-em

We have a cron check set to run at the start of every month (0 0 1 * *), following the run on 1st May we started having failures on Server leaders, where they'd attempt to schedule checks before subsequently dying. 

The issue is due to the large amount of time to the next check when calculated by ```determine_check_cron_time``` which causes a failure in EM: https://github.com/sensu/sensu/blob/a27da6df7d1e9467a07b59e9e4f9d165638fb324/lib/sensu/utilities.rb#L351-L356

## Expected Behavior
Cron schedules as far away as a month should be scheduled correctly, or appropriate guards/documentation should be put in place, as this unfortunately caused the entire environment to die, as one leader after another crashed.

## Current Behavior
If a cron checks next execution is too far away, the resulting value is too large for EM to handle, and the below is observed:

```
{"timestamp":"2017-05-02T09:24:37.530368+0000","level":"info","message":"i am now the leader"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:327:in `add_oneshot_timer': integer 2558122467 too big to convert to `int' (RangeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:327:in `add_timer'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/em/timers.rb:12:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:848:in `new'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:848:in `schedule_check_cron_request'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:892:in `block in schedule_checks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:890:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:890:in `schedule_checks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:908:in `setup_check_request_publisher'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:1096:in `leader_duties'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:1130:in `block in become_the_leader'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-2.1.0/lib/sensu/redis/client.rb:334:in `dispatch_response'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-2.1.0/lib/sensu/redis/client.rb:350:in `parse_response_line'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-2.1.0/lib/sensu/redis/client.rb:384:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:31:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'
```

I don't know what the exact limit is, but we definitely breached it I think.

## Possible Solution
Add relevant support so that EM can handle these large integers, or provide documentation/safe guards around this current limitation.

## Steps to Reproduce (for bugs)
1. Set cron check that is considerable time in the future, e.g. (0 0 1 10 *)
2. Restart sensu servers to pick up new check configuration
3. Leaders will be elected, and will then shortly crash with the above stack trace

## Context
Monthly check to email out a diagnostic report, there isn't a need to run any more frequently than this.

This caused any leader attempting to schedule checks to die, until there were no servers left running.

## Your Environment
* Sensu version used: 0.28.4
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.2
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Erlang 18.2, Rabbit 3.6.2

**Comment by portertech** [comment]
The culprit https://github.com/eventmachine/eventmachine/blob/master/lib/eventmachine.rb#L327

**Comment by portertech** [comment]
We also need to change https://github.com/eventmachine/eventmachine/blob/master/ext/em.cpp#L1154 to use uint64.

**Comment by portertech** [comment]
And https://github.com/eventmachine/eventmachine/blob/master/java/src/com/rubyeventmachine/EmReactor.java#L376 as well.

**Comment by portertech** [comment]
We should probably as @sodabrew about this.

**Comment by sodabrew** [comment]
Sounds like a reasonable change!

**Comment by portertech** [comment]
@sodabrew yes :+1:

**Comment by cwjohnston** [comment]
Opened https://github.com/eventmachine/eventmachine/pull/784 as a potential fix for this.
