### ISSUE TITLE
Support Fedora packages in Sensu official repos?

### ISSUE THREAD

**Issue by con5cience** [sensu/sensu#1667]
I have Fedora machines on which I would really really really like to be able to install Sensu using your official (or, really, any) repositories. Seems like it would be reasonably simple to branch from your existing CentOS infrastructure and support `dnf` via `https://sensu.global.ssl.fastly.net/dnf/$releasever/$basearch/` ?

Discuss!

**Comment by portertech** [comment]
We have to do further research on `dnf` and how the repository and metadata is structured. AFAIK Fedora still has YUM, why not just use the official Sensu YUM repository?

**Comment by con5cience** [comment]
`yum` redirects to `dnf` in Fedora at this point. I'm also unsure about the ramifications of installing EL7 RPMs on Fedora, but will definitely have a go and see what happens. Mostly just wanted to bring the issue to the table for discussion with the Sensu team in the event that it was a quick tweak to existing package assembly workflow and whatnot. Thanks! :)

**Comment by portertech** [comment]
@con5cience we have confirmed that Sensu can be installed on Fedora, using the existing YUM repository. In order for it to work, `$releasever` must be replaced by `7`.

**Comment by portertech** [comment]
Closing, as we have confirmed the edit above fixes installation of Fedora with existing repositories.

**Comment by con5cience** [comment]
Confirming that this works fine. Thanks for looking into it!
