### ISSUE TITLE
Enable IPv6 for repositories

### ISSUE THREAD

**Issue by ydkn** [sensu/sensu#1668]
I have a few machines that are in a IPv6 only environment. Currently the official repo (sensu.global.ssl.fastly.net) only supports IPv4 which means I can't use it on those machines.

According to https://www.fastly.com/blog/ipv6-fastly enabling IPv6 for the official repo should only be a configuration option that must be set. Using IPv6 would then mean using a different hostname / url but I guess it can be used side by side with the old one.

**Comment by cwjohnston** [comment]
@ydkn if you have sufficient control over your DNS infrastructure, you can try redirecting `repositories.sensuapp.org` CNAME to `j2.shared.global.fastly.net`. This will enable IPv6 and SSL for `repositories.sensuapp.org`, as Fastly has added our host to their certificate's SNI records. 

We want to cut over to this new CDN distribution soon but haven't thoroughly tested it yet. If you're able to try this and provide feedback we'd really appreciate it.

**Comment by ydkn** [comment]
Thanks @cwjohnston for your fast reply.

I had to use `dualstack.j2.shared.global.fastly.net` to make it work, `j2.shared.global.fastly.net` is the IPv4 only hostname.

I don't like messing with our DNS server but I added an entry to `/etc/hosts` instead. Hopefully fastly won't change the IP.

```
# /etc/hosts
2a04:4e42:1b::561 repositories.sensuapp.org
```

It works great that way, thanks again.

**Comment by cwjohnston** [comment]
We've announced our intention to update the CDN configuration on May 17th via [the 
 Sensu blog](https://blog.sensuapp.org/announcement-sensu-core-repositories-adding-https-ipv6-and-http-2-support-8480005b5ea4) and the sensu-user mailing list.
