### ISSUE TITLE
Escaping check commands to prevent inadvertent shell substitutions

### ISSUE THREAD

**Issue by davidk01** [sensu/sensu#1669]
## Expected Behavior
If a check command definition has `:escape => true` then the command should have all shell characters escaped before being passed to `Spawn.process`.

## Current Behavior
The current behavior does not escape shell variables so it is possible to have variables interpolated into the check command that leads to unanticipated results if the interpolated variable has shell character sequences like `$?`.

## Possible Solution
As outlined above check command definition should allow for escaping with `:escape => true` option. It is possible to do this by appropriately splitting and re-joining the command with `command.shellsplit.shelljoin` after requiring `Shellwords` library. My suggested solution would modify `Sensu::Client::Process.execute_check_command` by adding the following block

```
if check[:escape]
  command = substituted[:command].shellsplit.shelljoin
  substituted[:command] = command
end
```

## Context
This would prevent inadvertent behavior when variables being substituted had shell character sequences like `$?`. It is potentially a vulnerability vector if the sensu user runs with elevated privileges. 

Ideally the default would be to escape all shell variables but that would most likely break existing client definitions so the compromise is to add an option to escape all commands either globally or locally. My suggested solution is for each command block but it could be a global option as well with local overrides for each command.

**Comment by portertech** [comment]
I think I need further use case and vulnerability vector examples.

**Comment by portertech** [comment]
Closing this issue. If someone can provide further use cases and potential current vulnerability vector examples, I will be more than happy to reopen.
