### ISSUE TITLE
Sensu:"handler ----error":"failed to connect to socket"

### ISSUE THREAD

**Issue by melpra** [sensu/sensu#1670]
I am using mailer.rb handler to send out email. the config is picked from mailer.json with tcp socket in it.
The error is below:
{"timestamp":"2017-05-08T09:45:01.751056-0400","level":"error","message":"handler error","handler":{"type":"tcp","command":"/etc/sensu/handlers/mail1.rb","timeout":30,"socket":{"host":"127.0.0.1","port":2014},"name":"mailer"},"event_data":"{\"id\":\"xxxxxxxxx\",\"client\":{\"name\":\"xxxxxxxxxx\",\"address\":\"xxxxxxx\",\"subscriptions\":[\"all\",\"xxxxxxxxxx\",\"xxxxx\"],\"keepalive\":{\"thresholds\":{\"warning\":1800,\"critical\":3600}},\"version\":\"1.3\",\"timestamp\":1494251059},\"check\":{\"notification\":\"Wan Status update\",\"command\":\"xxxxxxxxxxxxx\",\"subscribers\":[\"xxxxxxxxxxx\"],\"interval\":120,\"occurrences\":2,\"handlers\":[\"default\",\"mailer\",\"email\"],\"name\":\"wan-status\",\"issued\":1494251101,\"executed\":1494251061,\"duration\":0.184,\"output\":\"WARNING: [ISP: DOWN] [VPN: UP]\\n\",\"status\":1,\"history\":[\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\"],\"total_state_change\":0},\"occurrences\":711,\"action\":\"create\",\"timestamp\":1494251101}","error":"failed to connect to socket"}

**Comment by portertech** [comment]
@melpra This error suggests mailer.rb was unable to connect to the SMTP socket, perhaps first test the configured socket information manually with something like `telnet`. This is not an issue with Sensu itself and seems to be related to configuration. If the mailer.rb configuration is correct, please feel free to create a github issue on https://github.com/sensu-plugins/sensu-plugins-mailer
