### ISSUE TITLE
Debian package broken

### ISSUE THREAD

**Issue by envintus** [sensu/sensu#1671]
When installing a newer version of the Sensu Debian package on a system with an existing installation dpkg errors out because it's attempting to chown `/opt/sensu`, which does not exist anymore. That path no longer exists, because the packages removes it as part of the upgrade/installation.

## Expected Behavior
Clean upgrade in that installing an newer version of the package simply works and does not leave Sensu in a broken state on the system requiring intervention.

## Current Behavior
When upgrading an existing installation dpkg dies, because Sensu has removed `/opt/sensu` and then tries to chown that path, which leaves Sensu in a broken state requiring manual intervention.

## Possible Solution
None at the moment. Have not had a chance to look at the package to see what can be done.

## Steps to Reproduce (for bugs)
1. Find a system with an existing Sensu installation
2. Run `apt-get update`
3. Run `apt-get install sensu` for the latest or optionally pin to a newer version

## Context
Came across this issue when needing to upgrade our Sensu server and API after launching a client daemon set on our Kubernetes cluster, so we can now have proxy client and round robin support. We use Saltstack for configuration management of non-k8s instances and this failed the salt run. Upon investigation I determined it was the Sensu package itself and not something related to Salt by reproducing this error state manually by running apt-get commands another server with an existing Sensu installation.

Since then I've had to upgrade instances by hand by first removing & purging the existing installation and installing the newer version.

## Your Environment
* Sensu version used: 0.27.0 and upgrading to 0.29.0
* Active Sensu extensions (e.g. WizardVan 0.1.0): N/A
* Operating System and version (e.g. Ubuntu 14.04): Debian Jessie
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): N/A

Added output from log files capturing the dpkg error:
[errors.txt](https://github.com/sensu/sensu/files/997198/errors.txt)

**Comment by cwjohnston** [comment]
Hi @envintus, the situation you've described was fixed in https://github.com/sensu/sensu-omnibus/pull/116. Once you have upgraded to Sensu 0.27.0-3 or later, future upgrades should not encounter this error.

**Comment by envintus** [comment]
Hey Cameron,

Just looked back at what versions we upgraded from and it was 0.27.0-2.
Close, but not cigar for us!

I appreciate you taking the time to reply to this issue and providing
reference as well as further clarity on the subject. Sorry for the
unnecessary hassle by resurrecting an old problem.


[image: FC_MIC2017StandardLogo.png]

[image: TransLoc_logos_wordmark_blue.png]

Hunter Satterwhite

Lead Build & Operations Engineer, TransLoc

252.762.5177 | www.transloc.com

[image: facebook-color-32px.png] <https://www.facebook.com/TransLoc/> [image:
linkedin-color-32px.png] <https://www.linkedin.com/company/transloc> [image:
twitter-color-32px.png] <http://www.twitter.com/transloc> [image:
instagram-color-32px.png] <http://www.instagram.com/transloc_inc>

On Fri, May 12, 2017 at 12:52 PM, Cameron Johnston <notifications@github.com
