### ISSUE TITLE
Sensu configs are not applying after restarting Sensu service

### ISSUE THREAD

**Issue by ppanucool** [sensu/sensu#1673]
## Current Behavior
I modified the threshold value of a check like below
{
  "checks": {
    "check_ram_client": {
      "type": "metric",
      "command": "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe C:\\opt\\sensu\\plugins\\powershell\\check-windows-ram.ps1 -Warning 80 -Critical 85",
      "subscribers": [
        "client_name"
      ],
      "handlers": [
        "email"
      ],
      "interval": 60,
      "occurrences": 10,
      "refresh": 1800,
      "time_precision": "s",
      "notification": "[Client_name] Very less free memory on HP machine. Please look into this",
      "severities": ["critical", "unknown"],
      "influxdb": {
        "database": "sensu"
      }
    }
  }
}

**After that I have restarted all the services like below**
service sensu-server restart && service sensu-api restart &&  service uchiwa restart && service sensu-client restart && service rabbitmq-server restart && service grafana-server restart && service influxdb restart

Problem,
But even after restarting all the services modified check is not updated properly,
When I open Uchiwa it still shows,  threshold as 80 and 85%.
However, i modified it to lesser value as i mentioned. 

Restarting sensu services not applying the changes.

Thanks for any help

**Comment by portertech** [comment]
@ppanucool you can give the Sensu server CLI argument `--print_config` a try, see documentation for usage https://sensuapp.org/docs/latest/reference/configuration.html#sensu-command-line-interfaces-and-arguments One important thing to note, you must also still include the CLI arguments for the configuration file and directories, e.g. `-c /etc/sensu/config.json -d /etc/sensu/conf.d`.

**Comment by ppanucool** [comment]
Hi @portertech thanks for your reply.

I tried to execute the below command. But getting error

root@ip-10-0-0-139:/etc/sensu# /opt/sensu/bin/sensu-server -c /etc/sensu/conf.d/config.json -d /etc/sensu/conf.d.
{"timestamp":"2017-05-20T08:37:57.466886+0000","level":"warn","message":"config file does not exist or is not readable","file":"/etc/sensu/conf.d/config.json"}
{"timestamp":"2017-05-20T08:37:57.467020+0000","level":"warn","message":"ignoring config file","file":"/etc/sensu/conf.d/config.json"}
{"timestamp":"2017-05-20T08:37:57.467074+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d."}
{"timestamp":"2017-05-20T08:37:57.467106+0000","level":"fatal","message":"insufficient permissions for loading","directory":"/etc/sensu/conf.d."}
{"timestamp":"2017-05-20T08:37:57.467131+0000","level":"fatal","message":"SENSU NOT RUNNING!"}
root@ip-10-0-0-139:/etc/sensu#

**Comment by ppanucool** [comment]
Hi @portertech @calebhailey 
please help,
Due to this bug, we are facing issues in production environment

**Comment by mcbsdEU** [comment]
Have you tried to follow error message in your output?
Application log is pretty clear I would say, you could start there and see if if helps.

**Comment by portertech** [comment]
Please fix your `/etc/sensu/conf.d` directory permissions so the Sensu user can access your configuration files, as per your log line `{"timestamp":"2017-05-20T08:37:57.467106+0000","level":"fatal","message":"insufficient permissions for loading","directory":"/etc/sensu/conf.d."}`.
