### ISSUE TITLE
Windows - Odd token substitution with double quotes

### ISSUE THREAD

**Issue by absolutejam** [sensu/sensu#1674]
## Current Behavior

When using check token substitution with a json list/array, it looks like the interpolation is mangling the string somehow.

For example, I have the following check
```powershell
powershell.exe -noprofile -noninteractive -executionpolicy bypass -nologo -file C:\\opt\\sensu\\check-scripts\\check-services.ps1 -criticalservices ':::services.critical:::' -importantservices ':::services.important:::'
```
And my client attributes:
```json
{
  "services": {
    "critical": [ "dnscache", "SMTPSVC" ],
    "important: [ "someotherservice" ]
  }
}
```
Error output:
```
C:\opt\sensu\check-scripts\check-services.ps1 : A positional parameter cannot 
be found that accepts argument 'SMTPSVC]''.
+ CategoryInfo : InvalidArgument: (:) [check-services.ps1], Paren 
tContainsErrorRecordException
+ FullyQualifiedErrorId : PositionalParameterNotFound,check-services.ps1
```

## Expected Behavior

Contents of JSON/double-quoted strings from token substitution would be passed into the command string without it terminating prematurely - Possibly by escaping them with a backslash?

## Possible Solution

The only way to get around this *manually* is by escaping each double-quote in the json with a backslash (eg. `[ \"dnscache\" ]`). Obviously this isn't possible when Sensu executes the check!

Is there a way to escape any double quotation marks when the string is being interpolated?

## Context

To help my checks be more dynamic, I am trying to pass in parts of the client definition as raw json. This means that I can define a json dict/array and pass this to my checks and have the check run through them.

## Your Environment

Sensu client on Windows 10 x64 host, Version `WinSW 2.0.2.0`
Server version `0.29.0`

**Comment by portertech** [comment]
@absolutejam token substitution only works with string and integer (becomes a string) values, you cannot use an array attribute as a token. With your example, you may be able to do something like: `"critical": "dnscache, SMTPSVC"`, using a string of comma separated services.
