### ISSUE TITLE
Yum repo from fastly.net failing with 404 on EC2 AMI

### ISSUE THREAD

**Issue by totojack** [sensu/sensu#1675]
Hi.

It seems that RHEL yum repository configuration

[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
gpgcheck=0
enabled=1

installed on an aws ec2 ami fails with a 404 when trying to connect to https service. The url called from yum is:

https://sensu.global.ssl.fastly.net/yum/latest

Using the older repo version

[sensu]
name=sensu
baseurl=http://repositories.sensuapp.org/yum/$basearch/
gpgcheck=0
enabled=1

everything works fine, but the release installed is 0.26.5, so it's not the latest.

## Expected Behavior
Yum correctly using the fastly yum repository.

## Current Behavior
Yum fails with a 404 error.

## Possible Solution
Maybe the problem is in the $releasever/$basearch/ substitution value.

## Steps to Reproduce (for bugs)
Copy repo conf

[sensu]
name=sensu
baseurl=http://repositories.sensuapp.org/yum/$basearch/
gpgcheck=0
enabled=1

under dir

/etc/yum.repos.d 

in an aws ec2 ami instance and try to install sensu.

## Your Environment
The ami instance version is 

NAME="Amazon Linux AMI"
VERSION="2017.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.03"
PRETTY_NAME="Amazon Linux AMI 2017.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2017.03
cpe:/o:amazon:linux:2017.03:ga

Thanks.

**Comment by portertech** [comment]
@totojack perhaps replace `$releasever` with `6` or `7`, as Amazon Linux may not be setting it.

**Comment by portertech** [comment]
Modifying the repository URL with my suggest above should solve this issue.

**Comment by totojack** [comment]
Hi.

Just to confirm: on a AWS AMI I solved using 6.

> NAME="Amazon Linux AMI"
> VERSION="2017.03"
> ID="amzn"
> ID_LIKE="rhel fedora"
> VERSION_ID="2017.03"
> PRETTY_NAME="Amazon Linux AMI 2017.03"
> ANSI_COLOR="0;33"
> CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
> HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
> Amazon Linux AMI release 2017.03
> cpe:/o:amazon:linux:2017.03:ga
> 

> [sensu]
> name=sensu
> baseurl=https://sensu.global.ssl.fastly.net/yum/6/$basearch/
> gpgcheck=0
> enabled=1
