### ISSUE TITLE
Handlers don't handle OK severity for standard checks even if defined in config

### ISSUE THREAD

**Issue by ifourmanov** [sensu/sensu#1677]
## Expected Behavior
Sensu passes event to handler if OK severity is mentioned in severities array for said handler
https://sensuapp.org/docs/0.29/reference/handlers.html#handler-attributes
```json
{
  "handlers": {
    "logstash": {
      "type": "udp",
      "socket": {
        "host": "logstash",
        "port": 5111
      },
      "severities": ["ok", "warning", "critical", "unknown"]
    }
  }
}
```

## Current Behavior
Sensu drops event with OK severity if check is not set to be metric type:
https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L528

## Possible Solution
Either allow standard handlers to process OK events, dropping them if not defined in severities array (already implemented in https://github.com/sensu/sensu/blob/master/lib/sensu/server/filter.rb#L47), or provide global config switch for handling ok events or update documentation to mention that OK events are not handled even if defined in severities list 

## Context
Spent several hours trying to figure out why OK events are not handled though documentation says they should be. Had to dig into source code.
Don't want others to waste time on that.
Want to be able to send all events to handler for long term storage

**Comment by cwjohnston** [comment]
@ifourmanov sorry that you spent so much time on this. I think this is a bug in the documentation, as `ok` results from standard (non-metric) checks are not passed along to be evaluated by the logic which filters by event severities. I've opened https://github.com/sensu/sensu-docs/issues/596 to track this documentation issue.

From the handler snippet you've shared, I think a Sensu bridge extension --  essentially a handler which receives every event regardless of its severity -- would probably provide the behavior you seem to be looking for. There aren't many freely available examples of bridge extensions, but the one that I'm aware of is here https://gist.github.com/Buzer/262da357c24907a1d05d.

Sensu Enterprise provides an [event bridge integration](https://sensuapp.org/docs/latest/enterprise/integrations/event_stream.html) which sends events over the network in a way that may satisfy your requirements.
