### ISSUE TITLE
Extension installation via gem must use EMBEDDED_RUBY

### ISSUE THREAD

**Issue by portertech** [sensu/sensu#1678]
Sensu uses its embedded Ruby at runtime. The `/etc/default/sensu` variable `EMBEDDED_RUBY` defaults to `true`, allowing Sensu plugins and extensions to be installed by Sensu's embedded Ruby. When `EMBEDDED_RUBY` is set to `false`, Sensu itself still uses the embedded Ruby, however, Sensu does not add the embedded Ruby to `$PATH`, and plugins are expected to be installed by a system Ruby or not use Ruby at all. This does not work for Sensu extensions installed via gems, as THEY MUST be installed by Sensu's embedded Ruby in order to be loaded by Sensu.

## Expected Behavior
`sensu-install -e` should inspect `EMBEDDED_RUBY` to ensure it is set to `true` or return an informative message and exit 2.

## Current Behavior
`sensu-install -e` installs an extension gem to the system Ruby, but Sensu is unable to load it.

**Comment by amdprophet** [comment]
Rather than exiting if `EMBEDDED_RUBY` is false - let's just set it to true in the block that deals with installing extensions.

**Comment by amdprophet** [comment]
After some investigation we realized that setting `EMBEDDED_RUBY` to true would only be viable for Omnibus installations. We've backtracked to having the tool exit and log a message if `EMBEDDED_RUBY=false`.

**Comment by amdprophet** [comment]
Fixed in #1687.
