### ISSUE TITLE
Install lightweight client only

### ISSUE THREAD

**Issue by basickarl** [sensu/sensu#1679]
Hello! I was reading the installation here: https://sensuapp.org/docs/0.26/platforms/sensu-on-ubuntu-debian.html#sensu-core

It states: 

> The Sensu Core package installs several processes including sensu-server, sensu-api, and sensu-client.

It's great that yous have provided a .deb file for installation, this saves me time.

I have requirements to keep builds however as small as possible. So for the client Docker images we are to build I have to strip it as much as possible. Meaning that I would like to skip installing the `sensu-server` and `sensu-api` for the client images. How does one do this?

If it were me making this product I'd have two three `.deb` files. `sensu-server`, `sensu-api` and `sensu-client`. Then let me decide which hosts should have what.

So again how do I get the most lightweight install of a client?

**Comment by portertech** [comment]
@basickarl the difference would be a few KB (just the Ruby lib files), as every component shares the common base and set of runtime dependencies.

**Comment by portertech** [comment]
Creating separate packages for each component is not worth it at this time. In the future, when Sensu components have less in common and fewer runtime dependencies, you can expect separate packages.
