### ISSUE TITLE
redis.json does not understand IPv4

### ISSUE THREAD

**Issue by rwillmer** [sensu/sensu#1685]
redis.conf is set to bind to 0.0.0.0. It is not listening on an IPv6 address. 
redis.json is set to look for redis on a machine name which resolves for both IPv6 and IPv4 addresses.
The API server fails to connect to the redis server; 500 errors ensue.

Update the redis.json to use the IPv4 address without needing DNS resolution; it works.

## Expected Behavior

This IPv4 configuration should work using the machine name.

## Current Behavior

API fails to talk to redis. Lots of these messages in /var/log/sensu/sensu-api.log
{"timestamp":"2017-06-12T17:11:12.369550+0100","level":"info","message":"api response","request":{"remote_address":"<server IPv4>","user_agent":"Go-http-client/1.1","method":"GET","uri":"/stashes","query_string":null,"body":""},"status":500,"content_length":59,"time":0.0}

## Possible Solution

Probably connected to :
https://github.com/sensu/sensu-transport/issues/47 
I am providing this as another test case which should be checked when that is fixed.

Also possibly related to https://github.com/sensu/sensu/issues/1332, which has been marked as closed because of the "use-IPv4-address-directly-in-config" workaround.
And https://github.com/sensu/sensu/issues/1365

Short-term amelioration would be to add a comment to the documentation to let people be aware this is a potential problem.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used:
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04):
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):
Ubuntu 16.04 LTS, sensu installed on single server using https://github.com/sensu/sensu-ansible
Redis 3.0.6

**Comment by amdprophet** [comment]
Hi @rwillmer,

We are aware of this issue and we're tracking it under https://github.com/sensu/sensu-transport/issues/47.
