### ISSUE TITLE
API should help elucidate the distinction between incidents and events

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu#1690]
## Expected Behavior

It should be easy to understand the distinction between events and incidents.

## Current Behavior

As someone who aims to help folks become proficient with Sensu, I find that "event" is an overloaded term.

In event processing terms, each check result becomes an event when it is correlated with information from the client registry and other additional context. Subsequently, each event is  evaluated to determine whether or not it should be sent to a handler. 

In API terms, the events returned via the `/events` endpoint are only representative of the latest non-OK events, which I tend to think of as "incidents". 

## Possible Solution

Allow the API to treat `/incidents` as an alias for `/events` endpoint.

## Context

Prior to the introduction of metric check type, events were only generated when a check result indicated a non-OK state. This is why the `/events` endpoint only exposes a subset of all events.

As a result, explaining this behavior of the `/events` endpoint involves a lot of hand-waving. I believe that exposing the same information via `/incidents` endpoint would make this much easier to explain.

**Comment by portertech** [comment]
#1696 was merged into the 1.0 release 👍
