### ISSUE TITLE
Filters in Handlers of type "set"

### ISSUE THREAD

**Issue by slime-man** [sensu/sensu#1691]
A handler defined as `"type": "set"` doesn't seem to implement filters defined in it.

## Expected Behavior
When using a set handler, it can be used as a sort of "wrapper" for another handler. Defining
```json
"handlers": {
  "handler-with-other-filter": {
    "type" : "set",
    "handlers": [ "handler" ],
    "filter": "set-filter"
  },
  "handler": {
    "filter": "regular-filter"
  }
}
```
should filter out check results sent to the `handler-with-other-filter` with the `set-filter` and also the `regular-filter`, no?

I would expect that, for checks that I want to run through both filters, I would link them to the `handler-with-other-filter`, and for other checks, I would only link them to the `handler`.

## Current Behavior
Right now, as of the above example, a check result sent to the `handler-with-other-filter` will only be affected by the `regular-filter`

---

There seems to be no documentation of people using filters with set handlers, and multiple googlings of this configuration have given me nothing. So I do not know how handler sets are meant to interact with filters.

**Comment by cwjohnston** [comment]
@slime-man as you have noted, filters applied to handler sets have no effect. This detail is documented in a note here: https://sensuapp.org/docs/0.29/reference/handlers.html#handler-sets

> NOTE: Attributes defined on handler sets do not apply to the handlers they include. For example, `filter`, `filters`, and `mutator` attributes defined in a handler set will have no effect.

Please let me know if you think there's another place in the documentation we should include this note, as it seems it wasn't positioned somewhere you could easily locate it.

In https://github.com/sensu/sensu/issues/1445 we indicated that we aren't going to implement this functionality, so I'm going to close this issue now.

**Comment by slime-man** [comment]
Hi, thanks for the quick response. 

I think another place to reiterate that point could be here: https://sensuapp.org/docs/0.29/reference/filters.html#how-do-sensu-filters-work

Thanks!
