### ISSUE TITLE
sensu-0.29.0-11.el7.x86_64.rpm conflicting with OS packages

### ISSUE THREAD

**Issue by patrickatomic** [sensu/sensu#1695]
looks like that new sensu package is conflicting with other OS packages... since some directory are "owned" by the sensu packages, and it shouldn't be the case... Doing a
**rpm -qlp sensu-0.29.0-11.el7.x86_64.rpm**

indicates that, for instance, 
**/usr
/usr/bin
/usr/bin/sensu-install
/var**

are owned by the sensu package... older versions didnt have that issue. Looks to me like the new RPM as been created using a "/*" in the %files section of the RPM spec... 
Centos6.7 and older versions won't complain about it, but starting from 6.8 and 7... the RPM DB is smart enough to detect it's causing conflicts...

**/tmp/sesu (root@mtl-lnx-055) $ rpm -qf /usr/bin
filesystem-3.2-21.el7.x86_64**

**Comment by portertech** [comment]
@patrickatomic I've gone ahead and moved this issue to the proper repository, sensu-omnibus - https://github.com/sensu/sensu-omnibus/issues/219 Thank you for creating this issue.
