### ISSUE TITLE
sensu-client not reconnecting to rabbitmq

### ISSUE THREAD

**Issue by lobeck** [sensu/sensu#1698]
sensu-client lost it's transport connection and is just complaining, but not reconnecting:

    {"timestamp":"2017-07-04T02:49:36.666262+0000","level":"warn","message":"transport connection error","reason":"tcp connection lost"}
    {"timestamp":"2017-07-04T02:49:43.389747+0000","level":"error","message":"failed to publish keepalive","payload":{"redacted"},"error":"Transport is not connected"}

lsof reports no connection anymore, so i'd expect it to reconnect.

config:

    {
      "rabbitmq": {
        "port": 5672,
        "host": "sensu.rabbitmq.service.consul",
        "user": "sensu",
        "password": "REDACTED",
        "vhost": "/sensu",
        "heartbeat": 30,
        "reconnect_on_error": true,
        "prefetch": 1
      }
    }

Ubuntu 16.04
Sensu 0.29.0-7

**Comment by cwjohnston** [comment]
Hi @lobeck, are you still experiencing this issue? If so, will you please turn on debug-level logging by sending SIGTRAP to your sensu-client (e.g. `pkill -TRAP sensu-client`)? I believe reconnect messages should be visible at the debug level.

**Comment by lobeck** [comment]
Just saw this once, but the debug-level kill is a nice hint, will take a look when it happens again.

Want to close this then and i'll reopen it once i can reproduce it?

**Comment by cwjohnston** [comment]
Sounds good, thanks!

**Comment by lobeck** [comment]
just happened again - tried it with SIGTRAP, but the only debug message that gets logged now is `[...]publishing keepalive[...]`.

This has to be some edge case which i currently can't explain. It happened during a redis and rabbitmq cluster failover, but only 1 of 60 clients is affected.
