### ISSUE TITLE
Feature Request: Subscription Dependencies on Check Status

### ISSUE THREAD

**Issue by Evesy** [sensu/sensu#1699]
A new feature that allows a client to automatically unsubscribe from a subscription based on the status of a check, and resubscribe when the status of the check returns to OK -- Particularly focused around clients that are part of a roundrobin subscription.

## Expected Behavior
It would be useful to provide a means of having a client dynamically drop in & out of a subscription (particularly thinking of roundrobin subscriptions) based on the clients current health, to prevent checks being ran against a client that is not healthy.

## Current Behavior
Currently a client will remain part of a given subscription until configuration is changed & the client is reloaded. A client will never unsubscribe from a subscription in the face of degraded availability, except in the event of a client failure.

## Possible Solution
Client attribute to define the checks that should be used to determine if a node is healthy & ready to accept roundrobin checks.
i.e.
```
"subscription_dependencies": [
    "general_node_health_check"
]
```

## Context
**Scenario 1**
In cases where a roundrobin subscription is used to execute a check (specifically metric checks) against a clustered service, often specific nodes might need to be used to run this check (i.e. where an API is not available, and metrics must be gathered from one of the machines in the cluster.

In the event that the service in question on one or more of these nodes fails, it will still receive roundrobin requests to collect these metrics, however due to the failing service it will not be able to collect these metrics.

Example: A cluster that is split between two AZ's suffers a complete service failure in one AZ, however the nodes are still up and sending keepalives. All nodes will continue to receive the roundrobin requests, however only half will be executing successfully, resulting in a loss of metrics.

**Scenario 2**
In cases where dedicated Sensu servers are used to run remote checks (i.e. runners), a similar scenario could arise where checks are intermittently failing due to degraded performance on nodes

**Comment by amdprophet** [comment]
Hi @evesy,

The idea you have proposed falls outside of the scope of Sensu's intent. It would require sensu-server to have specific knowledge of your infrastructure and services being monitored. Even if the server had this level of information, sensu-client configuration is immutable while running and thus a client's subscriptions cannot be altered.

Thank you for your suggestion but we will not be implementing this at this time.
