### ISSUE TITLE
Feature Request: Config option to have client create a dynamic signature on startup

### ISSUE THREAD

**Issue by Evesy** [sensu/sensu#1700]
Allow a configuration option within the client to have it generate a random signature on startup.

## Expected Behavior
**Providing a signature has not been set in the config... **
If desired/specified via a client attribute, when a client starts up it should automatically generate a signature that exists for the duration of the clients runtime.
If a client is restarted, a new signature should be generated 

## Current Behavior
A client simply does not have a signature (afaik) unless one is specified in the config.

## Possible Solution
Some sort of client attribute, e.g.:
```signature: true```

## Context
Sensu 0.29 introduced client invalidation to prevent stale check results from already deregistered clients resulting in zombie clients being registered. This is functional through the use of the client signature to determine what is an old check result and should be ignored.

Having the option for an auto generated signature would provide the below benefits:

1. Makes it simpler for users to configure and get use out of the check result validation that signatures provide (They needn't configure their clients to generate a signature, as it will be handled by Sensu. The option should still remain to have a defined signature however)

2. When making use of client invalidation it will prevent potential delays in check results being accepted when the server is restarted.

Currently if I have a client with a static signature (that deregisters on client stop), and invalidation on my deregister script set to two minutes, when a client is restarted it will take two minutes before new results start showing up. We send check results to Sensu when a chef run is successful (and often a chef run means the client is restarted), so in this scenario if we are using client invalidation that result will never see the light of day.

With the proposed solution when a client is stopped for the purpose of deregistering, invalidation will perform its job, as events with the given signature will be dropped. When a client is stopped for the purpose of restarting, new results will immediately be available in Sensu, as the signature will have changed.

**Comment by cwjohnston** [comment]
Hi @evesy,

The client signature is intended to be static for the life of the Sensu client. From the server's perspective, rotating client signature every time a client restarts is indistinguishable from having two different clients with the same name -- essentially one of the cases client signature was implemented to prevent.

 I'm closing this issue since the requested enhancement isn't compatible with the current client signature design and other features that rely on it, e.g. client invalidation.

**Comment by majormoses** [comment]
@cwjohnston I have not really looked into client signatures (getting ready to upgrade sensu shortly) and I see several issues asking for documentation on this. Assuming there is no specific formula you have to use would it make sense to auto create a signature based on the client name by default?

**Comment by portertech** [comment]
In order for a client signature to be effective, it cannot be generated in a predictable way.

**Comment by majormoses** [comment]
ok so if I am understanding this correctly it sounds like something that would need to be set via something like `SecureRandom.uuid` the first time it is launched but not on any other occurrences? This definitely feels like something that should be handled by CM but I just want to make sure I understand this.

**Comment by portertech** [comment]
Yes, it would have to persist to disk, for the lifecycle of the host that the sensu-client is running on. Doing this through configuration allows users to generate their signature strings in unique ways.

**Comment by majormoses** [comment]
Could you specify this by just dropping json a file in conf.d? This would allow you to create the file on disk and avoid modification pretty easily once it exists.

**Comment by Evesy** [comment]
FWIW we currently just write `SecueRandom.uuid` to a file on disk if it doesn't already exist, and then read that file in as an attribute.

**Comment by Evesy** [comment]
Ahh, using `sensu_snippet` would appear to not work since:

```
sensu_snippet 'client' do
  content(
    :signature => SecureRandom.uuid
  )
end
```
will clash with client.json

**Comment by majormoses** [comment]
You could always do it yourself with file resource and just creating a json blob as the content with a different filename or we could enhance the snippet provider to allow specifying the file name.

**Comment by portertech** [comment]
With Chef, you would have to store the uuid client signature in a node attribute, as you don't want to regenerate on ever Chef run.

**Comment by majormoses** [comment]
Unless you are talking about a normal attribute (which I don't recommend) that would not work as it would regenerate it every time. The sanest approach is a file resource with a guard to only run if the file does not exist. Normal (or other persistent attribute types) have some unintended consequences and that also means that if you were to ever reuse the hostname it would be an issue. This is pretty common in cloud native envs like aws.
