### ISSUE TITLE
DELETE /results/:client_name/:check_name fails to remove "history:client:check" in redis

### ISSUE THREAD

**Issue by somic** [sensu/sensu#1704]
Sensu::API::Routes::Results::delete_client should also remote "history:client:check" from redis.

## Your Environment
* Sensu version used: master branch from github
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu, all distributions

**Comment by portertech** [comment]
A note: `history:client:check` is also used for event check history and flap detection. Do we assume that deleting results for a check means a future event for the check is not expected?

**Comment by portertech** [comment]
Closed by #1753
