### ISSUE TITLE
Sensu RPM prevents other RPMs from writing to /etc/sensu/conf.d

### ISSUE THREAD

**Issue by blee1170** [sensu/sensu#1705]
We have several RPMs that are droping sensu configs into the /etc/sensu/conf.d/checks directory. After version 0.27.0 the sensu RPM seems to own the /etc/sensu & /etc/sensu/conf.d directories which prevents our RPMs from installing and placing those files.

We are using the [nebula release gradle](https://github.com/nebula-plugins/nebula-release-plugin) plugin for create the RPMs. When it creates the spec file it ensures that the directories are created for the files its putting in place, which causes a conflict with the sensu RPM. This did not happen with sensu version 0.26.x.

Using rpm command I was able to see that sensu defiantly owned /etc/sensu directories: 

```
$ rpm -qf /etc/sensu/conf.d/
sensu-0.27.0-1.el7.x86_64
```

With sensu 0.26.0 it does not own that directory:

```
$ rpm -qf /etc/sensu/conf.d
file /etc/sensu/conf.d is not owned by any package
```

Any idea what has changed in the RPM creation on the sensu side that might be causing this problem?

## Expected Behavior

Install other RPMs that drop configurations to the sensu directory

## Current Behavior

Error from yum/rpm saying it is owned by sensu:

```
Transaction check error:
  file /etc/sensu from install of sampleapp-0:0.18.0-SNAPSHOT.x86_64 conflicts with file from package sensu-1:0.27.0-1.el7.x86_64
  file /etc/sensu/conf.d from install of sampleapp-0:0.18.0-SNAPSHOT.x86_64 conflicts with file from package sensu-1:0.27.0-1.el7.x86_64
```

## Possible Solution

Roll back directory ownership in the spec file.

## Your Environment

* Sensu version used: 0.26.0 & 0.27.0 
* Active Sensu extensions (e.g. WizardVan 0.1.0): NA
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7-3.1611
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): NA

**Comment by majormoses** [comment]
I believe that was an intentional choice @cwjohnston can you elaborate? I seem to recall a discussion about epel packages being signed. Btw I don't know as much about packaging RPMs as I do debs but this sounds like a sane thing to me, if you have 2 packages that manage the same group of files then how would you resolve conflicts. 

What is the purpose of managing files in /etc/sensu/conf.d with an rpm and not some config management like chef, puppet, ansible?

I have not really had to package RPMs in a while so take what I say with a grain of salt as I am probably missing something important.

**Comment by blee1170** [comment]
@majormoses Thanks for the feedback. This is not about signing the RPM, its about how the RPM claims ownership in the RPM database on the host. I don't know the best term for what RPM is doing, but it has to deal with the rpm database as far as I know.

We practice immutable infrastructure with our deployments. So we create a image once and deploy that image where we need to. If we make a change, then we create a new image. RPMs are the best why to manage that.

**Comment by cwjohnston** [comment]
@blee1170 thanks for reporting this issue, it does sound to me like a regression. Starting with Sensu 0.27 we switched our build tool chain to Chef Omnibus, and as a result the rpm specs are being built differently which may account for the behavior you are seeing.

**Comment by blee1170** [comment]
@cwjohnston Is it something that you might be willing to switch back?

**Comment by majormoses** [comment]
Agreed it sounds like a regression, my question is this preferable now after the fact? I still question the need for multiple packages to manage files in the same dir. I still feel like what you want is config management to manage files. Just my 2 cents...

**Comment by blee1170** [comment]
Looks like the sensu RPM is also owning the /etc/systemd/system directory as well. So we are unable to drop in systemd services as well.

**Comment by majormoses** [comment]
Again I see this as sane (and personally desired) behavior. IMHO you should not be using a package to manage other packages files, you need config management to manage these.

**Comment by majormoses** [comment]
Here are some links to the CM that sensu has out of the box code for:
- https://github.com/sensu/sensu-chef
- https://github.com/sensu/sensu-puppet
- https://github.com/sensu/sensu-ansible

**Comment by majormoses** [comment]
To clarify my stance I agree that it is a bug that it does not allow writing to `/etc/sensu/conf.d` but for every other resource that the package manages I do not feel that other packages should attempt to manage these. This introduces complexity and risk when dealing with upgrades (who wins between changes)

**Comment by cwjohnston** [comment]
@blee1170 

> Is it something that you might be willing to switch back? Not Omnibus, but how the RPM claims ownership of the directory.

I understand the use case as "RPM packages should be able to write JSON configuration into /etc/sensu/conf.d and its subdirectories." I think if at all practical we should enable this use case. 👍 

> Looks like the sensu RPM is also owning the /etc/systemd/system directory as well. So we are unable to drop in systemd services as well.

This sounds like a big problem as well, and  I'd like to be able to reproduce this myself. Is this causing problems with any publicly available packages you're aware of?

**Comment by cwjohnston** [comment]
I've opened https://github.com/sensu/sensu-omnibus/issues/224 to track this, as the changes to address the problem will likely be made the sensu-omnibus project.
