### ISSUE TITLE
Can't delete or access clients with spaces or other special characters in the name

### ISSUE THREAD

**Issue by karottenreibe** [sensu/sensu#1706]
It is easily possible to create clients with any number of special characters in their name, most notably with spaces (which is reasonable IMO). However, the API cannot handle any requests to clients that contain characters other than /[\w\.\-]/. This is due to the parsing of request URIs in the API's routes with the parse_uri method.

Creating such a client results in a client that can't be viewed in Uchiwa and can't be deleted via Uchiwa or the API either.

## Expected Behavior
- There should be a clear definition of which characters are allowed in client names
- Invalid client names should be rejected by the server and not propagated to redis
- All valid client names must be accepted by the API (possibly in URl-encoded form)

## Current Behavior
- I did not find any official definition of what constitutes a valid client name
- The server seems to accept arbitrary client names
- The API is very restrictive in what client names are accepted.

### Quick workaround
- Adjust all route regexes to allow more valid client names, in particular also URI-encoded ones. E.g. change the client route from `CLIENT_URI = /^\/clients\/([\w\.-]+)$/` to `CLIENT_URI = /^\/clients\/([^\/?#]+)$/` to allow a much larger character set.

### Cleaner solution
- Don't use regexes to parse URIs, use an actual URI parsing library, e.g. CGI::parse
- Don't use URI.escape since [it is apparently broken](https://stackoverflow.com/questions/2824126/whats-the-difference-between-uri-escape-and-cgi-escape#13059657).

## Steps to Reproduce (for bugs)
- Create a client.json and set `name: "Test Client"`
- Try to issue a DELETE request for that client:
  - `DELETE http://localhost:4567/client/Test Client` fails (404)
  - `DELETE http://localhost:4567/client/Test%20Client` fails (404)
  - `DELETE http://localhost:4567/client/Test+Client` fails (404)

## Context
I now have an undeletable client.

## Your Environment

* Sensu version used: 0.29.0
* Active Sensu extensions (e.g. WizardVan 0.1.0): none
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Redis

**Comment by mcbsdEU** [comment]
I had similar problem:
#1681

**Comment by ChrisOnToure** [comment]
Can confirm and +1 for this!

**Comment by portertech** [comment]
We were able to reproduce this issue. Sensu settings validation appears to be ineffective, we are actively working to determine the cause. There are several other reasons special characters (and spaces) can not be used in definition names.

**Comment by portertech** [comment]
Sensu 1.0.1-1 is now available, with a configuration validation fix - https://github.com/sensu/sensu/blob/master/CHANGELOG.md#101---2017-07-24
