### ISSUE TITLE
Zesty packages missing?

### ISSUE THREAD

**Issue by talonx** [sensu/sensu#1707]
Following the instructions [here](https://sensuapp.org/docs/latest/platforms/sensu-on-ubuntu-debian.html#sensu-core) for installation on Zesty (Ubuntu 17.04), the packages seem to be missing in https://sensu.global.ssl.fastly.net/apt/
## Expected Behavior

Installation to work
## Current Behavior

```
Err:8 https://sensu.global.ssl.fastly.net/apt zesty/main i386 Packages
  404  Not Found

```
## Possible Solution

Add Zesty packages to the mirror
## Your Environment

* Sensu version used:
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04):
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by majormoses** [comment]
@cwjohnston do you guys typically package for non LTS versions?

**Comment by cwjohnston** [comment]
@talonx @majormoses Its not clearly documented via our platforms page but we target our package builds Ubuntu LTS releases. Can you please try using xenial and let us know if you have any trouble?

**Comment by majormoses** [comment]
yup I had suspected as much, can we please make that clearer on the docs?

**Comment by cwjohnston** [comment]
@majormoses I've started work in https://github.com/sensu/sensu-docs/pull/608 to clarify.

**Comment by majormoses** [comment]
thanks
