### ISSUE TITLE
Sensu server crashing with undefined method error

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1708]
Sensu server is crashing with the error message below. This happens a couple of times a day with no timing pattern. 

`{"timestamp":"2017-07-20T08:35:32.389898+0700","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:150:in `update_client_registry': undefined method `+' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:190:in `block in setup_keepalives'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:162:in `block in on_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `block in exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:294:in `handle_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:348:in `block in <class:Consumer>'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/session.rb:959:in `receive_frameset'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/session.rb:933:in `receive_frame'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:33:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'`

## Your Environment
* Sensu version used: Sensu version 1.0.0 (sensu.x86_64 1:1.0.0-1.el6)
* Active Sensu extensions (e.g. WizardVan 0.1.0): All default no extra ones
* Operating System and version (e.g. Ubuntu 14.04): CentOS release 6.7 (Final)
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): "RabbitMQ","3.3.4" & "Erlang R14B04 (erts-5.8.5)

**Comment by portertech** [comment]
Odd, the line in question is https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L150 and the error suggests `client[:subscriptions]` is nil. Need to double check our client definition validations efforts.

**Comment by portertech** [comment]
Sensu 1.0.1-1 is now available, with a configuration validation fix - https://github.com/sensu/sensu/blob/master/CHANGELOG.md#101---2017-07-24
