### ISSUE TITLE
pipe handlers not honoring occurrences

### ISSUE THREAD

**Issue by robertlabrie** [sensu/sensu#1714]
Given the below handler and check definition, why is occurrences not being honored? I googled and read threads saying the plugin was dead or somesuch, but I don't get it. I have occurrences set, but the handler goes off anyway.

Any help would be appreciated. 
```
{
  "handlers": {
    "pagerduty": {
      "type": "pipe",
      "filters": [
        "environment_alpha"
      ],
      "severities": [
        "critical",
        "ok"
      ],
      "command": "/usr/share/pdagent-integrations/bin/pd-sensu -k **************************************"
    }
  }
}
```
and the check definition:
```
{
  "checks": {
    "check-ipsec-auto-vpn": {
      "command": "sudo check-ipsec-auto.sh",
      "subscribers": [
        "openswan"
      ],
      "handlers": [
        "pagerduty",
        "default"
      ],
      "refresh": 1800,
      "interval": 60,
      "description": "This checks IPSec VPN number of tunnels, as well as connection between site-to-site VPN servers -- OPS-1854",
      "occurrences": 3,
    }
  }
}

**Comment by robertlabrie** [comment]
This is Calebs gist, I'm guessing it's good?
https://gist.github.com/calebhailey/8a30a00c6aadfebf7f767444f0a3df49

**Comment by portertech** [comment]
@robertlabrie add "filters": ["occurrences"] to your handler definition.

**Comment by robertlabrie** [comment]
TYVM -- I swear I googled this. Hopefully next person find this one.
