### ISSUE TITLE
Hi..can we execute a handler after certain duration of time like every 10 minutes?

### ISSUE THREAD

**Issue by balajik1992** [sensu/sensu#1717]

**Comment by cwjohnston** [comment]
@balajik1992 can you please elaborate on your desired use case?

Handlers are executed only in response to the server processing a qualified event, i.e. events indicating non-OK state, or any event with check type "metric". Depending on what you're trying to achieve, you may have some success configuring a metric check with cron scheduling which would trigger a specified handler every 10 minutes.

**Comment by portertech** [comment]
You could use a check with `"cron": "*/10 * * * *"`, to produce an event to trigger a specific handler every ~10 minutes.
