### ISSUE TITLE
Debian Stretch (9.0) packages

### ISSUE THREAD

**Issue by gchenuet** [sensu/sensu#1718]
Hi,

Do you plan to release Sensu packages for Debian Stretch (9.0) distro ?

Thanks
Guillaume

**Comment by portertech** [comment]
@amdprophet this should be fairly trivial, yes?

**Comment by amdprophet** [comment]
Looking into this now.

**Comment by ghoneycutt** [comment]
+1

**Comment by amdprophet** [comment]
Debian 9 support has been added to our build pipeline. Sensu 1.0.3 will be the first version to include a Debian 9 package.

**Comment by ghoneycutt** [comment]
I don't see Stretch at https://sensu.global.ssl.fastly.net/apt/dists/

Could you leave this open until the packages are available.

**Comment by amdprophet** [comment]
Sensu 1.0.3 (with the first Debian 9 package) should be arriving sometime next week.

**Comment by ghoneycutt** [comment]
@amdprophet How's this coming along? We're getting requests for this.

**Comment by amdprophet** [comment]
@ghoneycutt the packages are currently in the unstable channel and will be promoted to stable on Monday.

**Comment by amdprophet** [comment]
Closing this out now as we've released Sensu 1.0.3. Packages for Debian 9 (Stretch) should now be available in the apt repository. :)

**Comment by ghoneycutt** [comment]
Thank you!
