### ISSUE TITLE
Hi...can we use different contacts in different client  environments

### ISSUE THREAD

**Issue by balajik1992** [sensu/sensu#1719]
for example
I am going to use contact routing and mail handler plugins
contacts are as below
userA:   a@domain.com
userB: b@domain.com

client.json :
enviroment : dev/uat

if It is uat, The USER A should receive mail, if dev User B should receive mail
is this possible ?
can we specify it in checks by any chance ?

**Comment by cwjohnston** [comment]
@balajik1992 this kind of functionality has to be implemented in the handler you choose to use.

Sensu Enterprise provides [contact routing](https://sensuapp.org/docs/latest/enterprise/contact-routing.html) as a feature which applies to all integrated handlers for notification and metrics. 

Some open source handler plugins, e.g. [handler-mailer.rb from the sensu-plugins-mailer package](https://github.com/sensu-plugins/sensu-plugins-mailer/tree/1.2.0#contact-based-routing), have implemented similar patterns.

**Comment by balajik1992** [comment]
I am using conatct routing and handler-mailer.rb from the sensu-plugins-mailer package, 

But How can I specify like below

if environment : dev
then my check should look like below
{
  "checks": {
    "check_cpu": {
      "handlers":  [ "x_email",     ],
      "contacts": **["ebb_dev"],**
      "command": "/usr/local/nagios/libexec/check_tcp -H imbhubu-mw03.nam.nsroot.net -p 25 -e 220 -s quit -e 221 -w 20 -c 10",
      "subscribers": [ "x-sub"      ] }
  }
}

if environment : uat
then my check should look like below
{
  "checks": {
    "check_cpu": {
      "handlers":  [ "x_email",     ],
      "contacts": **["ebb_uat"],**
      "command": "/usr/local/nagios/libexec/check_tcp -H imbhubu-mw03.nam.nsroot.net -p 25 -e 220 -s quit -e 221 -w 20 -c 10",
      "subscribers": [ "x-sub"      ] }
  }
}

**Comment by portertech** [comment]
@balajik1992 please re-open this issue against https://github.com/sensu-plugins/sensu-plugins-mailer, as this is not in scope of the sensu core project.
