### ISSUE TITLE
Cannot restart/kill sensu-client on FreeBSD via rc.d script.

### ISSUE THREAD

**Issue by madelaney** [sensu/sensu#1720]
## Expected Behavior
When running `sudo service sensu-client restart`, I'd expect the service to restart.

## Current Behavior
The script fails with the following message:
```sudo service sensu-client restart
Validating sensu-client configuration
configuration is valid
Stopping sensu_client.
kill: 72719: No such process
sensu_client already running?  (pid=72719).
```

However, that is a valid PID, and the sensu-client is running:
```sudo ps -p 72719
  PID TT  STAT     TIME COMMAND
72719  -  S    15:32.83 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -b -c /usr/local/etc/sensu/config.json -d /usr/local/etc/sensu/conf.d -e /usr/local/etc/sensu/extensions -p /var/run/sensu/sensu-client.pid -l /var/log/sensu/sens
```

## Possible Solution
Not really sure at this moment.

## Steps to Reproduce (for bugs)
1. Setup FreeBSD 10 or FreeBSD 11.
2. Set security.bsd.see_other_uids, and security.bsd.see_other_uids to '0' in `/etc/sysctl.conf`
3. Start the Sensu client
4. Try to restart the Sensu client.

## Context
This prohibits my puppet setup from being able to restart the sensu-client after a puppet catalog.

## Your Environment
* Sensu version used: `sensu-1.0.0_1`
* Active Sensu extensions: N/A
* Operating System and version: FreeBSD 11.1
* Transport and runtime versions: Erlang (erlang-runtime19-19.3.6.1), and RabbitMQ (rabbitmq-3.6.10_1)

**Comment by portertech** [comment]
Appropriate repository for this issue is https://github.com/sensu/sensu-omnibus

**Comment by portertech** [comment]
@amdprophet any ideas?

**Comment by amdprophet** [comment]
This is only happening on hardened systems that do not allow pid peeking. Some investigation will be needed to fix this. I've opened https://github.com/sensu/sensu-omnibus/issues/230 to track the work.
