### ISSUE TITLE
Sensu consumer find out hostname or IP

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1721]
Uchiwa is reporting in the datacenter view one more consumer (4) which is actually existing (3). The Sensu health check page is also reporting 4 consumers. How can I find out the hostname or IP of this consumer?

Thanks in advance.

**Comment by Evesy** [comment]
If you're running Sensu 0.28 or later you can hit the Sensu API /info endpoint to retrieve information on the known Sensu servers, i.e. ```http://{{url}}:4567/info```, which might show you what your fourth consumer is.

Alternatively you can look into your transport layer to see the hostnames/IP's of your consumers. If you're using Rabbit for example & have the admin GUI enabled you can login and navigate to `Queues` => Click into either `Results` or `Keepalives` queues => Expand the `Consumers` dropdown -- That should then list the IP's of your consumers.

**Comment by ChrisOnToure** [comment]
Nice! Exactly what i was looking for.
