### ISSUE TITLE
Sensu time sensitivity

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1722]
Hello,

We got an issue where our time servers weren't reachable, which resulted in a time offset of 1 - 3 seconds on the machines which has the sensu-clients installed. This resulted in many false keepalive alerts jumping all over the place from OK to Critical. Is there a way to adjust the Sensu time sensitivity or change the client to detect a time off and giving a warning instead of keepalive flapping resulting in email floods?

Thanks in advance.

**Comment by Evesy** [comment]
Hi Chris,

Assuming you are talking Client keepalives (and not check TTL's) the default values (unless changed in the client config) are set to warn after no keepalive for 120 seconds, and go critical after 180 seconds.

With that in mind I wouldn't expect to see you getting alerts based solely on a 3 second time offset with your client with the default values. First thing I'd check is if there's a backlog of keepalive events on your queue that might be being processed slowly -- You can use the /info endpoint `http://{{url}}:4567/info` to see number of messages on the results queue (assuming you are on the relevant release), however if not you can check in the Rabbit GUI itself.

In regards to changing the time sensitivity, it's entirely possible via the client config using keepalive attributes: https://sensuapp.org/docs/1.0/reference/clients.html#keepalive-attributes, however I don't think you should be having any trouble with the defaults.
