### ISSUE TITLE
Sensu API high availibility

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1725]
Hello,

question regarding high availability and the need of keepalived/haproxy.
For Rabbitmq as transport and Redis as store there are build in features to specify multiple endpoints and sensu-server takes care about if a server is not reachable anymore. But how is it with the sensu-api I didn't find a way to specify multiple sensu-api endpoints. Do I still need keepalived/haproxy to provide HA. As far as I know the API is needed for the sensu-server to check silenced alerts?! 

Thanks in advance

**Comment by portertech** [comment]
@ChrisOnToure you can configured multiple Sensu APIs per Uchiwa and the Sensu Enterprise Dashboard "datacenter", no need for an LB for the dashboard component. We recently added settings validation for API "endpoints" (https://github.com/sensu/sensu-settings/pull/65), however, tools like sensu-plugin have yet to be updated to use it.

**Comment by portertech** [comment]
@mcbsdEU see https://docs.uchiwa.io/guides/high-availability/#datacenters-high-availability 👍

**Comment by mcbsdEU** [comment]
@portertech Yeah, my fault, I overlooked this one. This is great option.
Thanks
