### ISSUE TITLE
Sensu RPM upgrade does not restart sensu-client

### ISSUE THREAD

**Issue by pgporada** [sensu/sensu#1727]
I'm currently running a mix of sensu 0.29.0, 1.0.0, 1.0.1, and 1.0.2 across some of my home lab. I've noticed that all the servers have successfully installed the 1.0.2 rpm, but they did not restart their local sensu services after the upgrade.

## Expected Behavior
I expect the rpm upgrade to restart whichever sensu services are running on a node.

## Current Behavior
The nodes that upgrade the sensu rpm package do not restart their sensu services.

## Possible Solution
I could not find a source RPM so I can't troubleshoot this.

## Steps to Reproduce (for bugs)
1. Have a centos7 node with 0.29.0, 1.0.0, or 1.0.1 installed
2. Have unattended upgrades upgrade the package to whatever is the latest version
3. Check Uchiwa to see that the sensu version reported for that client is NOT the latest version, but a prior version
4. https://deanoinamerica.files.wordpress.com/2014/02/khaaan.jpg

## Context
I have unattended upgrades which helps with a lot of things. When I am going through Uchiwa and resolving alerts, I want to know that my sensu clients/server are all running the same version of Sensu.

## Your Environment
* Sensu version used: 0.29.0, 1.0.0, 1.0.1, 1.0.2
* Operating System and version (e.g. Ubuntu 14.04): Centos 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):  RabbitMQ 3.6.9, Erlang 19.0.4

**Comment by portertech** [comment]
@pgporada The Sensu RPM source can be found at https://github.com/sensu/sensu-omnibus. The Sensu packages intentionally do not restart on upgrade, leaving restart to things like configuration management, allowing for more control (timing etc.).
