### ISSUE TITLE
Are the address and custom attributes for a proxy client possible?

### ISSUE THREAD

**Issue by pietervogelaar** [sensu/sensu#1729]
I a normal client definition like below it's possible to configure the "address" attribute and add custom attributes like "environment".

```
{
  "client": {
    "address": "10.15.1.10",
    "application": "myapp",
    "class": "myapp-tomcat-prd",
    "environment": "prd",
    "keepalive": {
    },
    "name": "myapp-tomcat-01p.example.org",
    "role": "tomcat",
    "safe_mode": true,
    "socket": {
      "bind": "127.0.0.1",
      "port": 3030
    },
    "subscriptions": [

    ]
  }
}
```

Is that also possible for a proxy client?

I have the following definition:

```
{
  "checks": {
    "otherhost1_check_total_procs": {
      "command": "/usr/lib64/nagios/plugins/check_nrpe -H 172.0.0.10 -t 20 -c check_total_procs",
      "interval": 60,
      "name": "check_total_procs",
      "source": "otherhost1",
      "standalone": true
    }
  }
}
```

So how can I add a custom attribute "environment" to this proxy client above?

**Comment by portertech** [comment]
@pietervogelaar you can create and manage Proxy Clients with the Sensu API or the latest version of Uchiwa (or the Sensu Enterprise Dashboard). The documentation for the POST /clients endpoint can be found at https://sensuapp.org/docs/1.0/api/clients-api.html#clients-post, you can add your "environment" attribute 👍

**Comment by pietervogelaar** [comment]
@portertech Are these changes persistent after reboot of rabbitmq, redis or sensu server?

**Comment by portertech** [comment]
@pietervogelaar they persist in Redis (which is persisted to disk), in the Sensu client registry.
