### ISSUE TITLE
Check failed to run: undefined method `missing_extensions?' for nil:NilClass

### ISSUE THREAD

**Issue by dmitrypol** [sensu/sensu#1730]
Please forgive a very newbie question but I keep getting errors on my Sensu server (someone else who has left the company set it up before I started).  I am really stuck and would appreciate any guidance on how to troubleshoot this.  

`Check failed to run: undefined method `missing_extensions?' for nil:NilClass, ["/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb:146:in `missing_extensions?'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1037:in `block in find_by_path'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1036:in `each'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1036:in `find'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1036:in `find_by_path'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:209:in `try_activate'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.16/lib/aws-sdk-core/xml/parser/engines/ox.rb:1:in `<top (required)>'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.16/lib/aws-sdk-core/xml/parser.rb:86:in `load_engine'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.16/lib/aws-sdk-core/xml/parser.rb:92:in `try_load_engine'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.16/lib/aws-sdk-core/xml/parser.rb:79:in `block in set_default_engine'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.16/lib/aws-sdk-core/xml/parser.rb:78:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.16/lib/aws-sdk-core/xml/parser.rb:78:in `set_default_engine'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.16/l…`

Sensu version 0.29
Ubuntu 14.04

**Comment by portertech** [comment]
This error is not related to Sensu Core, it is a AWS Sensu Plugin error. Please feel free to report this error at https://github.com/sensu-plugins/sensu-plugins-aws

Thank you 👍
