### ISSUE TITLE
sensu configured to use redis as transport tries to connect to amqp/rabbitmq

### ISSUE THREAD

**Issue by arthurlogilab** [sensu/sensu#1731]
Following https://sensuapp.org/docs/latest/reference/transport.html#example-transport-definition

## Expected Behavior
sensu-server and sensu-api to connect to redis and not try rabbitmq when transport has been set to redis

## Current Behavior
```
{"timestamp":"2017-08-29T14:09:46.771017+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-08-29T14:09:48.771974+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-08-29T14:09:52.772157+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2017-08-29T14:09:58.772358+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
```

## Steps to Reproduce (for bugs)

```
/etc/sensu# cat conf.d/transport.conf 
{
  "transport": {
    "name": "redis",
    "reconnect_on_error": true
  }
}
/etc/sensu# cat conf.d/redis.json 
{
  "redis": {
    "host": "127.0.0.1",
    "port": 6379
  }
}
/etc/sensu# rgrep rabbitmq *
[nothing]
```

## Your Environment

* Sensu version used: ii  sensu                             1.0.2-1 
* Active Sensu extensions (e.g. WizardVan 0.1.0): n/a
* Operating System and version (e.g. Ubuntu 14.04): debian jessie
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): redis (trying no rabbitmq)

(I did find a bunch of bugs about "[amqp] Detected TCP connection failure: Errno::ECONNREFUSED" but they all seemed to be for people trying to use sensu *with* rabbitmq, which is not my case.)

Thanks for your help.

**Comment by portertech** [comment]
@arthurlogilab I am unable to reproduce your error. Have you tried using `sensu-client --print_config` to confirm your running configuration?

**Comment by arthurlogilab** [comment]
The fix is renaming transport.conf to transport.json. Am using the sensu-formula for salt and fixed it there : https://github.com/saltstack-formulas/sensu-formula/pull/47/files
