### ISSUE TITLE
Fallback handler

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu#1733]
Provide a configuration option for a fallback/failover handler to be executed in the instance that the primary handler fails

## Expected Behavior
When using a handler (such as slack), if the Slack service is down, or the message can't be sent for any other reason, a fallback/failover handler should handle the event

## Current Behavior
If a handler fails, it's logged but there is no further attempt to handle the event.

## Possible Solution

```
{
  "handlers": {
    "slack": {
      "config_option": "config_value",
      "fallback": ["email"]
    }
  }
}
```

**Comment by testeddoughnut** [comment]
+1

**Comment by portertech** [comment]
We intend to implement this functionality in [Sensu 2.x](https://github.com/sensu/sensu-go), with Handler Hooks 🎉 Closing this issue in favour of https://github.com/sensu/sensu-go/issues/702
