### ISSUE TITLE
TCP socket handler raises an error with an empty output check result

### ISSUE THREAD

**Issue by multani** [sensu/sensu#1734]
## Current Behavior
I have a ``metric`` type check which generates check results with an empty string value in the ``output`` field. The handler associated to this check is ``tcp`` type handler.
When the check result is being passed to the TCP handler, it generates an error as follow:
```
{
  "timestamp": "2017-09-01T13:32:07.065531+0000",
  "level": "error",
  "message": "handler error",
  "handler": {
    "mutator": "only_check_output",
    "severities": ["ok", "warning", "critical", "unknown"],
    "timeout": 30,
    "socket": {
      "host": "10.40.3.7",
      "port": 2003
    },
    "type": "tcp",
    "name": "graphite-carbon"
  },
  "event_data": "",
  "error": "failed to connect to socket"
}
```

## Expected Behavior
I expect in this case to have:
* either a proper error message explaining the problem with the socket.
* or no error at all.

## Steps to Reproduce (for bugs)
I have the following handler configured:

```
{
  "handlers": {
    "graphite-carbon": {
      "mutator": "only_check_output",
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "socket": {
        "host": "10.40.3.7",
        "port": 2003
      },
      "type": "tcp"
    }
  }
}
```

And this is the check result which has been produced:
```
{
  "timestamp": "2017-09-01T17:42:36.888790+0000",
  "level": "debug",
  "message": "processing result",
  "result": {
    "client": "xxx",
    "check": {
      "command": "xxx",
      "handlers": [
        "graphite-carbon"
      ],
      "occurrences": 1,
      "refresh": 7200,
      "source": "xxx",
      "type": "metric",
      "name": "metrics-xxx",
      "issued": 1504287756,
      "executed": 1504287756,
      "duration": 0.488,
      "output": "",
      "status": 0
    }
  }
}
```

When this result is passed to the handler, Sensu generates the following error message:
```
{
  "timestamp": "2017-09-01T13:32:07.065531+0000",
  "level": "error",
  "message": "handler error",
  "handler": {
    "mutator": "only_check_output",
    "severities": [
      "ok",
      "warning",
      "critical",
      "unknown"
    ],
    "timeout": 30,
    "socket": {
      "host": "10.40.3.7",
      "port": 2003
    },
    "type": "tcp",
    "name": "graphite-carbon"
  },
  "event_data": "",
  "error": "failed to connect to socket"
}
```

## Context
I was debugging some missing metrics and I found these errors messages in my logs. I thought it was connected to the missing metrics I was looking for (actually not, there were other metrics) and I spend quite a bunch of time trying to understand why Sensu couldn't connect to this socket.
The socket really *is* opened:
```
$ echo "test.sensu 4 `date +%s`" | nc -q 0 -v 10.40.3.7 2003
Connection to 10.40.3.7 2003 port [tcp/cfinger] succeeded!
$
```
and other metrics checks are handled correctly.

## Possible Solution
I checked and tried to debug the code and it looks [Socket.connection_completed](https://github.com/sensu/sensu/blob/master/lib/sensu/server/socket.rb#L28) is never called. The ``@connected_at `` is not set and the [test in unbind](https://github.com/sensu/sensu/blob/master/lib/sensu/server/socket.rb#L42) triggers the error message.

I will add a filter to prevent these "empty" results to go the my handlers, I guess that would be a proper fix configuration-speaking.

That would be great if the error message generated by Sensu is *more correct*, or at least more comprehensible. But as far as my knowledge of EventMachine go, I don't know how to fix that further.

## Your Environment

* Sensu Server = 1.0.2
* Sensu Client = 0.28.2

**Comment by portertech** [comment]
We should produce a more informative error log event when the event_data is empty (no need to connect and write to a socket).
