### ISSUE TITLE
Silence with regex

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1736]
Hello Is it possible to create silencing eit regular expression in case a client is not yet registered to sensu but will be and I dont want get alerts?

Example: Silence testserver*
This would silence all hosts like testtserver1, testtserver2 etc.

**Comment by portertech** [comment]
Using regular expression characters in silence subscription entries is problematic for two reasons.

1. Users would then have to escape certain characters already used in their subscription names, e.g. `my\.escaped\.hostname`

2. Silencing currently utilizes quick Redis key lookups, for every result/event, introducing regular expression support would require a bit of a rewrite and come at a cost of performance

**Comment by ChrisOnToure** [comment]
@portertech Fair enough. Thanks for the explanation.
