### ISSUE TITLE
Sensu client long time for reconnect to amqp

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1738]
Hello,

We sometimes have the case that clients loosing connection to the message queue and take minutes to reconnect. This results into (false) keep alive alerts. The hartbeat on the clinets ist set to 20s.

sensu-client logs:
> {"timestamp":"2017-09-11T04:20:44.036412+0700","level":"info","message":"publishing check result","payload":{"client":"xxx","check":{"handle":true,"standalone":false,"refresh":3600,"dependencies":["keepalive"],"command":"/etc/sensu/plugins/linux/check-inodes.sh ","occurrences":1,"service":"linux_basic_checks","owner":"it-infra-external","severity":"high","aggregate":false,"name":"linux-disk-inodes","issued":1505078443,"executed":1505078444,"duration":0.005,"output":"OK","status":0}}}
{"timestamp":"2017-09-11T04:22:42.644134+0700","level":"error","message":"[amqp] Detected missing amqp heartbeats"}
{"timestamp":"2017-09-11T04:22:42.646467+0700","level":"warn","message":"transport connection error","reason":"skipped heartbeats"}
{"timestamp":"2017-09-11T04:22:42.646596+0700","level":"warn","message":"reconnecting to transport"}

client rabbitmq config
> {
  "rabbitmq": {
    "host": "xxx",
    "password": "xxx",
    "port": 5672,
    "user": "xxx",
    "vhost": "/sensu",
    "heartbeat": 20
  }
}

Sensu client version: 0.29
Sensu Server version: 1.0.0
Rabbitmq version: RabbitMQ 3.3.4, Erlang R14B04
Client OS: Centos 7.2.1511

**Comment by portertech** [comment]
@ChrisOnToure is this before or after you removed HAProxy from your RabbitMQ deployment?

**Comment by ChrisOnToure** [comment]
@portertech This was before remove haproxy from the configuration

**Comment by portertech** [comment]
Beyond setting/using Sensu rabbitmq heartbeat and tuning the TCP stack, there is little else that can be done. Your version of RabbitMQ and Erlang are very old and are known to contain bugs and security vulnerabilities, upgrading both of them will likely solve your RabbitMQ problems.
