### ISSUE TITLE
Is token substitution possible for proxy client checks?

### ISSUE THREAD

**Issue by pietervogelaar** [sensu/sensu#1739]
I have the following check:

```
{
  "checks": {
    "server1.example.org_check_esxi_hardware": {
      "command": "check_esxi_hardware -H 10.10.10.21 --user :::check_esxi_hardware.user::: --pass :::check_esxi_hardware.pass::: -t 8",
      "interval": 60,
      "name": "check_esxi_hardware",
      "source": "server1.example.org",
      "standalone": true
    }
  }
}
```

This generated a proxy client in Sensu. With uchiwa I edited the client and added:

```
"check_esxi_hardware": {
    "pass": "secret",
    "user": "root"
  },
```

But I the check keeps giving the error "Unmatched client token(s): check_esxi_hardware.user, check_esxi_hardware.pass". Is token substitution not possible for proxy client checks?

**Comment by pietervogelaar** [comment]
I created a wrapper script now to hide the sensitive data which is even better.

**Comment by portertech** [comment]
@pietervogelaar that will not work as you expect: the check will be executed on a sensu client, using the local client definition for the token substitution, and then the result will be published with the configured source. To accomplish what I think you are trying to achieve, you probably need https://sensuapp.org/docs/1.0/reference/checks.html#proxy-requests-attributes

**Comment by portertech** [comment]
Proxy requests are able to accomplish this task, https://sensuapp.org/docs/1.0/reference/checks.html#proxy-requests-attributes

@pietervogelaar glad you found a solution with a wrapper script tho 👍
