### ISSUE TITLE
 The repository 'https://sensu.global.ssl.fastly.net/apt yakkety Release' does not have a Release file.

### ISSUE THREAD

**Issue by rj-reilly** [sensu/sensu#1741]
did this from both chef and then manually as described in: I tried Ubuntu 17.04 and 16.10
[https://sensuapp.org/docs/0.29/platforms/sensu-on-ubuntu-debian.html](https://sensuapp.org/docs/0.29/platforms/sensu-on-ubuntu-debian.html)

I get the error and it cannot find sensu in the repo
The repository 'https://sensu.global.ssl.fastly.net/apt yakkety Release' does not have a Release file.

## Expected Behavior
sensu should get installed.

/etc/apt/sources.list.d/sensu.list
```cat sensu.list 
deb     https://sensu.global.ssl.fastly.net/apt yakkety main

**Comment by amdprophet** [comment]
Hi @rj-reilly,

We are currently building packages for LTS releases only. Try using the 16.04 repo with 16.10 and 17.04.

**Comment by rj-reilly** [comment]
@amdprophet  ok will do thanks for the response !
