### ISSUE TITLE
Using cron for checks doesn't trigger handler

### ISSUE THREAD

**Issue by renzner** [sensu/sensu#1744]
I have a standalone check that looks for a backup file every 12:30 am. So cron attribute would best fit this check. I confirmed that checks were issued by checking the sensu dashboard (uchiwa). The problem is it's not sending me an email that a file matched the check. To test the mail handler, I used interval instead of cron. And it's working fine. Maybe it's a problem with cron attrib. Anyone?

## Expected Behavior
Handler should be triggered and I should receive an email.

## Current Behavior
Seems like handler does nothing and I haven't receive any email.

## Steps to Reproduce (for bugs)
These are my config files

client check
```
{
  "checks": {
    "check_s01files": {
      "command": "sudo /opt/sensu/embedded/bin/check-file-exist.rb -c /disk1/backup/s01.snapzio.com/2017-09-20/files.tar.gz",
      "standalone": true,
      "cron": "30 0 * * *",
      "occurrences": 4,
      "handler": "notify"
    }
  }
}
```
notify handler
```
{
  "handlers": {
    "notify": {
      "type": "set",
      "handlers": ["email"]
    }
  }
}
```
email handler
```
{
  "handlers": {
    "email": {
      "type": "pipe",
      "command": "/opt/sensu/embedded/bin/handler-mailer.rb",
      "filter": "occurrences",
      "timeout": 10
    }
  },
  "mailer": {
    "mail_from": "test@test.com",
    "mail_to": "mail@mail.com",
    "smtp_port": "587",
    "smtp_address": "mail.test.com",
    "smtp_domain": "test.com",
    "smtp_username": "username@test.com",
    "smtp_password": "testpass",
    "smtp_authentication": "plain"
  }
}
```
## Environment
* Sensu version used: 1.0.2-1
* Operating System and version (Ubuntu 16.04):
* Transport and runtime versions (e.g. RabbitMQ 3.6.12-1 on Erlang 20.x):

**Comment by portertech** [comment]
@renzner the check execution would have to return a non-zero status in order to trigger its event handler. You could add `"type": "metric"` to your check definition if you would like every result to trigger your event handler.

**Comment by renzner** [comment]
@portertech If a file matched to the check it will return a non-zero status. That's how check-file-exist module works. Thus, it should trigger the handler. :)

**Comment by cwjohnston** [comment]
I'm going to go ahead and close this issue due to lack of activity. Please feel free to open a new issue if you think more investigation is needed.
