### ISSUE TITLE
Why do I get the log event "event filtering in sensu-plugin is deprecated"?

### ISSUE THREAD

**Issue by pietervogelaar** [sensu/sensu#1757]
I use the slack handler (https://github.com/sensu-plugins/sensu-plugins-slack) and sometimes I get the log entry below in the sensu-server.log. When I look at the slack plugin I don't see any deprecated filtering functionality. Why do I get the error below?

`
{"timestamp":"2017-09-27T15:49:52.379390+0200","level":"info","message":"handler output","handler":{"command":"handler-slack.rb","type":"pipe","filters":["production_environment","state_change"],"severities":["ok","critical"],"handle_flapping":false,"handle_silenced":false,"name":"slack"},"event":{"id":"79cf548e-3ad4-49c7-9117-462ab9622793"},"output":["warning: event filtering in sensu-plugin is deprecated, see http://bit.ly/sensu-plugin\nconnection refused attempting to query the sensu api for a stash\nconnection refused attempting to query the sensu api for a stash\nconnection refused attempting to query the sensu api for a stash\nwarning: occurrence filtering in sensu-plugin is deprecated, see http://bit.ly/sensu-plugin\n"]}
`

**Comment by pietervogelaar** [comment]
See also https://github.com/sensu-plugins/sensu-plugins-slack/issues/52

**Comment by portertech** [comment]
@pietervogelaar the deprecated functionality is in the sensu-plugin library, which is a dependency of the slack handler that you are using. Please see https://blog.sensuapp.org/deprecating-event-filtering-in-sensu-plugin-b60c7c500be3 for the reasoning behind these messages and how to move forward. Once the slack handler and other plugins like it are updated to use a more recent version of sensu-plugin, these messages will go away.
