### ISSUE TITLE
Proxy Client creation from json config file

### ISSUE THREAD

**Issue by xblitz** [sensu/sensu#1758]
Since the introduction of the proxy_requests so that checks can be created from matching clients in the registry, I think there should be a way to add those Proxy Clients from the configurations files on the server.

## Expected Behavior
Specify Proxy Clients from json config file

## Current Behavior
We can only create Proxy clients from normal Proxy Checks, or from the API.

## Context
Since we use CHEF to deploy our infrastructure, it would be the perfect way to define all of our Proxy Clients that we want to monitor via proxy_requests feature.

**Comment by portertech** [comment]
@xblitz alternatively, a Chef resource could be added to create/manage the Proxy Clients via the Sensu API.

**Comment by xblitz** [comment]
true, it could be done with chef via the API, but this would mean that the service needs to be up, timing could be an issue, and the way chef manages resources, and to detect if the resources already exists would also be difficult,  while if it's done via the json like all the current settings i think it would personally make more sense.

**Comment by portertech** [comment]
Perhaps this functionality (proxy clients from config) should begin its life in a separate script/tool, outside of Sensu Core and its release cycle. This functionality introduces potential conflicts, between configuration (living on disk) and state (living in Redis), what is the definitive source of truth? How should it reconcile? I suspect the answer will be different depending on the user and their use case.

@mbbroberg this would be a great community project 👍

**Comment by portertech** [comment]
Closing this, as it's not something we plan to implement in Sensu 1.x Core.
