### ISSUE TITLE
When using multiple handlers if one exits unsuccessfully the other handlers are not run

### ISSUE THREAD

**Issue by sabbene** [sensu/sensu#1759]
This bug is similar to #1733, but slightly different/a bug in current functionality instead of a feature request.  The case in the linked issue/feature request is:

`do handler1; if false do handler2;`

In my case the behavior I am looking for is:

`do handler1; do handler2;`

What I think is happening is:

`do handler1 && do handler2`

If what I am seeing is correct if handler1 fails then handler2 is never run.  From talking to the people on the sensu community slack instance, this is an unexpected behavior.

He is an example of how my check is configured:
```
# cat test.json
{
  "checks": {
    "test": {
      "type": "standard",
      "command": "/path/to/test",
      "subscribers": [
        "subscriber1",
        "subscriber2"
      ],
      "interval": 900,
      "refresh": 1800,
      "timeout": 300,
      "handlers": ["handler1", "handler2"]
    }
  }
}
```

## Expected Behavior

I would expect all listed handlers to run even if one of them fails.

## Current Behavior

If you have multiple handlers configured, when one of the handlers fails the other handlers are not run.

## Steps to Reproduce (for bugs)

I have not had a chance to reproduce this, since it was impacting my production instance.  I will try and repro in my test env with the following steps:

1. Create an event handler that only runs /bin/false called a-hander, since I believe that sensu runs the handlers in alphabetical order.
2. Create an event handler that touches a file.
3. Create a check that only runs /bin/true.
4. Check if the file has been touched.

My steps to remediate this issue were:
1. Modify the checks to remove the broken handler from the defination.
2. Stop sensu server
3. Run `FLUSHALL` in the redis cli.
4. Start sensu-server

## Context

This issue resulted in our users running on systems that are in a degraded state.  We are using two event handlers in a check to keep each event handler as simple as possible.  In this particular case the event handlers did the following:

1. Stop the degraded host from accepting new user processes.
2. Report the issue to elk for trend analysis (This is the handler that was exiting non-zero).

## Your Environment

* Sensu version used:
```
# rpm -aq  sensu
sensu-1.0.2-1.el6.x86_64
```
* Operating System and version (e.g. Ubuntu 14.04):
```
# cat /etc/redhat-release
CentOS release 6.8 (Final)
# uname -rmo
2.6.32-642.6.2.el6.x86_64 x86_64 GNU/Linux
```
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):
```
# rpm -aq rabbitmq-server
rabbitmq-server-3.6.9-1.el6.noarch
```

**Comment by sabbene** [comment]
I am unable to reproduce this.  Please close it.

**Comment by majormoses** [comment]
closing per: https://github.com/sensu/sensu/issues/1759#issuecomment-333969447

**Comment by portertech** [comment]
👍
