### ISSUE TITLE
Upgrading windows client to 1.0.3 breaks sensu-client

### ISSUE THREAD

**Issue by jothoma1** [sensu/sensu#1760]
## Expected Behavior

After upgrading to 1.0.3 all my windows clients failed to start sensu client 
Error: 

> Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.4/rubyeventmachine (LoadError)
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-logger-1.2.1/lib/sensu/logger/stream.rb:2:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-logger-1.2.1/lib/sensu/logger.rb:1:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.3/lib/sensu/daemon.rb:22:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.3/lib/sensu/client/process.rb:1:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.3/exe/sensu-client:7:in `<top (required)>'
	from C:/opt/sensu/embedded/bin/sensu-client:22:in `load'
	from C:/opt/sensu/embedded/bin/sensu-client:22:in `<main>'

## Current Behavior

With 1.0.2 everything was fine, 1.0.3 breaks something on Windows OS (Linux works)

## Steps to Reproduce (for bugs)

1. Have a windows client (2008, 2012, 2012R2)
2. Install 1.0.2, it works
3. Upgrade to 1.0.3 it dont work
4.

## Context

Upgrading windows to 1.0.3 breaks all sensu-client, in the changelog i see that the EventMachine version 1.2.5 is used. There seems to be a problem with windows.
Reverting to 1.0.2 do not work too... :(

## Your Environment

* Sensu version used: 1.0.2 & 1.0.3
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): CentOS, Windows, etc
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by portertech** [comment]
@amdprophet I believe we need to update sensu-omnibus to compile/build the new EM version (with openssl support) on windows.

**Comment by benh57** [comment]
Kinda seems like 1.03 should be retracted since it totally breaks.

**Comment by benh57** [comment]
Ah, it was. Nevermind! :)  Reverting to 1.0.2 still failed though, perhaps i need to clean up its install.

**Comment by jothoma1** [comment]
@benh57 yes it should be retracted ... It has breaked all my windows OS (200)
And yes you have to clean all the install to be able to make 1.0.2 work again

**Comment by portertech** [comment]
We are actively working on a fix.

**Comment by amdprophet** [comment]
We've pulled 1.0.3-1 Windows builds from the repositories and 1.0.3-2 should be available tomorrow.

**Comment by amdprophet** [comment]
I'm going to close this issue as Sensu 1.1.0 has been released with a fix for this problem. Please make sure to uninstall Sensu 1.0.3 before installing 1.1.0.

**Comment by jothoma1** [comment]
@amdprophet Sorry but i have tried to uninstall 1.0.2 (1.0.3 didnt work on Windows) then install 1.1.0 and it didnt work either.
It seems that uninstalling 1.0.2 keep windows service (and maybe some dependencies) and 1.1.0 start but dit not work for some reason ... So we have a Windows sensu client problem...

**Comment by jothoma1** [comment]
@amdprophet  @palourde 
It warn me about a RabbitMQ connection problem but the config is the same as the 1.0.2 and it was working fine and it works great on all my linux clients (500)

> {"timestamp":"2017-10-06T10:03:40.753653+0200","level":"warn","message":"transport connection error","reason":"possible authentication failure. wrong credentials?","user":"sensu"}
