### ISSUE TITLE
Resolving flapping events doesn't resolve them.

### ISSUE THREAD

**Issue by multani** [sensu/sensu#1766]
[`resolve_event()` documentation](https://github.com/sensu/sensu/blob/992571bb67ee99c2f8785273162746b4e485e73b/lib/sensu/api/utilities/resolve_event.rb#L13) says it will resolve events even if they are marked as "flapping" thanks to the `:force_resolve` flag.

However, [`update_event_registry()`](https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L516-L532), where this flag is being used, explicitly re-update the Sensu registry with the event if it's flapping, completely ignoring the `:force_resolve` flag.

This prevents from resolving flapping events using `DELETE` on `/events/:client/:check` or `POST` on `/resolve`.

**Comment by portertech** [comment]
We need to update https://github.com/sensu/sensu/blob/5c24cafc0c82635f61ce5ef9ba0d98d649a2c6e4/lib/sensu/server/process.rb#L518 to `(event[:action] == :flapping && event[:check][:force_resolve] != true)`
