### ISSUE TITLE
Results sent to http socket without client.http_socket config raise an exception

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu#1767]
## Expected Behavior

By default I should be able to send valid check results to the client http socket input without an error.

## Current Behavior

Since Sensu 1.1.0, sending check results to the client http socket raises an exception 

## Possible Solution

As a workaround, adding `{ "client": { "http_socket": {} } }` to sensu-client configuration avoids the exception.

To fix this regression directly we should verify that `@settings[:http_socket]` is a hash before attempting to test keys inside such a hash. c.f. https://github.com/sensu/sensu/blob/v1.1.1/lib/sensu/client/http_socket.rb#L125

## Steps to Reproduce (for bugs)

1. Stand up a sensu-client instance with default configuration (no `client.http_socket` settings)
2. Post a check result to the client http socket
3. Observe 500 internal server error response
4. Observe the following in sensu-client.log:
```
"undefined method `[]' for nil:NilClass","backtrace":["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.0/lib/sensu/client/http_socket.rb:125:in `process_request_results'"
```

e.g.
```
$ curl -v -H 'Content-Type: application/json' -X POST -d '{"name": "http_socket_test", "status": 2, "output": "this will fail" }' 127.0.0.1:3031/results
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Failed to set TCP_KEEPALIVE on fd 3
* Connected to 127.0.0.1 (127.0.0.1) port 3031 (#0)
> POST /results HTTP/1.1
> Host: 127.0.0.1:3031
> User-Agent: curl/7.54.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 70
> 
* upload completely sent off: 70 out of 70 bytes
< HTTP/1.1 500 Internal Server Error
< Content-length: 77
< Content-type: application/json
< 
* Connection #0 to host 127.0.0.1 left intact
{"response":"Internal Server Error: Check your Sensu logs for error details"}
```

## Context

This unexpected exception causes check result submission via client http socket to fail unexpectedly.

## Your Environment

* Sensu version used: 1.1.0, 1.1.1
* Active Sensu extensions (e.g. WizardVan 0.1.0): N/A
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): N/A

**Comment by cwjohnston** [comment]
Thanks to @betorvs for reporting this issue via [Sensu Community Slack](https://github.com/sensu-plugins/community/blob/master/HOW_WE_SLACK.md) 👍

**Comment by portertech** [comment]
![catwalk](https://user-images.githubusercontent.com/149630/31560771-73188410-b00a-11e7-8813-5e766c2042b4.gif)

**Comment by portertech** [comment]
I'll whip up a fix 👍
