### ISSUE TITLE
can't use multiple filters with same attributes

### ISSUE THREAD

**Issue by ninjasloth22** [sensu/sensu#1771]
Using a handler with multiple exclusive filters comparing the same attributes, causes the handler to never fire. 
It appears if you are trying to use *filter1* OR *filter2* and both filters have the same attributes being evaluated they fail to process independently. 

## Expected Behavior
Using the following config: 
I would expect that the exclusive filters would be evaluated independently of each other.
In this case the handler has two filters - evaluate the clients frequency attribute and then notify based on the matched occurrences.
```
	"handlers": {
		"mail-hourly": {
			"command": "/etc/sensu/handlers/mailer/handler-mailer.rb -c \"text/html; charset=UTF-8\"",
			"type": "pipe",
			"filters": [
				"hourly",
                                "daily"
			],
			"severities": [
				"ok",
				"warning",
				"critical",
				"unknown"
			],
			"handle_flapping": false,
			"handle_silenced": false
		}
	}
```

```
	"filters": {
		"hourly" : {
			"attributes": {
				"check": {
					"interval": 60
				},
				"occurrences": "eval: !(':::check.frequency:::' == 'hourly' and value == 5 || value % 60 == 0 || ':::action:::' == 'resolve')"
			},
			"negate": true
		}
	}
```

```
	"filters": {
		"daily" : {
			"attributes": {
				"check": {
					"interval": 60
				},
				"occurrences": "eval: !(':::check.frequency:::' == 'daily' and value == 5 || value % 1440 == 0 || ':::action:::' == 'resolve')"
			},
			"negate": true
		}
	}
```

## Reproduce

I can change the handler to use a single filter event of the ones configured above, and the event is filtered as expected. 
Following this I configured both filters on the handler but changed the daily filter to use a random unique attribute only:
```
	"filters": {
		"daily" : {
			"attributes": {
				"check" : {
					"attrib1": false
				}
			},
			"negate": true
		}
	}
```
Once done and both filters are applied they work as expected, and events can match on either filter exclusively.
If I change the filter back to filter on occurrences (or non unique attribute between the listed filters), it again stops processing. 

I could not find this behaviour documented anywhere. Unsure if this is a bug/limitation. 

sensu version: 1.1.1

**Comment by portertech** [comment]
@ninjasloth22 Sensu filters are applied to an event serially, one after another. Sensu filters are AND'd, if a single filter negates an event, Sensu drops the event and stops executing further filters. This is the expected behaviour.

**Comment by ninjasloth22** [comment]
Thanks I miss-read the docs there. 

It would be good if we could have an option to use Inclusive filters on a handler in an OR fashion via an attribute.
