### ISSUE TITLE
Env vars changed without warning

### ISSUE THREAD

**Issue by cnees** [sensu/sensu#1772]
## Expected Behavior
Changelog shows potentially breaking changes

## Current Behavior
Changelog doesn't warn about switching `CONFIG_DIR` env var name to `CONFD_DIR`
https://sensuapp.org/docs/1.0/installation/upgrading.html#update-environment-variables

## Possible Solution
Add a note to 0.27.0 changelog

## Context
Preparing to upgrade Sensu

I couldn't find CONFD_DIR in the source of this repo, so perhaps this issue is in the wrong place, or perhaps its a change in a dependency that 0.27.0 upgrades.

**Comment by portertech** [comment]
Fixed! https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0270---2017-01-26

Thank you for reporting! 👍
