### ISSUE TITLE
Check hooks not firing

### ISSUE THREAD

**Issue by absolutejam** [sensu/sensu#1773]
After upgrading to 1.1.1-1 (server and API) for check hooks, I'm struggling to get them to work.

## Expected Behavior
Check hook should fire and display information in the `/checks` API and Uchiwa.

Example check:
```json
{
  "checks": {
    "disk-free": {
      "command": "C:\\\\opt\\\\sensu\\\\embedded\\\\bin\\\\ruby C:\\\\opt\\\\sensu\\\\check-scripts\\\\check-windows-disk.rb -w :::vars.disk.warn|80::: -c :::vars.disk.crit|90:::",
      "description": "Checks how full disks are",
      "handlers": [
        "default"
      ],
      "hooks": {
        "2": {
          "command": "echo test",
          "timeout": 30
        }
      },
      "interval": 60,
      "occurrences": 1,
      "refresh": 3600,
      "subscribers": [
        "winservers"
      ]
    }
  }
}
```
(I have tried this with `"non-zero"` but also tried `2` to see if this worked as an explicit value).

When the check fires (or I fire it via. API), there is no mention of the check hook result, only the check hook info from the check definitioon

## Current Behavior
No hook result is recorded. This is the same on Linux and Windows hosts.

## Your Environment
* Sensu version used: 1.1.1-1
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04, Windows Server 2012 R2, Windows Server 2016
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Redis currently (Redis server v=3.2.11 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=60be07af25e933f5)

**Comment by portertech** [comment]
Expected behaviour is:

Check hook should fire and display information in the `/results/:client/:check` and `/events/:client/:check` APIs and Uchiwa.

We discussed this a little on the Sensu Community Slack, expecting an update soon.

**Comment by epierotto** [comment]
Same issue here.
I'm running sensu 1.1.1 on CentOS
This is the hook definition inside the check:
```
"hooks": {
    "non-zero": {
    "command": "df -h"
  }
},
```
I check `/results/:client/:check` on API and the are no signs of hook execution.
Also changed `LOG_LEVEL=debug` on the client and I can see pretty much the same json that the API has.

**Comment by portertech** [comment]
@absolutejam @epierotto So with debug logging, neither of you are seeing this log line? https://github.com/sensu/sensu/blob/b32a0c1a88cf8f6f1b377ababcc8d5804a8698a6/lib/sensu/client/process.rb#L132

**Comment by epierotto** [comment]
I can see that line on client's log:
```
{
  "timestamp": "2017-11-03T13:44:31.687525+0000",
  "level": "debug",
  "message": "attempting to execute check hook",
  "check": {
    "command": "check-disk-usage.rb -t xfs,ext4 -w 90 -c 95 -W 80 -K 95",
    "handlers": [
      "slack"
    ],
    "hooks": {
      "non-zero": {
        "command": "df -h"
      }
    },
    "occurrences": 2,
    "refresh": "1800"
```

And this is the next line:
```
{
  "timestamp": "2017-11-03T13:44:31.687661+0000",
  "level": "info",
  "message": "publishing check result",
  "payload": {
    "client": "ip-10-0-7-167",
    "check": {
      "command": "check-disk-usage.rb -t xfs,ext4 -w 90 -c 95 -W 80 -K 95",
      "handlers": [
        "slack"
      ],
      "hooks": {
        "non-zero": {
          "command": "df -h"
        }
      },
      "occurrences": 2,
      "refresh": "1800",
```

**Comment by portertech** [comment]
@epierotto cool, thanks! I'll continue to investigate.

**Comment by portertech** [comment]
@epierotto is the check status currently non-zero? not included in your snippets above.

**Comment by epierotto** [comment]
I've updated the snippets above

**Comment by absolutejam** [comment]
Sorry, hadn't had chance to reply yet.

```
{
  "timestamp": "2017-11-07T10:41:19.365418+0000",
  "level": "info",
  "message": "received check request",
  "check": {
    "command": ":::ruby:::/check-disk-usage.rb -w :::vars.disk.warn|80::: -c :::vars.disk.crit|90:::",
    "description": "Checks how full disks are",
    "handlers": [
      "default"
    ],
    "hooks": {
      "non-zero": {
        "command": "df -h / | sort -h",
        "timeout": 30
      }
    },
    "occurrences": 1,
    "refresh": 3600,
    "name": "disk-free-linux",
    "api_requested": {
      "reason": null,
      "creator": null
    },
    "issued": 1510051279
  }
}
{
  "timestamp": "2017-11-07T10:41:19.443203+0000",
  "level": "info",
  "message": "publishing check result",
  "payload": {
    "client": "docker01",
    "check": {
      "command": ":::ruby:::/check-disk-usage.rb -w :::vars.disk.warn|80::: -c :::vars.disk.crit|90:::",
      "description": "Checks how full disks are",
      "handlers": [
        "default"
      ],
      "hooks": {
        "non-zero": {
          "command": "df -h / | sort -h",
          "timeout": 30
        }
      },
      "occurrences": 1,
      "refresh": 3600,
      "name": "disk-free-linux",
      "api_requested": {
        "reason": null,
        "creator": null
      },
      "issued": 1510051279,
      "executed": 1510051279,
      "duration": 0.078,
      "output": "CheckDisk OK: All disk usage under 80% and inode usage under 85%\n",
      "status": 0
    }
  }
}
```

**Comment by cwjohnston** [comment]
@absolutejam your most recent event data reflects status 0, meaning the 'non-zero' check hook would not be expected to fire. Can you provide an example event with a non-zero status?

**Comment by RiRa12621** [comment]
so after i tried that out, the following behaviour seems to occur but i need to validate that on more hosts:

i see the ```{"timestamp":"2006-10-02T18:00:40.015679+0200","level":"debug","message":"attempting to execute check hook”```
but the hook does not fire
then i moved the check config file to that specific host and the check fires

so situations is as follows: 
if check config file is not present on the host, where the sensu client is and the check is executed, the hook does not fired
if the check config file present, the hooks gets fired and behaves exactly the way it should.

Sensu version : 1.1.1 (client and server)
OS:
Distributor ID --> Ubuntu
Description -->    Ubuntu 16.04.2 LTS
Release -->        16.04
Codename -->       xenial

**Comment by portertech** [comment]
@RiRa12621 thank you! I will reproduce this and get back to you!

**Comment by RiRa12621** [comment]
@portertech feel free, to hit me up on slack

**Comment by portertech** [comment]
@absolutejam @epierotto @RiRa12621 I just cut 1.1.3-1, it will likely find it's way into unstable this evening and stable on Monday/Tuesday 🎉  Thank you all for your help!
