### ISSUE TITLE
API not listing checks

### ISSUE THREAD

**Issue by Yuav** [sensu/sensu#1775]
All of my checks are defined at the server, but when asking the sensu api sensu:4567/checks I get '[]'.

Hitting other API endpoints like /clients works properly.

Uchiwa shows everything also except for the Checks tab is entirely empty, but if I click on a client and click on a check under the client I see all of the correct data.

I have verified that checks are loaded from config using;

```
/opt/sensu/bin/sensu-api --print_config
/opt/sensu/bin/sensu-server --print_config
```

Partial output:
```
  "checks":{
    "port-ssh-tcp-22":{
      "command":"/opt/sensu/embedded/bin/check-ports.rb --ports 22",
      "interval":60,
      "standalone":true
    },
    "redis-process":{
      "command":"/opt/sensu/embedded/bin/check-process.rb --pattern redis-server --warn-under 1",
      "interval":60,
      "standalone":true
    },
    "sshd-process":{
      "command":"/opt/sensu/embedded/bin/check-process.rb --pattern ssh --warn-under 1",
      "interval":60,
      "standalone":true
    },
    "memory":{
      "command":"/opt/sensu/embedded/bin/check-memory.rb",
      "interval":60,
      "standalone":true
    },
 (...)
```

Sensu 1.1.1
Uchiwa 0.26.3

**Comment by mcbsdEU** [comment]
Hi,
do you run sensu-api instances on same machine as sensu-server?

**Comment by Yuav** [comment]
Yes

**Comment by mcbsdEU** [comment]
Ok, because I had same problem but I wanted to run sensu-api on separate machine, which is supported but then when you query the API you get only those checks which are "visible" by sensu-api.

**Comment by cwjohnston** [comment]
@yuav Because your checks are configured as standalone this is expected behavior, see https://github.com/sensu/sensu/blob/v1.1.2/lib/sensu/api/routes/checks.rb#L17. 

Sorry for the confusion here, seems that this isn't explained in our documentation. I've opened https://github.com/sensu/sensu-docs/issues/654 to track the need for this in our docs.

**Comment by nosretep** [comment]
Is this a side effect of solving a bug related to duplicate name conflicts? Feels broken.
