### ISSUE TITLE
check attribute ttl_status is undocumented

### ISSUE THREAD

**Issue by wfindley** [sensu/sensu#1779]
There are no docs explaining that you can set a `ttl_status` on a check .

## Expected Behavior
It should be documented in https://sensuapp.org/docs/1.1/reference/clients.html#creating-a-dead-mans-switch and https://sensuapp.org/docs/1.1/reference/checks.html#check-result-check-attributes so that users know about its existence.

**Comment by cwjohnston** [comment]
@wfindley thanks for reporting this. We currently track documentation issues on https://github.com/sensu/sensu-docs, so I've opened https://github.com/sensu/sensu-docs/issues/653 to track this need. 👍
