### ISSUE TITLE
Should have option in events API to return all clients failing a specific check.

### ISSUE THREAD

**Issue by stupiddr** [sensu/sensu#1780]
The events API only allows you to filter by host then check. I should be able to see all hosts that have a event for a specific check.

Current behavior:
I can view the failed checks for a host:
http://localhost:4567/events/client-01
I can view the specific failed check for the host:
http://localhost:4567/events/client-01/check_name

There should be an option where I can view all hosts which have failed a check:
http://localhost:4567/events/*/check_name
or 
http://localhost:4567/events//check_name
Would show all clients that have failed to successfully run the check check_name.

**Comment by mcbsdEU** [comment]
Have you considered using:
https://sensuapp.org/docs/1.0/api/overview.html#response-content-filtering

**Comment by cwjohnston** [comment]
@stupiddr as @mcbsdEU points out, the response content filtering should cover this use case. For example, 

```
curl http://127.0.0.1:4567/events\?filter.check.name=keepalive
```

Will return all events where the check name is `keepalive` :+1:
