### ISSUE TITLE
CentOS 7 /var/run/sensu doesn't survive a restart on CentOS 7

### ISSUE THREAD

**Issue by robertlabrie** [sensu/sensu#1782]
On CentOS 7 (at least the AWS image) `/var/run` is a `tmpfs`. Apparently, this is not a bug. http://www.linuxbase.org/betaspecs/fhs/fhs.html#runRuntimeVariableData

Also, `/run` is `root:root 0o755` apparently because security. So, installing Sensu creates `/var/run/sensu` (`/var/run` is --> `/run`) but if the system is restarted (because EC2 says my hardware is being decommissioned or whatever) when it comes back `/run/sensu` doesn't exist and sensu won't start. Try it!

Ok so anyway apparently the fix is to do:
`execStartPre=mkdir /var/run/sensu && chown sensu:sensu /var/run/sensu` and to specify
`PermissionsStartOnly=true` in the service file. This way the execStartPre will run as root.

**Comment by amdprophet** [comment]
Hi @robertlabrie 

This issue has been reported in the past and we were able to fix it by adding a tmpfilesd config file. Are you running an older version of Sensu by chance?

See: https://github.com/sensu/sensu-omnibus/issues/110 and https://github.com/sensu/sensu-omnibus/blob/master/config/templates/sensu-gem/tmpfilesd/sensu.conf.erb

**Comment by robertlabrie** [comment]
@amdprophet Thanks, I'll check into this over the weekend and let you know. My sensu version is:
`sensu.x86_64                           1:0.29.0-11.el7                  @sensu`

I don't have an `/etc/tempfiles.d`

`CentOS Linux release 7.2.1511 (Core)`

**Comment by robertlabrie** [comment]
@amdprophet that did it, thanks. I package my own RPM using FPM, starting with sensu 0.29.0 as a base. I didn't know tmpfiles.d was a thing so that file was missed. 100% my fault and very thankful for the assist.
