### ISSUE TITLE
0.28.x msi packages for Windows 2008/2008r2

### ISSUE THREAD

**Issue by tcador** [sensu/sensu#1783]
I'm looking for the latest .28.0.x packages for Windows 2008/2008r2 platforms. Is that available for download? I checked here: https://repositories.sensuapp.org/msi/2008r2/

I should mention, I just need sensu-client compatiblity from the older 2008/2008r2 windows platform to connect to 0.28.0.x version of the sensu_api and sensu_server, so if a newer version of the client can connect to the 0.28 version of the api/server that would work for this use case.

**Comment by cwjohnston** [comment]
> I'm looking for the latest .28.0.x packages for Windows 2008/2008r2 platforms. Is that available for download? I checked here: https://repositories.sensuapp.org/msi/2008r2/

@tcador ignoring 32bit vs 64bit CPU architecture, .NET Framework requirements are the only significant difference between the MSIs we've published for various versions of Windows. The MSIs labeled for newer versions of Windows (e.g. 2012 or 2012r2) are expected to work on Windows 2008 provided you have .NET 4.0 installed. See https://github.com/sensu/sensu-omnibus/issues/234 for some additional context.

> I should mention, I just need sensu-client compatiblity from the older 2008/2008r2 windows platform to connect to 0.28.0.x version of the sensu_api and sensu_server, so if a newer version of the client can connect to the 0.28 version of the api/server that would work for this use case.

Newer versions of Sensu should be compatible with running 0.28.x on the server. FWIW, Sensu services do not connect to one another directly, instead they use RabbitMQ as a message bus.

**Comment by tcador** [comment]
Thank you for the information, tested with the newer version on Windows and as you suggested there were no issues.
