### ISSUE TITLE
Failed to start LSB: Sensu monitoring framework server

### ISSUE THREAD

**Issue by fretagi** [sensu/sensu#1785]
my sensu installation came to halt, because I am not able to restart sensu, after creating config files.
It comes with the above error:
my operating system is ubuntu 17.10
the sensu log contains the following:

systemctl status sensu-server.service
â sensu-server.service - LSB: Sensu monitoring framework server
   Loaded: loaded (/etc/init.d/sensu-server; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-11-30 15:30:17 CAT; 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16131 ExecStart=/etc/init.d/sensu-server start (code=exited, status=1/FAILURE)

Nov 30 15:30:16 cmoveldb02 systemd[1]: Starting LSB: Sensu monitoring framework server...
Nov 30 15:30:16 cmoveldb02 sensu-server[16131]:  * Starting sensu-server
Nov 30 15:30:17 cmoveldb02 sensu-server[16131]:    ...fail!
Nov 30 15:30:17 cmoveldb02 systemd[1]: sensu-server.service: Control process exited, code=exited status=1
Nov 30 15:30:17 cmoveldb02 systemd[1]: Failed to start LSB: Sensu monitoring framework server.
Nov 30 15:30:17 cmoveldb02 systemd[1]: sensu-server.service: Unit entered failed state.
Nov 30 15:30:17 cmoveldb02 systemd[1]: sensu-server.service: Failed with result 'exit-code'.

The log file in /var/log/sensu contains the following:

tail /var/log/sensu/sensu-server.log
{"timestamp":"2017-11-30T15:30:16.525823+0200","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2017-11-30T15:30:16.525861+0200","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/check_cpu_linux.json"}
{"timestamp":"2017-11-30T15:30:16.525918+0200","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/check_cpu_linux.json","changes":{"checks":{"check-cpu-linux":[null,{"handlers":["mailer"],"command":"/opt/sensu/embedded/bin/check-cpu.rb -w 80 -c 90 ","interval":60,"occurrences":5,"subscribers":["linux"]}]}}}
{"timestamp":"2017-11-30T15:30:16.525961+0200","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2017-11-30T15:30:16.526025+0200","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/client.json","changes":{"client":{"name":["localhost","sensu-server"],"environment":[null,"sensu"],"keepalive":[null,{"handler":"mailer","thresholds":{"warning":250,"critical":300}}],"socket":[null,{"bind":"127.0.0.1","port":3030}]}}}
{"timestamp":"2017-11-30T15:30:16.526080+0200","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/transport.json"}
{"timestamp":"2017-11-30T15:30:16.526117+0200","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/transport.json","changes":{}}
{"timestamp":"2017-11-30T15:30:16.526148+0200","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/check_disk_usage_linux.json"}
{"timestamp":"2017-11-30T15:30:16.526182+0200","level":"fatal","message":"config file must be valid json","file":"/etc/sensu/conf.d/check_disk_usage_linux.json","error":"unexpected character at line 2, column 11 [parse.c:652]"}
{"timestamp":"2017-11-30T15:30:16.526213+0200","level":"fatal","message":"SENSU NOT RUNNING!"}
root@cmoveldb02:/etc/default#

Can I have some help?

**Comment by barryorourke** [comment]
Looks like there is an error in check_disk_usage_linux.json, on line 2. Happy to discuss this with you on community slack if you are a member. Will be available in about 30 mins.

**Comment by fretagi** [comment]
what could possible be wrong in line 2:
 1 ": {
  2         "check-disk-usage-linux": {
  3 "handlers": ["mailer"],
  4       "command": "/opt/sensu/embedded/bin/check-disk-usage.rb -w 80 -c 90",
  5       "interval": 60,
  6       "occurrences": 5,
  7       "subscribers": [ "linux" ]
  8         }
  9       }
 10     }

**Comment by barryorourke** [comment]
Here's what I have in my disk usage check, the error in your server log says the issue is line 2, position 11 which is the second `-`, I'm not entirely sure why that you cause issues? Do you have other checks with more than one dash in their name?

```
{
  "checks": {
    "disk_usage": {
      "command": "check-disk-usage.rb -x nfs,nfs4 -i /scratch -p '^/var/named|^/cvmfs|^/run|^/proc|^/opt/BIOVIA|^/tmp/.x2go*'",
      "subscribers": ["all-linuxes", "firewall"],
      "interval": 60,
      "occurrences": 10,
      "refresh": 1800,
    }
  }
}
```

**Comment by fretagi** [comment]
yes there is 3 other files! Shoul I change their names?

**Comment by cwjohnston** [comment]
@fretagi hope that the assistance offered here has helped point you in the right direction! 

If you need assistance diagnosing configurations issues like this one, I recommend joining  our community slack. You can sign up via https://sensuapp.org/community
