### ISSUE TITLE
Is it possible to acquire history data of a client whose check results come back "OK"?

### ISSUE THREAD

**Issue by andrewxiii** [sensu/sensu#1787]
Hello!

I am wondering if there's a way to acquire "History" data from a client when check results are returning "OK" on standard checks that do not have action "resolve". Right now it appears that I cannot access this data through the events API as event data is never being created for these situations. I noticed that "/clients/:client/history" has been deprecated, but I am not seeing the same functionality listed in the results API documentation.

I would like to access this data in order to perform actionable analysis on my clients, such as closing incident tickets when previous events are truly resolved after waiting a number of check intervals. If not built in already, would it be possible to add this history information to the check result object stored in the results API?

Thanks!

**Comment by mcbsdEU** [comment]
Hi,
results are available per each check via API described here:
https://sensuapp.org/docs/latest/api/results-api.html
Is this what you are looking for?

**Comment by andrewxiii** [comment]
So the Client I'm looking at is called test-client-01.

Querying Results, I get back :

  {
    "client": "test-client-01",
    "check": {
      "command": "/opt/sensu/embedded/bin/check-file-exists.rb",
      "subscribers": [
        "test"
      ],
      "interval": 10,
      "handlers": [
        "snow"
      ],
      "name": "fileExists",
      "issued": 1512138726,
      "executed": 1512138726,
      "duration": 0.045,
      "output": "CheckFileExists OK: No matching files found\n",
      "status": 0,
      "type": "standard"
    }


Where as if I query /clients/test-client-01/history I get back : 

 {
    "check": "fileExists",
    "history": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "last_execution": 1512138806,
    "last_status": 0,
    "last_result": {
      "command": "/opt/sensu/embedded/bin/check-file-exists.rb",
      "subscribers": [
        "test"
      ],
      "interval": 10,
      "handlers": [
        "snow"
      ],
      "name": "fileExists",
      "issued": 1512138806,
      "executed": 1512138806,
      "duration": 0.044,
      "output": "CheckFileExists OK: No matching files found\n",
      "status": 0,
      "type": "standard"
    }



That History array is what I'm looking for, but I would like to utilize a more "future proof" method of acquiring the data if possible.

**Comment by mcbsdEU** [comment]
Right, I see. Indeed, this history array is only available for active events.
I am interested in answer from Sensu guys as well.

**Comment by portertech** [comment]
@andrewxiii given the existing check history endpoint is deprecated, I think it's reasonable to add the history array to the result objects. This would require an additional Redis query per result to fetch the Redis set and then it can be encoded in the result JSON.

I'm going to label this as a feature and add to the 1.2 milestone.

**Comment by portertech** [comment]
Closed by #1794, result data will include check history in Core 1.2.0 (released later today).
