### ISSUE TITLE
RFE: add inverse condition to silencing

### ISSUE THREAD

**Issue by jpackagejasonc** [sensu/sensu#1788]
I'm having a hard time wording this well, so apologies in advance. we have a script that silences a client before performing maintenance. this works for the most part except in our dev environment we have client deregistration enabled, and the silencing of a client stops the deregistration handling. I'd like to specify an inverse condition along the lines of:
    curl -s \
      -H 'Content-Type: application/json' \
      -d "{ \"dc\":\"datacenter\", \"expire\":86400, \"reason\":\"username: ticket_number\", \"subscription\":\"client:i-99999-dev\", \"check\":\"!deregistration\" }" \
      http://my.sensu.host/silenced
but my reading of the docs and a quick perusal of the code didn't seem to indicate anything like the above is doable currently.

**Comment by cwjohnston** [comment]
@jpackagejasonc have you tried adding `"handle_silenced": "true"` to the handler definition for your deregistration handler? This [handler attribute](https://sensuapp.org/docs/latest/reference/handlers.html#handler-attributes) should cause the deregistration events to be handled despite being silenced.

**Comment by jpackagejasonc** [comment]
@cwjohnston that does indeed appear to work for my specific use case, thanks! I still think the RFE would be nice for other uses, but that definitely does what I need

**Comment by cwjohnston** [comment]
Our current implementation of silencing is optimized for performance in a way that precludes us from implementing this requested enhancement. Since the need here has been met with our existing `handle_silenced` feature, we're opting not to implement this right now.
