### ISSUE TITLE
POST /clients should not require subscription 

### ISSUE THREAD

**Issue by Evesy** [sensu/sensu#1795]
I'd like the ability to register clients against the API without having to specify a subscription.

## Expected Behavior
Proxy clients created via the `source` attribute in checks are configured with a single client subscription, i.e. `client:i-424242`.

I believe this behaviour should be consistent when registering a client manually via the `/clients` api, giving a user the option to not specify any additional subscriptions and just having the client default automatically added as per https://github.com/sensu/sensu/blob/master/lib/sensu/api/routes/clients.rb#L22

## Current Behavior
Currently registering a client via the `/clients` API will create a client subscription however an additional subscription must be passed as well as part of the payload:

201 Created:
```
{
  "name": "example",
  "address": "0.0.0.0",
  "subscriptions": ["sub"]
}
```

400 Bad Request:
```
{
  "name": "example",
  "address": "0.0.0.0"
}
```

## Possible Solution
Client validation fails due to https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/validators/client.rb#L9-L16

## Context
Registering clients for use with proxy requests requires you to pass a subscription, even if not required.

It's only a minor thing, since you can just pass the client subscription in the payload, and it will be merged with the default, ultimately just leaving the one subscription. This did however catch me out since I assumed you could opt to leave out the subscription and just have Sensu create the client default.

**Easily worked around.**

**Comment by cwjohnston** [comment]
Seems reasonable. Assigning to 1.3 milestone.
