### ISSUE TITLE
How to change request routes from the difference of connection sources

### ISSUE THREAD

**Issue by Mikawamoto** [sensu/sensu#1796]
Hi,
I want to set request routes to RabbitMQ as follows;

from SensuClient to RabbitMQ: via ELB
from SensuServer to RabbitMQ: to localhost directly
(I never want the route from SensuServer to Rabbit MQ via ELB)

my config.json is as follows, but
I think both connections are now directly to localhost with this setting.

  "rabbitmq": {
    "ssl": {
      "cert_chain_file": "/etc/sensu/ssl/cert.pem",
      "private_key_file": "/etc/sensu/ssl/key.pem"
    },
    "host": "localhost",
    "port": 5671,
    "user": "sensu",
    "password": "***********",
    "vhost": "/sensu"
  }

How to change request routes from the difference of connection sources ?

I use Amazon Linux 4.9.51-10.52.amzn1.x86_64 and version of aws-sdk :
aws-sdk (2.10.69)
aws-sdk-core (2.10.69)
aws-sdk-resources (2.10.69)
aws-sdk-v1 (1.66.0)

**Comment by majormoses** [comment]
Well on servers you would give it a list of ips and then on the clients using the elb hostname.

An example of multiple rabbitmq nodes here: https://sensuapp.org/docs/0.28/reference/rabbitmq.html#sensu-rabbitmq-configuration-examples-high-availability

**Comment by Mikawamoto** [comment]
It worked with setting you said. Thanks for everything !
