### ISSUE TITLE
rogue sensu-server on our network

### ISSUE THREAD

**Issue by sonegoh** [sensu/sensu#1797]
Hey, 
We experienced a keepalive storm on our sensu environment , after investigation we found that one of our developers accidentally started the sensu-server service on his dev machine, this machine is part of our infra and need to be monitored, as part of the installation process we are installing sensu on dev machines, and unfortunately sensu install comes with a bundle of sensu-client \ server \ API.
After he lunched the server the RabbitMQ started to get confused who to send the keep alive (Or at least this is what we think. if you think that the problem is different i would like to hear about it )
Is the a smart way to prevent rogue sensu server on the network, or to install only sensu-client on machines?
Thanks in advanced.

**Comment by portertech** [comment]
@sonegoh the only way to completely lock it down is through RabbitMQ user credentials. Secrets management could stop rogue servers from being able to connect to the transport. The Sensu Dashboard and Uchiwa provide a listing of the connected Sensu servers, on the datacenter view, which comes in handy when troubleshooting rogue servers. This data comes from the Sensu API /info.

**Comment by majormoses** [comment]
Aside from using different credentials I think you have a few options:
- Don't use the default rabbitmq port, by using a non standard port you have significantly decreased the chance of someone connecting. 
- Network ACLs (temp turn on/off, require SSH tunneling or VPN to reach rabbitmq)

I am still not sure how without service discovery the sensu server connecting to your rabbitmq node without being explicitly configured to do so. Without knowing more all I can do is make wild guesses.

**Comment by cwjohnston** [comment]
I think the responses on this issue so far have sufficiently covered possible solutions. Closing. ❤
