### ISSUE TITLE
FR: Allow the Client TCP/UDP JSON Socket to be disabled

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu#1799]
I would like to be able to completely disable the TCP/UDP client socket and only expose the HTTP socket.

## Possible Solution
I think the easiest way to do this is to add an `enabled` option to this section: https://github.com/sensu/sensu/blob/master/lib/sensu/client/process.rb#L464-L480 similar to how the `setup_http_socket` function uses that option. 

## Context
In my environment, we are looking to disable the TCP/UDP socket as it can not require authentication whereas the HTTP socket can. 

## Your Environment
* Sensu version used: 1.2.0
* Active Sensu extensions: None
* Operating System and version: CentOS 6 and CentOS7
* Transport and runtime versions: RabbitMQ 3.6.5 and Erlang 19.1.5

**Comment by cwjohnston** [comment]
Closed by #1800 👍
