### ISSUE TITLE
Network connection interruption causes sensu-server to hang and process keepalive storm

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1802]
We had some network connection issues in our environment. This causes the 3x sensu-servers to reconnect to redis & rabbitmq. Redis also reelected a new master at that time as well. 2x of 3x sensu-servers reconnected properly, the other one kept hanging and didn't executed any tasks. This caused a keepalive storm (couple thousand mails) triggered by random clients. Restarting this server process hanged as well and we used sigkill. After starting it back everything went back to normal. 

Please see the LOG below of the misbehaving server:
> {"timestamp":"2018-01-04T15:36:01.514381+0700","level":"info","message":"determining stale clients"}
> {"timestamp":"2018-01-04T15:36:07.132487+0700","level":"info","message":"updated server registry","server":{"id":"a0087e65-82ec-4313-8fcd-b713e0f97463","hostname":"server1","address":"10.118.204.74","tasks":["client_monitor"],"metrics":{"cpu":{"user":51802.09,"system":6243.27}},"sensu":{"version":"1.0.2","settings":{"hexdigest":"9e857b0091e3997e2f1423d9d6e296089114f1bf9f1031c9c6aeab756bda1330"}},"timestamp":1515054941}}
> {"timestamp":"2018-01-04T15:36:07.134287+0700","level":"info","message":"updated server registry","server":{"id":"a0087e65-82ec-4313-8fcd-b713e0f97463","hostname":"server1","address":"10.118.204.74","tasks":["client_monitor"],"metrics":{"cpu":{"user":51802.09,"system":6243.27}},"sensu":{"version":"1.0.2","settings":{"hexdigest":"9e857b0091e3997e2f1423d9d6e296089114f1bf9f1031c9c6aeab756bda1330"}},"timestamp":1515054951}}
> {"timestamp":"2018-01-04T15:36:07.134487+0700","level":"info","message":"updated server registry","server":{"id":"a0087e65-82ec-4313-8fcd-b713e0f97463","hostname":"server1","address":"10.118.204.74","tasks":["client_monitor"],"metrics":{"cpu":{"user":51802.1,"system":6243.27}},"sensu":{"version":"1.0.2","settings":{"hexdigest":"9e857b0091e3997e2f1423d9d6e296089114f1bf9f1031c9c6aeab756bda1330"}},"timestamp":1515054961}}
> {"timestamp":"2018-01-04T15:36:07.313510+0700","level":"warn","message":"reconnecting to redis"}
> {"timestamp":"2018-01-04T15:36:07.313643+0700","level":"warn","message":"unsubscribing from keepalive and result queues"}
> {"timestamp":"2018-01-04T15:36:07.313879+0700","level":"warn","message":"relinquishing server task","task":"client_monitor"}
> {"timestamp":"2018-01-04T15:36:07.321407+0700","level":"error","message":"transport connection error","error":"rabbitmq channel error"}
> {"timestamp":"2018-01-04T15:36:07.321467+0700","level":"warn","message":"reconnecting to transport"}
> {"timestamp":"2018-01-04T15:36:10.335029+0700","level":"info","message":"reconnected to transport"}
> {"timestamp":"2018-01-04T16:57:07.731659+0700","level":"warn","message":"received signal","signal":"TERM"}
> {"timestamp":"2018-01-04T16:57:07.731853+0700","level":"warn","message":"stopping"}
> {"timestamp":"2018-01-04T16:57:07.731898+0700","level":"warn","message":"unsubscribing from keepalive and result queues"}
> {"timestamp":"2018-01-04T16:57:07.732052+0700","level":"info","message":"completing work in progress","in_progress":{"check_results":470452,"events":0}}
> {"timestamp":"2018-01-04T16:58:05.735155+0700","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
> {"timestamp":"2018-01-04T16:58:05.735301+0700","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}

LOG of a server which worked after the reconnect:

> {"timestamp":"2018-01-04T15:36:07.233654+0700","level":"warn","message":"reconnecting to redis"}
> {"timestamp":"2018-01-04T15:36:07.233811+0700","level":"warn","message":"unsubscribing from keepalive and result queues"}
> {"timestamp":"2018-01-04T15:36:07.234761+0700","level":"warn","message":"relinquishing server task","task":"check_request_publisher"}
> {"timestamp":"2018-01-04T15:36:08.237319+0700","level":"info","message":"reconnected to redis"}
> {"timestamp":"2018-01-04T15:36:09.238992+0700","level":"info","message":"updated server registry","server":{"id":"05945c92-2f02-4527-8478-8078800e7635","hostname":"server3","address":"10.118.204.72","tasks":[],"metrics":{"cpu":{"user":47554.98,"system":7564.95}},"sensu":{"version":"1.0.2","settings":{"hexdigest":"9e857b0091e3997e2f1423d9d6e296089114f1bf9f1031c9c6aeab756bda1330"}},"timestamp":1515054969}}
> {"timestamp":"2018-01-04T15:36:09.240448+0700","level":"info","message":"i am now responsible for a server task","task":"client_monitor"}
> {"timestamp":"2018-01-04T15:36:19.239095+0700","level":"info","message":"updated server registry","server":{"id":"05945c92-2f02-4527-8478-8078800e7635","hostname":"server3","address":"10.118.204.72","tasks":["client_monitor"],"metrics":{"cpu":{"user":47554.98,"system":7564.95}},"sensu":{"version":"1.0.2","settings":{"hexdigest":"9e857b0091e3997e2f1423d9d6e296089114f1bf9f1031c9c6aeab756bda1330"}},"timestamp":1515054979}}

## Expected Behavior
Not sure what was happening in the server process but letting it die if something unexpected happened would be easier to catch.

## Your Environment
* Sensu version used: 1.0.2
* Active Sensu extensions: defaults + opsgenie handler
* Operating System and version: CentOS 7
* Transport and runtime versions: RabbitMQ 3.6.9, Erlang 19.2.3

**Comment by cwjohnston** [comment]
Hi @ChrisOnToure 

I think what you've described makes some sense, in that the following log line  indicates that your "stuck" sensu server was responsible for consuming keepalives:

```
04T15:36:07.313879+0700","level":"warn","message":"relinquishing server task","task":"client_monitor"}
```

If this particular server was connected to the non-master Redis instance at the time of this log entry relinquishing this task would have failed, meaning that the responsibility for processing keepalives queue would have been locked until this server instance reconnected or the lock expired. We expect that these server task locks expire after 30 seconds, but your description of the issue gives me the impression that this condition lasted significantly longer.

Are you using Redis Sentinel to handle failover in this scenario? Can you share your Sensu configuration?

**Comment by ChrisOnToure** [comment]
Hello @cwjohnston 

First thanks for looking into this. Yes we use redis sentinel. Down below i put you all the configs:

```
#Sensu config
{
  "api": {
    "host": "hk-sensu-2000",
    "port": 4567,
    "user": "xxx",
    "password": "xxx"
  },
  "handlers": {
    "default": {
      "handlers": [
        "logstash",
        "opsgenie"
      ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "type": "set"
    },
    "logstash": {
      "command": "/etc/sensu/handlers/logstash.rb",
      "filters": [ "check_dependencies", "occurrences" ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "type": "pipe",
      "timeout": 90
    },
    "opsgenie": {
      "command": "/etc/sensu/handlers/handler-opsgenie.rb",
      "filters": [ "check_dependencies", "occurrences" ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "type": "pipe",
      "timeout": 90
    },
    "remediator": {
      "command": "/etc/sensu/handlers/remediator.rb",
      "filters": [ "check_dependencies" ],
      "type": "pipe",
      "timeout": 90
    }
  },
  "logstash": {
    "server" : "xxx",
    "port" : 5004,
    "output": "tcp"
  },
  "opsgenie": {
      "source": "sensu",
      "customerKey": "xxx",
      "overwrite_quiet_hours": false,
      "tags": ["sensu", "hkg"],
      "proxy_addr": "xxx",
      "proxy_port": 3128
  },
  "redis": {
    "auto_reconnect": true,
    "reconnect_on_error": true,
    "password": "xxx",
    "master": "xxx",
    "sentinels": [
     
 {
        "host": "hk-sensu-2001",
        "port": 26379
      },
      {
        "host": "hk-sensu-2002",
        "port": 26379
      },
      {
        "host": "hk-sensu-2003",
        "port": 26379
      }
    ]
  }
}
```
```
[~]# grep "^[^#;]" /etc/redis.conf
bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile "/var/run/redis/redis.pid"
loglevel notice
logfile "/var/log/redis/redis.log"
databases 16
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename "dump.rdb"
dir "/var/lib/redis"
masterauth "xxx"
slave-serve-stale-data yes
slave-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no
slave-priority 100
requirepass "xxx"
appendonly no
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
lua-time-limit 5000
cluster-node-timeout 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
aof-rewrite-incremental-fsync yes
```

```
[ ~]# grep "^[^#;]" /etc/redis-sentinel.conf
daemonize no
pidfile "/var/run/redis/redis-sentinel.pid"
logfile "/var/log/redis/redis-sentinel.log"
port 26379
bind 0.0.0.0
sentinel myid xxx
sentinel monitor mymaster 10.118.204.74 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
sentinel auth-pass mymaster xxx
sentinel config-epoch mymaster 8
sentinel leader-epoch mymaster 8
dir "/"
sentinel known-slave mymaster 10.118.204.72 6379
sentinel known-slave mymaster 10.118.204.73 6379
sentinel known-sentinel mymaster 10.118.204.73 26379 d4721a0b32e0a5646e4ae36077bb7740a30063d7
sentinel known-sentinel mymaster 10.118.204.72 26379 0e01acd0d8c6a7683cbaf185e916603b2d11d724
sentinel current-epoch 8
```

**Comment by cwjohnston** [comment]
Hi @chrisontoure, thanks for providing these additional details.

From reviewing your redis-sentinel.conf it looks like you have configured at least some of your sentinels to run on the same hosts where you are running Redis. I cannot fully account for the architecture or topology of your Sensu implementation, but I think it's worth noting the following from the [Redis Sentinel Documentation](https://redis.io/topics/sentinel)

> **Fundamental things to know about Sentinel before deploying**
> 1. You need at least three Sentinel instances for a robust deployment.
> 2. The three Sentinel instances should be placed into computers or virtual machines that are believed to fail in an independent way. So for example different physical servers or Virtual Machines executed on different availability zones.

I am under the impression that you have three Sentinels (per your Sensu configuration) but they do not appear to adhere to fundamental #2 as described above. This may explain, at least in part, why one of your three systems wasn't able to return to service without manual intervention.

**Comment by cwjohnston** [comment]
Closing due to lack of updates on this issue. Please let us know if you have an ongoing problem after addressing the Sentinel deployment issues described in this thread.
