### ISSUE TITLE
Feature Request: Check summary via API

### ISSUE THREAD

**Issue by ephur** [sensu/sensu#1808]
## Expected Behavior
The API would implement an endpoint (or parameter to /results) which provides a summary of check results in each status.

Example:
get /results?summary=true

or 

get /summary/results  (types could be provided for other places where a summary is desirable).

## Current Behavior
In order to get an overview of the health inside of a datacenter one must look at the check results for every check (a huge payload) or iterate over every client and look at the results for that client (slow with 20k+ hosts in a datacenter). With several data centers we would like to look at an aggregated view of the dashboards (something like Grid) but it's currently impossibly slow.

## Possible Solution
It seems like the path of most resistance would be to adjust the results route to keep a small table of results found in each state.

https://github.com/sensu/sensu/blob/master/lib/sensu/api/routes/results.rb

I am not familiar with the data structure inside of redis, but it looks like this might still be less than ideal as it still has to iterate over every host. I don't know if results could be more optimally selected from redis based on a state.

## Context
We deploy a sensu cluster in every data center and cloud provider that is responsible for the resources in that area. We would like to aggregate a summary of each region into a single console. The console will then link to the proper uchiwa page for drilling down into results.

This console is an operators central view into the entire monitoring infrastructure so it must be responsive, and have up to date results. 

We would value your feedback and insight on reasonable ways that this could be implemented, and if a PR was submitted what the most likely path to acceptance would be. Running a forked sensu is not desirable.

## Your Environment
* Sensu version used: Sensu server/api 1.1.2
* Operating System and version: various, server runs on centos
* Transport and runtime versions: rabbitmq (unrelated)

**Comment by cwjohnston** [comment]
Hi @ephur, have you considered the [API response content filtering](https://sensuapp.org/docs/latest/api/overview.html#response-content-filtering) feature as a potential solution for your case?

**Comment by ephur** [comment]
Thanks, that's something I briefly looked at but wasn't sure if it would suit our needs. Is there a source I could use to find the patterns or more info on the dotted notation items I'd be able to use?
