### ISSUE TITLE
Sensu client validation for `source` fails with token substitution

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu#1812]
I would like to allow the source to be set by the client in the form of token substitution. From my conversation yesterday with @portertech this should work:
> @majormoses 1.x tokens work in every check attribute

When I tried leveraging this it did not work:
```json
{"timestamp":"2018-02-22T00:35:10.048056+0000","level":"fatal","message":"check source cannot contain spaces or special characters","object":{"command":"check-es-cluster-status.rb -h :::address::: -T 30","subscribers":["roundrobin:es5_app","roundrobin:es5_logs"],"handlers":["pagerduty"],"source":":::es5_cluster_name:::","interval":30,"pager_team":"urgent","notification":"ES cluster health is red.","occurrences":2,"dependencies":["es_service","es_node_status"],"runbook":"https://docs.google.com/document/d/<REDACTED>","name":"es5_cluster"}}
```

## Expected Behavior
A source can be set via token substitution.

## Current Behavior
The client fails validation

## Possible Solution
While I agree that sources should not contain certain characters such as spaces and such 

## Steps to Reproduce (for bugs)

Configure a check that leverages a token and then specify it in the client. I specially used the token `es5_cluster_name`.

## Context
Running multiple Elasticsearch clusters and would like to dynamically set the source of the es cluster

## Your Environment
* Sensu version used: 1.1.1
* Operating System and version: Ubuntu 16.04

**Comment by majormoses** [comment]
Here is the code in question: https://github.com/sensu/sensu-settings/blob/v10.12.0/lib/sensu/settings/validators/check.rb#L35-L46

**Comment by majormoses** [comment]
I have tried multiple iterations but this seems completely broken, I tried using:
```
"source":":::es5.cluster.name:::"
"source":":::es5clustername:::"
```

I am confused by the escaped `A` at the beginning of the regex and the same with `z` they are not in a range or capture group that means that a source would always have to start with a `A` and end with a `z` which makes no sense.

I think it should look something more like this:
```
/([A-Z-a-z-0-9\-]+)?(\:{3})([A-Z-a-z-0-9\-\|\_\.]+)?(\:{3})?/
```

**Comment by portertech** [comment]
@majormoses the validator changes were added in Sensu 1.2.x.

The validator specs suggest we can use tokens in source successfully: 

specifically https://github.com/sensu/sensu-settings/blob/v10.12.0/spec/validator_spec.rb#L374-L379

**Comment by majormoses** [comment]
Ah the `\A` is the start of a string and `\z` is the end of the string which is not standard regex at all. I saw it and was like that makes no sense. I did some quick testing and it seems to work.

**Comment by majormoses** [comment]
Will do some further testing and close if it's all good.

**Comment by portertech** [comment]
@majormoses rad 👍

I thought `\A` is a standard anchor 🤔 Seems to work tho! 😆

**Comment by majormoses** [comment]
After finding it in some ruby docs I went through the perl (as much as I dislike perl their regex is the gold standard in my opinion) regex [docs](https://perldoc.perl.org/perlre.html#Regular-Expressions) and it is indeed a valid anchor there as well. I am sure I used it years ago but I have not seen it in years. To be honest I am usually more looking to anchor the beginning or end of a line rather than a string. I personally like to comment "uncommon" or "complex" regex so that people at 1 AM I don't have to think so hard. I will probably create a PR to add some extra explanation on the regex. Also the verbiage is wrong in my opinion, you can have a special character inside a token substitution just not outside of it. Also pretty sure most people call `-` a special character which `\w` does include.

**Comment by majormoses** [comment]
From the perl docs:
> \w        [3]  Match a "word" character (alphanumeric plus "_", plus other connector punctuation chars plus Unicode marks)
