### ISSUE TITLE
Round robin really a round robin?

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1813]
## Expected Behavior
Documentation indicates that "...will have its check requests sent to clients in a round-robin fashion, meaning only one member (client) in the subscription will execute a round-robin check each time it is published."

https://sensuapp.org/docs/1.0/reference/clients.html#round-robin-client-subscriptions

I would expect, that if there are etc. 3 clients subscribed for round-robin check, the execution of check is rotating over these 3 clients.

## Current Behavior
Check is executed always on single client, on the one where the check was executed as first. All other executions are landing on the same machine.
However, when I manually turn off client on machine where check is always executed over and over, the execution is shifted seamlessly to another machine.
At the end, it works good, check is executed only on one machine, but I would expect to have it with round-robin fashion as documented.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Define round robin check, assign roud-robin sub to at least 3 clients.
2. Watch which machine executed given check, it should rotate over given clients.
3. --check environment below, might have impact?--

## Context
There is no direct impact, but it makes me nervous somehow:)
Maybe it is working like that by design....then OK, but documentation says something different.

## Your Environment
We are using distributed installation. Sensu server is running on 3 machines. These 3 servers have also sensu-client installed and subjected round robin checks are assigned to these 3 machines.
Not sure if this might have impact on behaviour. I believe not.

* Sensu version used: 1.2
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): RedHat
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by stupiddr** [comment]
Can you provide your sensu-client client.json as well as your check.json?
I'm currently utilizing roundrobin for thousands of checks and its working as intended.

**Comment by cwjohnston** [comment]
@mcbsdEU strictly speaking, `roundrobin:` subscriptions do not guarantee a true round-robin distribution of check execution requests. Standard subscriptions use the “fan out” AMQP exchange type, meaning each queue bound to the exchange will receive a copy of each execution request. Roundrobin subscriptions, on the other hand, use the “direct” AMQP exchange type, meaning that each execution request is consumed by a single subscriber, without guarantees that the consumer will change each time the execution request is issued.

In practice this means that any number of clients with the same compute performance characteristics and latency to the AMQP broker will have a roughly equal chance at consuming the single check execution request. 

Perhaps there are some compute resource or network factors involved which are causing one client in your infrastructure to have a better chance at “winning the race” for these check requests? As mentioned, providing your client and check definitions may also shed some light on the behavior you are seeing.

**Comment by mcbsdEU** [comment]
Hi,

there are 3 clients with this configuration (of course, differs by ip/hostname):
```
{
  "client": {
    "name": "sensu_server1.some.domain",
    "address": "192.168.200.131",
    "shortname": "sensu_server1",
    "environment": "production",
    "model": "rhel",
    "custom_thresholds": {"none": "none"},
    "subscriptions": ["lx_std", "proxy_net", "adm_vcsns", "roundrobin:adm_vcsns"],
    "keepalive": {
      "handlers": ["handler1", "handler2"],
      "thresholds": {
        "warning": 60,
        "critical": 60
      }
    }
  }
}
```

Subjected subscription is "roundrobin:adm_vcsns".

The check definition is:
```
{
  "checks": {
    "lx_cus_state-graphiteage": {
      "type": "standard",
      "handlers": ["handler1", "handler2"],
      "command": "python /opt/sensu/custom/client/CheckGraphiteDataAge.py -a 90 -f '-3min ' -t ':::environment:::.:::model:::.:::shortname:::.load.load_avg.cpunum'",
      "interval": 60,
      "subscribers": ["roundrobin:adm_vcsns"],
      "auto_resolve": true,
      "source": "sensu-cluster"
    }
  }
}
```
**Note:** I have fixed source so if check fails, I get only one event regarding that. Without this fixed source, I would receive critical event from each of these 3 clients.

**Comment by mcbsdEU** [comment]
@cwjohnston @stupiddr 
I didn't know there is no guarantee that consumer will change...
I had intention to use round robin also for load balancing....etc. proxy requests....sensu-server is doing snmp polling for network devices....with round robin and 3 clients, I could spread the load of this polling. But with actual information you wrote, this seems to be not applicable....which makes me bit disappointed:) (it was good idea).

Speaking of network infrastructure, we don't experience any issues in other areas. Infrastructure is very little utilized and we have resources in advance....we also monitor for packet drops and so on, which could affect this behaviour, but all is good.

**Comment by mcbsdEU** [comment]
I am closing this as intended design was explained, I'll observe the situation further...
