### ISSUE TITLE
Tracking for silencing

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1814]
## Expected Behavior
We are forwarding events to ticketing system on state-change.
When new device is integrated into Sensu, it is silenced right after for 5 minutes - so all checks have time to be executed. Some of them are not really a checks, they are etc. metric collectors for further evaluation.
The point is, that after 5 mins, device should consolidate.

Sometimes, when device is silenced, some check does not consolidate and it ends up in non-OK state even after silencing - and such situation should be alarmed. This will actually not happen, because there was no state change.

## Current Behavior
By use case explained above, when check ends up in non-OK state when device is silenced and this non-OK state survives silencing expiration, it is not handled for alerting, because state-change did not happen -it is non-OK all the time and handler reacts only on state-change.
When check with non-OK state survives silencing, it is not expected situation and should be alarmed as usual. 

## Possible Solution
If silencing was tracked, it could be used in filtering criteria - etc. beside state change handling, it would activate handler when state is non-OK _AND_ silencing[-2] was 1(enabled) _AND silencing[-1] was 0 (disabled). So in case that previous result was silenced and now it is not silenced and there is non-OK state, it would trigger handler. Is it too crazy idea?

Alternative 1:
One could be OK when reoccurrence is used, but that would mean to wait for given interval, etc. 1 hour or so. We are not using reoccurrence.

Alternative 2:
After silencing, all checks could be resolved by API to reset the state and start from green field.
This is hard to manage, we are integrating new devices by ansible. It would require postponed treatment (to resolve checks after 5 mins...)

## Steps to Reproduce (for bugs)
N/A

## Context
As described, when check fails to recover during silencing period (5 min), it is standard faulty issue which should be reported. When using state-change only handling, such situation will stay unseen.

## Your Environment
* Sensu version used: 1.2
* Operating System and version (e.g. Ubuntu 14.04): RedHat
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by cwjohnston** [comment]
Hi @mcbsdEU, thanks for raising this issue. If I understand correctly, the current behavior you are describing hinges on using a configuration-defined (native) filter to enforce "state change only" alerting. 

I believe that the expected behavior you desire could be achieved using a filter which also accounts for the check's `refresh` attribute, using the same logic as the `occurrences` filter. As with the `occurrences` filter, this additional logic may require your filter to be implemented as an extension instead of as a configuration-defined filter.

Do you think this would address your need? Interested to hear your thoughts on this approach.

**Comment by mcbsdEU** [comment]
Hello @cwjohnston , thanks for your comment.
I have multiple thoughts on this.

I know there was confusion between occurrences and refresh, correct me if I am wrong, but as documented at [Filters](https://docs.sensu.io/sensu-core/1.1/reference/filters/#example-handling-events-during-office-hours-only), you don't strictly need to work with refresh attribute. All you need is to check for value and modulo, is that true?

Either way, what I am missing, is relationship to silencing, otherwise how to control when exactly is the moment for handling an event?
I could configure re-handling by mentioned link, but this would apply in general. Let's say I would re-handle every 5~10 minutes flat. That means unnecessary requests to handler, which at the end, turns into requests towards some back-end ticketing tool etc. This is quite overwhelming with lots of checks.

Just thinking how to effectively cover this key point - relationship to silencing. My first idea was to track history of silencing ...but I am not sure if this is reliable and usable.
Maybe, if we could attach some registry action when silencing is removed/expired - then action of that could be used at other side. Etc. to introduce boolean field "unsilenced" - which would be populated during silencing remove/expire with value 1. This value could be consumed by standard filtering, and with value 1 it would pass the filter to the handler. Handler could then reset this field back to 0.
Alternative could be to implement generic programmable action on removed/expired silencing and everything else is up to implementer - etc. to use stashes to store additional data about silencing.

**Comment by mcbsdEU** [comment]
This request could be cancelled as #1876 handed this over.
