### ISSUE TITLE
Exclude aggregates individual results from events API

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1815]
## Expected Behavior
Sorry, it is maybe weird idea, but I think it might find its use case.

Main purpose of aggregates is to treat multiple results as one. Idea has very good placement and there are many use cases for it. The problem I see is form of representation.

I am interested in result as whole, I am not interested in individual sub-results. That's why it feels bit irritating to see these sub results under /events endpoint.
When I open uchiwa and look at events tab, I am looking at actual state of environment. Partial result, evaluated as "critical", has no relevance, because overall aggregator is what matters.
Etc. when I have server cluster (active/standby) and some services are present only on active node, it makes no sense to have "critical" events that standby node does not have them. This is not critical, it is fully OK state and I evaluate aggregator to say if situation is critical or not.

## Current Behavior
Sub-results of aggregator are visible in /events API. This might not show real situation, because individual sub-results might be "critical" but their critical state is actually fully OK.

I understand that aggregates have default option "handle": false. So sub-results won't be handled (etc. forwarded to ticketing system). But visually, they are sill present at /events endpoint and they might be sitting there in red colour for weeks - which is unnecessary dirt in the dashboard because this "red" colour is actually green (etc. in use case described above).

## Possible Solution
1.
Dirt solution could be to make sub-results always green (requires modification of script itself to exit with 0 regardless of result).
Only what would matter is output.
The evaluation of aggregates would be based on output only - check individual sub-outputs for specific patterns.
In this way, sub-results would not appear in /events API, but this usable only for home-made plugins/scripts. Community plugins can't be modified like that...

2.
There is an alias for /events endpoint, called /incidents - which is actually not documented I think.
Maybe this /incidents endpoint could not be just an alias. It would display same content as /events endpoint except non-OK sub-results of aggregates - and that would actually fit also terminology of "incidents".
This would require modification of Uchiwa, to have additional tab "Incidents" next to "Events". 

## Steps to Reproduce (for bugs)
N/A

## Context
Even we are using handlers, and ticketing happens in external tool. We also use Uchiwa to see _actual_ state of environment. For some checks where aggregators are perfect feature to use, non-OK sub-results are making the dashboard dirty even overall situation is good (etc. mentioned active/standby cluster checks).

## Your Environment
* Sensu version used: 1.2
* Operating System and version (e.g. Ubuntu 14.04): RedHat
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

**Comment by cwjohnston** [comment]
Hi @mcbsdEU, have you had a look at the (API response content filtering)[https://sensuapp.org/docs/latest/api/overview.html#response-content-filtering] feature?

Although it would be harder to do so when using named aggregates, it may be possible to use this API feature to achieve your objective without code changes in Sensu itself.

**Comment by portertech** [comment]
Check results (and their associated events) can be apart of one or more named aggregates. They can also operate and inform independently of the aggregate(s), it's up to the user of how aggregates and the individual events are used. For this reason, we cannot make any assumptions in regards to "sub results".

**Comment by cwjohnston** [comment]
Hi @mcbsdEU, have you had a look at the [API response content filtering](https://sensuapp.org/docs/latest/api/overview.html#response-content-filtering) feature?

Although it would be harder to do so when using named aggregates, it may be possible to use this API feature to achieve your objective without code changes in Sensu itself.

**Comment by mcbsdEU** [comment]
Thanks for your comments!
@cwjohnston  Did you mean to apply filtering on /events endpoint?
