### ISSUE TITLE
Enable pagination on all sensu API list endpoints

### ISSUE THREAD

**Issue by davideauee** [sensu/sensu#1830]
as sensu clusters keep increasing in size, the sensu API is struggling in handling un-paginated queries. 

Unfortunately, not all endpoint support paginations. At the moment /silenced, /stashes and /clients support the "limit" and "offset" querystrings. However /results does not.

all the listing endpoints should support pagination

**Comment by portertech** [comment]
Thanks for the issue @davideauee 👍

**Comment by portertech** [comment]
Closed by #1853, Sensu Core 1.4.0 will have this 👍
