### ISSUE TITLE
Keepalive check results should honor token substitution

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu#1840]
## Expected Behavior

Token substitution syntax is honored in client `keepalive` attributes.

## Current Behavior

Token substitution syntax is not honored in client `keepalive` attributes. For example, using token substitution to populate the `contacts` array does not result in desired values from custom client attributes.

## Possible Solution

Apply `object_substitute_tokens` method to `client.keepalive` hash in [`create_keepalive_check`]( https://github.com/sensu/sensu/blob/v1.3.0/lib/sensu/server/process.rb#L1049-L1076)

## Steps to Reproduce (for bugs)

1. Configure a client with `client.keepalive` attributes using token substitution, e.g.:
    `{ "client": { "keepalive": { "contacts": [ ":::primary_contact|ops:::" ] }, "primary_contact": "dev" } }`
2. Shut off the client and wait for keepalive check result
3. Observe that tokens not substituted in keepalive event

## Context

In the case of `keepalive` check results, the client keepalive attributes, are merged into the top level of the check result, making it a reasonable place to use token substitution.

This customization works for standard client check results, so folks expect it to work for keepalives also. 

## Your Environment

* Sensu version used: 1.2.1

**Comment by cwjohnston** [comment]
Assigning to 1.4 milestone per @portertech

**Comment by portertech** [comment]
Closed by #1854
