### ISSUE TITLE
Deregistration handler should be builtin and even work for silenced clients

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1841]
Right now the deregistration handler is just some sens-plugin which is called as a normal handler. It would be better to have some builtin function which also runs if clients are silenced. Otherwise silenced clients stay there forever even if the sent some deregistration.

**Comment by majormoses** [comment]
I can certainly see value in this, if you are looking for a solution in the mean time that protects you even from silenced clients I would look at: https://github.com/eheydrick/aws-cleaner while it currently only supports aws environments the concept could be applied to any modern computing platform.

**Comment by cwjohnston** [comment]
@runningman84 although I can see an argument for including the deregistration handler as a built-in, I think you can already configure sensu to handle deregistration events for silenced clients using the existing handler by setting the value of the `handle_silenced` attribute to `true` in your handler definition. See https://docs.sensu.io/sensu-core/latest/reference/handlers/#handler-attributes

If you haven't already tried this, will you please do so and let us know if this solves your problem?

**Comment by jspaleta** [comment]
@cwjohnston 
Since  sensu-extensions-deregistration  is an extension and not a handler defined via config management, where exactly do you set the "handle_silenced" attribute?

The deregistration extension has
```
@options.merge!(@settings[:deregistration]) if @settings[:deregistration].is_a?(Hash)
```
Does this mean that a server-side config outside of the "handlers" scope is where to put the handle_siilenced attributes?

Maybe the deregistration extension needs some documentation concerning where to drop the mergable configs?

**Comment by cwjohnston** [comment]
@jspaleta I think the comment here was aimed at the use of [the Deregistration handler](https://github.com/sensu-plugins/sensu-plugins-sensu/blob/3.0.0/bin/handler-sensu-deregister.rb) provided in sensu-plugins-sensu. At the time of my comment above, I had forgotten that I started work on porting the handler to an extension for including in Sensu Core.

To be clear, the [deregistration extension](https://github.com/sensu-plugins/sensu-extensions-deregistration) isn’t fully tested nor is it publicly published on RubyGems, etc. I think figuring out how it can be made to handle silenced events sounds like an important part of testing the extension for a first release.

I have now updated the readme for the deregistration extension to indicate that it is considered experimental.

**Comment by majormoses** [comment]
if its gonna be included in the core I think we should transfer it to the sensu org, thoughts?

**Comment by majormoses** [comment]
I have reviewed, approved, and merged the functionality. We will need to version and publish it to rubygems. If you guys are gonna own it then you might not want to follow the processes that the main plugins org follows so I have not touched that until we figure out where it should live and who should maintain it.

**Comment by amdprophet** [comment]
I've release sensu-extensions-deregistration 1.0.0 and have opened a PR against the sensu-extensions repository: https://github.com/sensu/sensu-extensions/pull/21

Once the above PR has been merged, we can bump the version of sensu-extensions and include it in Sensu Core.
