### ISSUE TITLE
Redis TLS problem "redis and transport connections not initialized"

### ISSUE THREAD

**Issue by djgrubson** [sensu/sensu#1850]
# Problem withTLS for redis

## Expected Behavior
Encryption between server/ client endpoint and Redis used as a transport

According to this PR TLS supposed to be supported for redis transport

[https://github.com/sensu/sensu-redis/pull/20](https://github.com/sensu/sensu-redis/pull/20)

## Current Behavior
500 Error and message
``{"error":"redis and transport connections not initialized"``

Just trying to test SSL between sensu node server and redis on AWS

We have created the certs using  tools:

keys and cert generated with tool http://docs.sensu.io/sensu-core/0.29/files/sensu_ssl_tool.tar

Certificates seems to be working
``
openssl s_client -connect master.sensu.xxxxx.cache.amazonaws.com:6379 -cert cert.pem -key key.pem -CAfile cacert.pem 
CONNECTED(00000003)
depth=4 C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority
verify return:1
``

however sensu is unable to connect to the redis instance on AWS using tls:

ERROR:

sensu-enterprise-dashboard.log:
``
{"timestamp":"2018-04-19T10:17:43.749666193Z","level":"warn","message":"GET http://172.31.80.68:4567/stashes returned: 500 Internal Server Error"}
``
``
 curl localhost:4567/info
{"error":"redis and transport connections not initialized"
``
Our sensu redis config file:
../conf.d/redis.json
> 

{
"redis": {
          "host": "master.sensu.xxxxx.cache.amazonaws.com",
          "port": 6379,
          "reconnect_on_error": true,
          "auto_reconnect": true,
          "password": "redacted",
          "ssl": {
                "cert_chain_file": "/etc/sensu/ssl/cert.pem",
                "private_key_file": "/etc/sensu/ssl/key.pem"
         }
    }
}

> 

transport file
../conf.d/transport.json
>
{
"transport":
{
"name": "redis",
"reconnect_on_error": true
}
}

>
Please advice how we can overcome the problem.

## Possible Solution
- SSL  does work with stunnel installed locally on the server 
However we are trying to avoid additional proxy on each server and client host just for sensu.
- Another solution not to use SSL 

##  Environment

* Sensu version used: Enterprise 2.8.3 (vers. 1.2.1)
* Operating System and version (e.g. Ubuntu 16.04):
* Transport and runtime versions (e.g. Redis on AWS engine 3.2.6. In Transit Encription enabled ):

**Comment by cwjohnston** [comment]
Hey @djgrubson, sorry you're having trouble here. The [Sensu Core changelog](https://docs.sensu.io/sensu-core/latest/changelog/) indicates that support for connecting to Redis via TLS/SSL was released in version 1.3.0. 

We have not yet released a version of Sensu Enterprise built on Sensu Core 1.3, but work to incorporate these and other changes in a new Enterprise release is ongoing and we are looking forward to releasing it soon.

**Comment by portertech** [comment]
Sensu Enterprise will include a Sensu Core 1.4 release which will add TLS support for Redis.
