### ISSUE TITLE
Proxy Check with Token Substitution for the subscription retains previous values

### ISSUE THREAD

**Issue by stevenviola** [sensu/sensu#1855]
I'm attempting to create proxy checks for different proxy clients, which are intended to be sent to different subscriptions based on the environment of the proxy client. When using token substitution in the subscribers value, the substitution seems to occur the first time sensu-server is started, but after the first token substitution happens, the subscribers value stays the same for all subsequent proxy clients. This means that the checks are being sent to the wrong subscriptions to be executed most of the time.

## Expected Behavior

When specifying a token substitution in the subscription field for a proxy check, the token substitution should happen every time the proxy check is created, not just the first time. Token Substitution for the subscription values should work the same way as it currently does for the command values.

## Steps to Reproduce

1. Create two proxy clients, each with the following definition:
```
{
  "name": "region1-router",
  "address": "192.168.1.1",
  "client_type": "router",
  "region": "region1",
  "keepalives": false,
  "subscriptions": [
    "client:region1-router"
  ]
}
```
```
{
  "name": "region2-router",
  "address": "192.168.2.1",
  "client_type": "router",
  "region": "region2",
  "keepalives": false,
  "subscriptions": [
    "client:region2-router"
  ]
}
```
2. Create a proxy check for the client
```
{
  "checks": {
    "check-router": {
      "command": "check-ping.rb -h :::address:::"
      "interval": 120,
      "subscribers": [
        "roundrobin:check-:::region:::-network"
      ],
      "enable_deprecated_filtering": false,
      "proxy_requests": {
        "client_attributes": {
          "client_type": "router"
        }
      }
    }
  }
}
```
3. Watch the logs and observe that when the check request is published, it's always set to one of the subscriptions, and does not update based on the proxy client's region. Example logs:
```
{"timestamp":"2018-04-30T18:18:35.560147+0000","level":"info","message":"publishing check request","payload":{"command":"check-ping.rb -h 192.168.2.1","enable_deprecated_filtering":false,"proxy_requests":{"client_attributes":{"client_type":"router"}},"name":"check-router","source":"region2-router","issued":1525112315},"subscribers":["roundrobin:check-region1-network"]}
```

## Context

In environments with many proxy clients which need checks to be executed in particular environments, it is not feasible to create a new check for each different environment or region, and instead would be more streamlined if the proxy checks could use the token substitution when building the subscriber to send the check to.

## Environment
OS: CentOS 6
Sensu Server: 1.3.3

**Comment by portertech** [comment]
Sounds like we're mutating the Proxy Check settings object.

**Comment by amdprophet** [comment]
I was able to reproduce this issue. I can confirm that the check definition is mutated after the first pass of token substitution. Working on a fix.
