### ISSUE TITLE
/results API endpoint reporting the same client for all results

### ISSUE THREAD

**Issue by adriananeci** [sensu/sensu#1861]
The /results API endpoint returns the same client for all results
Normally it should return the corespondent client for each result
For example if I have 2 clients, in /results response I'll have 2 keepalive results that bind to the same client instead of having one result per client.
## Expected Behavior
Return the correct client per result in "client " field

## Current Behavior
 /results API returns a single client for all results.
/results/:client works as expected

no errors in sensu-api.log
.............
"method":"GET","uri":"/results","query_string":null,"body":""},"status":200,"content_length":8289391,"time":2.694
.............

## Steps to Reproduce (for bugs)

curl -u sensu:1234 sensu:4567/results | jq .

## Context
We are relying on the /results endpoint in order to check the keepalive of all sensu clients

## Your Environment

Redis 3.0.5
RabbitMQ 3.7.4 on Erlang 20.3.4
Sensu core 1.4.1
CentOS 7.4

**Comment by portertech** [comment]
We need to get this into a patch release asap.

**Comment by portertech** [comment]
Sensu 1.4.2-1 is on the way!
