### ISSUE TITLE
AIX Client - logrotate suggestion

### ISSUE THREAD

**Issue by adammcdonagh** [sensu/sensu#1864]
At present, though deployed, the logrotate config for AIX will not get triggered by anything. By default, AIX does not have it's own version of logrotate that will read anything put into `/etc/logrotate.d`.

If left without any additional work, the `sensu-client.log` file will continue to grow forever.

It might be worth adding some documentation around logging to advise of this, and suggest installing and configuring the logrotate RPM that is available on IBM's site - [here](https://www-03.ibm.com/systems/power/software/aix/linux/toolbox/alpha.html#L). Once installed, this appears to work just fine (with the default `/etc/logrotate.d/sensu` file that is packaged.

In general, I couldn't find anywhere in the docs about how the log files are handled. Fortunately I stumbled across the logrotate.d file on the server. 😄 

Adam

**Comment by cwjohnston** [comment]
@adammcdonagh thank you for brining this issue to our attention! We've opened an issue against the documentation project to track this need.

Closing in favor of https://github.com/sensu/sensu-docs/issues/430
