### ISSUE TITLE
GEM Sensu private key needed

### ISSUE THREAD

**Issue by vansoest** [sensu/sensu#1865]
Tried to upgrade the Sensu version from 1.2.1 to 1.4.2 in an Alpine Linux version 4.7 docker container.
Install Sensu in version 2.1 works like a charm but 1.4.2 need a ssh private key.  `/root/.ssh/gem-sensu-private_key.pem`

## Expected Behavior

Excepted in version 1.4.2 should it like 1.2.1:

```
RUN set -x \
# Build and install Sensu.
&& printf "install: --no-rdoc --no-ri\n" >> /etc/gemrc \
&& bundle install --binstubs \
&& rake install
```

```
+ rake install
sensu 1.2.1 built to pkg/sensu-1.2.1.gem.
sensu (1.2.1) installed.
/
```

## Current Behavior

```
RUN set -x \
# Build and install Sensu.
&& printf "install: --no-rdoc --no-ri\n" >> /etc/gemrc \
&& bundle install --binstubs \
&& rake install
```

I've got by running `rake install` this:
``` 
+ rake install
rake aborted!
WARNING:  pessimistic dependency on rspec (~> 3.0.0, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.0', '>= 3.0.0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - /root/.ssh/gem-sensu-private_key.pem

Tasks: TOP => install => build
(See full trace by running task with --trace)
```

## Possible Solution

Disable the requirement of the private ssh key also including the feature.

## Steps to Reproduce (for bugs)
In an linux environment.
* Download sensu-1.4.2.
* Extract.
* Run bundle.
* Run rake.

## Context

Ok there's no provided ssh private key `/root/.ssh/gem-sensu-private_key.pem`
How can I get or ignore this key?

found this commit https://github.com/sensu/sensu/commit/4c30f5155c5484410bb8b22a451ad85d5fa896fe

## Your Environment

* Sensu version used: 1.4.2
* Operating System and version: Alpine Linux 3.7

**Comment by majormoses** [comment]
Thanks for reporting I think this. A couple of things, you do not need the private key you need the public key. Hmm I personally would say this is a breaking change that should not have happened in a minor release ping @portertech. From what I recall about this from other experiences you only need the public key when installing and the private key should only be needed when building. Sensu would obviously not want to distribute its private key as it would defeat the purpose of signing the gems. I imagine looking at [this](https://github.com/sensu/sensu/blob/v1.4.2/sensu.gemspec#L37-L38) that is the intent but something may not be right, you probably need to do something like this first:
```
gem cert --add <(curl -Ls https://raw.githubusercontent.com/sensu/sensu/master/certs/sensu.pem)
```

And then you should be able to install with something like this:
```
gem install sensu -v '1.4.2' --trust-policy MediumSecurity
```

I also see that `bundle install` supports `--trust-policy`

Here is the documentation about gem signing: https://guides.rubygems.org/security

We are gonna have to update all the install docs, CM tools, etc to account for this.

**Comment by majormoses** [comment]
Actually this will only affect installing from gem directly as most people install with a deb/rpm and I imagine this happens in the installer process it should not likely affect the CM tools.

**Comment by vansoest** [comment]
Installation in Alpine Linux with gem works. Thank you!

**Comment by cwjohnston** [comment]
Closing as the underlying issue has been solved. I have opened sensu/sensu-docs#644 to track the documentation of this workaround.
