### ISSUE TITLE
Redaction of vars on clients created from the API

### ISSUE THREAD

**Issue by danragnar** [sensu/sensu#1869]
When creating proxy clients through the API, passwords/sensitive vars does not seem to be handled the same way as if they're created through a regular client (in a client.json file).
## Expected Behavior

When accessing a client created via the API, vars set on that client that is subject to redaction should be redacted. Further check commands/results where token substitution is made on those vars, should also be redacted. 
## Current Behavior

Vars subject to redaction set on clients created through the API does not get redacted in any way. Check commands/results containing vars subject to redaction is not redacted in any way.
## Possible Solution

Not a technical solution, but an idea: sensitive vars should be treated the same independently of where they're created or accessed. Maybe have a scope or key through which to specify sensitive stuff and a way for clients/api to access that data, but only those clients that have subscriptions relating to the client or check that defines the sensitive object.  
## Steps to Reproduce (for bugs)

1. Create a proxy client through the API with a variable set that should trigger redaction.
2. Create a check with token substitution utilizing that var (with proxy_requests).
3. Run the check.

## Context

I'm trying to create an ipmi check where the password is needed as an option on the command line. The ipmi check is run through proxy requests and the clients are created through an api call to which the results are reported. The password is stored on the client as a hash: "ipmi": {"user": "x", "password": "y"} and is substituted in the check through :::ipmi.user::: and :::ipmi.password::: which gives me the possibility to set different passwords on different servers.
## Your Environment

* Sensu version used: 1.4.2
* Active Sensu extensions (e.g. WizardVan 0.1.0):  None
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.4
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):  RabbitMQ 3.73, Erlang 19.3

**Comment by cwjohnston** [comment]
@danragnar thanks for bringing this issue to our attention. We're going to look into how we can address redaction of proxy client attributes, but we could use your help in identifying places where you've seen this kind of information displayed unredacted. 

I'm guessing the following are likely points of exposure:

* /clients API endpoint
* /events API endpoint
* /results API endpoint

If you can confirm the above and share any additional observations that would be wonderful!

**Comment by danragnar** [comment]
@cwjohnston Great to hear :+1:
I can confirm that all three of the listed api endpoints contains the password field unredacted. I have peaked through the other endpoints, but the client vars are not an attribute of those objects. I guess if you would define the sensitive var on the check it would be shown on the checks endpoint, but that maybe out-of-scope, since the redact parameter clearly isn't defined to be used that way.
Other than that, it can be seen in the log files of the executing client and in the server log as well.

**Comment by portertech** [comment]
Due to the nature of proxy check requests, all token substitution is done by the sensu-server, the check requests may contain sensitive information, such as the check command (e.g. `-p :::password:::` becomes `-p my_password`). I do not think we can avoid sending sensitive information over the wire. To avoid storing the check command secrets in Redis (therefor exposing via the API) we could replace the command in received _check results_ with the version w/o substituted tokens.

**Comment by portertech** [comment]
To fix API GET /clients (and /clients/:name), we can use the attribute redaction utility for returned objects.

**Comment by portertech** [comment]
Part of this was fixed by #1910 (included in 1.6). We still need the other part of the solution, which is API /clients redaction, which will ship as part of 1.7.
