### ISSUE TITLE
Disable Multi sensu-servers

### ISSUE THREAD

**Issue by mordechaia** [sensu/sensu#1870]
Hey,

We experienced a keepalive storm on our sensu environment, after investigation, (with help from https://github.com/sensu/sensu/issues/1797)  we found that we  started the sensu-server service on one of our machines, and this server was automatically signed up to rabbitmq as  a second consumer, and as a consumer, it takes part of the keepalive events from the real server, and because the real server didn't get this event we got critical alerts of keepalive.

I'm looking for a way to disable clients to sign as servers to the rabbitmq.
 I think maybe to disable sensu server process on the system of all our clients but i don't like it, because it's a patch and not real solution, and I need to deploy it to all of our clients instead of fixing it in one place (the server).

i thought maybe to change permissions of the rabbit user to only write event but I think it will not work because as i understand it, every client read event schedule from the rabbitmq.

your help will be much appreciated,
Thanks!

**Comment by cwjohnston** [comment]
@mordechaia thanks for the feature request. We are noting this as one potential way to help folks avoid the "rogue sensu server" condition. Additionally we're working on changes to our documentation which will make clearer available options for RabbitMQ ACLs that might help here as well.

**Comment by portertech** [comment]
The way to prevent rogue sensu servers is now documented at: https://docs.sensu.io/sensu-core/1.4/guides/securing-rabbitmq/#client-perms-strict
