### ISSUE TITLE
https://docs.sensu.io/ down with application error

### ISSUE THREAD

**Issue by nullify005** [sensu/sensu#1877]
docs.sensu.io appears to be down

![image](https://user-images.githubusercontent.com/13192879/41690392-a4ce2d22-7538-11e8-871b-2238ea87a0b0.png)

## Expected Behavior

documentation site is up!

## Current Behavior

documentation site is down :(

- either it shows 'application error'; or
- an nginx 403 page regardless of where you attempt to go

## Possible Solution

nada

## Steps to Reproduce (for bugs)

Open up a browser & point it to the doc site

**Comment by rgeniesse** [comment]
Thanks @nullify005. We have identified the issue and https://docs.sensu.io is back up.

We are opening an issue against our documentation site to track the root cause and eventual fix. @cwjohnston  can you provide that once it is made? Thanks.

**Comment by cwjohnston** [comment]
Opened https://github.com/sensu/sensu-docs/issues/514 to describe what we ran into here.
