### ISSUE TITLE
sensu server is vulnerable to the right "wrong payload" directly injected into the RabbitMQ pipeline

### ISSUE THREAD

**Issue by davideauee** [sensu/sensu#1885]
The Sensu servers are optimistic  about the validity of the data retrieved from RabbitMQ and are vulnerable to invalid payloads directly injected into RabbitMQ.

This happened to us when one of our client teams tried to bypass the normal APIs (Sensu api, client checks, client input socket) and brought down the entire Sensu cluster instantly.

bringing the cluster back up meant editing the server code in our live deployment until we could find the source of the erroneous data inputs.

This was caused by a "rogue" client team but since rabbitMQ needs to be accessible from any server running the client, it is tricky to protect ourself against such an attempt. 

## Expected Behavior
 - sensu-server instances should handle invalid data record safely and not crash if given invalid data object from the transport or the registry
 
## Current Behavior
- the Sensu server can crash as soon as it tries to process the right "wrong payload". see the steps to reproduce
 
## Possible Solution
 - validate any payload consumed from the transport or  the registry  

## Steps to Reproduce (for bugs)
 1- manually inject the following payload to the {{keepalive}} queue in RabbitMQ  
`{"name":"localhost","hostname":"localhost","version":"0.0.1","timestamp":1531987235}`
 2- watch the sensu-server instances crashing
 
## Context

the only way i managed to bring the sensu server back up was by refactoring the live **/sensu/server/process.rb** file:

 ```
...

       def update_client_registry(client)
         @logger.debug("updating client registry", :client => client)
         client_key = "client:#{client[:name]}"
 
 if client[:subscriptions].nil?
   @logger.warn("BRPR log (process.rb, line 150, #{caller_locations(1,1)[0].label}): the client #{client_key} is missing a 'subscriptions' attribute: #{client}")
   return
 end

         client[:subscriptions] = (client[:subscriptions] + [client_key]).uniq
         signature_key = "#{client_key}:signature"
  ...
```

## Your Environment
sensu 1.2.1

**Comment by ChrisOnToure** [comment]
+1 we sometimes having CRC errors on the network what results into wired characters and causes the sensu server/api to crash. Will this be catched as well?

![image](https://user-images.githubusercontent.com/25243862/43821319-17e81714-9b13-11e8-886f-18e816005856.png)

**Comment by portertech** [comment]
We could leverage https://www.rubydoc.info/github/eventmachine/eventmachine/EventMachine.error_handler for an improved report.

**Comment by portertech** [comment]
Sensu 1.7.0 will include the changes in #1938, a global catch-all error handler. If users bypass defensive input APIs, it's nearly impossible for Sensu to handle every conceivable error etc.
