### ISSUE TITLE
Sensu Client on Windows

### ISSUE THREAD

**Issue by yogeshrao** [sensu/sensu#1887]
Hello,

I am trying out sensu for our infrastructure which comprises majorly of Centos 7 and Windows 2008+servers. 

As part of the install on Windows I noticed following 

1. sensu_install found within opt\sensu\bin does not have a .bat extension which throws below error
_'sensu-install' is not recognized as an internal or external command, operable program or batch file._

2. sensu-client.xml has incorrect path configured as part of executable and argument. I had installed sensu on my D drive but the location mentioned within xml was still pointing to c:\opt\...

3. sensu_install batch file has incorrect environment variable path set. I had to change it manually to reflect the paths. perhaps relative paths can be used instead.

BTW is there any restriction that sensu has be installed within c:\opt itself ? 

Other details needed

* Sensu version used:  Sensu Core 1.4.3
* Active Sensu extensions (e.g. WizardVan 0.1.0): cpu_metrics with Graphite
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04 LTS (Sensu-Server)  
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2) : RabbitMQ 3.7.7:

please let me know.

Regards,
-Yogesh

**Comment by cwjohnston** [comment]
Hello @yogeshrao, thanks for your question. 

As currently constructed, the Windows MSI for Sensu may allow you to change the installation path, but this does not change the content of a number of different files installed by the MSI. 

As a result, we currently only support installing Sensu to C:\opt\sensu, but are looking into how we can make this requirement less strict for our upcoming Sensu 2.0 MSIs.
