### ISSUE TITLE
Provide API that deletes all results for a given check name.  

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu#1893]
As of now, there is no simple way to delete results for a given check from all clients. 

## Expected Behavior
- Ability to easily specify/execute the deletion of all results for a given check. 

## Current Behavior
- No such ability exists except for manually removing from Redis. 

## Possible Solution
- Provide an API that deletes all results for a given check name. 
- Provide a CLI utility that iterates over all client/check pairs and on the API to delete matching check results.

## Your Environment

* Sensu version used:
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04):
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by annaplotkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [There’s no easy way to delete results for a given check from all clients](https://trello.com/c/iGSXK0J1/30-theres-no-easy-way-to-delete-results-for-a-given-check-from-all-clients)

**Comment by majormoses** [comment]
I think once we add this it will make life much easier for people, see: https://github.com/sensu/sensu-docs/issues/189 as to the "current" guide on manual cleanup.

**Comment by portertech** [comment]
Closed by #1909
