### ISSUE TITLE
Add additional sensitive information to default redaction list

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu#1906]
## Expected Behavior
All sensitive information is redacted from Sensu merged configuration dumps as those are frequently provided to Customer Success for troubleshooting purposes.

## Current Behavior
A number of entries that should be redacted are currently not. From Sensu Enterprise integration:

```
pagerduty: routing_key
rollbar: access_token_read, access_token_write, access_token_patch
slack: webhook_url
irc: nickserv_password, channel_password
snmp: community
puppet: keystore_password, truststore_password
chef: proxy_password
ec2: access_key_id, secret_access_key
```

## Possible Solution
Add these items to the default list.

https://github.com/sensu/sensu/blob/v1.5.0/lib/sensu/utilities.rb#L125

## Steps to Reproduce (for bugs)
Create integration definition in within Sensu Enterprise install. Example:

```
{
  "pagerduty": {
    "routing_key": "r3FPuDvNOTEDyQYCc7trBkymIFcy2NkE",
    "timeout": 10
  }
}
```

Run the following to dump merged configuration:

```
sudo -u sensu java -jar /usr/lib/sensu-enterprise/sensu-enterprise.jar -c /etc/sensu/config.json -d /etc/sensu/conf.d --print_config
```

Observe that `routing_key` is not redacted.

## Context
Causes a security risk for customers as we inform them that the configuration dump redacts sensitive items, but currently does not redact all of them.

## Your Environment

* Sensu version used: sensu-1.5.0-1.el7.x86_64, sensu-enterprise-3.1.0-1.noarch
* Active Sensu extensions (e.g. WizardVan 0.1.0): None
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.5.1804
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): N/A.

**Comment by portertech** [comment]
Closed by #1907
