### ISSUE TITLE
Incorrect variable expansion within hooks for proxy_requests checks

### ISSUE THREAD

**Issue by bartlamboo** [sensu/sensu#1908]
## Expected Behavior
I'd expect consistent variable expansion within a check hook identical to the actual check command when using the proxy_requests function.

## Current Behavior
At the moment it seems that (at least) the :::name::: is replaced with a random host name when I do an "Issue Check Request" from the Uchiwa interface.
Variable expansion seems to be functioning correctly when using the same construct without the proxy_requests feature.

## Steps to Reproduce (for bugs)
`{
    "checks": {
        "test_check":{
            "command": "echo \":::name::: - `hostname`\"; exit 1",
            "subscribers": [
                "roundrobin:sensu"
            ],
            "hooks": {
              "non-zero": {"command": "echo \":::name::: - `hostname`\"", "timeout": 900}
            },
            "interval": 604800,
            "splay": true,
            "ttl": 1209600,
            "proxy_requests": {
                "splay": true,
                "splay_coverage": 2,
                "client_attributes": {
                    "subscriptions": "eval: value.include?('redhat')"
                }
            }
        }
    }
}
`

The above check returns the following within my environment:
_The check output: kvm-elk02-am6 - kvm-mon-am5.ourdomain.com
The hook output: kvm-elk01-am5 - kvm-mon-am5.ourdomain.com_

The host which is proxying the check was the _kvm-mon-am5_ and the host for which it was proxying was the _kvm-elk02-am6_

## Your Environment
All hosts in our environment are Red Hat 7.5 and run Sensu 1.4.3.

[root@kvm-mon-am5 conf.d]# rpm -qa | egrep -i "rabbitmq|sensu|erlang|redhat-release-server|uchiwa"
uchiwa-1.3.1-1.x86_64
rabbitmq-server-3.7.6-1.el7.noarch
erlang-20.3.7-1.el7.centos.x86_64
sensu-1.4.3-1.el7.x86_64
redhat-release-server-7.5-8.el7.x86_64

**Comment by mcbsdEU** [comment]
Hi,

there are several issues like that (from my personal perspective) around checks for proxy clients.
I have reported #1832 and not directly similar but basically same issue also #1904
