### ISSUE TITLE
sensu client is too fat

### ISSUE THREAD

**Issue by maxadamo** [sensu/sensu#1918]
Would it be possible to split the packages, and would this help to get a small client package? 
I was thinking to something like this: 
1. sensu-common
1. sensu-api
1. sensu-server
1. sensu-client

**Comment by majormoses** [comment]
For what it's worth in the next generation of sensu (go rewrite) the packages are split into `sensu-agent` and `sensu-backend` (server and api process are now the same).

I am not sure it'w worth it at this point as it would be a painful breaking change. I'd be :+1: to offering _new_ packages that are slimmer but I dont think its worth breaking everyone to shave a few MBs.

**Comment by majormoses** [comment]
Honestly not sure how much would actually be saved we are shipping a full embedded ruby so shaving a few libs and init scripts out may not yield much in terms of size reduction, if you want to check out https://github.com/sensu/sensu-omnibus and do some investigation on what kind of size reduction we would get that would inform us on the value of attempting this.

**Comment by maxadamo** [comment]
If the next generation of sensu will be split in two packages, it's probably not worth to spend any time with the current version. 
I was also expecting the second reply, but I wasn't able to quantify. 
I'm gonna close the request.
