### ISSUE TITLE
History reset "another sensu server is responsible for the task" in log

### ISSUE THREAD

**Issue by nflantier** [sensu/sensu#1924]
I have a custom mail handler with a filter that allow the handler to be fired only when the state change.
I started recieving some mail that was fire even if the state was unchanged.
Uppon debugging, the history of all checks from all client was deleted ( i think redis was reset or flush ) that is why the handler was fired and in the sensu-server log i found, coresponding to the right timestamp ( the mail reception time )
```
{"timestamp":"2018-11-26T10:55:39.398722+0100","level":"warn","message":"another sensu server is responsible for the task","task":"check_request_publisher"}
{"timestamp":"2018-11-26T10:55:39.398767+0100","level":"warn","message":"relinquishing server task","task":"check_request_publisher"}
{"timestamp":"2018-11-26T10:55:39.398845+0100","level":"warn","message":"another sensu server is responsible for the task","task":"client_monitor"}
{"timestamp":"2018-11-26T10:55:39.398903+0100","level":"warn","message":"relinquishing server task","task":"client_monitor"}
{"timestamp":"2018-11-26T10:55:39.398948+0100","level":"warn","message":"another sensu server is responsible for the task","task":"check_result_monitor"}
{"timestamp":"2018-11-26T10:55:39.398980+0100","level":"warn","message":"relinquishing server task","task":"check_result_monitor"}
```

## Your Environment

* Sensu version used: 1.6.1

**Comment by cwjohnston** [comment]
hi @nflantier , thanks for raising this issue. If your Redis database was infact reset or flushed, seeing these messages related to server tasks is expected. 

Redis is used as the locking mechanism for tasks which should only run on one Sensu server at a time, so when Redis is flushed it is likely that task ownership would transfer between servers as the database is repopulated with new task locks.

I'm going to close this issue for now but please let me know if you think I've misunderstood or there's some other issue at play here.
