### ISSUE TITLE
Can not filter api results by integers other than 0

### ISSUE THREAD

**Issue by robertely** [sensu/sensu#1925]
When attempting to filter on `filter.check.status` values above zero will not return any results.

## Expected Behavior
_Assume our sensu instance contains many check results with status values of 0,1,2_

A `get` request to `http://sensu.company.net:4567/results?limit=10&filter.check.status=2`
Returns a set of results where the check status is `2` with a `http/200` status.

## Current Behavior
_Assume our sensu instance contains many check results with status values of 0,1,2_
A `get` request to `http://sensu.company.net:4567/results?limit=10&filter.check.status=2`
Incorrectly returns an empty set `[]` with a `http/200` OK status.

A `get` request to `http://sensu.company.net:4567/results?limit=10&filter.check.status=0`
Returns a set of results where the check status is `0` with a `http/200` OK status as expected.

## Possible Solution

I can only guess a type conversion is happening someplace unexpected. I didn't see any thing obvious when looking over the filter code.
A fix could perhaps be rolled into this little guy: https://github.com/sensu/sensu/issues/1768

## Context
I want to check if any instances of a specific check are in an 'unhealthy' state(status>0). It's currently not possible (so far as i can see) to filter for this directly. I settled on filtering for `filter.check.status=2` and `filter.check.status=1` as a work around. Unfortunately that's when i discovered i was unable to filter for any value of `check.status` besides zero.

Ideally we could fix this bug and also provide a more direct/correct method of filtering status>0. 

## Your Environment

* Sensu version used: `1.4.2`
* Active Sensu extensions: `None`
* Operating System and version: `CentOS 6.9`
* Transport and runtime versions:
  * Sensu embedded Ruby runtime `ruby 2.4.1p111`
  * Transport `RabbitMQ 3.4.3, Erlang 17.4`
  * Redis `Redis server v=2.8.19`

**Comment by majormoses** [comment]
I was able to replicate this with `1.5.0`

**Comment by cwjohnston** [comment]
@robertely thanks for raising this issue. Response content filtering is mean to support filtering on  string values only, so this issue will be addressed by adding documentation that makes this limitation clear. Opened https://github.com/sensu/sensu-docs/issues/1080 to track this.
