### ISSUE TITLE
HTTP 204 responses can inappropriately include content

### ISSUE THREAD

**Issue by tmonk42** [sensu/sensu#1961]
HTTP 204 "No Content" should not respond with content.

The API endpoint health initializes "@response_content" to an empty array. If health is okay as determined by the array still being empty, then it calls the "no_content!" response.
https://github.com/sensu/sensu/blob/master/lib/sensu/api/routes/health.rb#L34

The def for "no_content!" appropriately sets the status code and string (204/No Content) then calls "respond".
https://github.com/sensu/sensu/blob/master/lib/sensu/api/http_handler.rb#L281

The "respond" method does a JSON.dump of "@response_content", which in the case of the health endpoint being healthy, is an empty array, which gets serialized to a response of "[]".
https://github.com/sensu/sensu/blob/master/lib/sensu/api/http_handler.rb#L205

## Expected Behavior

If response is 204/No Content, then response should not return any content (including empty arrays).

## Current Behavior

Health endpoint responds when healthy with a 204 than includes "[]" in the content.

## Possible Solution

PR incoming shortly. In the def for "no_content!" we should nil out @response_content.

## Steps to Reproduce (for bugs)

1. Call /health api endpoint, note that headers look correct, and body include []
2.
3.
4.

## Your Environment

* Sensu version used: 1.8.0
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by portertech** [comment]
Closed by #1962
