### ISSUE TITLE
Get list of all checks

### ISSUE THREAD

**Issue by akahn** [sensu/sensu#364]
Hi,

We're in the process of building a dashboard of service health using Sensu. Is there a way to get a list of all checks across all clients and their statuses with the API? There is `/checks` but that doesn't list the hosts that make each check. What is the best way to approach this?

Thanks,
Alex

**Comment by chrisduong** [comment]
From this request, I want to know if we can **get all the checks of a client** from Sensu API. Right now, I can only get all checks of the Sensu Server itself where Sensu API is running.
