### ISSUE TITLE
SSL Client certificates

### ISSUE THREAD

**Issue by vjanelle** [sensu/sensu#434]
The documentation doesn't seem to highlight the risks of using the same SSL certificate on all clients.  

Is this an issue that should be revised?  I'm going to add a notice about it in the demo readme for sensu-puppet, but I don't know if it should be highlighted in the demo docs?

I noticed sensu-chef might also be facilitating this issue, but haven't verified this.

**Comment by lattwood** [comment]
I'm using the rabbitmq-auth-mechanism-ssl plugin on github to provide something similar to the desired functionality. https://github.com/rabbitmq/rabbitmq-auth-mechanism-ssl

I use the common_name functionality, which (unfortunately) means if a certificate is compromised that CN is burned forever.
