### ISSUE TITLE
Drop the client info requirement for event data

### ISSUE THREAD

**Issue by portertech** [sensu/sensu#541]
531

**Comment by ripasapa** [comment]
+1 we are using a lot e.g. AWS services and source name should be able to override. Putting source name to check_name is not recommended. Sensu is a great tool and i hope this custom json event with "source name whatever you like to put " can be implemented.

**Comment by samion** [comment]
+1

**Comment by jkamper** [comment]
https://github.com/sensu/sensu/issues/541#issuecomment-67759128

+1

**Comment by roobert** [comment]
+1

**Comment by roobert** [comment]
I've expanded @solarkennedy's patch so that masqueraded hosts are also visible through the API, see this ticket for details: https://github.com/Yelp/sensu/issues/1

**Comment by Copse** [comment]
+1
If this get's implemented we can get rid of Nagios for good!

**Comment by jtyr** [comment]
+1

**Comment by johntdyer** [comment]
:+1: * :100:

**Comment by johntdyer** [comment]
@portertech  any movement on this ?

**Comment by josqu4red** [comment]
Being able to run checks on behalf on other hosts is a critical feature to me too; Any news on this ?

**Comment by nien4521** [comment]
We are an it company that mostly sell and configure monitoring solutions (mostly nagios) for large infrastructure, and we are not allowed or we can't ( ip cam,switch, router, ...)  to install any kind of "client" on 70%  of the devices we have to monitor, sometime we only have acces to  :
- SNMP
- HTTP
- JUST A PING
- SSH/Telnet/Only a socket

The ONLY reason that we dont (yet) sell/install sensu is that we can't see those device as "client" in uchiwa and the api but instead we have to run our check on a client and we have as result in uchiwa 
localhost.device1.check1
localhost.device2.check1
....

The day we see a device without a sensu-client as a client in uchiwa/api we switch immediately to sensu.(curently we use nagios)
How come that a monitoring system doesn't have (natively) this kind of feature ?
I believe that the day this kind of feature is enabled in sensu everyone will drop nagios for sensu

**Comment by TinajaLabs** [comment]
I have to say...  I was interested in sensu when we were using Icinga
1.8.4. Now Icinga 2.x is a re-written release and kicks ass.  Open source,
and pretty amazing.  The fact that the developers of sensu are not willing
to respond to their users means they are not really in the game.

Icinga 1.8.4 was just a clean-up of Nagios.  Icinga 2 is a re-write and the
team has built a really powerful monitoring application.

I recommend trying Icinga 2 (if you use nrpe, just set up a parallel server
to access the same nrpe checks) and move on.  Connects easily to
graphite/grafana, node-red, etc.  Very powerful service check
definitionstructure.






*So long, it's been good to know yuh;So long, it's been good to know yuh;So
long, it's been good to know yuh.This dusty old dust is a-gettin' my
home,And I got to be driftin' along. -- Woody Guthrie*




--
Chris Jefferies
TinajaLabs.com
510.409.0003

**Comment by johntdyer** [comment]
@portertech  any comments on why this is such a tough nut to crack ?

**Comment by portertech** [comment]
@johntdyer https://trello.com/c/eowfiJQ8/21-as-an-operator-i-would-like-to-monitor-external-resources-that-do-not-have-sensu-client-they-require-their-own-check-execution-h

**Comment by portertech** [comment]
@roobert @solarkennedy thoughts on this approach? https://trello.com/c/eowfiJQ8/21-as-an-operator-i-would-like-to-monitor-external-resources-that-do-not-have-sensu-client-they-require-their-own-check-execution-h It's capable of dynamically creating a clients when a new check source is provided, and provides a way of managing/updating the clients.

**Comment by portertech** [comment]
I have set a due date of next Friday. Aiming to have the check result data storage bits and this in 0.18.

**Comment by portertech** [comment]
![200](https://cloud.githubusercontent.com/assets/149630/7149592/34b7c3cc-e2c4-11e4-85f1-1797892e9c70.gif)

https://github.com/sensu/sensu/pull/924

**Comment by johntdyer** [comment]
![happy panda](http://fc08.deviantart.net/fs11/i/2006/232/6/3/Happy_Panda_by_Nieme.jpg)

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/924 is ready for review/feedback :+1:

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/924 has been merged, 0.18 will have this functionality :+1:

**Comment by calebhailey** [comment]
![](http://media.giphy.com/media/PDNrFEx1JUoLe/giphy.gif)
