### ISSUE TITLE
[feature] Set check timeout exit code per check

### ISSUE THREAD

**Issue by cbarraford** [sensu/sensu#552]
Right now, you can set a timeout (in seconds) on a per check level so that if the check takes longer than X seconds, the check is killed and you get a return code of 2 with message "Execution timed out".
https://github.com/sensu/sensu/blob/master/lib/sensu/io.rb#L39

I'd like to be able to set the exit code of a timeout to anything i want (ie 3 or "unknown" state).

**Comment by fessyfoo** [comment]
updated links for anyone stumbling onto this: 

Spawn with timeout happens here:  https://github.com/sensu/sensu/blob/ef9f915/lib/sensu/client/process.rb#L151

`Execution timed out` with exit code 2 happens here: 
https://github.com/sensu/sensu-spawn/blob/dd9ae05/lib/sensu/spawn.rb#L163
