### ISSUE TITLE
sensu-server not reconnecting after redis crash and failover

### ISSUE THREAD

**Issue by bencaron** [sensu/sensu#599]
Just had a issue with sensu-server that did not reconnected to redis server after a crash of the redis server.

We are using a HA redis setup as described here:
https://blog.theroux.ca/sensu/high-availability-sensu/

The master redis server (01) had a kernel panic. The failover worked as expected, with the master switching to 02 and HAProxy marking the redis 01 as down and 02 as up.

Normally, sensu should have reconnected automatically:

https://github.com/portertech/em-redis/blob/unified/lib/em-redis/redis_protocol.rb#L490

But the events started piling up into rabbitmq for a good 15 minutes until the sensu servers (we have 2) started processing them again. CPU load on the sensu servers turned to almost none and almost nothing got logged in the mean time:

In the logs:

```
{"timestamp":"2013-08-16T09:34:44.885847-0400","level":"info","message":"only handling every 30 occurrences: my-server-name/check_swap"}
{"timestamp":"2013-08-16T09:50:41.209103-0400","level":"warn","message":"reconnecting to redis"}
```

The part missing from the redis HA tutorial is how the HAProxy is configured:

```
backend bk_redis
  log     global
  mode    tcp
  option  log-health-checks
  option  tcplog
  option  httpchk GET /
  balance leastconn
  timeout connect 10s
  timeout queue 5s
  timeout server 3600s
  server redis-01 xx.yy.zz.aa:6379 check port 12345
  server redis-02 xx.yy.zz.bb:6379 check port 12345
```

Maybe the socket got stuck between sensu-server and HAProxy, but since the redis-01 was in kernel panic, it was not a socket left in a incomplete state.

We had a similar but not-quite-the-same (and not as throughly examined) incident this week. I'll update this issue with more details if the problem happens again.

I know that it's not absolutely obvious to figure what went wrong here, but thanks for tips on what could have went wrong.

**Comment by dblessing** [comment]
I just experienced the same thing today. I was baffled when sensu-api and sensu-server on all my nodes just stopped. Same log output as noted by @johntdyer

**Comment by sa-shukla** [comment]
Yes. I have setup Redis HA and whenever Redis failover happens, sensu-api crashes. Though sensu-server is able to reconnect to the redis-master.

I am running sensu version 0.19.1

Seems this issue is open since couple of years and the maintenance team should look into this more seriously.

Regards,
Sagar

**Comment by portertech** [comment]
You can use the Redis connection option `"reconnect_on_error": true`, in Sensu 0.17.x.

**Comment by sa-shukla** [comment]
Thanks for the update. Will give it a try. As per my understanding, it should be true by default.

**Comment by portertech** [comment]
The Redis client will always reconnect in the event of a connection issue, but not if Redis has an error, e.g. READONLY.
