### ISSUE TITLE
[SENSU CLIENT WIN32]: Service shutdown or crash leaves forked "cmd.exe" orphan checks indirectly holding the TCP 127.0.0.1:3030 socket and the UDP "*:3030" service port.

### ISSUE THREAD

**Issue by chiriaev** [sensu/sensu#611]
Guys, Hi. I have recently faced some serious issues/blockers with the Windows port of the SENSU client, latest version. Here is the story. In short, following a crash or a a graceful shutdown, checks being executed may not receive or interpret the termination signal from the parent PID and get stuck, running as “orphans”. The very unfortunate side-effect of this is that somehow the two TCP and UDP sockets, port 3030, that SENSU is allocating at start-up are not released and remain bound to a generic “system” process, without any PID reference to it. As a consequence, in the circumstances described above, the client couldn’t be started again without changing the port numbers. (i.e.: or a reboot; the sockets cannot be closed with TCPView or Cports, etc…)

To be more specific, SENSU is relying on the EVENTMACHINE module... The latter is by default using SO_REUSEADDR socket option for TCP. This is for some reasons not the case for UDP. It is where the exception was triggered. Having said that, a proper clean-up has to happen. The contrary is not really negotiable, at least to me.

What I currently have to do is working around this situation with changes to the "sensu-client.xml": whenever the service is stopped it has to “terminate” all of its children and whenever it is started it should clean-up potential “zombies”. 

It was tested with the "sensu-0.9.12-2" and "sensu-0.10.2-1" MSI(s) on "Windows 2008 R2 standard edition".

I would like to raise that as a bug. 

Regards, Andrei

**Comment by portertech** [comment]
Closing this issue, as Sensu >= 0.13 (now 0.18) process management on Windows has address this.
