### ISSUE TITLE
docs provide no indication of needed firewall rules

### ISSUE THREAD

**Issue by mreinstein** [sensu/sensu#623]
I think I've got sensu server running. I'm at the point where I need to set up a client. What ports need to be open between the server and client? There are a ton of ports uses: 
- rabbitmq: 5672, 5671
- api: 4567
- redis: 6379
- dashboard: 8080

Which ones need to be open, and in which directions  between the client and server?

**Comment by jflemer-ndp** [comment]
Where is the equivalent for current releases of Sensu & Sensu Enterprise?
