### ISSUE TITLE
Unable to connect to RabbitMQ w/ self-signed cert

### ISSUE THREAD

**Issue by jakedavis** [sensu/sensu#683]
Howdy all,

I have been thrashing against this problem for awhile and am at a loss on what the issue is. We have an internal CA which we use to deploy certificates; our own services use this to connect to RabbitMQ successfully. However, I have had no such luck with Sensu. An important note is RabbitMQ using both `verify_peer` instead of `verify_none`, and also `fail_if_no_peer_cert` is true, not false (as in the builtin cookbook template), although it fails in both cases.

Some steps I've gone through to validate the config for RMQ and certificates:
* Connect to an `openssl s_server` using `s_client`
* Connect to RabbitMQ using `s_client` and gotten a correct response
* Inspected text output of certs using `openssl x509 -text`

I've read over the RabbitMQ [SSL](http://rabbitmq.com/ssl.html) and [SSL troubleshooting](http://rabbitmq.com/troubleshooting-ssl.html) guides and nothing jumps out. I haven't done the stunnel test they have there but I should get the chance to do that at some point.

The next thing I did was hop into Sensu's embedded irb to see if I could connect. I was unable to. [Here](https://gist.github.com/jakedavis/8422928) is the irb output and relevant RabbitMQ logs from that, as well as openssl output and the sensu client logs.

The credentials are correct as I can connect successfully to the non-SSL port. It is only when I add the SSL options hash to the AMQP connection call that things go sideways. It points to the same certs I successfully use to connect to RMQ using openssl directly. The virtualhost, host, and port are also correct.

The only difference between the certs with which Sensu ships and our own is sha1 vs. sha256 hashing, respectively (and AFAICT). I'm not really sure how to proceed but appreciate any advice.

Let me know what other information I can provide.

**Comment by portertech** [comment]
@jakedavis Are you still having to use stunnel for RabbitMQ SSL connectivity?

**Comment by jakedavis** [comment]
We are, yep, although to be honest we haven't really revisited this since. We also haven't upgraded in awhile so maybe we can give that a spin and see what happens.

**Comment by WBasson** [comment]
We had all the same problems getting rabbitmq to work with self-signed certs on Debian Wheezy. Installing erlang from backports solved it.

**Comment by gsalisbury** [comment]
I'm having the same issue, using sha256  certificates generated by our pki setup.

openssl s_client connects without problems using the same certificate, key and CA certs.

Tried using stunnel as a workaround but it is giving errors: "SSL3_GET_RECORD:wrong version number".

I'm using Centos7 with latest updates
Sensu 0.20.3-1
OpenSSL 1.0.1e-fips
RabbitMQ 3.5.4-1
Erlang R16B03-1

**Comment by WBasson** [comment]
Ok, some more detail to my comment above:
We only got it working after upgrading Erlang to version 17.1 on Debian. Can you install something that new on Centos?

**Comment by gsalisbury** [comment]
Ok, I've updated to Erlang 18.0 and SSL connections are now working.

Thanks

**Comment by jakedavis** [comment]
Ha, a solution _would_ emerge right after we switched to SNS/SQS for transport :) glad to see there's a solution out there though.

**Comment by portertech** [comment]
We have updated the Sensu RabbitMQ (& Erlang) installation documentation to use the official Erlang and RabbitMQ repositories, instead of using Linux distribution specific repositories - https://sensuapp.org/docs/latest/install-rabbitmq This provides a consistent installation experience and recent builds (e.g. Erlang >= 0.18).

@jakedavis Have you updated your version of Sensu and/or your RabbitMQ setup? All good? Should we consider this one closed?

/cc @agoddard

**Comment by jakedavis** [comment]
Hey @portertech, we're on SNS/SQS now, so I am unable to say. I have decent faith it's fixed based on the report above about Erlang 18 working. Thanks for following up and lemme know if I can provide any other info.

**Comment by gregorkistler** [comment]
I would mark this as completed. I´ve hit the same issue a few minutes ago. The sensu_ssl_tool still uses SHA1 and I wondered why I can´t use certificates from my FreeIPA CA which dropped support for SHA1 long time ago. 
Figured out that I still had Erlang 16b3 installed. After an upgrade to 18.2 I´m able to use my certificates from my own CA.

**Comment by calebhailey** [comment]
Closing per the latest comments that this issue was resolved by upgrading Erlang. Please feel free to open a new issue if this matter isn't fully resolved.
