### ISSUE TITLE
Sensu + Graphite, no data received and no errors

### ISSUE THREAD

**Issue by grigio** [sensu/sensu#686]
Hi, I'd like to attach some interesting info to debug but I can't find that, everything seems to work.
Graphite can receive data via netcat over port 2003 and here is some relevant configs:

```
{
  "handlers": {
    "graphite_tcp": {
      "type": "tcp",
      "socket": {
        "host": "172.17.0.79",
        "port": 2003,
      },
      "mutator": "only_check_output"
    }
  }
}
```

```
{
  "client": {
    "name": "sensu-server",
    "address": "127.0.0.1",
    "safe_mode": false,
    "subscriptions": [
      "os",
      "default"
    ]
  }
}
```

I've some checks and Sensu Dashboard shows their update the timestamp but Graphite receive no data, do you know why or how to debug it?

**Comment by hanynowsky** [comment]
I had the same issue. But this time to make it work, especially for this Handler, I had to move its config to the main config file: /etc/sensu/config.json

```

	"redis": {
			"host": "localhost",
			"port": 6379
		},
		"api": {
			"host": "localhost",
			"port": 4567
		},
		"handlers": {
			"default": {
				"type": "set",
				"handlers": [
					"stdout"
					]
			},
			"graphite_tcp": {
				"type": "tcp",
				"socket": {
					"host": "graphite.mycomp.net",
					"port": 2003
				},
				"mutator": "only_check_output"
			},
			"stdout": {
				"type": "pipe",
				"command": "cat"
			}
		},

```

**Comment by neizmirasego** [comment]
Just a small comment from me. Sometime handler definition can not be loaded due to wrong json. I this case you will get "unknown handler" error too. So check logs for the errors like this.
