### ISSUE TITLE
Requesting /health with no Accept header 404s

### ISSUE THREAD

**Issue by mattwhite** [sensu/sensu#689]
Hitting the /health endpoint on the sensu dashboard will return a 404 if you haven't specified an Accept header (e.g. "Accept: */*"). While many agents will insert that automatically, some don't (e.g. Pingdom). This can be relatively hard to debug, as using curl will just work.

I believe this should actually be returning a 406 Not Acceptable instead of a 404. Alternatively, don't fail when the Accept header is missing.

**Comment by portertech** [comment]
Master has a patched Sinatra :+1:

**Comment by mattwhite** [comment]
awesome
