### ISSUE TITLE
Secure client-server communication

### ISSUE THREAD

**Issue by acasajus** [sensu/sensu#696]
Clients should be authenticated and authorised to participate. Currently once a client has connected to the rabbitMQ it can impersonate anybody including the server! It would be desirable that:
- Client/servers sign each message each party can verify the origin
- Clients should not be able to pry on messages not sent to them
- Ideally rabbitMQ authentication should be tied to the signing of each message, so misbehaving clients can have their credentials revoked from rabbitMQ also.

This is derived from: https://groups.google.com/forum/#!topic/sensu-users/Meby6qus4D4

**Comment by trevorlauder** [comment]
I've been playing around with RabbitMQ users and permissions trying to get an account setup for the server and one for the clients (with restricted permissions) but can't seem to find a way to get Sensu to like it...  when I restrict writes to just results and keepalives, rabbitmq restricts access to the FQDN queue and the client won't start.  Am I missing something or does this currently not work?

**Comment by ctheune** [comment]
Hey @portertech, I thought the minimal permissions would be as you described. However, we noticed that the actually required minimal permissions at the moment are:

``
rabbitmqctl set_permissions -p /sensu ${client.node}
    "^((default|results|keepalives)$)|${client_name}-.*"
    "^((keepalives|results)$)|${client_name}-.*"
    "^(default$)|${client_name}-.*"
``

According to my colleague @zagy passive mode would be helpful (although I'm out of my depth there right now).

**Comment by calebhailey** [comment]
I'm giving this issue the "feature" label as part of an ongoing issues triage. This isn't a commitment that we're going to implement any new features, however it does mean we'll be revisiting this in the near future. 

In the interim, we have also scheduled RabbitMQ ACL documentation for the upcoming 0.24 release, here: https://github.com/sensu/sensu-docs/issues/306, so we'll have an update on this pretty soon, one way or the other.

**Comment by vonamgun** [comment]
Hi, @portertech, @calebhailey

Would it be clearer if Sensu optionally supported two different RabbitMQ vhosts for sending messages 
from server to clients and from clients to servers?

For the argument's sake let's call these vhosts server_to_client and client_to_server. Then the configuration would be:

rabbitmqctl add_user sensu_client secret
rabbitmqctl add_user sensu_server super_secret

rabbitmqctl add_vhost server_to_client
rabbitmqctl add_vhost client_to_server

rabbitmqctl set_permissions -p server_to_client sensu_server ".*" ".*" ".*"
rabbitmqctl set_permissions -p server_to_client sensu_client ".*" "^$" ".*"
rabbitmqctl set_permissions -p client_to_server sensu_server ".*" ".*" ".*"
rabbitmqctl set_permissions -p client_to_server sensu_client ".*" ".*" "^$"

In this configuration sensu_client can't write to other clients impersonating a server, and it can't read other clients' keepalive's and results.

Is there something that I miss out?

**Comment by cwjohnston** [comment]
I’m going to close this issue as we’ve documented strategies for defining unique Sensu client and server credenitals and permissions in our [Securing RabbitMQ guide](https://docs.sensu.io/sensu-core/latest/guides/securing-rabbitmq/).

If you have any suggestions on improving this guide, please let us know by opening an issue or pull request against sensu/sensu-docs.
