### ISSUE TITLE
Possible to use Redis as the queue?

### ISSUE THREAD

**Issue by rightaway** [sensu/sensu#703]
Is it possible to configure sensu so that redis is used as the queue instead of rabbit? It'd allow us to need to worry about configuring and maintaining one less thing, since there's already a redis instance as part of sensu (and redis is used for so many other things). If not would this be an acceptable feature request?

Just as a little side note, I noticed that Logstash used to offer rabbit but now recommends redis. "Previous versions of this guide used AMQP via RabbitMQ. Due to the complexity of AMQP as well as performance issues related to the Bunny driver we use, we're now recommending Redis instead." http://logstash.net/docs/1.3.3/tutorials/getting-started-centralized

**Comment by kshep** [comment]
Just stumbled across this and thought I'd leave pointers to...

- https://github.com/sensu/sensu-transport/pull/12
- https://github.com/sensu/sensu/pull/952

Per @portertech, redis transport is in 0.19
