### ISSUE TITLE
support to configure handlers to internal sesnu server bad states dependent on infrastructure

### ISSUE THREAD

**Issue by piavlo** [sensu/sensu#712]
Currently if something is wrong with infrastructure that sensu server relies on ,like for example, rabbitmq hiting high memory usage watermark or low free disk space available, publishers will be blocked and unless there is an independent outside of sensu monitoring
of rabbitmq there is no way to get notified of such issues by the sensu itself.
for this specific usecase rabbitmq extensions supports blocked/unblocked notifications
to publishers that request to get notified on these events.
There is example on how to use these callbacks in the amqp gem
https://github.com/ruby-amqp/amqp/blob/master/examples/extensions/rabbitmq/connection_blocking.rb#L24
the on_blocked callback would stop from publishing new check requests and craft a sensu event and pass it to the handle_event method , the on_unblocked callback would resume the check requests publishing and generate resolve event and pass it to the  handle_event method, the config might be smthing like:
<pre>
{
  "server": {
    "rabbitmq": {
      "onblock": {
        "handlers": ["email", "blah"]
      }  
    }
  }
}
</pre>

wdyt?

**Comment by portertech** [comment]
@piavlo Going to close this. The Sensu transport has since been abstracted and decoupled, using the sensu-transport API https://github.com/sensu/sensu-transport. API /health is still a more reliable means of monitoring Sensu's health.
