### ISSUE TITLE
Sensu API -> RabbitMQ connection failure on startup causes exit

### ISSUE THREAD

**Issue by jhmartin** [sensu/sensu#714]
When launching sensu-api, a failure to reach the rabbit server is logged as an error but causes the daemon to exit. 

```json
{"timestamp":"2014-04-30T10:34:27.958073-0400","level":"error","message":"[amqp] Detected TCP connection failure"}
```

**Comment by portertech** [comment]
Newer version of Sensu (currently 0.18) go into a reconnecting state and event reconnect in the event of AMQP channel errors.
