### ISSUE TITLE
unknown handler: handler_name="default"

### ISSUE THREAD

**Issue by ghost** [sensu/sensu#725]
This is configured on my server:

$ sudo cat /etc/sensu/conf.d/checks/check_disk.json {
  "checks": {
    "check_disk": {
      "handle": true,
      "interval": 10,
      "handlers": [
        "default"
      ],
      "standalone": false,
      "subscribers": [
        "sensu-test"
      ],
      "command": "/usr/lib64/nagios/plugins/check_disk -w 50% -c 10% -p /"
    }
  }
}

This is on the client:

$ sudo cat /etc/sensu/conf.d/client.json  
{
  "client": {
    "safe_mode": false,
    "address": "192.168.150.84",
    "subscriptions": [
      "sensu-test"
    ],
    "name": "dev02.corp.f7"
  }
}

The client seems to quite happily receive requests, and publishes the result:

{"timestamp":"2014-05-14T15:20:25.824795+1000","level":"info","message":"received check request","check":{"name":"check_disk","issued":1400044825,"command":"/usr/lib64/nagios/plugins/check_disk -w 50% -c 10% -p /"}}
{"timestamp":"2014-05-14T15:20:25.832241+1000","level":"info","message":"publishing check result","payload":{"client":"dev02.corp.f7","check":{"name":"check_disk","issued":1400044825,"command":"/usr/lib64/nagios/plugins/check_disk -w 50% -c 10% -p /","handle":true,"interval":10,"handlers":["default"],"standalone":false,"subscribers":["sensu-test"],"executed":1400044825,"output":"DISK WARNING - free space: / 3272 MB (43% inode=75%);| /=4202MB;3937;7086;0;7874\n","status":1,"duration":0.006}}}

But the server throws a dummy spit when it tries to process the response against the "default" handler:

{"timestamp":"2014-05-14T15:21:15.831723+1000","level":"info","message":"publishing check request","payload":{"name":"check_disk","issued":1400044875,"command":"/usr/lib64/nagios/plugins/check_disk -w 50% -c 10% -p /"},"subscribers":["sensu-test"]}
{"timestamp":"2014-05-14T15:21:15.844213+1000","level":"error","message":"unknown handler","handler_name":"default"}

Why does all the docs say to use the built in "default" handler if it doesn't work?

**Comment by mateodelnorte** [comment]
The docs describe: 
```
Out of the box Sensu ships with a ‘default’ handler which does nothing more than parse the JSON its fed via STDIN and spits back to STDOUT. A sample JSON document for testing purposes is available here: https://gist.github.com/1723079
```
but clearly the default handler doesn't seem to be included if a default setup provides the following log messages: 
```
{"timestamp":"2015-02-15T13:56:26.847099-0500","level":"error","message":"unknown handler","handler_name":"default"}
```
It seems to me that this default handler isn't being found...

**Comment by scalp42** [comment]
Running into the same issue @portertech
