### ISSUE TITLE
substitute_command_tokens fails when the token name matches the default

### ISSUE THREAD

**Issue by octete** [sensu/sensu#736]
Hi, 
I just came across this little problem when trying to use some variable expansions for a nagios ActiveMQ check.

I defined a default value such as ``-H :::amq.host|localhost:::`` and then, I never defined anything in the config for clients, so it would have to return localhost anyway.

However, it always return ``host`` there. 

My knowledge or ruby is not that good, but I have prepared a test case here:
https://gist.github.com/octete/a2a14a74132e9d662060

If you execute that code, taking the bit from ``lib/sensu/client.rb`` for ``substitute_command_tokens``, you can see how this happen:

```
 % ruby gistfile1.rb 
"host"
["PATH=$PATH:/usr/local/nagios/libexec check_activemq -H host -q mailer.fast -w 5:5 -c 2:5 -C",
 []]
```

If you change the check for the other one, where the parameter has been changed to ``amq.hostname``, then this doesn't happen.

I believe this has to do with ruby doing something like: ``"localhost"["host"]`` and returning ``host`` ?

Sorry, I would send you a PR, but my knowledge of ruby is fairly limited. I would appreciate if anyone could have a look at that at some point.

Thanks.

**Comment by calebhailey** [comment]
Looks like this should have been closed a long time ago.
