### ISSUE TITLE
Handler without "OK" severity defined shouldn't handle "OK"/"RESOLVED" events.

### ISSUE THREAD

**Issue by jbehrends** [sensu/sensu#753]
I have a handler that has the following setting:
      "severities": [
        "warning",
        "critical",
        "unknown"
      ]

In this case I want to make sure this handler never gets called when the check returns a status of "0". Currently Sensu will call the handler when the event is resolved even though I have not defined OK as a valid severity.

**Comment by br0ch0n** [comment]
@portertech I'm not sure I follow.  Do metrics checks ever have a "resolve" action?   I'd think they're always "create".  An event having a resolve action appears to be the only thing causing the normal filtering to get skipped (if I'm reading https://github.com/sensu/sensu/blob/81cf45d176c60bd03d09a9a0d677c1a823de42c2/lib/sensu/server/filter.rb#L148 correctly). Could you elaborate more on the metric-data scenario you're talking about?

In any case, the severities array is a per-handler config.  If on a certain handler that I know will never use with metrics checks (which always return 0), shouldn't I be able to filter however I want without duplicating logic in the handler code?  I'd think people are using certain handlers for certain types of checks (e.g. pagerduty for normal checks vs graphite for metrics checks) thus I might want to set the pagerduty handler to not handle OK (less noise) but the graphite one should always handle OK (needs to process all data).

An alternative, though maybe a bit redundant might be to add an "ignore_resolution" handler option for handle_severity to use?
