### ISSUE TITLE
mail handler Could not find 'mail' (~> 2.5.4)

### ISSUE THREAD

**Issue by RaymiiOrg** [sensu/sensu#761]
Mails are not working. Defined as in the getting started guide on the website, sensu installed from the packages.

Ubuntu 14.04

    /opt/sensu/embedded/bin/ruby handlers/mailer.rb  --help
    Usage: handlers/mailer.rb (options)
    /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'mail' (~> 2.5.4) - did find: [mail-2.6.1] (Gem::LoadError)
	    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	    from handlers/mailer.rb:14:in `<main>'

Tried to install the gem:

    /opt/sensu/embedded/bin/gem install mail --no-ri --no-rdoc
    Fetching: mime-types-2.3.gem (100%)
    Successfully installed mime-types-2.3
    Fetching: mail-2.6.1.gem (100%)
    Successfully installed mail-2.6.1
    2 gems installed

Did not solve the problem.

    /etc/sensu# /opt/sensu/embedded/bin/ruby -v                        
    ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]

**Comment by amdprophet** [comment]
Closing this out as this issue should be fixed by using the new [sensu-plugins-mailer plugin](https://github.com/sensu-plugins/sensu-plugins-mailer). Please open any future plugin-related issues with the new plugin repositories.

#monitoringlove
