### ISSUE TITLE
Allow a check to be run on a single client, not on all clients

### ISSUE THREAD

**Issue by philandstuff** [sensu/sensu#764]
I have multiple instances of a service. The service has an endpoint which checks its external dependencies, and I'd like to write a sensu check to ping this endpoint, but I want to do it once only, not once for each instance.  Therefore I'd like a way of specifying that I want want to run a check once, not once per service.  I'm using sensu-dashboard and I don't want a proliferation of CRITICAL errors when an external dependency goes down.

There's two sides to this: one is that the request should probably be sent using a "direct" topology queue rather than fanout; the other is that the results processing shouldn't care which particular client ran the check -- ie if client1 finds the external dependency down and reports CRITICAL, and then client2 discovers the dependency has returned and reports OK, this should cancel the CRITICAL from client1 in sensu-dashboard.

**Comment by srodrig0209** [comment]
(Apologies for reviving an older issue)

@jhmartin +1. Currently, I went with the standalone route, but I'd like to spread the checks across a range of machines and not have 1 do all the heavy lifting.

**Comment by Entr04y** [comment]
+1 on @jhmartins wording for us as well.  The manual check method should work for things the server can check, but if the subscribed clients are the only ones who can actually perform the check, then hitting the api won't work.

**Comment by portertech** [comment]
This feature is on my radar https://trello.com/c/5GN1GyXs/6-as-an-operator-i-would-like-to-have-a-check-request-go-to-a-single-subscriber-of-a-subscription We need a definition attribute or a subscription naming scheme to indicate that a subscription uses the "direct" routing topology, instead of "fanout".

**Comment by amdprophet** [comment]
This feature has been implemented since 0.19.0. Please see the following documentation for instructions on how to use it: https://sensuapp.org/docs/latest/clients#round-robin-client-subscriptions
