### ISSUE TITLE
Node tags for aggregations

### ISSUE THREAD

**Issue by omribahumi** [sensu/sensu#766]
I'm currently in a research process for replacing our monitoring system.
I've been looking at the aggregations API of Sensu and I think it's lacking an important feature: tagging (or grouping, or whatever). I'll explain:

Consider the following scenario: We have 10 different roles in our cluster.We're performing some generic system checks on all of them: Load average, CPU, Disk, Memory, Ping, SSH.
I want to aggregate based on role and check, for example, I would like to be notified if more than 1 "web" node has a "ping" check failure, without creating a separated "ping" check for "web" nodes.
With the way things are, there's no avoiding creating multiple checks for the same check.

Any thoughts?

**Comment by Seraf** [comment]
Hello, I :+1:  this issue, I have (for cost reason and not my choice) only one sensu server for two regions and 4 environments. If I want to aggregate checks on a node type, it will do it for every regions and env.
I know it can be tricked with one sensu per env or namespacing check's name but it should be a core feature to be able matching regexp in the client's name, or support tagging imho. I guess it could use the client's subscriptions as tag ?

**Comment by Seraf** [comment]
I was thinking about that, could we use subscriptions as tags ?
I mean for example I have nodes on aws in the region eu-west-1 and us-east-1. I have a subscription for each region containing the name of the region.
It should be great to have an aggregate check for keepalive check with the subscription 'eu' and another for the subscription 'us'.

What do you think about that ?

**Comment by portertech** [comment]
We may be able to expand check aggregates or add another primitive/endpoint if it makes sense. Let's continue the discussion around some code https://github.com/sensu/sensu/pull/915

**Comment by calebhailey** [comment]
Tagged this in #1218 for renewed discussion. Adding the "feature" label here as well.
