### ISSUE TITLE
[SENSU-CLIENT]: Flood gates in case of alarm sotrm

### ISSUE THREAD

**Issue by chiriaev** [sensu/sensu#777]
Sean, Guys, Hello. Let's imagine a situation when a set clients would send thousand of "critical" alerts per seconds. That could be in the case of a miss-configured check. That will overload Rabbit. It is also understood that the latter will kick-off the built-in flow-control mechanism. In other words, that wouldn't be necessary if the client had a way to down-sample the number of alerts sent. Any thoughts?

Regards, Andrei

P.S.: this is based on a real situation; a check from a single host was sending an average of 4K alarms per second.

**Comment by calebhailey** [comment]
@chiriaev hi there! :wave: 

Sorry for the radio silence on this. I'm giving this issue a "feature" label as part of an ongoing issues triage, but I'm also going to add this to the list of related issues on the new meta issue aimed to revive a discussion around a subdue redux; see: https://github.com/sensu/sensu/issues/1219

**Comment by calebhailey** [comment]
Silencing alerts is moving into Sensu Core in version 0.26 (currently in the unstable repos). See #1400, which implements #1328. This may not directly resolve this issue however, as this initial implementation of built-in silencing only provides the mechanism for silencing – it does not automatically trigger per-client silencing based on some threshold of events being generated. 

@chiriaev - does the availability of a new `/silenced` API endpoint help address your concerns, or do you see a need for further enhancements to resolve this issue? Please advise. :) 

/cc @portertech

**Comment by chiriaev** [comment]
Guys, Hi. Thanks for that. I think it should happen on the client, before reaching the transport. We are mostly doing standalone checks, FYI.

Regards, Andrei

P.S.: I hope I didn't misunderstand what your "moving silencing to the core" mean in practice.

**Comment by portertech** [comment]
The Sensu client designed to be as simple or minimalistic as possible. The client has no concept of history, it is just an execution platform. Sensu 0.26 has built-in event silencing, improved check subdue (time windows), filter when (time windows), and more. Many of Sensu's features rely on a complete centralized and serialized sense of history, filtering data at the client would break these features and/or create an incorrect idea of current state. I am going to close this issue, as many features in 0.26 greatly reduce load normally cause by excessive event handling and reduce notification noise.

**Comment by chiriaev** [comment]
Hi, Sean. Understood and agreed. One possible (minimalist) approach would have been to count the outgoing messages per second on the client an start throttling after reaching a certain threshold. Dropping the excess, perhaps. We could also have envisaged an automated alarm raised on the back of that.

What you described for "0.26" is not exactly what I would call fencing out. It should happen much earlier in the game, before the Sensu server is reached.

Regards, Andrei
