### ISSUE TITLE
Feature: tell who's the master

### ISSUE THREAD

**Issue by octete** [sensu/sensu#792]
Hi,

Would it be difficult to add an entry to the API to tell who's the master? maybe part of ``/info`` ?

I'll try to look at the source code and see if adding it as a PR is easy enough, but my ruby is not strong.

In any case, just leaving it here for the record :)
Thanks.

**Comment by chuqyang** [comment]
+1

**Comment by chiriaev** [comment]
+1 - another operationally viable feature would be to silence "keep-alive" alarms, globally, and/or have a TTL for them - fire up N times before expiring. Both need dealing @ the master level... I can expand if needed. 

Regards, Andrei

**Comment by calebhailey** [comment]
This was implemented quite a while ago. Leader election activities are logged in the Sensu server logs, and leader election is even documented as of version 0.22 docs! See: https://sensuapp.org/docs/latest/server \o/ 

I'm going to go ahead and close this, but please feel free to create a new issue if this matter is not fully resolved. #monitoringlove
