### ISSUE TITLE
sensu-client does not reconnect when it initially cannot connect to rabbitmq and just stops working.

### ISSUE THREAD

**Issue by stefanandres** [sensu/sensu#812]
If the rabbitmq-server is not available when doing  `service sensu-client start` sensu-client just stops working with

```
{"timestamp":"2014-10-30T15:19:06.142641+0100","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2014-10-30T15:19:06.142820+0100","level":"fatal","message":"transport connection error","error":"failed to connect to rabbitmq"}
{"timestamp":"2014-10-30T15:19:06.142878+0100","level":"warn","message":"stopping"}
```

and the init-script will just say failed to start.

That behavior is not what I would expect it to be. E.g. it is problematic when bootstrapping several nodes where the rabbitmq-server is finished at last.

There seems to be a rabbitmq-reconnect feature in the sensu-client when the sensu-client is already running though.

**Comment by ctheune** [comment]
Interestingly, the keepalive didn't turn red.
