### ISSUE TITLE
no way to have alerts sent only on state change

### ISSUE THREAD

**Issue by FlorinAndrei** [sensu/sensu#824]
By default, when a check triggers an alert, Sensu keeps sending alerts every 1800 seconds (the "refresh" parameter) until the problem is resolved. There seems to be no way to configure it to only send exactly one alert, during the initial state change, and never send anything afterwards until the situation is normalized.

**Comment by portertech** [comment]
@FlorinAndrei you could use event["check"]["history"] to filter events, either w/ a Sensu filter (using "eval:") or with sensu-plugin filter().

**Comment by FlorinAndrei** [comment]
Is there an example of this somewhere in the docs?

**Comment by portertech** [comment]
@FlorinAndrei we finally documented eval filter attributes http://sensuapp.org/docs/latest/filters#filter-eval-attributes the `value` in your case (check history) will be e.g. `[0,0,0,0,1]`, could compare the array items -2 and -1.
