### ISSUE TITLE
You're awesome

### ISSUE THREAD

**Issue by johanek** [sensu/sensu#837]
Hey,

We use sensu on our entire linux estate, and it's awesome - it's really flexible in allowing us to perform the monitoring workflows we want.

Thanks to everyone who has contributed!

:+1:

**Comment by portertech** [comment]
My favourite issue of 2014, by far. :+1:

**Comment by calebhailey** [comment]
I created a new #monitoringlove just for this issue, because this is just great. Best issue ever.

**Comment by portertech** [comment]
Still the best issue ever :+1:
