### ISSUE TITLE
Create an API call for events for a check on all clients

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu#838]
Currently, the events API endpoint allows you to check:
- All events
- All events for a client
- All event on a client for a specific check

I'd like to propose adding an API call for for all checks with a specific check name, such as:

`/events/:check`

My reasoning for this is that it allows the creation of a method called something `def filter_maxed_events` whereby you're able to have the handler bail if there's more than a certain number of events for a particular check. There could be a case for adding this filter event to the sensu-plugins handler, but not sure.

I believe this will help in managing alert storms - if you're able to define a method like this and implement it in your handler if you wish, you can prevent large amounts of issues being created.

**Comment by jaxxstorm** [comment]
I just had a look at the redis schema - I was hoping this would be a relatively simple change to make, but it seems the events are stored in a events:client table, which means I think it'll be a bit tricky..

**Comment by jcmartins** [comment]
Please include a API to do a  aggregation alert check per host, maybe a /aggregates/:hostname/:check/:issued or  show the aggretates in /events/:client/:hostname/ 
exemple: /events/:client/:hostname/:issued

tks
joao

**Comment by portertech** [comment]
@jaxxstorm we could add API query params to filter, e.g. `/events?check=check_http`

Thoughts?

**Comment by jaxxstorm** [comment]
@portertech sorry for the delay. That seems like a great way to go, it also means we can extrapolate it to different params as well. If you can keep it generic then we should be able to check for anything in the JSON string, I can think of many uses for that. 

If you need help contributing for this I'd be happy to (try) chip in, just need an idea of how you want it done

**Comment by calebhailey** [comment]
@jaxxstorm as part of an ongoing issues triage I'm labeling this issue with the Feature flag, which will prompt some renewed discussion around a potential solution. This isn't a commitment that we will implement a new feature, but we will definitely revisit this soon. There are handful of other issues floating around in which we're considering adding support for query parameters to the API, so _something_ should change in the near future. :smile:

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1595 implements this :+1:
