### ISSUE TITLE
sensu-client: No feedback on amqp connection issues

### ISSUE THREAD

**Issue by terrorobe** [sensu/sensu#842]
When the connection between the sensu-client and RabbitMQ is broken the client will emit few if any messages aiding in the remediation of the problem.

Connection refused/no SYN-ACK:
```
{"timestamp":"2015-01-13T17:21:10.480005+0100","level":"warn","message":"reconnecting to transport"}
{"timestamp":"2015-01-13T17:21:15.482465+0100","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-01-13T17:21:20.484431+0100","level":"error","message":"[amqp] Detected TCP connection failure"}
[..]
```

Wrong password:
```
{"timestamp":"2015-01-13T17:19:21.430849+0100","level":"warn","message":"reconnecting to transport"}
```

RabbitMQ not responding after TCP connect (kill -STOP):
```
{"timestamp":"2015-01-13T17:24:59.401125+0100","level":"warn","message":"reconnecting to transport"}
```

Furthermore since AMQP heartbeats are not enabled in the client, if a TCP connection is established but the server can't acknowledge the data the client will happily emit data until the TCP send window on the client is full instead of providing timely feedback.

**Comment by portertech** [comment]
AMQP isn't a great protocol in regards to connection error reporting. Those messages you're seeing logged are provided by the AMQP lib itself. Please have a look at the libs and have at it :+1: 

https://github.com/sensu/sensu-transport
https://github.com/ruby-amqp/amqp

**Comment by terrorobe** [comment]
I'm looking at it from an end-user perspective and as an end-user I don't necessarily care about _where_ the messages come from.

The amqp gem already provides hooks that allow for sufficiently helpful feedback: https://github.com/sensu/sensu-transport/blob/008a95ad83d2832ce394b2dfe8beee0a39cb8e2d/lib/sensu/transport/rabbitmq.rb#L119-128, so the stab on amqp not being great for error reporting is a bit moot ;)

If this is a request to file a bug against sensu-transport I'll happily oblige. Otherwise I want to keep this open for other people to see and maybe I'll cook something up as soon as time/pain permits.

**Comment by shearn89** [comment]
Aha - found this while googling my problem, commenting for SEO.

To add to this, another case where the client log will print `[amqp] Detected TCP connection failure` is when the config file are unreadable: in my case, they were owned by `root` and not `sensu`.

**Comment by nhooey** [comment]
@portertech Any plans to fix this soon?

**Comment by nhooey** [comment]
Does anyone know where the code is that emits this error?

I couldn't find the string in the repositories `sensu/sensu` and `sensu-transport`.

**Comment by nhooey** [comment]
It looks like the string: `Detected TCP connection Failure` no longer exists as of [sensu-transport/commit/00c46be](https://github.com/sensu/sensu-transport/commit/00c46be6c9ca660072c01cce6875ae06ce8e4d53).

Does the actual type of error bubble up in the latest version?

**Comment by nhooey** [comment]
This is where the error is emitted in [ruby-amqp/amqp](https://github.com/ruby-amqp/amqp):
* [lib/amqp/session.rb](https://github.com/ruby-amqp/amqp/blob/c665bdca4bf36db761d7e87f3e2e73244b684e25/lib/amqp/session.rb#L638)

It seems that even that library doesn't provide any specific information, just a callback.

**Comment by nhooey** [comment]
I reported this bug:
* [Emit more specific error than `[amqp] Detected TCP connection failure` #222
](https://github.com/ruby-amqp/amqp/issues/222)

**Comment by nhooey** [comment]
And I submitted this pull request:
* ruby-amqp/amqp#223

**Comment by nhooey** [comment]
@portertech After that pull request gets merged, when could we get a new release of `sensu-client` and `sensu-server` that uses that code?

**Comment by nhooey** [comment]
The maintainer of ruby-amqp/amqp just merged it today. I'll post here when he cuts a new release.

**Comment by portertech** [comment]
@nhooey nice work! I will update sensu-transport to use 1.6.0 (includes your change!)

**Comment by nhooey** [comment]
Great! Thanks @portertech.

Will whatever thing `sensu-client` is a part of get updated to use the new `sensu-transport` as well?

**Comment by calebhailey** [comment]
Tagging this for inclusion in version 0.24. Nice work @nhooey!

**Comment by nhooey** [comment]
Great, thanks Caleb.

I've been reading your replies to issues and you're doing an amazing job explaining priorities and debating proposed solutions. Beat job I've seen in open-source. Keep it up!

Are you a product manager?

**Comment by calebhailey** [comment]
@nhooey among other things, yes. :smile: 

Thanks for the vote of confidence!

**Comment by portertech** [comment]
Opened a PR to use amqp 1.6.0 for the Sensu RabbitMQ transport :+1:

https://github.com/sensu/sensu-transport/pull/29

I'll cut a release and then submit a Core PR bumping the sensu-transport version.
