### ISSUE TITLE
msi package not found

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#851]
I haven't found any msi here:
http://repos.sensuapp.org/

Is the link mentioned here wrong?
http://sensuapp.org/docs/0.16/windows

**Comment by tim-john** [comment]
I've encountered this problem too. When I use my desktop browser (IE, Firefox, Chrome) vist this link, the page printed as a plain XML content. But when I vist it in my Virtualbox Ubuntu Guest (using firefox), it works fine. Still don't know why !!!
By the way, I'm in China, and I wondered if this issue has something to do with region?

**Comment by portertech** [comment]
Because the index file is on S3, you need to specify the full path http://repos.sensuapp.org/index.html
