### ISSUE TITLE
Some one can answer if it's possible or not ?

### ISSUE THREAD

**Issue by mfinkelstine** [sensu/sensu#853]
Hi all , 

How do you monitor your storage/switch's/security hosts/ with sensu ?
I cant install "sensu-client api" on my storage devices for example (netapp/xiv/vmax etc) ?
and the same question goes for client that his security is not allowed me to install "sensu-client api" on  it ?
I hope this time I will get the answer here.
second question when you will have a forum for those kind of questions?

Thanks,
Meir.

**Comment by ohaddal** [comment]
Re-use Nagios plugins and use "source" mostly, i.e;

{
  "checks": {
    "HP29-F5-S2-HEALTH": {
      "handlers": ["default"],
      "command": "/usr/lib/nagios/plugins/check_snmp_hp-procurve.sh snmpcommunity HP29-F5-S2",
      "interval": 60,
      "source": "HP29-F5-S2",
      "standalone": true
    }
  }
}

It doesn't create a client, but events fire off with the source name instead of the client running the check.

#sensu on irc (irc.freenode.net) is mostly used for support.

**Comment by mfinkelstine** [comment]
Thanks ohaddal for your fast replay.

I dont want only to configure the check in cli , 
I want to see it also in the uchiwa dashboard and to see what I'm monitoring.. 

Thanks, 
Meir.

**Comment by ohaddal** [comment]
That's currently not possible, but it's something several people have requested, and it's being worked on.

https://github.com/Yelp/sensu/issues/1

**Comment by calebhailey** [comment]
This was implemented as ["JIT Clients" in Sensu 0.18 (released in May 2015)][1], which we are now starting to call ["Proxy Clients"][2] in the latest versions. 

[1]: https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0180---2015-05-05
[2]: https://sensuapp.org/docs/latest/clients#proxy-clients

**Comment by UnitedMarsupials** [comment]
@calebhailey, could you post a link to a sample implementation of SNMP trap-handler for Sensu -- using the proxy clients?

The ability to feed SNMP traps into our new monitoring system (Sensu is one of the candidates) is a critical requirement for us here.

And not just it, we also want to be able to create [dependencies](https://sensuapp.org/docs/0.16/checks#check-dependencies). For example:

> **if this switch (proxy client) has already alerted (using SNMP trap), do _not_ alert about keep-alives missing from these 15 servers, which are plugged into it.**

Thank you!
