### ISSUE TITLE
Maintain the last submitted state, irrespective of outcome

### ISSUE THREAD

**Issue by warmfusion** [sensu/sensu#860]
Many checks include useful output even when the warning/critical thresholds have not been reached. This information may be useful for users to quickly understand the current working state of their infrastructure.

For example, a check-ram script returns a human friendly message (94% free RAM left) but I only see this value when I'm either watching logs, or running the script manually. While I could setup metrics tools (eg graphite) and setup graphs and so on, it seems redundant when I simply want to know the 'right now' state of a machine, which Sensu+Uchiwa are poised to give me.

It'd be much easier to simply have the last state displayable within the Uchiwa dashboard at all times.

**Comment by brad508** [comment]
I would use this as well. I think it is very important

**Comment by portertech** [comment]
The upcoming 0.18 release includes the latest check result (even if OK) in the client check execution history https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0180---tbd

**Comment by warmfusion** [comment]
As you appear to enjoy a nice gif....
![thumbs up!](http://ak-hdl.buzzfed.com/static/2014-08/29/16/enhanced/webdr10/anigif_enhanced-9754-1409344312-11.gif)
