### ISSUE TITLE
Configuring check extensions

### ISSUE THREAD

**Issue by rmc3** [sensu/sensu#866]
I'm trying to get check extensions working in 0.16.0-1, and I'm having a bit of difficulty. Currently, I have an extension named ```checkping```, for which the check configuration looks like the following:

```
{
  "checks": {
    "checkping": {
      "extension_opts": {
        "host": "127.0.0.1"
      },
      "handlers": [
        "default"
      ],
      "interval": 10,
      "occurrences": 2,
      "refresh": 300,
      "standalone": true
    }
  }
}
```
From my reading of [the source code](https://github.com/sensu/sensu/blob/master/lib/sensu/client.rb#L135), ```Sensu::Client.process_check()``` should check to see if an extension with the name of the defined check exists if the check does not have a ```command``` key, and run the extension if so.  I believe my configuration reflects this logic. However, when I run the Sensu client, it fails to start due to not being able to validate the check configuration. 

```
{"timestamp":"2015-02-19T18:40:31.932782+0000","level":"fatal","message":"check command must be a string","object":{"extension_opts":{"host":"127.0.0.1"},"handlers":["default"],"interval":10,"occurrences":2,"refresh":300,"standalone":true,"name":"checkping"}}
```

This validation error appears to come from [this code in sensu-settings](https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/validators/check.rb#L64).

Thus, my question follows: If all check definitions must have a ```command``` key whose value is a string, how is it possible to have a check definition without a ```command``` key to allow a check extension to be executed?

**Comment by rmc3** [comment]
Alternatively, if this isn't how check extensions are supposed to be configured to be executed, how should they be?

**Comment by rmc3** [comment]
Also, once we figure this out, we need to make sure a description of how check extensions are configured needs to make it in to the official documentation :)

**Comment by rmc3** [comment]
@portertech Any insight into how this is supposed to work?

**Comment by portertech** [comment]
You do not configure check extensions as you would a regular check. Do not create a standard check definition for them, as they exist in the extension themselves, eg. https://github.com/sensu/sensu-community-plugins/blob/master/extensions/checks/system_profile.rb#L32-L40

**Comment by rmc3** [comment]
@portertech Thanks for the clarification! A couple of follow up questions.

1. How can we go about getting this documented on http://sensuapp.org/docs/latest/extensions ? I'm happy to write up some documentation on it if there's some place it should be contributed.

2. I see that in https://github.com/sensu/sensu/pull/697, you said the following:

> I am concern that this may cause further confusion, blurring the line between the extension API, and the normal check definition + plugin configuration. Extensions are intended to be self contained, the definition() method should contain the setting hash required for the extension to be referenced. 

Why is it important that extension checks and plugin checks be configured in different ways? This increases configuration complexity and decreases the flexibility of check extensions. One of the primary advantages of check extensions for us is that they do not fork off new processes. This highly advantageous for checks that need to be executed many times per minute with different configurations, as running hundreds of checks per minutes can easily fork bomb a system. Examples of this are ping checks which need to ping hundreds of different hosts per minute, or SNMP metric checks which need to pull SNMP statistics from hundreds of devices per minute. 

Disallowing a check extension from being configured to run in the same manner as a non-extension check prevents us from using check extensions to solve this problem. Using the ping extension as an example, the only solution I see involves writing quite a bit of extra logic in the extension as follows:

- Have the definition() method read a list of hosts and all parameters that are needed to run the ping check for them.
- Write logic to manage scheduling and running the ping checks within the extension.

This logic is, to my mind, extraneous and duplicates logic already provided by Sensu core's configuration and scheduling facilities. This is extra complexity that would make managing a Sensu installation much more difficult.

**Comment by rmc3** [comment]
A followup on my first question, @cloakedcode has pointed me to sensu-docs. I've opened https://github.com/sensu/sensu-docs/issues/189 to track documentation of check extensions.

**Comment by Igorshp** [comment]
@portertech How would one go about reusing extension code for multiple checks?

similar to how we supply one script with different parameters at the moment

**Comment by willejs** [comment]
@portertech I think @rmc3 has a really good point in the above. can you address please?
We too would like to define multiple checks with different configurations via the standard check definition json files using the same extension.
Having the check definition in the extension, and using configuration files lacks flexibility and breaks convention of non extension based checks?

**Comment by rmc3** [comment]
From our conversation in #sensu IRC today, I'm working on a PR that will

1. Allow check extensions to be executed multiple times with differing configurations based on the presence of an ```extension``` key with the extension name as the value of the key, and

2. Still allow check extension to be executed as they are presently.

https://gist.github.com/rmc3/b9673da45692cbd0f4c8 describes a pattern of check extensions that this should permit.

**Comment by willejs** [comment]
:+1:
