### ISSUE TITLE
Sensu client socket leak

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu#869]
When the Sensu client cannot connect to the transport (RabbitMQ) it looks like the client may be spinning up a thread for every reconnection attempt -- this eventually causes the client to run out of file handles.  When connectivity is restart, each unique thread will attempt to connect back to Rabbitmq.  This causes a a massive DDoS against RabbitMQ due to the inflated number of threads from each Sensu client.

This is present in Sensu 0.16.0

**Comment by xyntrix** [comment]
Trying to get more data on this -- such an lsof output.  ..and trying to reproduce in the lab.

**Comment by xyntrix** [comment]
A snippet from one of the clients, where we see multiple concurrent TCP connection failures and then multiple reconnects.  Perhaps this is one connection per eventmachine threads?  {"timestamp":"2015-02-23T11:45:32.177980-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.178241-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.178453-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.178668-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.186855-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.187112-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.193783-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.204504-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.215736-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.254715-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.279983-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.290878-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.291990-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.391041-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.408326-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.411900-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.422481-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.432011-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.454077-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.454420-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.461744-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.482386-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.490245-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.494676-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.499076-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.595754-0700","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-02-23T11:45:32.596452-0700","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-02-23T11:45:32.596587-0700","level":"warn","message":"reconnecting to transport"}

**Comment by portertech** [comment]
Thank you @xyntrix for reporting this, we will investigate this afternoon.

**Comment by xyntrix** [comment]
We weren't able to reproduce this in our lab, and thus far have only seen this once (across a handful of hosts).  In our case, we have some network gear that prevents too many new TCP sessions from being opened at once to a single target. We had an event where several thousand clients were attempting to reconnect to RabbitMQ concurrently. I suspect this mangled packets in such a destructive way that even if there is a defect here, the chance of it occurring is super low.

**Comment by portertech** [comment]
@xyntrix I suspect that the open file limit is due to the SSL certificates being read on every transport reconnect https://github.com/sensu/sensu-transport/blob/master/lib/sensu/transport/rabbitmq.rb#L117 unfortunately, the code is all cpp :(

**Comment by ethergreg** [comment]
I have been hit hard by this issue. After a network interruption the windows clients were coming in with up to 300 TCP connections each putting sensu-server in a state where it could not communicate with redis or rabbitmq. This helps a lot: 
/sbin/iptables -A INPUT -p tcp --syn --dport 5673 -m connlimit --connlimit-above 50 --connlimit-mask 32 -j REJECT --reject-with tcp-reset
but rejecting the connections from the windows clients seems to have a snowballing effect and they pretty much live in a world of keepalive alert.

**Comment by xyntrix** [comment]
I haven't seen this issue since moving to Sensu >= 0.20.x.    If no one else is experiencing this, I think this is safe to close.

**Comment by chiriaev** [comment]
Guys, Hi. It's fixed in "0.21.0". Regards, Andrei

**Comment by calebhailey** [comment]
Thanks @xyntrix. Let us know if you see this pop up again.
