### ISSUE TITLE
How do you silent a status of "OK" on a particular check?

### ISSUE THREAD

**Issue by millernp** [sensu/sensu#890]
Running Sensu 0.12.6 and have the need to silent just an OK status of a check.  The check notification is sending 90 or so a day and want to eliminate just the OK status but not any of the other warnings or notifications from this check.  

Appreciate any help with this.

**Comment by portertech** [comment]
@millernp Set the following in your event handler definition:

```
"severities": ["warning", "critical", "unknown"] 
```

Sounds like you may have "type": "metric" in your check definition, you may not need this.

**Comment by millernp** [comment]
Hi Portertech,

I have "type": "pipe" in the mailer handler.  I changed the severities to the ones you suggested above.  If that sounds fine, I will let you know if that corrects issue.  Thanks brother.

**Comment by portertech** [comment]
@millernp I'm going to close this, as I'm assuming this worked for you :+1:
