### ISSUE TITLE
redis 'reconnect_on_error' config option

### ISSUE THREAD

**Issue by bimlendu** [sensu/sensu#898]
In the latest version. 0.17 , redis and transport got a new config option 'reconnect_on_error'. But in the sensu code, I am unable to see that setting for redis.

https://github.com/sensu/sensu/blob/master/lib/sensu/daemon.rb#L210-L215 . This block should have a conditionals like https://github.com/sensu/sensu/blob/master/lib/sensu/daemon.rb#L185-L191 for transport.

Thanks.

**Comment by portertech** [comment]
@bimlendu it's used in the Redis client itself. Passed through the connection settings.
