### ISSUE TITLE
Client API checks - adding checks - future releases

### ISSUE THREAD

**Issue by david-strejc** [sensu/sensu#900]
Dear authors,

do you plan to add Sensu API calls to add checks on the fly without restarting server or client?

Anyway Sensu is what I was looking for ;-) Nagios never more.

**Comment by jtblin** [comment]
+1. It'd be great if we could post to the API to create checks automatically rather than writing config. The new checks could be either added to the config directory as separate json files or stored in redis similarly to `stashes`. With the http check plugin, sensu could be a Pingdom replacement. 
Not too sure how reloading could be done without restarting the server though as it runs in a different process than the API.

I wouldn't mind sending a PR if you'd be willing to consider this. If ok, would you have suggestions re: config dir vs redis, server reload?

**Comment by Qwertyn** [comment]
+1 for such feature.

**Comment by jtblin** [comment]
I'm just using Sensu with the server, api and client on the same box at the moment. Obviously writing on the disk cannot work with a distributed setup as the API can be on a different machine than the server(s) so it's just a hack. Actually even writing to redis wouldn't work unless you have a way to restart the servers remotely so this feature is probably really hard to implement properly. That said, modifying the API to do that wasn't very hard, I'll push to my fork later.

**Comment by mag009** [comment]
:+1: I have not seen that thread (so I opened one recently) 
https://github.com/sensu/sensu/issues/935

**Comment by mag009** [comment]
any eta when this feature will be released ? Its a must feature in my setup.

**Comment by david-strejc** [comment]
It requires a bit of logic in my opinion.

Clients will have to pull down configuration and in best case plugins from sensu server where they will be stored in Redis or on disk.

**Comment by david-strejc** [comment]
We think about having consul for this specific solution - we will add check results into sensu client via 3030 port of sensu-client.

It is little bit crazy, but it can work.

**Comment by calebhailey** [comment]
@david-strejc hi there! My apologies for the radio silence on our end. 

It looks like https://github.com/sensu/sensu/issues/935 is a duplicate or very similar to this issue, which I have presumptuously tagged for potential inclusion into 0.24. Make sure to check on #935 for updates. :smile:

**Comment by calebhailey** [comment]
Removing this from the 0.24 release for reasons mentioned in PR #935. We'll keep this issue open for ongoing conversation related to overall API improvements in #1220

**Comment by portertech** [comment]
We do not plan to introduce/implement this feature with Sensu's current design. Sensu Inc. is currently working on Sensu's next generation architecture, for 2.0, which will support check creation and check dependency management via its API. Closing this on :+1:
