### ISSUE TITLE
Cannot Pull Sensu Install 

### ISSUE THREAD

**Issue by millernp** [sensu/sensu#903]
Hi,
 
Rebuilding a Sensu server and cannot pull Sensu from either apt-get or from instructions in online Sensu docs (http://sensuapp.org/docs/0.16/packages), I get access is denied.  Several days ago, I successfully pulled from apt-get from Ubuntu CLI.  Can someone shed some light on  this issue?  If beta just closed, when can we expect bits will be avail?

Also, can you point me to the new links for agent, server and dashboard?

Thanks,

**Comment by millernp** [comment]
I also tried signing up for Enterprise plan, just to go through the license agreement and to end up "we will contract you" early last week and have heard nothing.  Would appreciate some help on all of this or a referral to a source that can answer these questions if I am in the wrong queue.

Thanks,

**Comment by portertech** [comment]
@millernp Support for the Sensu Enterprise beta was through the helpdesk. The Sensu Core repositories do not use authentication, only the enterprise repositories do. The Sensu installation guide has seen some big improvements http://sensuapp.org/docs/latest/install-repositories If you have questions about Sensu Enterprise, please feel free to create a ticket at https://helpdesk.sensuapp.com
