### ISSUE TITLE
Redis reconnect_on_error setting not working

### ISSUE THREAD

**Issue by davent** [sensu/sensu#908]
As mentioned in this PR https://github.com/sensu/sensu/pull/875, when Redis throws an error Sensu Server will shutdown. This is particularly annoying when using AWS ElastiCache as a HA Alternative to standalone Redis. When an ElastiCache node is promoted/demoted (either manually or due to error) the TCP connection to the cluster is maintained to the original master node. As this node is now a read-only slave the following happens:

```
{"timestamp":"2015-03-25T14:23:44.611087+0000","level":"fatal","message":"redis connection error","error":"Redis server returned error code: READONLY You can't write against a read only slave."}
{"timestamp":"2015-03-25T14:23:44.611231+0000","level":"warn","message":"stopping"}
{"timestamp":"2015-03-25T14:23:44.611340+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-03-25T14:23:44.611607+0000","level":"warn","message":"resigning as master"}
{"timestamp":"2015-03-25T14:23:44.611684+0000","level":"info","message":"completing event handling in progress","handling_event_count":0}
{"timestamp":"2015-03-25T14:23:45.112436+0000","level":"warn","message":"stopping reactor"}
``` 

My Redis config uses the new reconnect_on_error flag but this does not appear to work in this instance.

```
"redis": {
    "host": "xxx.yyy.ng.0001.usw2.cache.amazonaws.com",
    "port": 6379,
    "reconnect_on_error": true
  },
```

**Comment by lenfree** [comment]
@davent this PR https://github.com/sensu/sensu/pull/899 should fix this I believe.

**Comment by davent** [comment]
@lenfree I believe the PR relates to the transport. My issue is specific to the Redis connector

**Comment by lenfree** [comment]
Ah yes you're right :)

**Comment by davent** [comment]
This PR solves this problem: https://github.com/sensu/sensu/pull/920

**Comment by portertech** [comment]
This functionality is now in the Redis client that Sensu uses (em-redis-unified). Sensu 0.17.x includes this feature.

**Comment by davent** [comment]
This was tested with 0.17.x and the new em-redis-unified. In this situation I described it does not force a reconnect

**Comment by portertech** [comment]
The code change https://github.com/portertech/em-redis/commit/17372db6375bdeb61c26f20c6b181a61d850eafa

**Comment by davent** [comment]
I know, that is the code I was testing that did not work in the situation I described.

**Comment by portertech** [comment]
@davent thank you :+1: Your log output suggests that the on_error callback is still being called, I was unable to reproduce myself, but I did not use ElastiCache when testing.
