### ISSUE TITLE
Having a sensu-client named "client" generates an error on sensu-API

### ISSUE THREAD

**Issue by epierotto** [sensu/sensu#912]
Testing the sensu-client config I realized that having a client with the name "client" generates an error

[Uchiwa #287](https://github.com/sensu/uchiwa/issues/287)

```
# curl -I http://10.73.0.10:4567/clients/client
HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Content-Length: 115
Connection: keep-alive
Server: thin 1.5.0 codename Knife

# curl -I http://10.73.0.10:4567/clients/client/history
HTTP/1.1 404 Not Found
Content-Type: application/json;charset=utf-8
Content-Length: 0
Connection: keep-alive
```

It is not a major issue, just a heads up.

**Comment by portertech** [comment]
@epierotto thank you for reporting! Must have something to do with the Sinatra route regex.

@amdprophet can you look into this?
