### ISSUE TITLE
[ SENSU && Rabbit ] : Timer based re-connection

### ISSUE THREAD

**Issue by chiriaev** [sensu/sensu#930]
Guys, Hi. Would a SENSU client-related feature to re-set/re-connect your Rabbit transport every configurable once in a while, makes sense? One use-case would be to re-balance client connections over a VIP faced Rabbit cluster.

Opinions?

Regards, Andrei

**Comment by portertech** [comment]
This is interesting, maybe create an issue on https://github.com/sensu/sensu-transport with a RabbitMQ or transport configuration example?

**Comment by chiriaev** [comment]
Hi, Sean. @ https://github.com/sensu/sensu-transport/issues/11 Regards, Andrei

**Comment by calebhailey** [comment]
Closing in favor of https://github.com/sensu/sensu-transport/issues/11 which we'll revisit soon.
