### ISSUE TITLE
Unable to delete a check that no longer needed

### ISSUE THREAD

**Issue by chrisduong** [sensu/sensu#937]
Hi,

I added a check, lets say it is located /etc/sensu/conf.d/checks/check_redis.json.
Later I want to replace this check with another check. I deleted the `check_redis.json`.  Restart sensu-server and all of its services (rabbitmq, redis). But the check is still there:

```bash
# sensu-cli check list
-------
command:  check-redis-ping.rb
standalone:  true
handlers:  ["default"]
interval:  30
name:  redis_availibility
```
I even stop Sensu server and then went to redis console, delete the key 

```
del execution:backup:redis_availibility
```
But after the Sensu server start. the key appear again.
Please tell me how can I delete the check. I've gone through all Sensu docs. Thanks a ton.

**Comment by chrisduong** [comment]
Hi,

I restarted sensu-api service and then sensu-server. The checks are gone. Please feel free to close the ticket.

**Comment by chrisduong** [comment]
By the way, I have to delete the check 'key' in 'redis' server manually.

**Comment by portertech** [comment]
The check data in redis will persist, to remain as part of the client check execution history.

**Comment by adfel70** [comment]
Hi, I am having the same issue:
I try to delete a check, so I removed the keys from Redis but the check keeps "coming back" about 10 sec after... Restarting the Sensu api and sensu Server did not help.
Any advice?
