### ISSUE TITLE
Stash API - Record current state of event for later comparison

### ISSUE THREAD

**Issue by warmfusion** [sensu/sensu#940]
I'd like to be able to submit the current state of an event to the Stash API such that the decision on whether to handle a given new event can be made based as a comparison to the stored stash.
# use case

I want to stash a WARNING event about my HAProxy pool being < 100%, (nodes out for some work) but I'd REALLY want to know if it goes critical before the maintenance window has closed.

With a Stash at the moment; I can specify an expected time to resolution, but then if it dies overnight i'll not know. 

Alternatively I can not stash it, but then put up with repeated notifications about the 'warning' state of the system.
## Handlers/Filters

The Event, and its Stashed event could be (optionally) sent to handlers (through filters) so that they can decide whether to handle the event based on some complex conditional processing.

**Comment by calebhailey** [comment]
Rereading through some old issues here and I think this is related to #1219. Tagging this for consideration in that redesign discussion.

**Comment by portertech** [comment]
Closing this issue, as most it can be accomplished via a mixture of existing primitives and filter/handler extensions.
