### ISSUE TITLE
Can not see checks on the Clients page

### ISSUE THREAD

**Issue by jtyr** [sensu/sensu#941]
I have just upgraded to Sensu 0.18 and I can not see checks on the Clients page. The notifications are sent by `write_sensu` plugin from Collectd (see this page for more details: http://www.kibinlabs.com/collectd-sensu-write-plugin/). I can only see check results on the Alerts page if the check state is Warning or Critical. If the check is in any state (warning, critical, ok), it doesn't show in the Clients page. All works just fine if I roll back to 0.17.2.

Do you know what has changed between 0.17.2 and 0.18 what could cause this problem?

**Comment by portertech** [comment]
Does the Uchiwa log show any query errors for client history?

**Comment by jtyr** [comment]
No, there is no error in the log file.

**Comment by portertech** [comment]
Can you query the client history directly, using the API `/clients/:client_name/history`?

**Comment by jtyr** [comment]
Please can you specify full URL?

**Comment by jtyr** [comment]
It did not work because of the ":" in front of the client name. This is the response for the http://my_sensu:4567/clients/my_host1/history:

```
[{"check":"keepalive","history":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"last_execution":1431036339,"last_status":0,"last_result":{"thresholds":{"warning":120,"critical":180},"name":"keepalive","issued":1431036339,"executed":1431036339,"output":"Keepalive sent from client 4 seconds ago","status":0}}]
```

I can see only the keepalive check which is sent by Sensu by default. But there are no check results coming from Collectd. Although I can see results in Redis (timestamp changes every 10 secs):

```
redis 127.0.0.1:6379> get result:my_host1:df-root.percent_bytes-used
"{\"status\":0,\"timestamp\":1431036509,\"handlers\":[\"default\"],\"collectd_plugin\":\"df\",\"collectd_plugin_type\":\"percent_bytes\",\"collectd_plugin_instance\":\"root\",\"collectd_plugin_type_instance\":\"used\",\"name\":\"df-root.percent_bytes-used\",\"output\":\"OK - Host my_host1, plugin df (instance root) type percent_bytes (instance used): All data sources are within range again. Current value of \\\"value\\\" is 8.474238.\",\"DataSource\":\"value\",\"current_value\":\"8.47423840\",\"issued\":1431036509}"
redis 127.0.0.1:6379> get result:my_host1:df-root.percent_bytes-used
"{\"status\":0,\"timestamp\":1431036519,\"handlers\":[\"default\"],\"collectd_plugin\":\"df\",\"collectd_plugin_type\":\"percent_bytes\",\"collectd_plugin_instance\":\"root\",\"collectd_plugin_type_instance\":\"used\",\"name\":\"df-root.percent_bytes-used\",\"output\":\"OK - Host my_host1, plugin df (instance root) type percent_bytes (instance used): All data sources are within range again. Current value of \\\"value\\\" is 8.473781.\",\"DataSource\":\"value\",\"current_value\":\"8.47378063\",\"issued\":1431036519}"
```

**Comment by portertech** [comment]
Does the check exist in "result:my_host1"? https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L360

**Comment by jtyr** [comment]
Yes, I can see the checks there:

```
redis 127.0.0.1:6379> smembers result:my_host1
1) "processes.ps_state-zombies"
2) "df-root.percent_bytes-used"
3) "fhcount.percent-used"
4) "tcpconns-22-local.tcp_connections-LISTEN"
5) "keepalive"
6) "memory.percent-free"
7) "load.load-relative"
8) "swap.percent-used"
9) "df-root.percent_inodes-free"
```

**Comment by jtyr** [comment]
I can also see the history records:

```
redis 127.0.0.1:6379> lrange history:my_host1:df-root.percent_bytes-used -21 -1
 1) "0"
 2) "0"
 3) "0"
 4) "0"
 5) "0"
 6) "0"
 7) "0"
 8) "0"
 9) "0"
10) "0"
11) "0"
12) "0"
13) "0"
14) "0"
15) "0"
16) "0"
17) "0"
18) "0"
19) "0"
20) "0"
21) "0"
```

And I can also the result:

```
redis 127.0.0.1:6379> get result:my_host1:df-root.percent_bytes-used
"{\"status\":0,\"timestamp\":1431086309,\"handlers\":[\"default\"],\"collectd_plugin\":\"df\",\"collectd_plugin_type\":\"percent_bytes\",\"collectd_plugin_instance\":\"root\",\"collectd_plugin_type_instance\":\"used\",\"name\":\"df-root.percent_bytes-used\",\"output\":\"OK - Host my_host1, plugin df (instance root) type percent_bytes (instance used): All data sources are within range again. Current value of \\\"value\\\" is 8.303626.\",\"DataSource\":\"value\",\"current_value\":\"8.30362606\",\"issued\":1431086309}"
```

I believe that the problem is that there is no `executed` key in the result JSON so the final item is not created:
https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L371:L379

**Comment by portertech** [comment]
@jtyr I just pushed a PR with a possible solution https://github.com/sensu/sensu/pull/943

**Comment by jtyr** [comment]
I have applied your patch on `lib/sensu/client/socket.rb`, restarted all Sensu services and I still can not see all the checks on the Clients page. There is still only the `keepalive` check visible. The API call for clients history did not change either - only the history for `keepalive` check is returned.

**Comment by portertech** [comment]
This should have the equivalent effect of removing `|| last_execution.nil?` from the API endpoint. Have the checks had new executions since you checked?

**Comment by jtyr** [comment]
Aaaaah! I was checking it on a host were I did not apply the patch. It works just fine for the host where the patch was applied. Thanks for fixing this!

Are you going to address this issue in a new minor release (0.18.1) now?

**Comment by portertech** [comment]
Welcome! :+1: I will be pushing 0.18.1 this evening.

**Comment by portertech** [comment]
0.18.1-1 is in the repositories \o/
