### ISSUE TITLE
Unable to delete a client.

### ISSUE THREAD

**Issue by bimlendu** [sensu/sensu#942]
Hi,

Facing a weird issue here. I just want to delete a client from sensu, but I am unable to. I have tried the following steps so far. The client doesn't have sensu-client running.

1. Deleting from uchiwa dashboard. Client re-appears with all checks listed.
2. Uchiwa reads sensu-api, so tried deleting from the api directly. curl -X DELETE http://sensu.api/clients/client. Client reappears with all checks listed.
3. Deleted client key from redis. It reappears with all checks. Same after issuing FLUSHALL.
4. Deleted client queue from rabbitmq. Client reappears, but this time only keepalive check is showing up.

What else can I do?

My setup has two sensu nodes, with server/api/uchiwa running. All these services are under load balancers and talk to each other via load balancers. RabbitMQ is also HA with mirrored queues, and for redis, we use AWS elasticache.

**Comment by portertech** [comment]
Is a `sensu-client` still running somewhere, using that client name? It will continue to register itself.

**Comment by bimlendu** [comment]
I have enabled elb access logging to see which clients connect to the rabbitmq. I will check if some unwanted client is using this client name.

One question, afaik, all client info on uchiwa comes from the client.json files present on each sensu-client. So one can set any key/value pair as one wishes. At the same time one can also set address or name to some in-correct value, probably by mistake. Is there any way to make address take client ip by default or client name take hostname by default and not from the client config json files. This can help identify clients in situations like these.

I have tried this as well:

Enabled sensu on the client box. Added some random checks.  Checks re-appear in uchiwa. Stopped sensu-client. Removed client from uchiwa. Client re-appears with keepalive showing up as green.

**Comment by bimlendu** [comment]
Have checked rabbitmq logs for past few hours. Only valid clients connect to it and all are accounted for in uchiwa. So I can confirm that no active `sensu-client` is using this client name.

**Comment by portertech** [comment]
This PR fixes the API routes that use regular expressions https://github.com/sensu/sensu/pull/945 I am cutting Sensu 0.18.1 with these changes.

**Comment by portertech** [comment]
Try upgrading to 0.18.1 :+1:

**Comment by bimlendu** [comment]
Upgrading to 0.18.1 also doesn't fix the issue for me. The client still re-appears for me.

I am planning to remove the loadbalancers from the setup and have the sensu components talk to each other directly. Not sure if it will help though.

Anything else I can try?

**Comment by portertech** [comment]
Did the API get restarted after upgrading to 0.18.1-1? Does the API log show the client getting deleted? Does the Sensu server log (w/ debug) show a keepalive for the client in question?

**Comment by bimlendu** [comment]
Yes, api and server was restarted after the upgrade.

API does show the client being deleted.

```
{"timestamp":"2015-05-12T21:07:02.968379+0000","level":"info","message":"DELETE /clients/ghost-client","remote_address":"*.*.*.*","user_agent":"Go 1.1 package http","request_method":"DELETE","request_uri":"/clients/ghost-client","request_body":""}
{"timestamp":"2015-05-12T21:07:07.974771+0000","level":"info","message":"deleting client","client":{"name":"ghost-client","address":"*.*.*.*","subscriptions":["base","webcontainer"],"version":"0.16.0","timestamp":1431464808}}
```

Sensu server log does show keepalives from the client.

```
{"timestamp":"2015-05-12T21:04:38.237599+0000","level":"debug","message":"publishing check result","payload":{"client":"ghost-client","check":{"thresholds":{"warning":120,"critical":180},"name":"keepalive","issued":1431464678,"executed":1431464678,"output":"Keepalive sent from client 10 seconds ago","status":0}}}
{"timestamp":"2015-05-12T21:04:38.253329+0000","level":"debug","message":"received result","result":{"client":"ghost-client","check":{"thresholds":{"warning":120,"critical":180},"name":"keepalive","issued":1431464678,"executed":1431464678,"output":"Keepalive sent from client 10 seconds ago","status":0}}}
```

**Comment by portertech** [comment]
And there are no keepalives (not referring to keepalive events) for the "ghost-client", that could be re-registering the client?

**Comment by bimlendu** [comment]
No, there aren't any keepalives for the 'ghost-client' that could re-register the client.

**Comment by portertech** [comment]
@bimlendu your example keepalive check result states otherwise, "Keepalive sent from client 10 seconds ago", which would suggest that there are keepalives for the client being sent by something.

**Comment by bimlendu** [comment]
Yeah this is confusing me too. 

Keepalives are sent by the sensu-client to the transport/rabbitmq.. right?. But I have checked rabbitmq logs for the past few hours again and whichever client connects to it are accounted for in uchiwa, other than this ghost-client.

Whatever address the keepalive check for this client is reporting, there is no sensu-client running there.

Also, the clients create a queue in rabbitmq, but there is no queue for this client there. 

If I delete the keepalives queue in rabbitmq, will it help?

I don't have redis logs as I am using AWS Elasticache for it.

**Comment by portertech** [comment]
Are you using a RabbitMQ cluster? If so, is the cluster healthy? Are all nodes reporting the same info?

**Comment by bimlendu** [comment]
Yeah I am using RabbitMQ cluster. The cluster is healthy and all nodes in the cluster are ok and have the same info. 

And I am able to delete other clients. Just  not able to delete this client.

When I delete other clients, their keys in redis gets deleted, as per https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L394, but for this ghost-client, this doesn't happen. A `set` call is made again, which adds the client back.

Monitoring the redis gives this, while deleting two clients, a normal client that gets removed successfully and this ghost client.

```
1431533456.887210 [0 *.*.*.*:47686] "srem" "clients" "ghost-client"
1431533456.887244 [0 *.*.*.*:47686] "srem" "clients" "normal-client"
1431533456.889122 [0 *.*.*.*:47686] "del" "client:ghost-client"
1431533456.889140 [0 *.*.*.*:47686] "del" "events:ghost-client"
1431533456.889154 [0 *.*.*.*:47686] "smembers" "result:ghost-client"
1431533456.889172 [0 *.*.*.*:47686] "del" "client:normal-client"
1431533456.889183 [0 *.*.*.*:47686] "del" "events:normal-client"
1431533456.889193 [0 *.*.*.*:47686] "smembers" "result:normal-client"
1431533456.891503 [0 *.*.*.*:47686] "del" "result:ghost-client:keepalive"
1431533456.891527 [0 *.*.*.*:47686] "del" "history:ghost-client:keepalive"
1431533456.891541 [0 *.*.*.*:47686] "del" "result:ghost-client"
1431533456.891704 [0 *.*.*.*:47686] "del" "result:normal-client:keepalive"
1431533456.891716 [0 *.*.*.*:47686] "del" "history:normal-client:keepalive"
1431533456.891752 [0 *.*.*.*:47686] "del" "result:normal-client"
1431533472.647609 [0 *.*.*.*:47614] "set" "client:ghost-client" "{\"name\":\"ghost-client\",\"address\":\"*.*.*.*\",\"subscriptions\":[\"base\",\"webcontainer\"],\"version\":\"0.16.0\",\"timestamp\":1431533472}"
1431533472.649445 [0 *.*.*.*:47614] "sadd" "clients" "ghost-client"
1431533475.858955 [0 *.*.*.*:37545] "get" "client:ghost-client"
1431533475.871225 [0 *.*.*.*:47686] "hgetall" "events:ghost-client"
1431533477.515864 [0 *.*.*.*:37545] "get" "client:ghost-client"
```

**Comment by portertech** [comment]
There are only two places where that set can happen: the client keepalive consumer, and the API POST /clients

```
portertech@d2o:~/projects/sensu/sensu (master=)$ grep -R 'set("client' lib/*
lib/sensu/server/process.rb:        @redis.set("client:#{client[:name]}", MultiJson.dump(client)) do
lib/sensu/api/process.rb:          settings.redis.set("client:#{data[:name]}", MultiJson.dump(data)) do
```

Therefore, you must have a client (or another producer) publishing client keepalives, using that client name. You can toggle on debug logging for the Sensu server, using SIGTRAP.

You may want to: `tail -f /var/log/sensu/sensu-server.log | grep keepalive` (after enabling debug logging)

**Comment by portertech** [comment]
@bimlendu did you end up resolving the issue? Rogue Sensu client with the details?

**Comment by bimlendu** [comment]
@portertech no I couldn't resolve the issue. I will be confirming this in the coming days by changing access credentials for rabbitmq or using a different vhost. But that will take some time. I have quite a number of hosts, so checking manually is something I don't want to do.

Anyway, I am closing this issue. I'll update this issue, once I have resolved this issue. Thanks a lot for your help. :+1:

**Comment by frodeb** [comment]
Deleting clients via sensu-cli instead of curl to API solved this for me. github .com /agent462/sensu-cli
