### ISSUE TITLE
Sensu-client receive checks from multiple Sensu-server (vhosts)

### ISSUE THREAD

**Issue by khuongdp** [sensu/sensu#949]
Hi

Is it possible for the sensu-client to receive checks from multiple sensu-server through same RabbitMQ with different vhosts.

User case:
We have 2 teams (ops and developers). All ops related checks is defined on one sensu-server and developer checks is defined on another. We want to use the same rabbitmq instance so we don't want to install another rabbitmq or open more ports but we would like to use different vhost e.g. /sensu-ops and /sensu-developers. Each team have theirs own dashboard that query it own sensu-api

**Comment by portertech** [comment]
Sensu components can only connect to a single transport at a time. The RabbitMQ Sensu transport does not support using multiple connections with different options (e.g. vhost). Sorry.

You may want to look for ways the ops and dev teams can coexist, particularly with the monitoring system, many benefits :+1:

**Comment by khuongdp** [comment]
We have solved it in another way. We are using 2x (sensu-server/sensu-api/rabbitmq/redis/uchiwa). Our /etc/init.d/sensu-service now support multiple conf defined in
/etc/sensu/clients/sensu01 /etc/sensu/clients/sensu02 ...

/etc/init.d/sensu-client start 

now scan the /etc/sensu/clients/ for configuration and start multiple instances up. We also have to use different ports:

  "client": {
    "socket": {
      "bind": "127.0.0.1",
      "port": 3031
    }

**Comment by portertech** [comment]
Neat, glad you found a solution that works for you :+1:
