### ISSUE TITLE
All handlers: Unexpected error: Broken pipe

### ISSUE THREAD

**Issue by khuongdp** [sensu/sensu#957]
We are using Sensu with almost 2k checks with no problem but now we have some strange issue. If we add batch1 (50 more checks) or batch2 (50 more checks) it is working fine. But we if add both batch1 and batch2 (100 more checks) we get following errors:

- All checks executed by sensu-client is returning status 127 (only the sensu-client instance on the sensu-server)
- In the sensu-server log all handlers is broken:

{"timestamp":"2015-05-22T14:10:14.452618+0200","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/debug.rb","name":"debug"},"output":["Unexpected error: Broken pipe"]}
{"timestamp":"2015-05-22T14:10:14.454732+0200","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/notification/mailer.rb","name":"mailer"},"output":["Unexpected error: Broken pipe"]}
{"timestamp":"2015-05-22T14:10:14.454905+0200","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/notification/logevent.rb","name":"logevent"},"output":["Unexpected error: Broken pipe"]}

All checks should be json valid. (checked with python -m json.too) and if we add batch1 or batch2 it is working fine.

Other log files I should look at to find the problem?

**Comment by portertech** [comment]
Perhaps the process ulimit? Unable to spawn additional processes?

**Comment by portertech** [comment]
My money is on the limit, /proc/<pid>/limits

**Comment by khuongdp** [comment]
I try to increase the limit for sensu user (nofile:50000, nproc: 100000):

sensu    30522 12.7  0.7 1467500 54888 ?       Sl   15:10   1:59 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-server -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-server.pid -l /var/log/sensu/sensu-server.log -L info
root@prod-monitor01-server01:/etc/sensu/conf.d/checks# cat /proc/30522/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             100000               100000               processes
Max open files            50000                50000                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       59753                59753                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

and one of the handlers:
root@prod-monitor01-server01:/etc/sensu/conf.d/checks# mypid=`ps aux | grep /etc/sensu/handlers/notification/mailer.rb | head -1 | awk '{print $2}'`; cat /proc/${mypid}/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             100000               100000               processes
Max open files            50000                50000                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       59753                59753                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

but still getting the error

**Comment by khuongdp** [comment]
We still have this issue. Open files and number of user processes has been increased for the sensu user.

If i run a strace on the sensu-client process I get this:
[pid 24218] getrlimit(RLIMIT_NOFILE, {rlim_cur=100000, rlim_max=100000}) = 0
[pid 24218] getrlimit(RLIMIT_NOFILE, {rlim_cur=100000, rlim_max=100000}) = 0
[pid 24218] getcwd("/", 200)            = 2
[pid 24218] getcwd("/", 200)            = 2
[pid 24218] chdir("/")                  = 0
[pid 24218] vfork(Process 25661 attached
 <unfinished ...>
[pid 25661] setpgid(0, 0)               = 0
[pid 25661] dup2(13, 1)                 = 1
[pid 25661] dup2(13, 2)                 = 2
[pid 25661] execve("/opt/sensu/embedded/bin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabb"...], [/* 33 vars */]) = -1 ENOENT (No such file or directory)
[pid 25661] execve("/usr/local/sbin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabb"...], [/* 33 vars */]) = -1 ENOENT (No such file or directory)
[pid 25661] execve("/usr/local/bin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabb"...], [/* 33 vars */]) = -1 ENOENT (No such file or directory)
[pid 25661] execve("/sbin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabb"...], [/* 33 vars */]) = -1 ENOENT (No such file or directory)
[pid 25661] execve("/bin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabb"...], [/* 33 vars */]) = -1 E2BIG (Argument list too long)
[pid 25661] exit_group(127)             = ?
[pid 25661] +++ exited with 127 +++

Is it because we have too many files in /etc/sensu/conf.d/checks

**Comment by portertech** [comment]
```
[pid 25661] execve("/opt/sensu/embedded/bin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabb"...], [/* 33 vars /]) = -1 ENOENT (No such file or directory)
```

Do the files exist with the appropriate permissions? Looks like process setup is working until ` ENOENT (No such file or directory)`.

**Comment by portertech** [comment]
Is a batch possibly merging with the existing definitions, setting the wrong attributes values?

**Comment by khuongdp** [comment]
If I have below about 2000 checks on the sensu-server then all sensu-client checks on the same server is working fine but when I get over about 2000 checks then all sensu-client checks on the same server is broken. See strace.

I think when you get "No such file or directory" from the strace It tried to find "sh" in different path and then it found it in the end. The files exist and have the right permissions because everything is working when I get below about 2000 checks.

I do not think it is a batch merging issue. I used Chef to create dummy checks

1.upto(100) do |i|
  sensu_check "mytest#{i}" do
    command "true"
    handlers ["default"]
    subscribers ["some.server"]
    interval 60
    additional(:notification => "mytest#{i}", :occurrences => 2)
  end
end

And when I get high enough I get the errors mention in the first post.

Should it be a problem if I have both a embedded_ruby and ruby (rvm)

/etc/default/sensu:
EMBEDDED_RUBY=false
LOG_DIR=/var/log/sensu
LOG_LEVEL=info
SERVICE_MAX_WAIT=60

ulimit -Hn 100000
ulimit -Sn 100000
ulimit -Hu 200000
ulimit -Su 200000

Some times I get this error:
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:67: [BUG] Segmentation fault
ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0022 p:---- s:0112 e:000111 CFUNC  :initialize
c:0021 p:---- s:0110 e:000109 CFUNC  :new
c:0020 p:0128 s:0106 e:000102 METHOD /usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:67
c:0019 p:0019 s:0098 e:000094 METHOD /usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:41
c:0018 p:0395 s:0090 e:000089 CLASS  /usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:167
c:0017 p:0009 s:0088 e:000087 TOP    /usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:34 [FINISH]
c:0016 p:---- s:0086 e:000085 CFUNC  :require
c:0015 p:0115 s:0082 e:000081 METHOD /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0014 p:0015 s:0072 e:000071 TOP    /usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/ffi.rb:32 [FINISH]
c:0013 p:---- s:0070 e:000069 CFUNC  :require
c:0012 p:0115 s:0066 e:000065 METHOD /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0011 p:0150 s:0056 e:000055 TOP    /usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi.rb:17 [FINISH]
c:0010 p:---- s:0054 e:000053 CFUNC  :require
c:0009 p:0115 s:0050 e:000049 METHOD /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0008 p:0052 s:0040 e:000039 METHOD /usr/local/rvm/gems/ruby-2.1.1@global/gems/childprocess-0.5.3/lib/childprocess.rb:63
c:0007 p:0091 s:0035 e:000034 METHOD /usr/local/rvm/gems/ruby-2.1.1@global/gems/childprocess-0.5.3/lib/childprocess.rb:14
c:0006 p:0097 s:0031 e:000030 METHOD /usr/local/rvm/gems/ruby-2.1.1/gems/sensu-spawn-1.1.0/lib/sensu/spawn.rb:47
c:0005 p:0013 s:0022 e:000021 METHOD /usr/local/rvm/gems/ruby-2.1.1/gems/sensu-spawn-1.1.0/lib/sensu/spawn.rb:81
c:0004 p:0011 s:0012 e:000011 BLOCK  /usr/local/rvm/gems/ruby-2.1.1/gems/sensu-spawn-1.1.0/lib/sensu/spawn.rb:24 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :call
c:0002 p:0046 s:0007 e:000006 BLOCK  /usr/local/rvm/gems/ruby-2.1.1@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037 [FINISH]
c:0001 p:---- s:0002 e:000001 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/rvm/gems/ruby-2.1.1@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `call'
/usr/local/rvm/gems/ruby-2.1.1/gems/sensu-spawn-1.1.0/lib/sensu/spawn.rb:24:in `block in process'
/usr/local/rvm/gems/ruby-2.1.1/gems/sensu-spawn-1.1.0/lib/sensu/spawn.rb:81:in `child_process'
/usr/local/rvm/gems/ruby-2.1.1/gems/sensu-spawn-1.1.0/lib/sensu/spawn.rb:47:in `build_child_process'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/childprocess-0.5.3/lib/childprocess.rb:14:in `new'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/childprocess-0.5.3/lib/childprocess.rb:63:in `posix_spawn?'
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi.rb:17:in `<top (required)>'
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/ffi.rb:32:in `<top (required)>'
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:34:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:167:in `<module:FFI>'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:41:in `typedef'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:67:in `find_type'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:67:in `new'
/usr/local/rvm/gems/ruby-2.1.1@global/gems/ffi-1.9.3/lib/ffi/types.rb:67:in `initialize'

**Comment by khuongdp** [comment]
More information:

from strace (sensu-client process):
22227 getrlimit(RLIMIT_NOFILE, {rlim_cur=300000, rlim_max=300000}) = 0
22227 getrlimit(RLIMIT_NOFILE, {rlim_cur=300000, rlim_max=300000}) = 0
22227 getcwd("/", 200)                  = 2
22227 getcwd("/", 200)                  = 2
22227 chdir("/")                        = 0
22227 vfork( <unfinished ...>
22596 setpgid(0, 0)                     = 0
22596 dup2(13, 1)                       = 1
22596 dup2(13, 2)                       = 2
22596 execve("/opt/sensu/embedded/bin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabbitmq-overview-metrics.rb"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
22596 execve("/usr/local/sbin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabbitmq-overview-metrics.rb"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
22596 execve("/usr/local/bin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabbitmq-overview-metrics.rb"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
22596 execve("/sbin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabbitmq-overview-metrics.rb"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
22596 execve("/bin/sh", ["sh", "-c", "/etc/sensu/plugins/rabbitmq/rabbitmq-overview-metrics.rb"], [/* 31 vars */]) = -1 E2BIG (Argument list too long)
22596 exit_group(127) 

On this link http://sourceforge.net/p/nagios/mailman/message/21629385/ they have same problem for nagios. They found out that it is not **args that is too long but **envp

And on this https://tomtools.its.cern.ch/jira/browse/SAM-326 they have a patch for nagios (large installation).

Should it be the same problem for Sensu?

**Comment by portertech** [comment]
Sensu sets the environment variable SENSU_CONFIG_FILES after loading and validating configuration. This variable provides check plugins w/ a list of current and validated configuration files. As a quick fix, can you consolidate your configuration files? We need to revisit the use of this variable now.

**Comment by portertech** [comment]
https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/loader.rb#L142

**Comment by portertech** [comment]
@khuongdp what's your max? `getconf ARG_MAX`

**Comment by portertech** [comment]
Possible solution https://github.com/sensu/sensu-settings/pull/14 - will need to ship a release that has both options for the transition, allowing libraries that use the ENV var to switch to reading the temporary file.

**Comment by khuongdp** [comment]
getconf ARG_MAX says 2097152
I will try to merge the configuration files together. Right now we are using Chef Sensu cookbook where each sensu_check ressource create one json file.

Great with a fast solution. I will try the changes in sensu-settings and sensu-plugin

**Comment by khuongdp** [comment]
Hi

I have just patched my sensu-settings and sensu-plugin with our changes. And for the sensu-client it is working fine. But on the sensu-server the handler is still broken. This time with this error:

{"timestamp":"2015-06-12T14:06:02.985832+0200","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/notification/mailer.rb","name":"mailer"},"output":["/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/utils.rb:7:in `read': No such file or directory - /tmp/sensu_loaded_files20150612-6640-b8ii6g (Errno::ENOENT)\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/utils.rb:7:in `config_files'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/utils.rb:20:in `settings'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:101:in `filter_repeated'\n","\tfrom /etc/sensu/handlers/notification/mailer.rb:52:in `filter_repeated'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:30:in `filter'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:54:in `block in <class:Handler>'\n"]}

Is it because sensu-server is not using sensu-settings? or because sensu-client and sensu-server is running on the same server and /tmp/sensu_loaded_files20150612-6640-b8ii6g is already deleted

**Comment by khuongdp** [comment]
If i keep the tempfile using

ObjectSpace.undefine_finalizer(file)

it is working fine for the sensu-server daemon. It looks like the object is garbage collected or the Ruby interpreter exits.

**Comment by portertech** [comment]
Ah, it will be GC'd and deleted when the process daemonizes, fork/detach. We can either leave tempfiles around or work the file write into the daemonize process.

**Comment by portertech** [comment]
Would you like to submit a PR to sensu-settings to remove the finalizer to stop it from being removed by GC? Patching the method. We would then rely on the platform/system to reap the tempfiles (on reboot etc).

**Comment by khuongdp** [comment]
Wouldn't it be better to persist the file (no temp file) in e.g. /var/run/sensu/sensu_loaded_files and then overwrite it each time?

**Comment by portertech** [comment]
@khuongdp was thinking about multiple Sensu services, each loading configs/settings at different times. Perhaps a single/consistent file is the better approach.

**Comment by portertech** [comment]
Will need to use the system tmp dir path, to support multiple platforms (e.g. Windows).

**Comment by portertech** [comment]
Hmm, wouldn't be good to have multiple Sensu services writing to the same file. Also, wouldn't want plugins to read a partially written file etc.

**Comment by portertech** [comment]
Possible solution https://github.com/sensu/sensu-settings/pull/17
