### ISSUE TITLE
multiples stashes for maintenances

### ISSUE THREAD

**Issue by mag009** [sensu/sensu#958]
Hi,

would it be  possible to be able to add multiple stashes for a same check/host

It is frequent that we have multiple maintenance in advance and we'd like to be able to schedule them in advance.

thx

**Comment by calebhailey** [comment]
@mag009 hi there! Sorry for the radio silence on this. :smile: 

I've tagged this issue for renewed discussion on a subdue redux in #1219. I'd love your input/feedback on that conversation as it evolves.

**Comment by mag009** [comment]
I will follow the new thread that you've started than thx.

**Comment by portertech** [comment]
Closing this, as event silencing has been implemented in Sensu core.
