### ISSUE TITLE
Flapping alarms are not cleared

### ISSUE THREAD

**Issue by jcmcken** [sensu/sensu#959]
There's an issue in the the code which handles the detection of flapping alarms. As I understand it, if an event had been flapping (``action`` == ``flapping``), but the number of event state changes is less than or equal to the low flap threshold, the event should no longer be considered flapping. In the way it's currently implemented (``Sensu::Server::Process#check_flapping?`` as of ``0.17.0``), this outcome isn't possible.

In ``0.16.0``, the flap detection functions as expected.

To users of ``uchiwa``, this manifests as 'green' events in the dashboard which never clear (sensu/uchiwa#329).

**Comment by randeffects** [comment]
I have this problem as well with version 0.17.2.  My workaround was to delete the event key in Redis in order to clear the event in Uchiwa.

**Comment by portertech** [comment]
Thank you both for reporting :+1: I have a possible solution at https://github.com/sensu/sensu/pull/964

**Comment by portertech** [comment]
Sensu 0.19.0-1 is in the repositories, it includes #964 :+1:
