### ISSUE TITLE
Add support for multiple mutators

### ISSUE THREAD

**Issue by magmax** [sensu/sensu#973]
Same way a check can have a handler or a list with handlers, handlers should allow to use a mutator or a list of mutators.

An usage example: I have a mutator to fix the output (i.e: only_check_output) and another one to filter by the day hours (i.e.: officehours.rb), and I want to sent to graphite just some hours a day.

**Comment by joshbeard** [comment]
+1 on this.  I'm using a community plugin mutator and want to use my own mutator on top of it to further massage the output.

**Comment by ernoaapa** [comment]
+1 Same here, I would like to use "redact" mutator with my custom mutator.

**Comment by calebhailey** [comment]
@magmax hi there! Sorry for the radio silence on this! 

I'm curious if your use case for multiple mutators is similar to this issue: https://github.com/sensu/sensu/issues/1175 

[Sensu 0.23][1] was released this week with support for [Filter attribute eval tokens][2], which make filters significantly more powerful & potentially eliminate the need for some mutators. 

[1]: https://sensuapp.org/docs/0.23/changelog
[2]: https://sensuapp.org/docs/latest/filters#filter-attribute-eval-tokens

Please advise. :smile:

**Comment by magmax** [comment]
I see filters and mutators like different features. A filter decides if the handler should be applied or not, and a mutator modifies the content. I'm not sure if current filters allow to modify the content, so multiple mutator should be supported too (and it is easier to understand, because if filters can be chained, why not mutators?)

Anyways, I do not need it right now, but I think it is an interesting feature.

**Comment by lgarciaaco** [comment]
Same here ... I am building my flew of mutators, and having only ony is making things ugly

**Comment by portertech** [comment]
Not going to implement multiple mutators and here's why:

Chaining mutators would require ordering and expressing ordering via handler configuration is problematic, as runtime configuration can be composed of multiple deep merged JSON configuration files. This could be solved by introducing mutator chain dependency solving via a mutator definition attribute, however, this not only introduces dependency solving issues but also makes handler definitions no longer explicit.
