### ISSUE TITLE
sensu-client service stops all sensu-client services when using openvz containers

### ISSUE THREAD

**Issue by pedroluislopez** [sensu/sensu#974]
If you stop sensu-client service in a host machine with openvz containers, it stops sensu-client service of the openvz containers too.

**Comment by portertech** [comment]
@pedroluislopez Could you please move this over to: https://github.com/sensu/sensu-build

Have a good idea of how to solve it?

**Comment by pedroluislopez** [comment]
@portertech 

The problem is in the "/etc/init.d/sensu-service" file lines 240 to 248 (0.19.2-1 version):

```
   # try pgrep
    pid=$(pid_pgrep)

    if [ ! -n "$pid" ]; then
        # try the pid file
        if [ -f "$pidfile" ] ; then
            read pid < "$pidfile"
        fi
    fi
```
In my host machine with openvz containers:

```
root@s02:~# pgrep -f -u sensu " /opt/sensu/bin/sensu-client "
205947
208029
208037
208041
208050
208086
209773
225177
root@s02:~# cat /var/run/sensu/sensu-client.pid 
205947
```

The question is: why is you using pgrep?, why not you use only the pid file?

**Comment by mkobel** [comment]
The same happens if you are using LXC

**Comment by rstarkey** [comment]
It's an easy fix.  Just add -P to pgrep.  Patch will be submitted shortly.

**Comment by mkobel** [comment]
Thank you very much. It looks as it solves my problem from Issue #815

**Comment by portertech** [comment]
Merged https://github.com/sensu/sensu-build/pull/127, the next Sensu build will include the init script fix (`-P 1`).

**Comment by calebhailey** [comment]
Closing because it looks like this was resolved.
