### ISSUE TITLE
sensu-client cannot start because of illegal instruction, starting with v0.18 

### ISSUE THREAD

**Issue by kosli** [sensu/sensu#981]
Hi

I have sensu-client successfully running on alix boards (http://pcengines.ch/alix.htm) and using voyage linux, which is based on debian. The systems are set up with debian squeeze (LTS support enabled) and all packages up-to-date. I use the sensu debian repository:

    deb     http://repos.sensuapp.org/apt sensu main

After upgrading the sensu package to the latest version, i couldn't start the sensu client anymore. It always crashes directly at executing /etc/init.d/sensu-client start with:

    Starting sensu-client:/etc/init.d/sensu-service: line 111: 12413 Illegal instruction     start-stop-daemon --start --chuid $1 --pidfile $2 --exec $3 -- $4
    failed!

I downgraded the package and found out that the last version that works successfully is 0.17.2. The next newer one, 0.18, has already the illegal instruction error.

I executed the binary as sensu user and used strace:

    strace -o /tmp/strace.log /opt/sensu/bin/sensu-client -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-client.pid -l /var/log/sensu/sensu-client.log -L info

You can find the strace output here: http://pastebin.com/URiZB1YM

Any idea what has changed in 0.18 and is causing this error?  Thanks

Kind regards
 KoS

**Comment by brettswift** [comment]
I'm getting this on 2.0.0 as well. 

I'll try 0.17.2.. thanks for the tip.

**Comment by calebhailey** [comment]
@kosli hi there! Sorry for the radio silence on this! 

Is this still an issue? Please advise.

**Comment by kosli** [comment]
@calebhailey i just tested it with the packages for 0.23 and it works. thanks a lot!
