### ISSUE TITLE
page is not getting created : not enough occurrences:

### ISSUE THREAD

**Issue by cchiremath** [sensu/sensu#982]
Hi all, i am not getting the page created for the below log. help appreciated.
we are using sensu - 0.12.2 .

{"timestamp":"2015-06-20T06:55:28.494291+0000","level":"info","message":"handling event","event":{"client":{"name":"sensu-01-internal","datacenter":"sc-tx2","address":"192.168.90.9","keepalive":{"thresholds":{"warning":120,"critical":180},"handlers":["pagerduty"],"subscribers":["keepalives"]},"subscriptions":["base","sensu-server-buddy"],"service_level":"prod","socket":{"bind":"127.0.0.1","port":3030},"buddy":{"url":"http://sensu-01-internal.sc-tx2.huron-dev.com:4567","host":"sensu-01-internal.sc-tx2.huron-dev.com","port":"4567","user":"sensu","password":"REDACTED","rabbit":{"host":"rabbitalerts.sc-tx2.huron-dev.com","vhost":"%2fsensu","user":"sensu","password":"REDACTED","port":"15672"}},"timestamp":1434783321},"check":{"notification":"Buddy Sensu Server sensu-01-internal.sc-tx2.huron-dev.com health check failed!","handlers":["pagerduty"],"command":"/etc/sensu/plugins/check-http.rb -u ':::buddy.url:::/health?consumers=1&messages=100' -U :::buddy.user::: -a :::buddy.password::: --response-code 204","subscribers":["sensu-server-buddy"],"runbook":"For help, see: http://sqbu-github.cisco.com/Platform-Internal/service-index","interval":60,"occurrences":5,"name":"buddy_sensu_health_check","issued":1434783327,"executed":1434783327,"output":"CheckHTTP CRITICAL: 503\n","status":2,"duration":0.371,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2"]},"occurrences":1,"action":"create"},"handler":{"type":"pipe","command":"/etc/sensu/handlers/pagerduty.rb","severities":["critical","ok"],"name":"pagerduty"}}
{"timestamp":"2015-06-20T06:55:28.719328+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/pagerduty.rb","severities":["critical","ok"],"name":"pagerduty"},"output":"not enough occurrences: sensu-01-internal/buddy_sensu_health_check\n”}

**Comment by suraj-kamath** [comment]
Can anybody help us out with this ?

**Comment by petere** [comment]
Your check is configured to be handled after 5 occurrences, but at that time only 1 occurrence has happened.  So this appears to be working correctly.

**Comment by oryband** [comment]
might be related to sensu/sensu-plugin#91

**Comment by calebhailey** [comment]
Closing due to OP inactivity, and because it doesn't look like this is an issue with Sensu itself. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
