### ISSUE TITLE
Need to differentiate 2 separate situations in /health in sensu-api

### ISSUE THREAD

**Issue by somic** [sensu/sensu#984]
https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L305

Sensu-api should probably differentiate between a situation when it's not connected to transport or redis and when it considers itself not healthy (too many messages in queue and/or too few consumers).

Right now it signals both situations to caller as HTTP 503 Service Unavailable with no response body, and when caller receives 503, it is unable to determine if sensu-api is not connected or it's overloaded.

Not necessarily arguing for different HTTP response code, maybe include error json in response body when returning 503 explaining exactly what's going on? This could also make it backwards compatible.

**Comment by calebhailey** [comment]
@somic hi there! Sorry for the radio silence on our side! 

We just arrived at the same conclusion yesterday and created an issue & PR with a proposed resolution, here: #1216  

I'd love your comments/feedback on that before we implement it in the 0.24 release.

**Comment by somic** [comment]
I am not particularly tied to any solution as long as a caller can tell these 2 situations apart. Your proposed solution sgtm.

**Comment by calebhailey** [comment]
@somic thanks for the reply! We've tagged this change for the 0.24 release, so it should be implemented soon!

**Comment by calebhailey** [comment]
This has been resolved via #1243 and will be including in the upcoming 0.24 release. 👍
