### ISSUE TITLE
keepalive check does not have subscription

### ISSUE THREAD

**Issue by alex-leonhardt** [sensu/sensu#986]
Hi, 

based on this change (and my comment on it) https://github.com/sensu-plugins/sensu-plugins-mailer/commit/9500dbb2152aa8897c4dde2db878fb08eb5a94b4 it's currently not possible to route emails for keepalive checks based on the host's subscriptions.

![keepalive](https://cloud.githubusercontent.com/assets/4490686/8495257/161f65ee-2164-11e5-8cf7-9b42c1fa0f66.png)

**Comment by portertech** [comment]
The event data contains the client configuration that has subscriptions, keepalives do not target check subscribers.
