### ISSUE TITLE
Increased memory usage for sensu-client with 0.20.0

### ISSUE THREAD

**Issue by shawnbutts** [sensu/sensu#995]
Upgraded my test environment and from 0.19.2 to 0.20.0 and I'm seeing a significant increase in memory usage.  

Version       VIRT  RES  SHR
0.19.2        276m  31m 1812
0.20.0        828m 447m  356

No config changes.  It's not clear to me from the change log why this would be the case.

**Comment by portertech** [comment]
Does usage continue to grow?

**Comment by shawnbutts** [comment]
Not as far as I can tell.  However, I wasn't able to let it run too long after I discovered the issue.

**Comment by portertech** [comment]
Changes in core https://github.com/sensu/sensu/compare/v0.19.2...v0.20.0

**Comment by portertech** [comment]
Changes in sensu-settings https://github.com/sensu/sensu-settings/compare/v1.9.0...v3.0.0

**Comment by portertech** [comment]
Changes in sensu-spawn https://github.com/sensu/sensu-spawn/compare/v1.2.0...v1.3.0

**Comment by portertech** [comment]
Changes in childprocess https://github.com/jarib/childprocess/compare/v0.5.3...v0.5.6

**Comment by portertech** [comment]
Changes in multi_json https://github.com/intridea/multi_json/compare/v1.11.0...v1.11.2

**Comment by portertech** [comment]
Change in sensu-build https://github.com/sensu/sensu-build/commit/2fb820153ae208fca5219aa63c7c1f112504b979 (OpenSSL 1.0.1p)

**Comment by shawnbutts** [comment]
looks like this is not caused 0.20.0.  Nothing in the code changes jump out at me as a possible cause and I am not able to reproduce the issue today.

Sorry for the noise.
