### ISSUE TITLE
server process fails to shut down cleanly after upgrade to 0.20.0

### ISSUE THREAD

**Issue by barryorourke** [sensu/sensu#998]
I recently updated my sensu server to 0.20.0 and have noticed that it no longer shuts down cleanly.

```bash
[root@baratheon sensu]# service sensu-server stop                                                                                                                                                                
Timed out waiting for sensu-server to stop                 [FAILED]
```

Whilst the process continues to run, logging to /var/log/sensu/sensu-server.log stops, with the last lines reading.

```json
{"timestamp":"2015-07-17T11:24:51.729391+0100","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2015-07-17T11:24:51.729896+0100","level":"warn","message":"stopping"}
{"timestamp":"2015-07-17T11:24:51.730108+0100","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-07-17T11:24:51.731089+0100","level":"warn","message":"resigning as leader"}
{"timestamp":"2015-07-17T11:24:51.731610+0100","level":"info","message":"completing event handling in progress","handling_event_count":751094}
```

The only way I've managed to stop the server process is by forcibly killing it.

**Comment by barryorourke** [comment]
I've done a little digging and discovered if I can temporarily resolve this by going through the following process;

1. forcibly kill the server process.
2. flush redis
2. start the server process.
3. stop the server process.

This only works for a short period of time and the original behaviour returns.

This sounds similarr to #916, which was fixed in 0.17.2. Is there any chance it may have been reintroduced somehow?

**Comment by portertech** [comment]
`"handling_event_count":751094` is concerning :fearful:

Did you introduce the use of a new event filter or mutator at the same time?

**Comment by portertech** [comment]
Are you using a event handler extension?

**Comment by barryorourke** [comment]
I use an influxdb handler extension, disabling it fixes the problem :)

The extension was working up until I upgraded to 0.20.0, is there something obvious wrong with this? https://github.com/sopacst-infrastructure/sensu_influxdb_handler/blob/master/influx.rb

**Comment by NeckBeardPrince** [comment]
I'm using https://github.com/seegno/sensu-influxdb-extension for influx and getting the same thing.

{"timestamp":"2015-08-05T14:26:38.415519+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2015-08-05T14:26:38.415720+0000","level":"warn","message":"stopping"}
{"timestamp":"2015-08-05T14:26:38.415843+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-08-05T14:26:38.416040+0000","level":"warn","message":"resigning as leader"}
{"timestamp":"2015-08-05T14:26:38.416202+0000","level":"info","message":"completing event handling in progress","handling_event_count":3227}

**Comment by portertech** [comment]
The Sensu Extension API states that extensions must call the run() callback:

http://www.rubydoc.info/github/sensu/sensu-extension/Sensu/Extension/Base#run-instance_method

The InfluxDB integration is not calling the callback w/ the appropriate parameters. Please create an issue for that integration, I am closing this one as it's not an issue with Sensu.
